### ISSUE TITLE
Growing Inferium Crop always drops Inferium Essence

### ISSUE THREAD

**Issue by citpo** [BlakeBr0/MysticalAgriculture#1]
Hi,

When growing any variant of the Inferium Crop, no matter what Tier of the seed that is planted the produced essence is always Inferium Essence.

Is this intended or a bug?

Using version: mysticalagriculture[1.10.2]-1.3.6

**Comment by BlakeBr0** [comment]
I mean, the mod is OP, but not THAT OP.
Each tier drops +1 more Inferium Essence than the last. Thats intentional.
