### ISSUE TITLE
Feature Request:  Spawn Eggs

### ISSUE THREAD

**Issue by MentalMouse** [BlakeBr0/MysticalAgriculture#10]
For the amount of time and trouble we need to grow monster essence, I'd like to see the ability to actually craft a spawn egg for the mob.

**Comment by BlakeBr0** [comment]
The point is to be able to grow the mob drops, not the mobs themselves. Don't think I will be adding this. 

If you want those recipes you can use CraftTweaker to add them.

**Comment by MentalMouse** [comment]
OK, I did:  [CraftTweaker script for spawn eggs](https://pastebin.com/FK4XQCV3).  

Currently defaults to requiring mob chunks, but there are three variations available:  chunks plus tier essence, the default chunks only, or pure essence.

**Comment by MentalMouse** [comment]
OK, I did:  [CraftTweaker script for spawn eggs](https://pastebin.com/FK4XQCV3).  

Currently defaults to requiring mob chunks, but there are tables and code for three variations included:  mob chunks plus tier essence, the (default) mob chunks only, or just essence.
