### ISSUE TITLE
Craft silicon essence into Refined Storage silicon

### ISSUE THREAD

**Issue by cortus** [BlakeBr0/MysticalAgriculture#100]
I don't seem to be able to craft silicon essence into refined storage silicon and my instance does not have Applied Energistics 2 installed on it.  I can't seem to find a place in the configs (or just don't know what I'm doing!)

**Comment by BlakeBr0** [comment]
Is refined storage silicon registered in the oredictionary as itemSilicon?
Is there another itemSilicon in the game?

**Comment by IamAlathe** [comment]
I also have a problem with silicon.  I made the seeds, planted, got the essence, but there is absolutely no recipe of anything using the silicon essence.  Refined Storage is the only mod in my game which has silicon.  When I use JEI to find the recipe for silicon, it only tells me I can smelt nether quartz.  I'm not sure how to find out if it is in the oredictionary.  I know in previous versions I played where I had another mod that had silicon, things worked fine. (I think that was 1.10 though)
