### ISSUE TITLE
Can't fly with Tier 5 Armors

### ISSUE THREAD

**Issue by vincebae** [BlakeBr0/MysticalAgriculture#102]
Dear BlakeBr0,

I've made the full set of tier 5 armors, but cannot fly.
I've checked the config and the fly set bonus already is set to true, and also "Flight" set bonus is shown in the WAILA messages.

Here are the version info, FYI:
Minecraft: 1.12.1 - 14.22.1.2478
MA: 1.6.3

Thank you.

**Comment by BlakeBr0** [comment]
You probably have something turning off flight on you (like an angel ring)

**Comment by vincebae** [comment]
I don't have angel ring, but I had a diamond wing from magical wings mod at the time I made the armor set. (not now). 
Can it be the reason?
Is there any way to reset the flight ability?

**Comment by vincebae** [comment]
I just removed the magical wings mod and now I can fly.
