### ISSUE TITLE
(Tier 5) Paxel cannot harvest some blocks from other mods.

### ISSUE THREAD

**Issue by vincebae** [BlakeBr0/MysticalAgriculture#103]
Dear BlakeBr0

I've made the full set of tier 5 Paxel and found that some items are disappearing when broken by Paxel. Here are those items:

- Solar Panel from Extra Utilities 2 (confirmed that it can be harvested by iron pickaxe)
- Red Matter Furnace and energy collector MK3 from Project E (confirmed that the can be harvested by red matter pickaxe)

Here are the version info, FYI:
Minecraft: 1.12.1 - 14.22.1.2478
MA: 1.6.3
Extra Utilities 2: 1.12-1.6.3
Project E: 1.12-PE1.1.0

Thank you.

**Comment by vincebae** [comment]
Another block found: Redstone Clock from Cyclic (version 1.12-1.8.6)

**Comment by BlakeBr0** [comment]
Mystical Agradditions adds the paxels
