### ISSUE TITLE
Silicon can't be crafted with RefinedStorage loaded

### ISSUE THREAD

**Issue by PongoSapiens** [BlakeBr0/MysticalAgriculture#105]
With MysticalAgriculture 1.6.4, Forge 2478, Refined Storage 1.5.18, and Minecraft 1.12.1; there is no recipe to craft silicon from silicon essence. I can craft quartz enriched iron from it's essence.

**Comment by BlakeBr0** [comment]
This is because refined storage registers oredictionary entries during the same event as I register recipes, so load order becomes an issue.

**Comment by PongoSapiens** [comment]
Is this something I can work around? Force the load order? Or do you know how to fix it?

**Comment by BlakeBr0** [comment]
You can add your own recipes with crafttweaker
The refined storage devs could register items in the oredictionary when they register items

**Comment by PongoSapiens** [comment]
Looking at CraftTweaker, will log a request with Refined Storage, could you add a config option to force the recipe creation? I'm guessing not because you don't know what the item to be created is :(
Thanks for your prompt attention.

**Comment by PongoSapiens** [comment]
The refined storage author replied: "When you register recipes that are other mod dependant you probably need to be registering recipes in postInit."

**Comment by BlakeBr0** [comment]
It's worked up to this point, and this is the only issue with it, so I guess we'll just have to live with it.

**Comment by BlakeBr0** [comment]
I'll probably just add another recipe for it whenever I start working on the next update.

**Comment by PongoSapiens** [comment]
I've added craft tweaker and I'm using that, thanks for your attention, and the mod, I love it.
