### ISSUE TITLE
Incorrect work of growth acceleration system.

### ISSUE THREAD

**Issue by StrikerPro007** [BlakeBr0/MysticalAgriculture#107]
Hello,
When i set up a combination of growth acceleration blocks and helping with a water can (tier 5). Water can doesn´t work on crop where growth blocks were placed, is this correct? or is it my problem of my modpack that i did.

PD: I´m using version 1.10.2-1.5.7a
Thanks,
Best Regards.

**Comment by StrikerPro007** [comment]
Hello,
When i set up a combination of growth acceleration blocks and helping with a water can (tier 5). Water can doesn´t work on crop where growth blocks were placed, is this correct? or is it my problem of my modpack that i did. 
Thanks,
Best Regards.

**Comment by BlakeBr0** [comment]
https://github.com/BlakeBr0/MysticalAgriculture/issues/82
