### ISSUE TITLE
All 5 tier's of Inferium Crop only dropping tier 1 essence

### ISSUE THREAD

**Issue by Jenral** [BlakeBr0/MysticalAgriculture#11]
I've been trying out your mod with the "All The Mods 1.10.2" modpack currently using version v1.56 of the pack which has v1.3.8a of your mod.

The problem I have is that I have planted all 5 tiers of the Inferium Crop, but when I harvest them they all only drop the tier 1 essence.

**Comment by BlakeBr0** [comment]
Each tier adds +1 Inferium Essence dropped per harvest. That's intended.
