### ISSUE TITLE
[1.12.2] Latest update 1.6.5 drops support for rustic iron wood and others?

### ISSUE THREAD

**Issue by Gepett0** [BlakeBr0/MysticalAgriculture#111]
Hi,

after updating Mystical Agriculture to 1.6.5 Minecraft showed the screen about missing items and blocks on world load.
Missed are:
knightmetal_crop
steeleaf_crop
fiery_ingot_crop
ironwood_crop
and their respective essences and seeds ofc.

I've seen you added slate crops, so was this change/removal intentionally?

BR
Gepetto

**Comment by BlakeBr0** [comment]
Those are the twilight forest crops. Last time I checked rustic doesnt add ironwood ingots anyways.
