### ISSUE TITLE
Step assist reseting step height to wrong value when armor is taken off.

### ISSUE THREAD

**Issue by winauer** [BlakeBr0/MysticalAgriculture#112]
Walking up stairs made with the Chisels & Bits mod stops working after equipping and unequipping an armor set with step assist enabled.

It seems like the players step height is set to 1.5 while it should be 1.6 (See this discussion:  AlgorithmX2/Chisels-and-Bits#85)

**Comment by BlakeBr0** [comment]
I will say it is quite interesting that this has been in the mod for more than a year and this is the first time ive heard of an issue with it.
