### ISSUE TITLE
[Suggestion] Slow down the progress

### ISSUE THREAD

**Issue by xenoflot** [BlakeBr0/MysticalAgriculture#118]
Hi,

I've been playing AllTheMods3 for a couple of weeks and it didn't take me long to get a full suit of charmed armour. Obviously cross-mod interaction will almost always alter the balance of things but I can't help but feeling that it was far too easy to get to this stage. In ATM3 we have Cyclic which provides sprinklers and Actually Additions which provide both worms and Greenhouse Glass. I read that the sprinkler and glass do bonemeal actions, and the worms do growth ticks. Not sure which of these are relevant for MA crops but IMO only the MA accelerators should work. I used sprinklers and worms.

I also feel that the accelerator recipe is too simple. Even 4 blocks of Inferium is trivial to get by setting up an AA farmer and waiting a short time. Then geometric progression sets in and a week later you're making buildings out of Supremium blocks :D

I'd suggest either:
1. Having tiered accelerators that only work on crops of their tier  (and don't have a differential effect on crops of lower tiers (e.g. 4x accel on Inferium))
2. Changing the recipe to require a block of Supremium essence.

Perhaps also restricting them to 1 layer of accelerators under the crops (I understand it's currently 3 as per MCrops).

Cheers!

**Comment by BlakeBr0** [comment]
Balance is subjective. I'm not going to go out of my way to make things take longer just because the mod is "too fast" in one pack. It'll always be either too fast or too tedious just because thats the nature of things that require farming/grinding.

Tiered accelerators was an idea I had, but I don't plan to add more stuff to the current versions as I would rather wait for 1.13 when I overhaul the whole thing.

**Comment by Grotts** [comment]
I agree with you BlakeBr0, the speed of the mod should be up to a modpack creator to adjust, that is just my opinion.  I am currently working on custom Advancements that will unlock recipes through your mod potentially for my friends modpack.  For the reason that it seems too fast to them also, I have run into a snag though as it seems not all the recipes have been added to the new recipe book feature of 1.12, do you have someone assisting you with this or would you consider having someone help to fill out those recipes?

**Comment by BlakeBr0** [comment]
The recipes would all have to be converted to the new json format for them to show up in the book. I started converting them but it's just too tedious for me to want to sit down and convert them all.

**Comment by Grotts** [comment]
Right, I understand that. Do you have anyone helping with your project? Would that be something that, if I worked on them and got some done, you would accept and add to the .jar?

**Comment by BlakeBr0** [comment]
Kinda worrying to have someone else change them all because then I have to worry about recipes being changed unintentionally.

**Comment by Grotts** [comment]
I understand, no worries, I wanted to ask before doing anything I shouldn't be doing.  I will focus my efforts on other mods until the time comes that the recipes are added.

**Comment by BlakeBr0** [comment]
This mod adds quite a lot of recipes, so it would probably take a while. Another issue is that there are a lot of recipes that I can't really convert since they are registered too late (the recipes for all the essences).
