### ISSUE TITLE
[Suggestion] Fuel for charms

### ISSUE THREAD

**Issue by xenoflot** [BlakeBr0/MysticalAgriculture#119]
Having a full suit of charmed Supremium armour, I've now got a small stash of supremium blocks so I've disassembled my farm and that's it. Unless I lose all my armour (not happening since we have gravestones mod), I've no need to replace it or use the essence again. Just as mods like AE2 and Tico have you constantly expanding and tweaking your setup, it'd be nice to have some reason to come back to MA.

I suggest the development of Charmium, a fuel that powers the charms! 

IMO this would be better than simply burning durability. Older versions of TiCo (don't know about current) used to have two "damage" bars on their tools, one for regular durability and one for the RF stored (for those tools with an RF modifier), so I know that it's possible to track and display both these values.

I'm not sure about the recipe though. The charm effects don't change by level so we can't scale it to that. Perhaps just have tiered fuel buffers on the armour.

Food for thought!

Cheers

(Side note not worthy of its own post... you might want to change the model for your tinker table because it looks just like a TiCo Tools Station, even has a virtually identical recipe, but doesn't do the same job. Is the similarity because you're planning to integrate with the TiCo stuff?)

**Comment by BlakeBr0** [comment]
This idea is neat but I don't feel like it fits with my vision of the mod. Thanks for the suggestion though!

This message was sent using Internet Explorer.
