### ISSUE TITLE
About the inferium seeds in garden cloche.

### ISSUE THREAD

**Issue by JimMoen** [BlakeBr0/MysticalAgriculture#123]
Hi,
I added the Immersive Engineering in my private modpack (Minecraft version 1.11.2) and I can't plant tier1-tier5 inferium seeds in the Garden Cloche.But in the modpack [The Simple Life 2(Minecraft version 1.10.2)](https://minecraft.curseforge.com/projects/the-simple-life-2-hqm) they can be planted.
I don't know if the modpack writer modified the configuration or it was a feature in version 1.10.2.
If it's can be changed,how to configure the setting to make the seeds can be used in the Garden Cloche?
If it's a bug...ummm...forget about it...

**Comment by BlakeBr0** [comment]
The mystical agriculture compat was added by immersive engineering. From what I've seen they forgot to add it to the 1.11 verison, and don't support it anymore.

**Comment by JimMoen** [comment]
Thanks very much.
I will ask the writer of the Immersive Engineering about the problem.
