### ISSUE TITLE
When removing an essence, recipes requiring it should also be removed.

### ISSUE THREAD

**Issue by ManMan36** [BlakeBr0/MysticalAgriculture#124]

**Comment by BlakeBr0** [comment]
Any specific recipes?

**Comment by ManMan36** [comment]
Yes I am referring to disabling a seed in the config. For example, if I disable the stone essence, the recipe for cobblestone still shows up in JEI, just without the stone essence in it.

**Comment by BlakeBr0** [comment]
Interesting, id assume this is 1.12?
