### ISSUE TITLE
Uranium 238 Essence has no recipe

### ISSUE THREAD

**Issue by SparkyBx** [BlakeBr0/MysticalAgriculture#126]
Can't do anything with it at all, Can't make or use it unless in creative in 1.10.2
It does work in 1.12.2 but i'm waiting for EnderIO to update before i play 1.12.2

**Comment by jmac460** [comment]
I also have this issue. When starting a loaded savegame, Hermit Skies for example, does not allow me to play the world because of "4 Missing blocks".... then it goes on to say it has errors with anything uranium.
