### ISSUE TITLE
suggestions ore integrations

### ISSUE THREAD

**Issue by Hypsellis** [BlakeBr0/MysticalAgriculture#127]
I noticed this mod missed many integreations for many mods, I thought it was a shame because it's a really nice mod. So here is a little list if it can help. :)

- Tinkers Construct
    - Green Slime Crystal
    - Blue Slime Crysal
    - Magma Slime Crystal
    - Silky Jewel

- PlusTic
    - Alumite
    - Osmiridium
    - Mirion
    - Osgloglas

- TechReborn
    - Refined Iron
    - Tungstensteel
    - Advanced Alloy
    - Red Garnet
    - Yellow Garnet

- Redstone Arsenal
    - Flux Crystal
    - Fluxed Electrum

- ImmersiveEngineering
    - Uranium

- Extreme Reactors
    - Yellorium
    - Cyanite
    - Blutorium
    - Lucidrite
    - Graphite

- ProjectRed
    - Red Alloy
    - Electrotine

- ExtraUtilities
    - Demon
    - Enchanted
    - Evil Infused

- Actually Additions
    - Black Quartz
    - Redstonia
    - Palis
    - Diamatine
    - Void
    - Emeradic
    - Enori

- Calculator
    - Enriched Gold
    - Reinforced Iron
    - Redstone
    - Weakened Diamond
    - Flawless Diamond
    - Fire Diamond
    - Electric Diamond
    - End Diamond

- Botania
    - Gaia Spirit
    - Mana Diamond
    - Dragon Stone
    - Red Quartz
    - Blaze Quartz
    - Sunny Quartz
    - Elven Quartz
    - Mana Quartz
    - Lavender Quartz
    - Smokey Quartz

- Psi
    - Psimetal
    - Psigem
    - Ebony
    - Ivory

- Quark
    - Biotite

- Embers
    - Drawstone

- Gadgetry
    - Redmetal

- AbyssalCraft
    - Abyssalnite
    - Refined Coralium
    - Dreadium

- The Betweenlands
    - Aqua Middle Gem
    - Crimson Middle Gem
    - Green Middle Gem

- Aether
    - Ambrosium
    - Gravinite
    - Zanite

- ProjectE
    - Dark Matter
    - Red Matter

- EvilCraft
    - Dark Gem
    - Empowered Dark Gem

- Astral Sorcery
    - Aquamarine
    - Starmetal
    - Crystal

- Avaritia
    - Crystal Matrix
    - Neutronium
    - Infinity

- Steves Cart
    - Stabilized
    - Reinforced
    - Galgadorian
    - Enhanced Galgadorian

- Terraqueous
    - Burnium
    - Endimium

**Comment by BlakeBr0** [comment]
I wouldnt say "missed", i would say unnecessary. You also listed a bunch of stuff thats already in the mod.

**Comment by Hypsellis** [comment]
I never asked to add all the integration, just gave a list of potential integration. You do as you want, it's your mod. ;)

**Comment by Alroy1000** [comment]
If I'm allowd to ask at these task.
I want ask if it is possible to add a prosperity crop for example in the source code so that you have the possibility to make a recepi if you needed example sky packs based on these mod to gether your first resources and without a crop for prosparety I have the problem wher can you gether it without any athor way to get recources like void ore mining ore ather stuff like this 

In hop you understand and answer me M.M.

**Comment by BlakeBr0** [comment]
@Alroy1000 There is intentionally no prosperity shard crop. Even if there was, you wouldn't be able to make it anyways because you'd still need to get some to make the seeds. The pack dev should add an alternative way to get them.

**Comment by IamAlathe** [comment]
@Alroy1000 Most skyblock packs do have ways to get prosperity shards, like from sieving.  Check JEI (included in almost every pack) to see how to obtain shards in that pack.  Most also have Tinkers, and you can make tools with some of the Mystical Agriculture materials that drop more shards.

**Comment by tyler489** [comment]
Yellorite and uranium are in. Fluxed electrum is too.. also if you do [] then it becomes a check off list

**Comment by MauveCloud** [comment]
@MentalMouse I might be coming into this a bit late, but how do you figure MystAg is "focused on raw materials", and that crafted materials shouldn't be included?  There are already a number of seeds for alloys (e.g. brass, bronze, electrum, various alloys added by Ender IO if the mod is installed (the only thing Ender IO adds that I can see calling a "raw material" is the grains of infinity))

**Comment by MentalMouse** [comment]
I haven't used EnderIO, but from what I've seen, the vast majority of the essences and recipes thereof are indeed "raw materials" -- blocks and materials found in the world, or mob drops.  The big exception is that minerals are produced in smelted/dropped form, presumably to bypass ore multiplication.  There's also dyes, but that would seem to be as much convenience as anything else.

If Blake has chosen to include some alloys, that's his prerogative, but they don't really fit the pattern.  If I were in his place, I would probably allow alloys to be made from mixing essences, or (more likely) just let people use ModTweaker to add such recipes.  On the other hand, there might well be some oddity to EnderIO recipes that warrants treating those alloys as basic materials.
