### ISSUE TITLE
Infusion crystal fuzzy recipe needed

### ISSUE THREAD

**Issue by munsta0** [BlakeBr0/MysticalAgriculture#13]
Any recipe that uses the Infusion crystal requires the crystal to be brand new. A used one work.

I'm using the pack with Sky Factory 3.0 ( Minecraft 1.10 with JEI )

**Comment by BlakeBr0** [comment]
Definitely not the case.

**Comment by munsta0** [comment]
Have you even bothered to test it? It's super easy to reproduce

Inventory : http://puu.sh/troix/ec4b253d8b.png

Crafting window : http://puu.sh/trola/f6213e2492.jpg

As you see in inventory, I do indeed have the crystal, but when trying to auto complet the recipe, it doesn't work.

**Comment by BlakeBr0** [comment]
I did bother to test it, both in skyfactory and another modpack. The fact JEI doesn't work well with damaged items isn't a problem with my mod. You can still craft with it by simply putting the items into the crafting table yourself.

**Comment by munsta0** [comment]
Ah, thanks for precision.

I'll look into JEI then, cheers.
