### ISSUE TITLE
1.10 Weirdness with Thermal Dynamics

### ISSUE THREAD

**Issue by jamzam90** [BlakeBr0/MysticalAgriculture#130]
When using item ducts on the inferium furnace. The item ducts send items but the items dont place into the inventory of the furnace at all, essentially acting as a void chest randomly.
Heres a video of whats happening.
https://youtu.be/jo3P4d9vRgU
heres the report link for the cofh guys about it.
https://github.com/CoFH/Feedback/issues/776

**Comment by BlakeBr0** [comment]
Kinda hard to watch a video that doesnt exist

**Comment by jamzam90** [comment]
Should be viewable now I usually don't use the unlisted/private buttons on youtube.

**Comment by jamzam90** [comment]
I dont think its on you end now it also seems to be happening with vanilla furnaces as well.

**Comment by BlakeBr0** [comment]
Yeah, I kind of figured that, considering my furnaces are just slightly modified vanilla furnaces anyways.

**Comment by jamzam90** [comment]
So it seems to be a forge thing according to kinglemming 
https://github.com/CoFH/Feedback/issues/779

**Comment by BlakeBr0** [comment]
Have you tried using a different forge version?

**Comment by jamzam90** [comment]
Ive tried it in different versions of minecraft both of which still has the issue with only itemducts as hoppers and other means of moving items dont do it.

**Comment by BlakeBr0** [comment]
Definitely a weird issue. Hopefully you can find a solution, as I can't really think of one.
