### ISSUE TITLE
Block of Supremium registered as 'blockSuperium' in OreDictionary

### ISSUE THREAD

**Issue by OneEyeMaker** [BlakeBr0/MysticalAgriculture#132]
The title says it all. Block of Supremium just registered with wrong OreDictionary name - 'blockSuperium'.

MC 1.12.2
Mystical Agriculture 1.6.7

**Comment by sithrebel15** [comment]
This is correct. I suggest you review the guidelines for ore dictionary. 

https://mcforge.readthedocs.io/en/latest/utilities/oredictionary/

**Comment by sithrebel15** [comment]
forgot to rename the files in that pull request
