### ISSUE TITLE
Question: How big is Growth Accelerator Range?

### ISSUE THREAD

**Issue by Tyranuss** [BlakeBr0/MysticalAgriculture#133]
As titled says: How big is the range of Accelerator? Is it just on the block above it? Meaning just 1? Or does it have some kind of range? For example: If I set up 3x3 area and a growth accelerator under the middle farm block, will it affect entire 3x3 area or just that block? Also how many can I stack under until it becomes pointless?

**Comment by BlakeBr0** [comment]
Up to 64 blocks above it.
