### ISSUE TITLE
ModTweaker Support

### ISSUE THREAD

**Issue by 016Nojr** [BlakeBr0/MysticalAgriculture#14]
Would be nice to have this so I can add recipes to the furnaces in MA.

**Comment by BlakeBr0** [comment]
http://minetweaker3.powerofbytes.com/wiki/Tutorial:Furnace

**Comment by 016Nojr** [comment]
Let's rephrase then. It doesnt work then, The printed parts for the circuits in Refined Storage you can smelt gold/dia/iron/silicon in a furnace, however this doesnt work in the MA furnaces. It's using the furnace.addRecipe function.

**Comment by 016Nojr** [comment]
@BlakeBr0 ^^

**Comment by BlakeBr0** [comment]
It does work though. :/

**Comment by 016Nojr** [comment]
Doesnt work for me in the latest SkyFactory 3 3.0.5 atleast, using MA version 1.3.9

**Comment by 016Nojr** [comment]
//Refined Storage Alternate Route
furnace.addRecipe(<refinedstorage:processor:1>, <minecraft:gold_ingot>);
furnace.addRecipe(<refinedstorage:processor:2>, <minecraft:diamond>);
furnace.addRecipe(<refinedstorage:processor>, <minecraft:iron_ingot>);
furnace.addRecipe(<refinedstorage:processor:6>, <ore:itemSilicon>);

**Comment by 016Nojr** [comment]
Never mind, just me derping. Sorry :/
