### ISSUE TITLE
Yellorite is oredicted with Uranium

### ISSUE THREAD

**Issue by tyler489** [BlakeBr0/MysticalAgriculture#140]
When using yellorite to craft yellorite seeds it ends up making uranium seeds. 1.10 and 1.11

**Comment by BlakeBr0** [comment]
Do you have unidict installed?

**Comment by tyler489** [comment]
Nope. Happens in every pack i have plaayed because extreme reactors has it registered as ore uranium and ore Yellorite

**Comment by BlakeBr0** [comment]
Unfortunate. If they're considered the same thing then it's not an issue.

**Comment by BlakeBr0** [comment]
I guess it's not necessarily a bug, as yellorium is supposed to be equal to uranium if thats the case. It wasnt that way when I added the seeds though.

**Comment by tyler489** [comment]
Uranium seed makes 2 and yelloeite 3

**Comment by BlakeBr0** [comment]
Yea, because when I added them I considered Uranium > Yellorium. You can disable the uranium seeds and shouldn't lose out on anything.
