### ISSUE TITLE
Empty Stack for enderio Recipys

### ISSUE THREAD

**Issue by tyler489** [BlakeBr0/MysticalAgriculture#141]
https://gyazo.com/a12f845a49927b5ba1540dbddd065004 Viberent alloy redstone alloy and energetic alloy all appear that way with no ingots. This is using the 1.11 beta builds
Im Guessing its because https://github.com/BlakeBr0/MysticalAgriculture/blob/8003210f22778efd4b39b1f2aba6932503b6448c/src/main/java/com/blakebr0/mysticalagriculture/lib/Parts.java#L40-L47 Has Changed
Speaking to the enderio devs they said it would be best to look for  net.minecraftforge.oredict.OreDictionary.getOres("ingotElectricalSteel")

**Comment by tyler489** [comment]
**MysticalAgriculture/src/main/java/com/blakebr0/mysticalagriculture/crafting/ModRecipes.java**

**Comment by BlakeBr0** [comment]
Don't remember why I used the item IDs for those, might not have had oredict names back then. 

Whenever Ender IO gets a public release on curse I'll make sure to fix this up asap.

**Comment by tyler489** [comment]
Can u push an update for this? Would like to see it fixed on my server
