### ISSUE TITLE
[Request] Fluxed Electrum Seed

### ISSUE THREAD

**Issue by GWSheridan** [BlakeBr0/MysticalAgriculture#142]
Please could we have a seed for Fluxed Electrum for the mod Redstone Arsenal mod

As some modpacks include over the top recipes like this one https://i.imgur.com/QX1ULP7.png

**Comment by Lewdicolo** [comment]
I would love Fluxed Electrum seeds! Would be great for many packs

**Comment by Reoshinta** [comment]
Yes, please implement a fluxed electrum seed, that would help so much.

**Comment by Spazley** [comment]
I definitely support this addition as it could encourage me to delve into other mods and further increase my dependence on MA. Certain over the top recipes simply compound that support.
