### ISSUE TITLE
astral sorcery seeds do not work with TE phytogenic insulator

### ISSUE THREAD

**Issue by bogger33** [BlakeBr0/MysticalAgriculture#144]
neither starmetal, rock crystal nor aquamarine seeds seem to work with the phytogenic insulator, while all other seeds from this mod do seem to work

**Comment by BlakeBr0** [comment]
This is most likely an issue on TE's end as they add the compat.

**Comment by KingLemming** [comment]
It's not really an issue exactly, just that  you apparently added new seeds and the plugin hasn't been updated.

Feel free to close this.
