### ISSUE TITLE
[Suggestion] Toggle-able Set Bonuses / Toggle-able Step Assist

### ISSUE THREAD

**Issue by Spazley** [BlakeBr0/MysticalAgriculture#145]
It would be nice to be able to toggle each set bonus with a key.  This is mostly only applicable to step assist, though someone else may see use for it with the other bonuses.  While step assist is a useful feature to me, its usefulness is situational.  I love it when I'm running around adventuring and stuff.  

I don't like it when I'm near a cliff and needing to step carefully or when I'm trying to build stuff.  Near a cliff it isn't inherently a safety concern if I'm crouching, but it does cause somewhat unpredictable movement which can be dangerous if it startles me. (It does actually startle me sometimes.)  If I'm not crouching, I risk stepping up to a block I would have normally been able to use as a railing.

When I'm building or terraforming, I tend to use the blocks next to me as barriers to restrict my movement and to better control where I'm aiming.  With step assist enabled, the barrier is removed and it becomes easy to misplace/misbreak things if I accidentally step up.  This is largely just a nuisance, but it happens very often.

As it is, I can get around the issues by disabling all set bonuses while I want step assist disabled.  However, a key to toggle the feature would be nice.

**Comment by wil-langford** [comment]
Agreed.  Building is much more difficult with step assist enabled.

I also plant my ender lilies on 1-high blocks to prevent me from stepping up and taking damage from them while harvesting.  Step assist prevents that from working.

**Comment by BlakeBr0** [comment]
I'm not going to add this simply because step assist is a part of the armors functionality. I don't want to add a toggle for every single feature everything adds simply because some people don't want to learn new mechanics. The best way to not have to deal with step assist is to not make and wear the armor.

The movement is quite predictable as it only happens when you walk into a block. Even without the armor on, the same movement happens with stairs and slabs.

**Comment by Spazley** [comment]
Totally fair. I’d originally been thinking of the set bonuses as secondary features to the protection and flight aspects, but in hindsight that doesn’t seem to be the case. I’ll still make the armor and make do. 

Anyway, thanks for the explanation and thanks for a fun mod!
