### ISSUE TITLE
[1.12.2 Suggestion] Add support to use Andesite, Diorite & Granite in Recipes

### ISSUE THREAD

**Issue by Morpheus1101** [BlakeBr0/MysticalAgriculture#146]
When making the Growth Accelerator, would you add support to be able to use the other Default stone types in minecraft?

**Comment by BlakeBr0** [comment]
The recipe already uses the oredict entry for stone, so anything that is equivalent to stone will work. If it's not in there then I guess it's not meant to be 😭 .
