### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tyler489** [BlakeBr0/MysticalAgriculture#147]
Was working on making your crops compatible with enderio rightclick to harvest and i was wondering. It seems that your block and seed state changes based on what tier the crop is in. For instance by default meteoric iron would be mysticalagriculture:tier4_meteoric_iron_seed but if someone changed it to be a tier 2 seed then it would change to mysticalagriculture:tier2_meteoric_iron_seed am i reading this correctly.

 Or is it not possible to change tiers.

**Comment by BlakeBr0** [comment]
Not sure what you're talking about. Changing the tiers doesnt change anything about the item ids.

**Comment by tyler489** [comment]
Ok so meteoric iron would be  mysticalagriculture:meteoric_iron_seed correct.

**Comment by BlakeBr0** [comment]
Pressing f3+h shows registry names for items
