### ISSUE TITLE
License not available

### ISSUE THREAD

**Issue by arcriley** [BlakeBr0/MysticalAgriculture#148]
As it stands nobody is legally permitted to use, modify, or redistribute this mod in any way. While there's a note on the project description stating that it can be used in modpacks, the rights for using and redistributing modpacks which include your copyrighted work are still expressively reserved.

By hosting your code on Github you have already granted other Github users the right to fork and thus offer modified versions of this mod - but only through the Github platform, not in modpacks.

Please consider adopting a software license which confers the rights you intend your users to have. This tool was created by github to help in this; https://choosealicense.com/

**Comment by BlakeBr0** [comment]
https://github.com/BlakeBr0/MysticalAgriculture/blob/master/LICENSE.md

This should be good enough I think

**Comment by arcriley** [comment]
Not really. That's a document explaining the rights you'd like to provide,
but is not a legal copyright license - and unless you're a lawyer you
shouldn't try to write one. Licenses are written in a specific unambiguous
manner that will hold up in court.

Your code was being distributed on our servers in various modpacks and
running on modified servers (as this came up during an audit). Our lawyers
only rarely review custom licenses - when they do we have to pay them
hourly to do so. The industry standard practice of selecting an existing
software license exists because the cost to have such licenses reviewed is
so high.

This also doesn't protect your rights as an author, for example what your
LICENSE.md does not require attribution; you've allowed others to fork your
work and include any amount of your code in their projects, which legally
speaking could be 100% of your code only changing the trademarks. So Mr
Hypothetical Badguy can fork your code, edit out your name and the mod's
name, slap his own license on it, and distribute it claiming to be his own.

For your sake as an author and for the sake of a few dozen of our users
who've had their accounts temporarily suspended due to their inclusion of
your mod, it looks like you're trying to get an effect similar to the MIT
license. This is used for quite a few Minecraft mods.
https://opensource.org/licenses/MIT

The only thing the MIT license doesn't do is restrict redistribution of
your modpack by itself, however as the trademark holder you may still
enforce your right to determine who can use the trademark "mystical
agriculture" and through which channels your official work may be
distributed as a stand-alone product.

**Comment by BlakeBr0** [comment]
Fair enough. At the end of the day I it's just a minecraft mod so it's not that important.

MIT looks good enough for what I want.

**Comment by arcriley** [comment]
It wasn't a big deal until hosting providers started getting sued. Now we
have to be paranoid and ensure all the legal rights are in place, because
the legal fees alone for a lawsuit would be enough to end our company.

**Comment by BlakeBr0** [comment]
I'm gonna work on switching all the things to MIT, thanks for the help.
