### ISSUE TITLE
[1.10.2] EnderIO Farming Station breaking tool

### ISSUE THREAD

**Issue by tedsenft** [BlakeBr0/MysticalAgriculture#15]
Top-tier tools are being broken in the EnderIO farming station. This has been reported [on the EnderIO issue tracker](https://github.com/SleepyTrousers/EnderIO/issues/3983) as well and marked as not their problem. Perhaps overriding the durability methods on the superium tools would fix this on your end?

EnderIO calls the damageItem methods.

Mod versions:
EnderCore 0.4.1.65-beta
EnderIO 3.1.164
Mystical Agriculture 1.3.9

Forge 12.18.3.2185

**Comment by blakexd** [comment]
It has -1 durability.

**Comment by BlakeBr0** [comment]
http://prntscr.com/e0dh39 looks fine to me.

**Comment by BlakeBr0** [comment]
Also worth noting that Supremium is the top tier, not Superium.
