### ISSUE TITLE
Core Remover broken

### ISSUE THREAD

**Issue by tyler489** [BlakeBr0/MysticalAgriculture#150]
attempting to use a core remover with a supremium sword returns 1supremium tool core and not the charm. this can be repeated multiple times per sword for infinate supremium tool cores

**Comment by BlakeBr0** [comment]
Not sure I understand what you mean, when using the core remover I just get the core back, as intended.

**Comment by tyler489** [comment]
When i use my core remover on my supremium sword with  a charm of strength 2 i get 1 supremium tool coore  the charm js removed.  The core remover takes 25% damage and the sword remains but with no charm this means i can get 4 supremium tool charms from 1 sword...

**Comment by BlakeBr0** [comment]
Which minecraft version is this?

**Comment by BlakeBr0** [comment]
I would assume this happens in the 1.10 and 1.11 versions. Those versions are kind of end of life as far as MA dev goes so I'm not sure if ill end up releasing a fix sadly. There should be a config option to disable charm returning which would prevent this issue but also not allow for getting charms back.

**Comment by tyler489** [comment]
1.12
 @BlakeBr0

**Comment by BlakeBr0** [comment]
When I put a supremium sword with a strength 2 charm in the crafting grid with a core remover then craft it, i get a tool core, 1 less use on the core remover, and nothing else.

**Comment by tyler489** [comment]
the sword remains in the crafting grid doesnt it?

**Comment by BlakeBr0** [comment]
Nope

**Comment by tyler489** [comment]
hmm must be a mod intereataction
try in a tinkers table or a ae terminal?

**Comment by BlakeBr0** [comment]
Doesnt happen

**Comment by tyler489** [comment]
alright... ill chalk this up to cross mod interaction... dont know which one
