### ISSUE TITLE
Yellorium and Uranium seeds issue

### ISSUE THREAD

**Issue by Yhuxz** [BlakeBr0/MysticalAgriculture#151]
The thing is if I use yellorium is it supposed to produce yellorium ingot instead of uranium ingot and vice versa?

Tried to disable yellorium generation in extreme reactor and yellorium in config but crafting 8 uranium essence produce yellorium ingot and the other way, disabled uranium generation in immersive engineering and uranium in config but crafting yellorium essences outputs uranium ingot.

Using Immersive Engineering Garden Cloche with your crops, RF Tools' Crafter as Automation and Xnet for transport

Modlist:
Mystical Agriculture - mysticalagriculture-1.12-1.6.8.jar
Immersive Engineering - Immersive Engineering 0.12 - 78
Forge - 1.12.2-forge1.12.2-14.23.2.2611
Xnet - xnet-1.12-1.6.8.jar
RFTools - rftools-1.12-7.31.jar

**Comment by tyler489** [comment]
#140

**Comment by BlakeBr0** [comment]
I guess I'll just have to make a workaround, shouldn't be too difficult. Kind of annoying though.

**Comment by Yhuxz** [comment]
Well we're sorry If this annoys you but its annoying to see the by product mismatch

**Comment by BlakeBr0** [comment]
I meant the fact that yellorium == uranium now is annoying.

**Comment by BlakeBr0** [comment]
There isnt a good way to work around this. If they are both considered uranium then I don't really see the issue anymore. You can always change the recipes to your liking using crafttweaker if it's important.
