### ISSUE TITLE
furnace not working with itemducts/servos from thermal dynamics

### ISSUE THREAD

**Issue by Bircko** [BlakeBr0/MysticalAgriculture#152]
![2018-03-31_17 10 11](https://user-images.githubusercontent.com/29576723/38164591-34b0c084-3507-11e8-9c5b-f46e16a59bcb.png)
when i remove the hopper and connect it directly it just stops importing items, when only one itemduct is connected (import/export) it works fine but if both (import and export) used none works

mysticalagriculture-1.12-1.6.8
ThermalDynamics-1.12.2-2.3.10.4-universal

**Comment by BlakeBr0** [comment]
Does the same thing happen with a vanilla furnace? I just tested with a vanilla furnace and it seems to do the same thing, which makes sense since when I made the furnaces I just copy pasta'd the code.
