### ISSUE TITLE
[Request] Tiered Seed Reprocessor

### ISSUE THREAD

**Issue by Yhuxz** [BlakeBr0/MysticalAgriculture#153]
Since the EIO's Farmer and IE's Garden Cloche have tunable processing speeds, can we have tiered reprocessor just like the tiered furnace so it can catch up processing rather than redirecting it to a quantum storage so it wont pile up

**Comment by BlakeBr0** [comment]
https://github.com/BlakeBr0/MysticalAgriculture/issues/83

I do plan to deal with this issue, but I'm still unsure if that will be for the current version or for 1.13.

**Comment by Yhuxz** [comment]
Thanks for the info
