### ISSUE TITLE
Setting hostile mob essence drop chance too high makes it not work

### ISSUE THREAD

**Issue by dragon3025** [BlakeBr0/MysticalAgriculture#156]
Mystical Agriculture version: 1.6.9
Forge Version: 14.23.2.2611

Even if I set hostile drop chance to 100%

**Comment by BlakeBr0** [comment]
Cant reproduce

**Comment by BlakeBr0** [comment]
Set it to something lower and it'll work

**Comment by dragon3025** [comment]
I see what you mean. I did 99, 90, 80 and it didn't work, but the default 20 does.
