### ISSUE TITLE
[1.12.2.] 2x2 Recipes Don't Work In The 2x2 Grid

### ISSUE THREAD

**Issue by EmosewaPixel** [BlakeBr0/MysticalAgriculture#157]
2x2 recipes don't work in the 2x2 crafting grid in the player's inventory as the recipes have specifically been made for a 3x3 grid, which means you also can't craft them in other parts of a 3x3 grid.
![image](https://user-images.githubusercontent.com/25333164/38770535-ae1c9e58-4014-11e8-973e-44e23ce6940f.png)
![image](https://user-images.githubusercontent.com/25333164/38770539-bb9cd836-4014-11e8-9cd1-151b6efa63d2.png)
![image](https://user-images.githubusercontent.com/25333164/38770541-bf9c989a-4014-11e8-8e9b-50bdaec03517.png)

**Comment by TheSnowyChickens** [comment]
Maybe its coded as shaped and not shapeless recipes?

**Comment by EmosewaPixel** [comment]
It surely isn't shapeless because only that shape works.

**Comment by MentalMouse** [comment]
Definitely not shapeless. This mod uses unslideable and unflippable recipes, to allow more combinations and permutations from a few hard-used essence types.
