### ISSUE TITLE
Can't plant inferium seeds in cropsticks

### ISSUE THREAD

**Issue by xGnoSiSx** [BlakeBr0/MysticalAgriculture#158]
I have been trying to do this and work with the configs and JSON for weeks with no results. Is it impossible on purpose or just a bug? I can plant inferium seeds in normal soil, but that's not what I want or like to do. There are videos on 1.10 that this was working. I remember it also working on older versions like 1.7.10 

I'm looking for a resolution, under this project first. Apologies if this is inappropriate.

Pack: Modified DireWolf 1.12
agricraft-2.12.0-1.12.0-a4
mysticalagriculture-1.12-1.6.9
mysticalagradditions-1.12-1.2.8 (with/without - doesn't make much difference)

I tried messing with the JSON for the seeds to no avail. Here's the default that doesn't work.
If you have a working solution/set of config files, then I'm in your debt.

{
  "path": "mod_mysticalagriculture/plants/tier1_inferium_plant.json",
  "enabled": true,
  "id": "tier1_inferium_plant",
  "plant_name": "Tier1 Inferium Crop",
  "seed_name": "Tier1 Inferium Seeds",
  "seed_items": [
    {
      "item": "mysticalagriculture:tier1_inferium_seeds",
      "meta": 0,
      "tags": "",
      "ignoreMeta": false,
      "ignoreTags": [
        "*"
      ],
      "useOreDict": false
    }
  ],
  "description": {
    "translations": {},
    "default": "Tier1 Inferium Seeds."
  },
  "growth_chance": 0.9,
  "growth_bonus": 0.025,
  "bonemeal": false,
  "tier": 1,
  "weedable": false,
  "aggressive": false,
  "spread_chance": 0.1,
  "spawn_chance": 0.0,
  "grass_drop_chance": 0.0,
  "seed_drop_chance": 1.0,
  "seed_drop_bonus": 0.0,
  "products": {
    "products": [
      {
        "min": 1,
        "max": 5,
        "chance": 0.9,
        "required": true,
        "item": "mysticalagriculture:inferium_essence",
        "meta": 0,
        "tags": "",
        "ignoreMeta": false,
        "ignoreTags": [],
        "useOreDict": false
      }
    ]
  },
  "requirement": {
    "min_light": 10,
    "max_light": 16,
    "soils": [
      "farmland_soil"
    ],
    "conditions": []
  },
  "texture": {
    "render_type": "cross",
    "seed_texture": "mysticalagriculture:items/inferium_seeds",
    "plant_textures": [
      "mysticalagriculture:blocks/crop0",
      "mysticalagriculture:blocks/crop1",
      "mysticalagriculture:blocks/crop2",
      "mysticalagriculture:blocks/crop2",
      "mysticalagriculture:blocks/crop3",
      "mysticalagriculture:blocks/crop4",
      "mysticalagriculture:blocks/crop4",
      "mysticalagriculture:blocks/inferium_crop"
    ]
  }
}

**Comment by BlakeBr0** [comment]
Does the mod not already come with the jsons for them? I honestly have no idea how to make agricraft work, never really tried to figure it out. Have you checked any modpacks that might have it working?

**Comment by xGnoSiSx** [comment]
Yes, agricraft comes with all the JSON for the myriads of seeds from all mods. All work except the inferium seeds.

The repository for the seeds JSON can be found under the agriplants moniker
[github repo]( https://github.com/AgriCraft/AgriPlants)
My concern is that there could be a change of the seed naming that leads agricraft to not recognize them at all. Can you confirm this is correct as far as naming is concerned? It think it is.

"item": "mysticalagriculture:tier1_inferium_seeds",

**Comment by BlakeBr0** [comment]
Should be correct yea

**Comment by xGnoSiSx** [comment]
That's too old - from May 2017. 1.10 is working - there are videos out there.

**Comment by PirateToshio** [comment]
I too am having this issue, it appears that the inferium seeds aren't being added to the ore dictionary, atleast for me.
![javaw_2018-05-16_17-05-27](https://user-images.githubusercontent.com/7453525/40144079-5b10495a-592b-11e8-9cc5-ed5c49d04807.png)

**Comment by PirateToshio** [comment]
Found the problem, the product of the plants in the Agricraft configs do not refrence the new ID for Inferium Essence: `mysticalaggriculture:crafting`

changing their Product: Item to the new ID solves the problem

seems to be a agricraft issue, you can probably close this @BlakeBr0

**Comment by BlakeBr0** [comment]
Surprised I didn't notice that
