### ISSUE TITLE
cant plant Infernium seeds in agricraft crop sticks

### ISSUE THREAD

**Issue by flamingram** [BlakeBr0/MysticalAgriculture#161]
hey there i cant plant my inferium seeds in the agricraft crop sticks i there a way to fix

**Comment by BlakeBr0** [comment]
There was already an issue about this thats right near the top of the list of issues https://github.com/BlakeBr0/MysticalAgriculture/issues/158

I have no idea why it doesn't work, could be an issue on agricraft's side.
