### ISSUE TITLE
[1.12.2, Idea] Theoretical infinite water source

### ISSUE THREAD

**Issue by TheSnowyChickens** [BlakeBr0/MysticalAgriculture#164]
Hello,
I see, that the "Theoretical infinite water source" has only 5 recipes for only watering cans and no other use.
For the moment, I only know that "Pressure Pipes" has something like a "infinite water source block" and maybe this could be a Idea for the "Theoretical infinite water source" too.

Only as Idea, but I would be very happy, if you can think about this. :)

Possible operational purposes:
-work as water source for farms (9x9 field or something like that)
-accessible with pipes from EnderIO, Thermal and more
-useable as bucket (Maybe? :D)
-and more^^

Thx

MC: 1.12.2

PS: I have not the best english.

**Comment by MentalMouse** [comment]
I'd say you should at least be able to use it to fill empty buckets and bottles in the crafting grid.

**Comment by BlakeBr0** [comment]
I'm going to be closing this as the 1.12 version is EOL and there is no theoretical infinite water source in newer versions.
