### ISSUE TITLE
[1.12] Anti-virus is detecting malware

### ISSUE THREAD

**Issue by faeldray** [BlakeBr0/MysticalAgriculture#166]
Mod version: 1.6.8 and 1.6.9

My anti-virus program is Avira and during a scan it did last night, it says it detected malware in 2 versions of your mod that I have installed as part of SevTech (versions 3.0.6 and 3.0.7 are both installed). I've had SevTech installed for at least a month now and I'm not sure why it didn't detect this before if it was a problem. I imagine these are false positives but I thought I'd let you know.

Clicking for more info on the malware brings me to this page: https://www.avira.com/en/support-threats-summary-product?tid=148061&threat=EXP&track=1

![image](https://user-images.githubusercontent.com/967709/40131157-ceaafe96-58fe-11e8-8fd9-950408fea5aa.png)

**Comment by BlakeBr0** [comment]
Probably one off false positive, anti-virus programs tend to do that every once in a while.
