### ISSUE TITLE
Crafts with infusion crystal causing lag

### ISSUE THREAD

**Issue by DDarkstorm** [BlakeBr0/MysticalAgriculture#167]
I use the latest version of mystical agriculture in a custom modpack on a server.

Every craft that use infusion crystal cause lags when crafted by stacks. This implies lag for 3 seconds and rollback to 3 seconds back to the time the craft was made.

Thanks for helping me.

**Comment by BlakeBr0** [comment]
Crafting is laggy in general in 1.12, nothing I can do about it

**Comment by BlakeBr0** [comment]
Any other container items would cause the same lag, there isn't anything I can do about it sadly.
