### ISSUE TITLE
Supremium armor (red armor) isnt enchantable

### ISSUE THREAD

**Issue by CharCharthemonkey** [BlakeBr0/MysticalAgriculture#169]
when trying to enchant the armor it breaks the flight on it no matter what the enchant is or on which armor piece

**Comment by BlakeBr0** [comment]
The armor intentionally can't be enchanted in an enchanting table. I'm not entirely sure what you mean by it breaks the flight?

**Comment by CharCharthemonkey** [comment]
trying to put the 2 enchants of soul bound or block reach on it will cause the flight aspect of it to stop working and the only way to fix is to recraft the entire armor to fix but mending does work on it and doesnt break the flight (soulbound is from COFH and block reach is from cyclic)

**Comment by CharCharthemonkey** [comment]
issue #833 from cyclic for the block reach enchant
