### ISSUE TITLE
[Suggestion] Mob Chunk drops

### ISSUE THREAD

**Issue by Hazmatik** [BlakeBr0/MysticalAgriculture#17]
Would be nice if the drop rate for mob chunks was higher or to have the Looting enchant effect the drop rate. By the time I've killed enough of a mob to make a semi-decent sized farm of their crops I've already gotten so many drops from them there is no need to make the farm.

**Comment by BlakeBr0** [comment]
You only ever need 4 to get a decent size farm. If the pack dev has it set to 0 then that's on them.
You can always farm zombies and use the chunks to craft other chunks.
