### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by MasterSloth1** [BlakeBr0/MysticalAgriculture#171]
so we have a server that is running we are in creative and when ever we punch a astral sorcery block we insta crash to desktop. The server is running on 
Sponge : 1.12.2-2705-7.1.0-BETA-3214
forge : 1.12.2 forge-14-23-3-2705

we originally thought it was foam fix so we tried removing it but no luck, the developer of foam fix said it was mystical agriculture so we removed
mystical agriculture
mystical agriditions
mystical agriditions compat
once we removed these 3 mods everything worked perfectly fine with no crash

crash report before removing foam fix
https://pastebin.com/nSjhnZ7M
crash report after removing foam fix
https://pastebin.com/1uS3eFRY

**Comment by BlakeBr0** [comment]
Something is setting the crop to a growth stage of 16 when the max is 7, not entirely sure what would be trying to do that.

**Comment by SacrificialFlame** [comment]
I do not know if its the new mod we are using but if it is I cant remove it and the mod dev did say custom support might be needed if his mod causes a problem
