### ISSUE TITLE
not sure which side this goes but mod compat pretty please?

### ISSUE THREAD

**Issue by CharCharthemonkey** [BlakeBr0/MysticalAgriculture#173]
trying to use the mod minecolonies with mystical agriculture for tools weapons and possibly armor and aside from 1 NPC they dont use the items at all so was wondering if thats on mystical agriculture or minecolonies?

**Comment by CharCharthemonkey** [comment]
@wissi as requested tho idk how to cross pull github things https://github.com/ldtteam/minecolonies/issues/2571

**Comment by BlakeBr0** [comment]
All of my tools should be extending the right classes already. If they don't work there may be a different issue, but as far as I can tell it shouldn't be on my end.
