### ISSUE TITLE
Lag when wearing armors with charm

### ISSUE THREAD

**Issue by LemADEC** [BlakeBr0/MysticalAgriculture#178]
As of 1.12-1.6.13, LagGoggle is reporting 1 ms lag on each player wearing a Supremium armor with at least 1 Resistance or Fire resistance charm applied to it.

**Comment by BlakeBr0** [comment]
As I'm no longer maintaining the 1.12 version I'm going to close this issue. I'll make sure to keep an eye on performance of augments in newer versions.
