### ISSUE TITLE
Fertilized Essence and Mystical Fertilizer not working

### ISSUE THREAD

**Issue by gaminggirl** [BlakeBr0/MysticalAgriculture#179]
When right clicking on a Mystical agriculture plant with any og the 2 items above nothing happens. The item is not consumed and the plant does not grow. This happens for all Mystical Agriculture plants and every time. We are running version 1.6.12

**Comment by Danklor** [comment]
Most crops are working fine for me with pack version 1.0.15, mod version 1.6.13.  However I have the trouble described above with Nether Star crops.

**Comment by Danklor** [comment]
The pack I'm playing is StoneBlock v1.0.15. I missed saying that above.
