### ISSUE TITLE
[1.10.2-1.3.9] Vibrant Alloy Essence crafting does not respect config file

### ISSUE THREAD

**Issue by SPMoo66** [BlakeBr0/MysticalAgriculture#18]
Despite changing the value for Vibrant Alloy to 1 in the mysticalagriculture_recipes config file, it remains at 3 for me. I've been able to change other values for other essences, but Vibrant Alloy refuses to budge from 3.

http://i.imgur.com/NYfnth6.png

**Comment by BlakeBr0** [comment]
Fixed in the next update. Thanks for reporting the issue.
