### ISSUE TITLE
[1.12.2] Some Materials not being loaded

### ISSUE THREAD

**Issue by ToMe25** [BlakeBr0/MysticalAgriculture#180]
The Materials from every Mod that registeres it's Items at RegistryEvent.Register<Item> not being available(without forcing the Material).

**Comment by BlakeBr0** [comment]
Any specifics? I've never had an issue with this.

**Comment by ToMe25** [comment]
For Example: 
if i am using Cucumber, Mystical Agriculture and [TriGems](https://minecraft.curseforge.com/projects/trigems) it wont load Ruby, Topaz and Sapphire(The Gems from TriGems are in the OreDictionary and they are used by Mystical Agriculture if i am forcing the Materials).

**Comment by BlakeBr0** [comment]
Ah I see. The oredictionary checks are basically useless as it would require the mod adding the item to both load before MA and register to the oredictionary at the same time. I need to specifically check for mods being loaded for it to always work. 

I'll add TriGems to the list.

**Comment by BlakeBr0** [comment]
The oredictionary checks for some of those crops are basically useless unfortunately. If the mod doesn't load and register its ores before MA then they wont work. This is the main reason I added the ability to force enable crops.

**Comment by Morpheus1101** [comment]
For a prime example of this, if you load thew Mod Embers rekindled, the base Mod Ores of Copper, Tin, Lead, Silver wont show seeds unless you force them, which i suspect is a matter of how it either registers//loads as you've indicated.

**Comment by ToMe25** [comment]
I tested that out with my own Mod before reporting.
If the other Mod registeres its Items at RegistryEvent.Register<Item> (to the Forge Registry and the Ore Dict!) Mystical Agriculture doesn't knows about them.
With registering the Items on preInit it works.(without changing anything else.)

**Comment by BlakeBr0** [comment]
As far as I know there's no reliable way to make this work for every mod. I have to add a check myself to see if each mod is loaded. I'm going to be taking a different approach in 1.13 for this which should hopefully fix problems like this.

**Comment by ToMe25** [comment]
I think you can load all this Stuff on RegistryEvent.Register<Item> with prioriry LOW to fix this.
But i tried to change that in your Mod and i were not able to do that.

**Comment by ToMe25** [comment]
That would not work for ALL Mods, but i think for the most of them.

**Comment by ToMe25** [comment]
Github allows to remote close Issues with Pull Request for other Repos?
