### ISSUE TITLE
[Suggestion] Crafting recipe for grass and tall grass

### ISSUE THREAD

**Issue by PongoSapiens** [BlakeBr0/MysticalAgriculture#184]
There is currently no nice way to acquire grass and tall grass, being able to craft them (using nature essence I imagine) would be really nice.

**Comment by MentalMouse** [comment]
I've done that and more with CraftTweaker scripts [here](https://github.com/MentalMouse/CraftTweaker-scripts).  However, my scripts are a bit elderly now, so they might need some updating.
