### ISSUE TITLE
cant craft rock crystals with essence

### ISSUE THREAD

**Issue by Aureliol** [BlakeBr0/MysticalAgriculture#188]
i finnaly made a rock crystal plant and got enough essence to produce a rock crystal but when i combine 9 essence it doesnt form a rock crystal sadly dont know why

**Comment by Aureliol** [comment]
same for aquamarine shale

**Comment by MentalMouse** [comment]
Just to cover the obvious:  Have you checked the recipe to be sure that it takes 9 essence, rather than a box of 8 or something else?

**Comment by Aureliol** [comment]
i did it conflicted with pams harvest craft for some reason because i first tried to check the recipe of it didnt show for both of the items then i removed pams harvest craft and it worked again
