### ISSUE TITLE
Settings in config causing stuff not to load.

### ISSUE THREAD

**Issue by ghost** [BlakeBr0/MysticalAgriculture#189]
when ever I change anything in the config files, from essence drop chance to how meany seeds drop from plants that I have planted, if i exit and reenter into minecraft and load up a world, it gives me an error saying (often whatever I have altered to my wishes) will suddenly not load, its annoying cause I then have to set everything to default and exit the game again just to do it all again, please fix this.

it only occurs after iv changes settings and exit the game, not as soon as I do the changes, and it works once iv done the changes, for instance, I can change the iron seeds for the iron plant to drop 5 intend of one and it works fine, but as soon as I leave minecraft and reenter in, it says iron seeds cant be loaded, or iron crops or anything related to that seed type.

**Comment by BlakeBr0** [comment]
The seed configs are for enabling/disabling the individual seeds.
