### ISSUE TITLE
[Suggestion] Allow higher tiered mob chunks to be used in lower tiered ones

### ISSUE THREAD

**Issue by blarghhh** [BlakeBr0/MysticalAgriculture#19]
It makes sense that the mob chunks which are harder to obtain, ie wither, to be able to used in the crafting recipes for lower tiered ones. after smelting them in a furnace of course

**Comment by BlakeBr0** [comment]
Or you can just get the correct tier chunks.

**Comment by macks2008** [comment]
@blarghhh or you could add a recipe to downgrade them. There's this thing called crafttweaker. Use it.
*hope this doesn't reopen the issue. I forget whether commenting on a closed issue reopens it. If it does, sorry*
