### ISSUE TITLE
Upgraded Seed reprocessor does not output to me-system.

### ISSUE THREAD

**Issue by MagnusGreiff** [BlakeBr0/MysticalAgriculture#191]
Hey. I'm trying to automate my seed reprocessor with AE2 import and export buses but I found out that the upgraded versions of the seed reprocessor does not output to the me-system. I tried different types of imports like itemducts from Thermal Dynamics and transfer nodes from Extra Utilities 2. Tried all ways with the standard seed reprocessor and that worked, then I tried again with the upgraded seed reprocessor and they failed. Is this a bug or am I just doing something wrong? I will include some images of the testing I did.

[Images](https://imgur.com/a/naibsfb)

**Comment by Dimensional** [comment]
I hate to bring up this old bug, but I'm running Release 1.7.5 for MC 1.12.2, and the Reprocessors from Infernium and above aren't outputting anything except the fuel. The basic one is outputting the essence but then again it's doesn't take any fuel like the higher tiered.
