### ISSUE TITLE
Mystical Agriculture what do the lower tinkering tables do?

### ISSUE THREAD

**Issue by Harcagnel** [BlakeBr0/MysticalAgriculture#193]
There is a Tinkering Table for all 5 tiers; however, they don't upgrade from lower levels, and the only armor with open charm spots as I understand it is the Tier 5 armor. So what are the 4 lower tier tinkering tables for? If you can use the Tier 1 table to upgrade the tier 5 armor then you don't need the other 2-5 and if you can only upgrade the lvl 5 armor and only in the level 5 tinkering table why are their even lower levels of the table? Its not clear to me what function the tinkering table provides other than an additional expense for upgrading level 5 armor. (As others have said, the FTB wiki is about the only source of information about the mod and its is woefully incomplete. https://ftb.gamepedia.com/Mystical_Agriculture)

- Thank you for any assistance/information here!

**Comment by Harcagnel** [comment]
Then what is the point of Tier 2-5?

**Comment by BlakeBr0** [comment]
They are different colors.

**Comment by Harcagnel** [comment]
Very well then. I appreciate the answer. I was trying to go strait for 5 but now, I will save my resources and worry about color if I get to the point of excess. Thanks.
