### ISSUE TITLE
Missing Inferium Furnace?

### ISSUE THREAD

**Issue by Harcagnel** [BlakeBr0/MysticalAgriculture#194]
Have Inferium Furnace been removed from the 1.12 version? Its the only thing I don't see in JEI and I attempted to craft it with a receipt I found and it didn't work. Just curious, not a big deal.

**Comment by BlakeBr0** [comment]
It's still there. Could be disabled or hidden possibly?

**Comment by Harcagnel** [comment]
Hmm... is it disabled by default? I got your mod through the "roguelike adventures and dungeons" pack. Perhaps they turned it off for the pack. I might have to go through the config files and figure out how to enable it.

**Comment by MentalMouse** [comment]
Are the higher tiers there?  If not, your modpack author may have decided to handle furnace upgrades through a different mod, or skip them altogether.

**Comment by Harcagnel** [comment]
Well it seems like they are ALL disabled, but one of the other mods also seems like it speeds up furnaces. Given that an that it is still part of the pack, I am guessing it might have been deliberately disabled in the mod pack to avoid a conflict.

**Comment by MentalMouse** [comment]
Yeah, that's how I'd bet.  MA has one central feature, which is resource farming.  Aside from the support structure for that, the rest (furnaces, weapons, armor) is pretty much candy, and a good modpack maker will be careful about mods stepping on each other's turf.
