### ISSUE TITLE
Inferium drops from mobs?

### ISSUE THREAD

**Issue by MentalMouse** [BlakeBr0/MysticalAgriculture#2]
The ore, natch.  Zombies... OK, could be parallel to iron ingots, but it seemed to happen rather more often.  But... chickens?  (mysticalagriculture[1.11]-1.3.6.jar)

**Comment by BlakeBr0** [comment]
You can lower or disable the drop chances in the config.

**Comment by MentalMouse** [comment]
Looking at that... I note that passive mobs actually have a higher drop  chance than hostile ones.

In general, I assume a mod's default represent how the maker chose to balance the mods, I just found this rather odd.

**Comment by BlakeBr0** [comment]
Whats wrong with that?

**Comment by MentalMouse** [comment]
Inferium, Inferium everywhere!  

Seriously, mobs normally drop items specifically associated with them -- pieces of the mob, items they were carrying, items reflecting their appearance (e.g., ghast tears) or role (evoker totems).  IIRC, the biggest stretch in vanilla is the zombie rare drops;  but then, zombies conceptually come out of the ground (graves), so it's plausible they might have a carrot or potato, and they have armor and weapons from somewhere, so it's reasonable they could have an iron ingot from the same source.  

But why would _all_ monsters, much less _all_ farm animals, potentially have pieces of inferium?

**Comment by BlakeBr0** [comment]
As I said you can disable it in the config. I made mobs drop Inferium because you generally need quite a lot of it. It's also an important way to get Inferium in certain types of modpacks (like skyblocks).
