### ISSUE TITLE
Load Order

### ISSUE THREAD

**Issue by Slowpoke101** [BlakeBr0/MysticalAgriculture#20]
Would it be possible to make a change to your load orders to register items in Preinit (disregard oredict or mods loaded) and do the ordict/mod check later and disable as neeeded. 

We have run into a situation with Ex Nihilo Ascendo where we are trying to add the Mystical Agriculture seeds into the drop table for the sieves (for a Custom version of Sky Factory 3)  This is working fine on single player, however on a server, no items are dropping at all.

**Comment by BlakeBr0** [comment]
When do you need this fixed by?

**Comment by BlakeBr0** [comment]
Nevermind, a fix should be out on curse in a bit,

**Comment by Slowpoke101** [comment]
awesome thanks very much for your help on this.
