### ISSUE TITLE
Fertilized essence drop rate not working. Version 1.12.2 - 1.7.1

### ISSUE THREAD

**Issue by akennedy4155** [BlakeBr0/MysticalAgriculture#200]
I have gotten 4 essence and I have produced maybe 4 stacks of inferium from crops and then destroyed them by hand.  I know that they don't drop with a 'soft harvest' but I have also tried using the Actually Additions farmer as well as doing it by hand.

Here is the config info on the server - 
    # Enable Fertilized Essence? [default: true]
    B:fertilized_essence=true

    # Percentage chance that a Resource Crop will drop a Fertilized Essence when harvested. [range: 0 ~ 100, default: 5]
    I:fertilized_essence_chance=8

**Comment by BlakeBr0** [comment]
Inferium crops dont drop fertilizer, every other crop should though.

**Comment by akennedy4155** [comment]
Cheers! Thanks for the info. I couldn't find this online. That explains it then because I started growing a few water crops and it must have dropped from that... But after that I just grew straight Inferium.  Thanks for the quick response.

**Comment by akennedy4155** [comment]
@BlakeBr0 How would you feel if I added some config options to the mod like FertilizedEssenceSpawnsFromInferium = false/true and FertilizedEssenceSpawnFromInferiumRate = 0-100 so that the server owner could decide how they want this to behave?  I'm a 4th year computer science student about to graduate and I'm looking for a fun project.
