### ISSUE TITLE
[Suggestion] Vanadium Seeds

### ISSUE THREAD

**Issue by Freebi85** [BlakeBr0/MysticalAgriculture#203]
Hello =)
Thank you very much for this great mod! I really appreciate your work.
I wanted to suggest introducing vanadium seeds. (if possible)
Vanadium Ore is mainly introduced by Zoesteria Biomes and Rockhound Mods.

Link to Zoesteria Biomes on Curse:
https://minecraft.curseforge.com/projects/zoesteria-valoegheses-basic-expansions?gameCategorySlug=mc-mods&projectID=305959

Freebi

**Comment by BlakeBr0** [comment]
I have no plans to add any more crops to the 1.12 version. However if the mod comes around for 1.14 I will look into this.

**Comment by BlakeBr0** [comment]
I will not be adding support as the 1.12 version is EOL. My plans for mod support in newer versions is to just have the most common mods supported by default and leave the rest to addons people will probably make.
