### ISSUE TITLE
[1.12.2] [1.14.4] [suggestion] Essence Recipes for Charcoal and Magma Cream

### ISSUE THREAD

**Issue by ToMe25** [BlakeBr0/MysticalAgriculture#205]
I suggest you to add Essence Recipes for Charcoal, Eye of Ender and Magma Cream.

An example Recipe for 24 Charcoal:
```
"CWC",
"W W",
"CWC",
'C', "mysticalagriculture:coal_essence",
'W', "mysticalagriculture:wood_essence"
```

An example Recipe for 3 Eye of Ender:
```
"BEB",
"E E",
"BEB",
'B', "mysticalagriculture:blaze_essence",
'E', "mysticalagriculture:enderman_essence"
```

An example Recipe for 6 Magma Cream:
```
"BSB",
"S S",
"BSB",
'B', "mysticalagriculture:blaze_essence",
'S', "mysticalagriculture:slime_essence"
```

**Comment by MentalMouse** [comment]
The thing is, MA recipes generally are for "raw materials" -- either blocks found in the world, or mob drops.  Ores are represented by their mined or smelted results, and experience gets a special case.

Charcoal is purely a craft product, and while magma cream _is_ a drop, it's also a craft product.  If you want to produce them directly with recipes, I'd suggest CraftTweaker.

**Comment by ToMe25** [comment]
@MentalMouse no!
There are many supported materials that are "Craftable" most of them are processed and not crafted but that is also the case for Charcoal.

For Example: Steel, all the Enderio Materials, Graphite and Stone.
