### ISSUE TITLE
[Suggestion] Tier Changes

### ISSUE THREAD

**Issue by Inonedn** [BlakeBr0/MysticalAgriculture#206]
I think the Dye Crops should be demoted to Tier 1 crops while Nature crops are promoted to Tier 2. The nature crop is surprisingly overpowered for a tier 1 with a gigantic amount of recipes, basically guaranteeing survival instantly. The recipe is surprisingly cheap for such a powerful crop.

**Comment by LeSwede** [comment]
Honestly, I agree with this assessment.

**Comment by Yhuxz** [comment]
Well you could just easily change that in the config
