### ISSUE TITLE
Startup crash with 1.7.5, Agradditions 1.3.1, TCon 2.12.0.135; 1.7.3 works.

### ISSUE THREAD

**Issue by Xetaxheb** [BlakeBr0/MysticalAgriculture#208]
https://paste.dimdev.org/itasexewed.mccrash

**Comment by Mrthomas20121** [comment]
https://paste.dimdev.org/ociqahakac.mccrash i get the same crash. hope it get fixed

**Comment by RetiredNavyVet** [comment]
I can confirm the crash; conflict with MA 1.7.5 and Buildcraft 7.99.24.1.

**Comment by BlakeBr0** [comment]
Should be fixed in version 1.3.2 of agradditions
