### ISSUE TITLE
[Suggestion] Step Assist Config Option

### ISSUE THREAD

**Issue by LeSwede** [BlakeBr0/MysticalAgriculture#211]
I was wondering if it would be possible to have the Step Assist functionality on the armor be a config option. Not every one like it (me included) as it can be really annoying when building, placing blocks and WHAM you are one block higher :P

**Comment by Chunkimunki** [comment]
Right there with you bud ;)

**Comment by Semi0ne** [comment]
I would also very much like a separate config option for the Step Assist functionality. Water Breathing and No Fall Damage I suspect will be seen as a great addition to most people, but Step Assist is more of a love it or hate one. And once you can fly with Supremium armor it's functionality becomes next to redundant.

So please consider adding a separate config option for Step Assist functionality.

And thanks for this amazing mod, I'm absolutely loving it!

**Comment by BlakeBr0** [comment]
As I won't be updating the 1.12 version anymore, I won't be implementing this. On the bright side though, in the 1.14 version step assist is opt-in.
