### ISSUE TITLE
[Suggestion] Growth Accelerator tiers

### ISSUE THREAD

**Issue by Zangdorx** [BlakeBr0/MysticalAgriculture#214]
Multiple tiers of Growth Accelerator could be a nice addition. Since everything else in the mod is tier-based, it would fit nicely.
It could allow for easier setup and equal/greater speed boost.
If even faster growth seems too strong, making their range smaller could prevent them from being able to speed up even more than the current Growth Accelerators.
Or they could allow for even faster growing.

**Comment by BlakeBr0** [comment]
This is added in the 1.14 version. Thanks for the suggestion!
