### ISSUE TITLE
Cows drop inferium essence instead of leather

### ISSUE THREAD

**Issue by EnderT5** [BlakeBr0/MysticalAgriculture#215]
Cows don't drop leather when they killed, instead they drop inferium essence.

MOD LIST: https://hastebin.com/igehuwazaq.md
SERVER LATEST LOG: https://drive.google.com/file/d/1TzspJj4benhLrLFtdUnZw64GXSDREJbJ/view?usp=sharing

**Comment by BlakeBr0** [comment]
There is probably a mod in the pack removing the leather drop. Plus there is no way this could be caused by inferium dropping as all that's doing is adding a drop to the list.
