### ISSUE TITLE
Accelerator Performance Issue

### ISSUE THREAD

**Issue by Sir-Will** [BlakeBr0/MysticalAgriculture#216]
MysticalAgriculture-1.12.2-1.7.5
![](https://i.imgur.com/obRGUJE.jpg)

**Comment by runescapejon** [comment]
Having the same issue https://gyazo.com/4e17d63f28335160b72ba7ddbd0dabbe

**Comment by AntonioToni** [comment]
Same issue here https://cdn.discordapp.com/attachments/648332488850014233/658399027804504114/unknown.png

**Comment by BlakeBr0** [comment]
I'm going to be closing this as the 1.12 version is EOL.
