### ISSUE TITLE
Unable to craft copper

### ISSUE THREAD

**Issue by Vuuubi** [BlakeBr0/MysticalAgriculture#217]
I have modified a modpack called OmniFactory and I planned on growing copper, but now I have some copper essence and I cant find a way to craft copper with it. Even JEI says it doesn't have any purpose, is there any config or something to fix?

**Comment by jkkiller101** [comment]
Hey Vuuubi! I was just playing this last night and had the exact same issue... I had the exact same idea when playing even though for some it may ruin the experience for some. I noticed its not only for copper but for many materials that are involved in greg tech like silver, lead, and so on. If you or anyone has found a workaround it would be much appreciated.

**Comment by BlakeBr0** [comment]
I'll look into this. As long as there's a an ingot in the correct oredictionary entry the recipes should work though.

**Comment by BlakeBr0** [comment]
I'm going to close this as I no longer support the 1.12 version. The newer versions should not have this issue any longer.
