### ISSUE TITLE
Add support for thaumic additions

### ISSUE THREAD

**Issue by vaderkos** [BlakeBr0/MysticalAgriculture#218]
Please, could you add support for thaumic additions metals (Mithrillium, Adaminite, Mithminite)? Thanks.

**Comment by BlakeBr0** [comment]
I have no plans to add any more crops to the 1.12 version. However if the mod comes around for 1.14 I will look into this.

**Comment by BlakeBr0** [comment]
I will not be adding support as the 1.12 version is EOL. My plans for mod support in newer versions is to just have the most common mods supported by default and leave the rest to addons people will probably make.
