### ISSUE TITLE
Core remover

### ISSUE THREAD

**Issue by InsaneBiscuit** [BlakeBr0/MysticalAgriculture#219]
So I'm playing a modpack called Roguelike Adventure and Dungeons (1.28) and the core remover doesnt seem to be working. I can craft it but I cant remove the core from the inferium watering bucket. Am I doing something wrong? I've joined the mod packs discord channel and raised the issue there as well.

**Comment by BlakeBr0** [comment]
This must be an issue with the pack as the recipes work fine for me.
