### ISSUE TITLE
/give command does not work with inferium thru supremium essences

### ISSUE THREAD

**Issue by Stiingrae** [BlakeBr0/MysticalAgriculture#223]
I am in the process of integrating the Mystical Agriculture crops into the "bonsai trees" mod. Everything works as it should, except that the essences do not drop for Inferium Crops tier 1-5. When troubleshooting I noticed that the /give command also doesn't work for the essences, with the error "There is no such item with name mysticalagriculture:inferium_essence"
![Inferium Essence Error](https://user-images.githubusercontent.com/7354002/64110464-791ba780-cd3f-11e9-979a-59d2e72eea6f.png)
![Inferium_Essence_Files](https://user-images.githubusercontent.com/7354002/64110465-7ae56b00-cd3f-11e9-98de-6d4aa61c4a13.png)

**Comment by BlakeBr0** [comment]
You have to use the item ids. IIRC inferium is mysticalagriculture:crafting with a meta of 0 for example. Use f3+h to see them.

**Comment by Stiingrae** [comment]
That worked beautifully. Is there a reason you set those 5 plants up that way instead of using "inferium_essence" etc like the rest of the essences? These 5 are the only ones that have to be called as a drop by "mysticalagriculture:crafting" with meta 0-4 rather than "stone_essence" or such.

**Comment by BlakeBr0** [comment]
Back when I made the 1.12 port I figured I would consolidate a bunch of ids. Didn't really need to do that for items to be fair but its too late now. Glad you got your stuff working
