### ISSUE TITLE
[1.12.2] Uranium 238 is part of Nuclearcraft as well

### ISSUE THREAD

**Issue by GigaOtomia** [BlakeBr0/MysticalAgriculture#224]
I was poking around in the Agricraft mutations, since I'm making my own modpack, and I see the existence of a Uranium 238 seed. Odd, I think to myself. I've got Uranium 238 in the game, why can't I see the seed for it? I check the configs, there it is, right there beside regular Uranium. Got a tier and everything. So why isn't the seed enabled?

Then I check the curseforge page for this mod, and I see Uranium 238 listed under Industrialcraft. "Ohh," I say aloud, "I need to install Industrialcraft to use that seed!" Unfortunately for me, I won't be installing Industrialcraft, because I already have Tech Reborn, which is Industrialcraft but better, in my opinion, and I'm not installing and disabling an entire mod just for a seed from another mod.

So I ask you, could you change the compatibility of Uranium-238 seeds to look for Nuclearcraft as well as Industrialcraft?

**Comment by BlakeBr0** [comment]
I'm going to close this since I am no longer working on the 1.12 version. 

I'm going to be making sure that these annoying mod compat issues aren't a thing anymore in the new versions. For now you can force enable crops in the config to get this to work.
