### ISSUE TITLE
crux support for all crops

### ISSUE THREAD

**Issue by TheNimbleNinja** [BlakeBr0/MysticalAgriculture#225]
i was wanting to make a mod that added this to all your crops and other mods that were addons to this mod, but i was told it might not be possible to do. so im asking for you to add the ability to have cruxs for each crop to be under them to grow. thanks for reading :)

**Comment by BlakeBr0** [comment]
I plan on adding cruxes to the base mod in the 1.14 version, so it would 100% be possible at that point. As far as 1.12 there is no clean way to do this though. You would have to basically overwrite all of the crops with your own and include the crux functionality yourself. This would probably break a lot of stuff however.

**Comment by BlakeBr0** [comment]
This is possible now with the new API.
