### ISSUE TITLE
Adding Advent Of Ascension Seeds

### ISSUE THREAD

**Issue by Pokesmile-modded** [BlakeBr0/MysticalAgriculture#226]
Adding these types of seeds to mystical agriculture to be able to actually produce AoA3´s Infinite Resources

Tier 3: Limonite, Opteryx, Rammerhead Hive, Moonstone, Halycon (Animal/Milk)
Tier 4: Runium, Rosite, Gemenyte, Jewelyte, Ormamyte, Jade, Charged Runium, Urka (Animal)
Tier 5 Amethyst, Sapphire, Crystallinite, Bloodstone, Elecanium, Shyrestone, Skeletal, Mystite, Lyon, Varsium, Elecanium, Blazium, Ghastly, Ghoulish, Lunar, Baronyte,Shyregem and Gemstones (Gemstones essences + Dye)

**Comment by BlakeBr0** [comment]
I have no plans to add any more crops to the 1.12 version. However if the mod comes around for 1.14 I will look into this.

**Comment by BlakeBr0** [comment]
I will not be adding support as the 1.12 version is EOL. My plans for mod support in newer versions is to just have the most common mods supported by default and leave the rest to addons people will probably make.
