### ISSUE TITLE
Problem with ME Systems

### ISSUE THREAD

**Issue by XiNaru** [BlakeBr0/MysticalAgriculture#227]
Hello, 
i have a problem. I Use the Mod in 1.12.2 and i cant it auto craft in my refined storage mod. 
i comes always the message, that the infusion crystal were missing. but i habe the unlimited (master) infusion crystal.

**Comment by BlakeBr0** [comment]
You would need a master crystal for each step, since it 'takes' the crystal out for one of the recipes. If there's a way to force it to craft it should work just fine however.
