### ISSUE TITLE
[1.12.2] Unable to Extract Essence from Seed Reprocessor Using Item Conduits

### ISSUE THREAD

**Issue by spooky-soft** [BlakeBr0/MysticalAgriculture#228]
So I'm trying to automate my essence farm, and I can successfully input seeds into a reprocessor just fine, but I can't extract essence from it at all, from any face. 

Here's my configuration: 

[Extract & Insert for Seed Reprocessor]
https://i.imgur.com/XRMMcD5.png

[Insert for ME System Chest]
https://i.imgur.com/Pabw9gq.png

I've tried doing the extraction from all sides of the seed reprocessor, with identical results. 

Yes, I am aware of [this issue](https://github.com/BlakeBr0/MysticalAgriculture/issues/81), however the thread says the issue is marked as resolved, when it clearly is not.

**Comment by BlakeBr0** [comment]
It works, you just have to pipe into the top and pipe out from the bottom.
