### ISSUE TITLE
Silver Essence Not Crafting 

### ISSUE THREAD

**Issue by ltkalpokas** [BlakeBr0/MysticalAgriculture#229]
Silver cannot be crafted using silver essence, also it doesn't show what can be crafted from silver essence. I don't know if this is a problem for me or it's just a bug, but I would like to know if there is a way to solve this because I have a lot of silver essence and it would be pointless to put it in the bin. 
Thanks.

**Comment by BlakeBr0** [comment]
If you are sure there is an item in the game in the "ingotSilver" oredictionary entry you can try forcing the crop to be enabled in the config. I'm not sure if that would solve your issue though.
