### ISSUE TITLE
Using Enchanted Infusion Crystal Ignores Enchantment Effect (Unbreaking)

### ISSUE THREAD

**Issue by Danekjovax** [BlakeBr0/MysticalAgriculture#235]
Version Info:
modpack-Dungeons Dragons & Space Shuttles v.6.3
forge-1.12.2-14.23.5.2807-universal
MysticalAgriculture-1.12.2-1.7.5
MysticalAgradditions-1.12.2-1.3.2
mysticallib-1.12.2-1.3.8

I recently enchanted my Infusion Crystal with Unbreaking III with the hopes it would help make it more durable during use.

Well, after converting thousands upon thousands of Inferium essence with it, I have great confidence to report that thel Unbreaking enchantment used on these crystals are being ignored.

See the screenshots below. 

In this example, I placed enough essence for 60 conversions, and observing the durability before/after, you'll see the durability was used each and every operation.
![2019-10-26_07 57 31](https://user-images.githubusercontent.com/10191173/67628968-1f1df680-f845-11e9-9f70-ee10dec729db.png)
![2019-10-26_07 57 50](https://user-images.githubusercontent.com/10191173/67628973-2cd37c00-f845-11e9-8719-e2864fc8b532.png)

Thank you for your time and this great mod! :2)

**Comment by BlakeBr0** [comment]
I don't plan on updating the 1.12 version anymore. I will add this to the 1.14 versions however.

**Comment by BlakeBr0** [comment]
This should be the case in 1.15
