### ISSUE TITLE
Consuming Master Infusion Stone while crafting

### ISSUE THREAD

**Issue by L0neGamer** [BlakeBr0/MysticalAgriculture#237]
Whenever I use the master infusion to craft essences together, the master infusion stone is consumed.

This was tested with inferium -> prudentium and prudentium -> tertium, in both a vanilla crafting table and a crafting station from Silent Gear.

Possible negatively interacting mods (subset of mod list):
RandomPatches, Just Enough Items, crafting tweaks

I removed FastWorkBench and it wasn't that.

**Comment by BlakeBr0** [comment]
Are you using the latest version of Cucumber Library?

**Comment by L0neGamer** [comment]
We are using cucumber 2.0.4, and mystical agriculture 2.0.1
Apologies for not mentioning versions in my initial post.

Also, seeing now that there is a fix for my exact issue in cucumber 2.0.5, I'm happy for this issue to be closed; again, apologies for the wasted time.
