### ISSUE TITLE
Infinity Supremium Bow with Triple Shot charm generates infinite tipped arrows

### ISSUE THREAD

**Issue by jolaquai** [BlakeBr0/MysticalAgriculture#238]
Modpack: _FTB Presents: Skyfactory 3 v3.0.15_
Minecraft 1.10.2

Issue: Supremium Bow (w/ _Triple Shot_ charm and the _Infinity_ enchantment) generates infinite tipped arrows
Steps to recreate:
1. Put _Triple Shot_ in the charm slot of a Supremium Bow
2. Enchant it with _Infinity_
3. Put singular tipped arrows in your hotbar / closer to the bow than any other kind of arrow (so they're used instead)
4. Use the bow and collect three extra arrows

Video: https://streamable.com/5zq3f

**Comment by BlakeBr0** [comment]
I'm going to close this issue as the 1.10 version is EOL.
