### ISSUE TITLE
enhancements for 1.14 needed

### ISSUE THREAD

**Issue by Warbringer12** [BlakeBr0/MysticalAgriculture#239]
mystical fertilizer doesn't work
watering cans do not fill up
add coal variants for all tiers of essences
add back in set bonus for higher tier armor
add back in tokens for people

**Comment by BlakeBr0** [comment]
1. Fixed
2. Fixed
3. Added in Mystical Agradditions
4. Set bonuses will come back in some form at a later date
5. Augments
