### ISSUE TITLE
Exoflame (Botania) support for the furnaces

### ISSUE THREAD

**Issue by BeardStroker** [BlakeBr0/MysticalAgriculture#24]
Just wondering if it is intentional that the furnaces will not run when using the exoflame flower from botania. If it's not intentional it would be a welcome addition :)

**Comment by BlakeBr0** [comment]
I thought the exoflames just generated mana?

**Comment by BeardStroker** [comment]
Thats the endoflames, the exoflames use mana to power nearby furnaces with a small efficiency boost

**Comment by BlakeBr0** [comment]
I see, I'll look into it. Might also keep it so they don't work for balance purposes.

**Comment by dmb1881** [comment]
@BeardStroker Might I suggest if you happen to have blood magic installed, to use Lava crystals? They are super handy because it's essentially an infinite fuel source.
