### ISSUE TITLE
Issue w Lycanites i think

### ISSUE THREAD

**Issue by German998** [BlakeBr0/MysticalAgriculture#240]
This is a bug with Mystical Agriculture accessing ItemColors, the way this is done has changed in newer versions of Forge, because Lycanites Mobs also uses item colors but in the new way it can trigger this bug in mods that haven't updated.

[crash-2019-11-06_08.03.47-client.txt](https://github.com/BlakeBr0/MysticalAgriculture/files/3815086/crash-2019-11-06_08.03.47-client.txt)
[latest (1).log](https://github.com/BlakeBr0/MysticalAgriculture/files/3815088/latest.1.log)

**Comment by BedrockLegends** [comment]
https://github.com/BlakeBr0/MysticalAgriculture/issues/241
