### ISSUE TITLE
 [1.12] arcane world sapphire and amethyst support, mystical world amethyst support

### ISSUE THREAD

**Issue by majijn** [BlakeBr0/MysticalAgriculture#242]
mystical world also adds amethysts, i see theres config options for these gems and yet they didnt seem to be recognised

**Comment by BlakeBr0** [comment]
I will not be adding support as the 1.12 version is EOL. My plans for mod support in newer versions is to just have the most common mods supported by default and leave the rest to addons people will probably make.
