### ISSUE TITLE
rustic herbs, sapling, logs and brewing support

### ISSUE THREAD

**Issue by majijn** [BlakeBr0/MysticalAgriculture#243]
the ids for the items are:
for saplings
olive "rustic:sapling"0
ironwood "rustic:sapling"1
for logs
"rustic:log"0 for olive wood
"rustic:log"1 for ironwood

for herbs
"rustic:aloe_vera"
"rustic:blood_orchid"
"rustic:chamomile"
"rustic:cohosh"
"rustic:deathstalk_mushroom" (this one is from the nether)
"rustic:horsetail"
"rustic:mooncap_mushroom"
"rustic:wind_thistle"
"rustic:cloudsbluff"
"rustic:core_root"
"rustic:ginseng"
"rustic:marsh_mallow"
"rustic:wildberry_bush"

for brewing support
"rustic:beehive"
"rustic:honeycomb"
"rustic:ironberries"
"rustic:wildberries"
"rustic:grapes"
"rustic:apple_seeds"

**Comment by BlakeBr0** [comment]
I will not be adding support as the 1.12 version is EOL. My plans for mod support in newer versions is to just have the most common mods supported by default and leave the rest to addons people will probably make.
