### ISSUE TITLE
unable to add charms to armor/tools

### ISSUE THREAD

**Issue by gamerpudding** [BlakeBr0/MysticalAgriculture#244]
![2019-11-11_14 15 09](https://user-images.githubusercontent.com/57328109/68590327-8915dd00-048e-11ea-8c26-b547dac2f394.png)
you can see that it won't show the armor with the charm to it and i can't grab it either. (i am playing stoneblock 2)

**Comment by BlakeBr0** [comment]
I would always recommend checking the uses of an item in JEI before creating a bug report. You install charms using the tinkering table.
