### ISSUE TITLE
Master Infusion Crystal

### ISSUE THREAD

**Issue by fistidgious** [BlakeBr0/MysticalAgriculture#248]
running latest version of M/A on forge 1.14.4 master infusion crystal only gives 1 infusion upgrade and dissapears.

**Comment by jmdev91** [comment]
Works a little better in All the Mods 4 for 1.14.4. There's a bug in the Crafting Tweaks mod there that causes items to sometimes visually disappear in those slots (affects the whole grid, never individual slots), could this be what you're experiencing? I can generally hit the take all button or leave the crafting interface to get my items back.

**Comment by BlakeBr0** [comment]
This should not be an issue with the latest Mystical Agriculture + Cucumber versions.
