### ISSUE TITLE
Flight not working

### ISSUE THREAD

**Issue by IamStig** [BlakeBr0/MysticalAgriculture#249]
I'm wearing the supremium armor, I am on single player, I have no flight.
Also can not find any config for flight in any of the 3 config files that I have found

I forgot to say ...1.14.4 2.0.3

**Comment by Jay-TAK** [comment]
I second this. i have just crafted the full Supremium Armour set and i am unable to fly - i am on my own server and i can see that the config has "    B:supremium_flight=true " doesn't seem to make a difference whether it is true or false - for now i am using my jet pack but this would be much more ideal.. The server settings has flight enabled. i have tried deleting the items and spawning a new set in same results..

**Comment by Jay-TAK** [comment]
**** 1.12.2-1.7.5

**Comment by BlakeBr0** [comment]
This no longer applies now that there's the Flight Augment.
