### ISSUE TITLE
Customized tier config client<>server problem

### ISSUE THREAD

**Issue by Thyriel** [BlakeBr0/MysticalAgriculture#25]
Hi,

i changed quite a lot in the config file - disabled various seeds, changed tier of some, activated harder ingots, etc.
Except changing tier of a seed it seems that every setting is correctly sent to the client on server connection (so the client doesn't need the servers config file) - even harder ingot settings displays the correct recipe on the client in JEI.
Only changing tiers doesn't work. (e.g. iron seed= tier 2 instead 3)
They are displayed as the old tier on the client and the wrong recipe is shown. I did not test which recipe does work.
Copying the server config to the local config solves the problem, but it's not optimal having to distribute server config files to all the players.

MA Version: 1.4.1a

**Comment by BlakeBr0** [comment]
From my experience I've always had to have the server configs on my client for things to work.
