### ISSUE TITLE
Seed Reprocessor incorrect slot management 

### ISSUE THREAD

**Issue by IamStig** [BlakeBr0/MysticalAgriculture#251]
The reprocessor has issues, (1) it accepts inputs to both the fuel and item slots from all sides AND (2) it allows output from all the slots.
The problem with the 2nd issue is that placing a reprocessor on a hopper allows ALL items to fall through....from the output, input and fuel slots.
The problem with the 1st issue is that placing a hopper on top (expected function) for seeds and back or side for fuel is that when the seeds run out coal is allowed into the input slot (this is another problem ...not limiting what can go into the input slot, the 1st is a lack of sidedness which would not be noticed if limiting coal to the fuel slot was in place)
The result is to make automation a huge problem, a vanilla furnace should be the basis of how this functions. Note: I was using the Supremium reprocessor  

I forgot to say ...1.14.4 2.0.3

**Comment by jmdev91** [comment]
I'm getting this issue as well in All The Mods 4 for Minecraft 1.14.4 using the Tertium Seed Reprocessor.
