### ISSUE TITLE
[1.14.4] JEI recipes missing in multiplayer

### ISSUE THREAD

**Issue by Draradech** [BlakeBr0/MysticalAgriculture#253]
JEI recipes are missing in multiplayer, unless a singleplayer world was openend before.

Versions:
Forge: 28.1.96
Cucumber-1.14.4-2.0.5
jei-1.14.4-6.0.0.25
MysticalAgriculture-1.14.4-2.0.3

**Comment by Shindur** [comment]
Can confirm, just tested this myself as I was also having the same issue.

**Comment by BlakeBr0** [comment]
Should be fixed in the next update.
