### ISSUE TITLE
unable to plant seeds 1.12.2 using MysticalAgriculture-1.12.2-1.7.3

### ISSUE THREAD

**Issue by topgun79** [BlakeBr0/MysticalAgriculture#256]
I am unable to plant the following seeds from MysticalAgriculture

Tanzanite - Biomes-o-Plenty
Apatite Seeds - Forestry
Quicksilver Seeds - Thaumcraft
Thaumium Seeds - Thaumcraft
Void Metal - Thaumcraft

**Comment by BlakeBr0** [comment]
All crops should work the same. If you mean they don't exist you can force enable them in the config.
