### ISSUE TITLE
Nature Seeds don't grow...

### ISSUE THREAD

**Issue by pixelblob** [BlakeBr0/MysticalAgriculture#258]
Nature seeds won't naturally grow. So I can use the fertilized essence stuff on the nature seeds and they will grow but they won't grow by them selfs, I have even tried using growth crystals.

btw I'm playing stoneblock 1
Version 1.7.3 of your mod.

**Comment by BlakeBr0** [comment]
Make sure they are well lit. IIRC they need light level 8 or higher.
