### ISSUE TITLE
[Question] 1.14.4 Disabling Items/Recipes

### ISSUE THREAD

**Issue by Xaikii** [BlakeBr0/MysticalAgriculture#259]
Looking at the config there doesnt seem to be a way to prevent Items from being loaded and neither to disable Recipes. Or at least I catn find it. 
Therefore is there a way to disable Recipes of Seeds, e.g. via CraftTweaker or anything like that?
Also will there be a config to disable certain items/seeds like it used to be possible in 1.12.2?

**Comment by BlakeBr0** [comment]
- You would edit recipes using datapacks
- You aren't supposed to be able to disable blocks/items, that being said something similar is planned but would be with an addon mod

**Comment by BlakeBr0** [comment]
You can now create, edit, or disable crops using my new addon Mystical Customization in 1.15.
https://www.curseforge.com/minecraft/mc-mods/mystical-customization
https://mods.blakebr0.com/docs/mysticalcustomization
