### ISSUE TITLE
Binding use / place block to a keyboard button makes watering can super fast

### ISSUE THREAD

**Issue by tiggerbiggo** [BlakeBr0/MysticalAgriculture#262]
Self explanatory, but I was trying to go AFK watering can mode by resting an object on numpad 0, with a watering can in my offhand and a hoe in my main hand so that i am simultaneously harvesting and watering. When it's bound to a different button the water particles are much more dense and everything grows insanely, overpoweredly fast, like 4x faster than normal. This is with the basic watering can, i havent tried with the others.

**Comment by BlakeBr0** [comment]
Well this issue is annoying. https://github.com/BlakeBr0/MysticalAgriculture/commit/b024b714c7e84584a9facb90c93f449cc692186b seems to slow it down a bit, but I can't figure out a way to make this work properly.
