### ISSUE TITLE
1.14.4 flight not working

### ISSUE THREAD

**Issue by Sh1mz** [BlakeBr0/MysticalAgriculture#263]
I have put the flight augment on my supremium boots and am still unable to fly, any ideas?

**Comment by jellonek** [comment]
it could be disabled in modpack settings. give some more details - which minecraft version, which forge version, which modpack, which version of MA?

**Comment by Sh1mz** [comment]
My bad, Minecraft 1.14.4, I don't know the forge version fully but it's the latest, the modpack is TNP limitless and MA version is 2.0.4

**Comment by Sh1mz** [comment]
I just checked what the forge version was, as I wasn't home when I wrote that, it is version forge-28.1.107

**Comment by jellonek** [comment]
My bad also - i don't see any config option for flight disabling in https://github.com/BlakeBr0/MysticalAgriculture/blob/1.14/src/main/java/com/blakebr0/mysticalagriculture/config/ModConfigs.java

**Comment by OmniKhaos77** [comment]
The Flight Augment needs to go on the Chest Plate, not the boots.

**Comment by Sh1mz** [comment]
I had it in all armor parts and it still didn't work, just tried putting it in chestplate and it still did not work so

**Comment by Mercenary4Hire** [comment]
I have been having this issue as well. it seems to not work sometimes after relogging or going between dimensions. Simply taking off the chest piece and putting it back on again seems to fix it. Same issue on any of the other armor pieces as well.

Using version 2.0.4
Forge 28.1.109
Pack all the mods 4 version 0.3.1

**Comment by Sh1mz** [comment]
Tried that already, didn't work
