### ISSUE TITLE
1.12 Many recipes not working.

### ISSUE THREAD

**Issue by ritz69** [BlakeBr0/MysticalAgriculture#264]
Tried to craft steel using steel essence, but it wouldnt craft. No recipe listed in NEI. Then found out all metals that are provided by Thermal Foundation in my current mod pack (enigmatica 2 + mystical agriculture + aggraditions, ex nihilo, ex compressum, cucumber) can not be crafted with essence. However this is only if the metal also has an alternative from another mod, eg copper does not work (is also in IC2, IE) but enderium does work. Tried with both crafting station and workbench. went into config to add I:steel=3 to the thermal foundation category. Nothing worked

**Comment by BlakeBr0** [comment]
Have you checked the uses for the essences? Could be trying to make a different mods items.

**Comment by ritz69** [comment]
yeah pressing 'u' over the item shows no results
