### ISSUE TITLE
[1.14] Can't use more than one augment in the tinkering table?

### ISSUE THREAD

**Issue by Awesomespore** [BlakeBr0/MysticalAgriculture#267]
Hey, so I was wondering how the tinkering table is intended to function in terms of the other five locked augment slots. Is there currently no implemented way to unlock those in the 1.14 versions yet?

**Comment by Awesomespore** [comment]
![image](https://user-images.githubusercontent.com/59407684/72774643-3d429980-3c70-11ea-8301-2a3dc24f6235.png)

**Comment by BlakeBr0** [comment]
All current tools/armor can only use one augment. Also the left slots won't be augment slots.

**Comment by Awesomespore** [comment]
Okay. Thank you!

**Comment by jarquafelmu** [comment]
I have found this to be quite confusing as there is no documentation else where on this. Is it intended that in the future there will be further ways to modify your tools and armor?

**Comment by JustJinxed** [comment]
I also ran into this confusion, assuming they might be for higher tiers. May as well hide them if you aren't going to use them at the moment. Which kinda is a bummer, because I wanted flight and mining fatigue resist.

**Comment by Awesomespore** [comment]
> I also ran into this confusion, assuming they might be for higher tiers. May as well hide them if you aren't going to use them at the moment. Which kinda is a bummer, because I wanted flight and mining fatigue resist.

_Ah, those pesky flying elder guardians!_

**Comment by choekstr** [comment]
Yeah, why would there be 5 locked slots if there was no way to unlock them nor any intent to leverage them?  Just remove them and remove the confusion I would think :)

**Comment by mouseas** [comment]
Or if you're really stubborn about leaving them, give them a tooltip "Not Yet Implemented"
