### ISSUE TITLE
[1.14.4] Base watering can is greatly superior to upgraded ones

### ISSUE THREAD

**Issue by elowanut** [BlakeBr0/MysticalAgriculture#268]
As stated in the title, the base watering can ticks crops noticeably more quickly than even the Superium watering can. I assume this is a bug, particularly when you compare the Inferium watering can, since they both cover the same area, but Inferium ticks more slowly. (i.e. the base -> Inferium upgrade is actually a downgrade)

As a corollary, the upgraded cans (Inferium -> Superium) differentiate only on area watered, not on speed. I have no idea if this is intentional. (imo it would be nice if they increased in speed as well, but honestly, the area is already a significant benefit).

**Comment by BlakeBr0** [comment]
It's 4x faster than it should be because of a typo. Also the upgraded cans do get about a 5% boost each.
