### ISSUE TITLE
Supremium Armor and other tier armors not giving buffs

### ISSUE THREAD

**Issue by aadrian5665** [BlakeBr0/MysticalAgriculture#269]
Mc 1.14.4 playing the limitless Mod pack version 1.10A, Ive talked to the mod pack creator and he hasn't messed with anything in the config's, reading the comments I noticed I wasn't the only one having the issue also.

**Comment by BlakeBr0** [comment]
Elaborate?

**Comment by aadrian5665** [comment]
With full supremium armor their are no buffs, and with flight modules attached to each piece their is still no flight.

**Comment by BlakeBr0** [comment]
There are no set bonuses. Flight is fixed in the next version. Anything else?
