### ISSUE TITLE
Add support for uranium for yellorium seeds? Or make yellorium essence make yellorium ingots

### ISSUE THREAD

**Issue by dmb1881** [BlakeBr0/MysticalAgriculture#27]
Like the title says, can you add support for yellorium essence to make yellorium ingots instead of uranium (I think it has something to do with a mod conflict with uranium from Immersive Engineering)

Image for examples...

http://imgur.com/a/wNbJR

**Comment by dmb1881** [comment]
Also just noticed that yellorium ingot isn't appearing in jei so I am now confused whether this is a jei bug, extreme reactors bug, or a mystical agriculture bug...

**Comment by BlakeBr0** [comment]
Does that modpack have unidict(or whatever it's called) installed?

**Comment by dmb1881** [comment]
Yeah, it does, but it doesn't show yellorium in there either. But I have found a bypass for now.Just gotta insert uranium into the reactor and the extract it and it turns into yellorium.
