### ISSUE TITLE
 augment upgrades

### ISSUE THREAD

**Issue by ghost** [BlakeBr0/MysticalAgriculture#272]
could i ask how or if im able to add multiple augments on the supre armour.
is there a way to do this or are you looking to update this to you next patch?

**Comment by Jokkama** [comment]
Would love a answer here as well. I can't seem to put more than 1 augment upgrade on the superium armor.

**Comment by Old-Man-D** [comment]
I’ve noticed the same thing. I think it’s intentional, because you can have 4 augments with 4 pieces of armor.

**Comment by BlakeBr0** [comment]
There is no equipment in the mod currently that can have more than 1 augment installed
