### ISSUE TITLE
1.14.4 not respecting 'models' files

### ISSUE THREAD

**Issue by ghost** [BlakeBr0/MysticalAgriculture#273]
Forge: 28.2.0
Minecraft 1.14.4
MysticalAgriculture: 1.14.4 - 2.0.6

Im creating a resource pack. In it Ive re-written the models/item/.json files for MysticalAgriculture. Basically just pointing them from "mysticalagriculture:**item**/coal_seeds" to  "mysticalagriculture:**items**/coal_seeds"

this way I can use the Faithful 32 Modded resource pack's textures from 1.12 in 1.14

The armour/weapons from your mod work fine. They display the Faithful Textures.  The Seeds/Essence however do not

The 1.15.2 version of your mod works perfect this way

**Comment by BlakeBr0** [comment]
I don't plan to update the 1.14 version. Since it works in the 1.15 version I will consider this not an issue. It should be able to grab the right textures if they're named correctly (I think).
