### ISSUE TITLE
Unusual mod interaction (Extra Utilities 2)

### ISSUE THREAD

**Issue by Halosos** [BlakeBr0/MysticalAgriculture#277]
The interaction relates to the item from Extra Utilities "Wireless RF Heating Coil".

Expected behaviour:
Put the coil in the fuel slot of the seed reprocess
The coil provides the machine fuel as though coal had been put in for 20 ticks
The coil is not consumed

Actual behaviour:
Put the coil in the fuel slot of the seed reprocess
The coil provides the machine fuel as though coal had been put in for 20 ticks
The coil is consumed

**Comment by BlakeBr0** [comment]
I'm going to be closing this issue as the 1.12 version is EOL.
