### ISSUE TITLE
Seed Reprocessor Crashes game when torch placed inside

### ISSUE THREAD

**Issue by epharian** [BlakeBr0/MysticalAgriculture#28]
I'll leave the crash report below, but here's what happened:

I have a seed reprocessor with a hopper above it to feed it seeds and a hopper below it to pull out the essence.  

For lighting purposes I had torches in various places, including above the hopper above the reprocessor.  I was in the middle of replacing the torches with machine frames lamps (from your mod :), which I love), and broke the block behind the torch, which then fell....into the hopper.  

Within a second, the server (this is on a locally hosted server that I play with my kids--LAN only) crashed.  Now obviously, this might be a fluke, but I tried restarting the server and it crashed again.  Here are the error logs:

``---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.62-dev-77.jar)
  RebornCoreASM (RebornCore-1.11.2-2.13.4.37-universal.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.2.jar)
  LittlePatchingLoader (LittleTiles v1.3.10 mc1.11.2.jar)
  CreativePatchingLoader (CreativeCore v1.6.21 mc1.11.2.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 3/2/17 8:09 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at com.blakebr0.mysticalagriculture.tileentity.TileEntitySeedReprocessor.func_73660_a(TileEntitySeedReprocessor.java:118)
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.blakebr0.mysticalagriculture.tileentity.TileEntitySeedReprocessor.func_73660_a(TileEntitySeedReprocessor.java:118)

-- Block entity being ticked --
Details:
	Name: minecraft:ma_seed_reprocessor // com.blakebr0.mysticalagriculture.tileentity.TileEntitySeedReprocessor
	Block type: ID #492 (tile.ma.seed_reprocessor // com.blakebr0.mysticalagriculture.blocks.BlockSeedReprocessor)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (230,79,257), Chunk: (at 6,4,1 in 14,16; contains blocks 224,0,256 to 239,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #492 (tile.ma.seed_reprocessor // com.blakebr0.mysticalagriculture.blocks.BlockSeedReprocessor)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: pi was life before we died
	All players: 1 total; [EntityPlayerMP['Epharian'/381395, l='pi was life before we died', x=229.21, y=79.00, z=255.92]]
	Chunk stats: ServerChunkCache: 441 Drop: 0
	Level seed: -1169673159
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (212,64,252), Chunk: (at 4,4,12 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 33927395 game time, 1681704 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 61264 (now: false), thunder time: 79894 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4893427816 bytes (4666 MB) / 5189795840 bytes (4949 MB) up to 5189795840 bytes (4949 MB)
	JVM Flags: 8 total; -Xmx5G -Xms5G -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=2 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2235 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2235-universal.jar) 
	UCHIJAAAA	forge{13.20.0.2235} [Minecraft Forge] (forge-1.11.2-13.20.0.2235-universal.jar) 
	UCHIJAAAA	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHIJAAAA	littletilescore{1.0.0} [LittleTilesCore] (minecraft.jar) 
	UCHIJAAAA	bdlib{1.13.1.4} [BD Lib] (bdlib-1.13.1.4-mc1.11.2.jar) 
	UCHIJAAAA	chancecubes{1.11-2.3.3.136} [Chance Cubes] (ChanceCubes-1.11-2.3.3.136.jar) 
	UCHIJAAAA	claybucket{1.1} [Clay Bucket] (ClayBucket-1.11-1.0.jar) 
	UCHIJAAAA	cyclopscore{0.9.2} [Cyclops Core] (CyclopsCore-1.11.2-0.9.2.jar) 
	UCHIJAAAA	colossalchests{1.5.0} [Colossal Chests] (ColossalChests-1.11.2-1.5.0.jar) 
	UCHIJAAAA	creativecore{1.5.0} [CreativeCore] (CreativeCore v1.6.21 mc1.11.2.jar) 
	UCHIJAAAA	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod-1.11.2-1.3.0.jar) 
	UCHIJAAAA	logicaldrops{0.9.4} [Logical Drops] (EM3R50N-LogicalDrops-1.11.2-13.20.0.2201.jar) 
	UCHIJAAAA	shetiphiancore{3.4.1} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.2.jar) 
	UCHIJAAAA	endertanks{1.5.2} [EnderTanks] (endertanks-1.11.0-1.5.2.jar) 
	UCHIJAAAA	pressure{1.3.1.4} [Pressure Pipes] (pressure-1.3.1.4-mc1.11.2.jar) 
	UCHIJAAAA	advgenerators{0.9.20.4} [Advanced Generators] (generators-0.9.20.4-mc1.11.2.jar) 
	UCHIJAAAA	hopperducts{1.4.9} [Hopper Ducts] (hopperducts-mc1.11.2-1.4.9.jar) 
	UCHIJAAAA	waila{1.8.10} [Waila] (Hwyla-1.8.10-B23_1.11.jar) 
	UCHIJAAAA	inventorytweaks{1.62-dev-77-7812cce} [Inventory Tweaks] (InventoryTweaks-1.62-dev-77.jar) 
	UCHIJAAAA	jei{4.2.7.240} [Just Enough Items] (jei_1.11.2-4.2.7.240.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJAAAA	littletiles{1.3.0} [LittleTiles] (LittleTiles v1.3.10 mc1.11.2.jar) 
	UCHIJAAAA	mysticalagriculture{1.4.1} [Mystical Agriculture] (mysticalagriculture[1.11.2]-1.4.1.jar) 
	UCHIJAAAA	oreexcavation{1.3.85} [OreExcavation] (OreExcavation-1.3.85.jar) 
	UCHIJAAAA	persistentbits{1.0.6} [Persistent Bits] (PersistentBits-1.11-1.0.6.jar) 
	UCHIJAAAA	reborncore{2.13.4.37} [RebornCore] (RebornCore-1.11.2-2.13.4.37-universal.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.13.4.37} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.13.4.37-universal.jar) 
	UCHIJAAAA	refinedstorage{1.4.1} [Refined Storage] (refinedstorage-1.4.1.jar) 
	UCHIJAAAA	shulkerbox{1.1.0} [Shulkerbox] (ShulkerBox 1.1.0.jar) 
	UCHIJAAAA	techreborn{2.1.6.76} [TechReborn] (TechReborn-1.11.2-2.1.6.76-universal.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.62-dev-77.jar)
  invtweaks.forge.asm.ContainerTransformer
RebornCoreASM (RebornCore-1.11.2-2.13.4.37-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.2.jar)
  shetiphian.core.asm.ClassTransformer
LittlePatchingLoader (LittleTiles v1.3.10 mc1.11.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
CreativePatchingLoader (CreativeCore v1.6.21 mc1.11.2.jar)
  
	List of loaded APIs: 
		* journeymap|client-api (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-display (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-event (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-model (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-util (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* JustEnoughItemsAPI (4.11.0) from jei_1.11.2-4.2.7.240.jar
		* pressureAPI (1.3.1.4) from pressure-1.3.1.4-mc1.11.2.jar
		* reborncoreAPI (2.13.4.37) from RebornCore-1.11.2-2.13.4.37-universal.jar
		* reborncoreAPI|Fuel (2.13.4.37) from RebornCore-1.11.2-2.13.4.37-universal.jar
		* reborncoreAPI|Power (2.13.4.37) from RebornCore-1.11.2-2.13.4.37-universal.jar
		* reborncoreAPI|Recipe (2.13.4.37) from RebornCore-1.11.2-2.13.4.37-universal.jar
		* reborncoreAPI|Tile (2.13.4.37) from RebornCore-1.11.2-2.13.4.37-universal.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* techrebornAPI (2.1.6.76) from TechReborn-1.11.2-2.1.6.76-universal.jar
		* WailaAPI (1.3) from Hwyla-1.8.10-B23_1.11.jar
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.13.4.37
		Mixin Status: 1
		Runtime Debofucsation 1
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['Epharian'/381395, l='pi was life before we died', x=229.21, y=79.00, z=255.92]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)`

That's from the original crash.  Here's from restarting the server:

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.62-dev-77.jar)
  RebornCoreASM (RebornCore-1.11.2-2.13.4.37-universal.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.2.jar)
  LittlePatchingLoader (LittleTiles v1.3.10 mc1.11.2.jar)
  CreativePatchingLoader (CreativeCore v1.6.21 mc1.11.2.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 3/2/17 8:13 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at com.blakebr0.mysticalagriculture.tileentity.TileEntitySeedReprocessor.func_73660_a(TileEntitySeedReprocessor.java:118)
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.blakebr0.mysticalagriculture.tileentity.TileEntitySeedReprocessor.func_73660_a(TileEntitySeedReprocessor.java:118)

-- Block entity being ticked --
Details:
	Name: minecraft:ma_seed_reprocessor // com.blakebr0.mysticalagriculture.tileentity.TileEntitySeedReprocessor
	Block type: ID #492 (tile.ma.seed_reprocessor // com.blakebr0.mysticalagriculture.blocks.BlockSeedReprocessor)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (230,79,257), Chunk: (at 6,4,1 in 14,16; contains blocks 224,0,256 to 239,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #492 (tile.ma.seed_reprocessor // com.blakebr0.mysticalagriculture.blocks.BlockSeedReprocessor)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: pi was life before we died
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -1169673159
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (212,64,252), Chunk: (at 4,4,12 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 33927396 game time, 1681705 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 61263 (now: false), thunder time: 79893 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4872218224 bytes (4646 MB) / 5189795840 bytes (4949 MB) up to 5189795840 bytes (4949 MB)
	JVM Flags: 8 total; -Xmx5G -Xms5G -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=2 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2235 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2235-universal.jar) 
	UCHIJAAAA	forge{13.20.0.2235} [Minecraft Forge] (forge-1.11.2-13.20.0.2235-universal.jar) 
	UCHIJAAAA	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHIJAAAA	littletilescore{1.0.0} [LittleTilesCore] (minecraft.jar) 
	UCHIJAAAA	bdlib{1.13.1.4} [BD Lib] (bdlib-1.13.1.4-mc1.11.2.jar) 
	UCHIJAAAA	chancecubes{1.11-2.3.3.136} [Chance Cubes] (ChanceCubes-1.11-2.3.3.136.jar) 
	UCHIJAAAA	claybucket{1.1} [Clay Bucket] (ClayBucket-1.11-1.0.jar) 
	UCHIJAAAA	cyclopscore{0.9.2} [Cyclops Core] (CyclopsCore-1.11.2-0.9.2.jar) 
	UCHIJAAAA	colossalchests{1.5.0} [Colossal Chests] (ColossalChests-1.11.2-1.5.0.jar) 
	UCHIJAAAA	creativecore{1.5.0} [CreativeCore] (CreativeCore v1.6.21 mc1.11.2.jar) 
	UCHIJAAAA	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod-1.11.2-1.3.0.jar) 
	UCHIJAAAA	logicaldrops{0.9.4} [Logical Drops] (EM3R50N-LogicalDrops-1.11.2-13.20.0.2201.jar) 
	UCHIJAAAA	shetiphiancore{3.4.1} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.2.jar) 
	UCHIJAAAA	endertanks{1.5.2} [EnderTanks] (endertanks-1.11.0-1.5.2.jar) 
	UCHIJAAAA	pressure{1.3.1.4} [Pressure Pipes] (pressure-1.3.1.4-mc1.11.2.jar) 
	UCHIJAAAA	advgenerators{0.9.20.4} [Advanced Generators] (generators-0.9.20.4-mc1.11.2.jar) 
	UCHIJAAAA	hopperducts{1.4.9} [Hopper Ducts] (hopperducts-mc1.11.2-1.4.9.jar) 
	UCHIJAAAA	waila{1.8.10} [Waila] (Hwyla-1.8.10-B23_1.11.jar) 
	UCHIJAAAA	inventorytweaks{1.62-dev-77-7812cce} [Inventory Tweaks] (InventoryTweaks-1.62-dev-77.jar) 
	UCHIJAAAA	jei{4.2.7.240} [Just Enough Items] (jei_1.11.2-4.2.7.240.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJAAAA	littletiles{1.3.0} [LittleTiles] (LittleTiles v1.3.10 mc1.11.2.jar) 
	UCHIJAAAA	mysticalagriculture{1.4.1} [Mystical Agriculture] (mysticalagriculture[1.11.2]-1.4.1.jar) 
	UCHIJAAAA	oreexcavation{1.3.85} [OreExcavation] (OreExcavation-1.3.85.jar) 
	UCHIJAAAA	persistentbits{1.0.6} [Persistent Bits] (PersistentBits-1.11-1.0.6.jar) 
	UCHIJAAAA	reborncore{2.13.4.37} [RebornCore] (RebornCore-1.11.2-2.13.4.37-universal.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.13.4.37} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.13.4.37-universal.jar) 
	UCHIJAAAA	refinedstorage{1.4.1} [Refined Storage] (refinedstorage-1.4.1.jar) 
	UCHIJAAAA	shulkerbox{1.1.0} [Shulkerbox] (ShulkerBox 1.1.0.jar) 
	UCHIJAAAA	techreborn{2.1.6.76} [TechReborn] (TechReborn-1.11.2-2.1.6.76-universal.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.62-dev-77.jar)
  invtweaks.forge.asm.ContainerTransformer
RebornCoreASM (RebornCore-1.11.2-2.13.4.37-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.2.jar)
  shetiphian.core.asm.ClassTransformer
LittlePatchingLoader (LittleTiles v1.3.10 mc1.11.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
CreativePatchingLoader (CreativeCore v1.6.21 mc1.11.2.jar)
  
	List of loaded APIs: 
		* journeymap|client-api (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-display (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-event (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-model (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-util (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* JustEnoughItemsAPI (4.11.0) from jei_1.11.2-4.2.7.240.jar
		* pressureAPI (1.3.1.4) from pressure-1.3.1.4-mc1.11.2.jar
		* reborncoreAPI (2.13.4.37) from RebornCore-1.11.2-2.13.4.37-universal.jar
		* reborncoreAPI|Fuel (2.13.4.37) from RebornCore-1.11.2-2.13.4.37-universal.jar
		* reborncoreAPI|Power (2.13.4.37) from RebornCore-1.11.2-2.13.4.37-universal.jar
		* reborncoreAPI|Recipe (2.13.4.37) from RebornCore-1.11.2-2.13.4.37-universal.jar
		* reborncoreAPI|Tile (2.13.4.37) from RebornCore-1.11.2-2.13.4.37-universal.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* techrebornAPI (2.1.6.76) from TechReborn-1.11.2-2.1.6.76-universal.jar
		* WailaAPI (1.3) from Hwyla-1.8.10-B23_1.11.jar
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.13.4.37
		Mixin Status: 1
		Runtime Debofucsation 1
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server `(map_server.txt)``

The relevant section in both is:

`Time: 3/2/17 8:13 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at com.blakebr0.mysticalagriculture.tileentity.TileEntitySeedReprocessor.func_73660_a(TileEntitySeedReprocessor.java:118)
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown `Source)``

I can't send the world (data file is yuge!), but this should be enough to figure it out.  I suspect this *may* happen when any non-seed item is inserted into the reprocessor, but haven't tested that.  If I get a chance I'll do that and update the issue.

let me know if there are other things you need to know.

**Comment by BlakeBr0** [comment]
Fixed for the next update, thanks for reporting.

**Comment by epharian** [comment]
Thank you for your quick response.  Out of curiosity, do you have a sense of how soon that update might happen?  I'm trying to decide if I want to look into getting rid of that block some way or if I can just wait it out for the update.

Thanks again.

**Comment by BlakeBr0** [comment]
Probably not for atleast a couple days. 
Theres a config option that allows you to disable it. You can turn it off, load the world, then turn it back on to remove the blocks in the world. Or you can just keep it off until I release the fix.
