### ISSUE TITLE
Items dissapearing in altar when trying to craft

### ISSUE THREAD

**Issue by tobi-polar** [BlakeBr0/MysticalAgriculture#280]
Forge:forge-31.1.14
Minecraft: 1.15.2

It's hard to describe what's happening but basically I'm trying to make a speed augment and its disappearing..

https://www.youtube.com/watch?v=ujqGLNt14Tg&feature=youtu.be

**Comment by the1upper** [comment]
Forge:forge-31.1.48
Minecraft: 1.15.2

Experiencing the same issue as above. Currently it's happening when I'm manually placing all the items by hand. I didn't have any issues until I started to try to crudely automate infusion with hoppers. Removing hoppers does not restore ability to get output. Only thing that seems to fix it is restarting the server.

**Comment by BlakeBr0** [comment]
Going to close this in favor of https://github.com/BlakeBr0/MysticalAgriculture/issues/354. Version 4.1.6 should theoretically have fixed this issue.
