### ISSUE TITLE
crash on launch 1.15.2[forge 31.1.16] net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [ 	Mystical Agriculture (mysticalagriculture) has failed to load correctly ยง7null ]

### ISSUE THREAD

**Issue by SDUBZ** [BlakeBr0/MysticalAgriculture#282]
forge 31.1.16
MysticalAgradditions-1.15.2-3.0.0
MysticalAgriculture-1.15.2-3.0.0
logs:
[latest.log](https://github.com/BlakeBr0/MysticalAgriculture/files/4291059/latest.log)

**Comment by SDUBZ** [comment]
http://puu.sh/FhFoW/d13649af11.jar is there something wrong going on with the jar from curseforge after redownloaing 4 times it worked and then after like 2 reboots it gives me same error @BlakeBr0 

[crash-2020-03-06_06.17.58-server.txt](https://github.com/BlakeBr0/MysticalAgriculture/files/4298037/crash-2020-03-06_06.17.58-server.txt)

**Comment by ghost** [comment]
I get the same error loading up MysticalAgriculture-1.15.2-3.0.0.jar and creating a new server. I can occassioanly get the server to run, but it usually crashes.  Output on the server was https://pastebin.com/GFAdPzC7

[crash-2020-03-06_16.21.26-server.txt](https://github.com/BlakeBr0/MysticalAgriculture/files/4299295/crash-2020-03-06_16.21.26-server.txt)

**Comment by BlakeBr0** [comment]
The crash log says its coming from whatever industrial agriculture is

**Comment by SDUBZ** [comment]
its a addon from what i seen that is linked back to MysticalAgradditions
some classes are wrong from i can tell but i will find dev and link him back to here hopefully we can get this figured out so there is better compat between mods and addons

**Comment by Elrol** [comment]
I am working on a fix, and Industrial Agriculture is a set of mods to add modded compatibility back into MA. Sorry for the bug.

**Comment by BlakeBr0** [comment]
@Elrol just to let you know, I plan on adding back (at least) the mod support crops from previous versions of MA, so there will probably be some overlap. Assuming you just use the default crop block/item generation stuff it should be fine though.
