### ISSUE TITLE
Infusion Altar building structure not showing/Altar not working (1.15 - All the mods 5)

### ISSUE THREAD

**Issue by N30NTV** [BlakeBr0/MysticalAgriculture#283]
As mentioned in the title the inferium to higher tier seed crafting works. Farming and growing them work too but if i place the altar on the ground it is not showing me the placement for the pedestals and if i build it by looking how it should work its not functioning even provided with a redstone signal.

**Comment by N30NTV** [comment]
Highest tier armor also does not give creative flight (that might be intentional though).

**Comment by dxns-hub** [comment]
> 
> 
> Highest tier armor also does not give creative flight (that might be intentional though).

It's part of the augment system now being used...though you can't put the flight on the armor without a working Altar :\. Farmed for 10+ hours to get most of the material to find out the altar is not working.  A rebuilt mystical mod, bugs are to be expected.

**Comment by dxns-hub** [comment]
Minecraft: 1.15.2
Forge: 31.1.18

Log: attached - can't see any issues showing up once the altar is placed down
[latest.log](https://github.com/BlakeBr0/MysticalAgriculture/files/4325722/latest.log)

**Comment by BlakeBr0** [comment]
This wasn't a bug, I just hadn't implemented the guide renderer because I wanted to get a release out and it was taking to long to get working. I'll be back in the next release.
