### ISSUE TITLE
Side Configuration For Furnaces

### ISSUE THREAD

**Issue by KlankSmash** [BlakeBr0/MysticalAgriculture#284]
Mods that are able to pull items out of blocks are pulling from both the input and output slots of the furnaces. Would it be possible to set these up with configurable sides or even pre-configured sides so so one can be set for input and one for output?

Minecraft Version
1.14.4
Forge Version
forge-1.14.4-28.1.109
Mod Version
MysticalAgriculture-1.14.4-2.0.6

**Comment by BlakeBr0** [comment]
I'm going to have to put the blame on their end because my furnaces are just extensions of the vanilla furnace. If this issue is happening with mine it should be happening with the vanilla furnaces as well.

The sides are top for input, side for fuel, bottom for extract.
