### ISSUE TITLE
1.15.2[crash on start up server side] MysticalAgriculture-1.15.2-3.0.0

### ISSUE THREAD

**Issue by SDUBZ** [BlakeBr0/MysticalAgriculture#285]
Forge: 1.15.2-31.1.18
MA: MysticalAgriculture-1.15.2-3.0.0

logs:
[debug.log](https://github.com/BlakeBr0/MysticalAgriculture/files/4332150/debug.log)
[latest.log](https://github.com/BlakeBr0/MysticalAgriculture/files/4332151/latest.log)

crash :
[crash-2020-03-14_12.06.48-server.txt](https://github.com/BlakeBr0/MysticalAgriculture/files/4332152/crash-2020-03-14_12.06.48-server.txt)

**Comment by BlakeBr0** [comment]
Does this happen consistently? Does this happen without addons?

**Comment by SDUBZ** [comment]
it randomly happend when i was testing a update with virtual server

**Comment by SDUBZ** [comment]
I will run the vritaul server like 10 times see how often it occurs

**Comment by SDUBZ** [comment]
okay down to odd occurrence and i think a mod interference once i disabled botany pots it all worked again
