### ISSUE TITLE
Same recipes for different items.

### ISSUE THREAD

**Issue by Blorfik** [BlakeBr0/MysticalAgriculture#287]
There are the same recipes for logs varieties made out of wood essence. The same recipe for beef and leather - cow essence. Feathers, chicken meat - chicken essence and others. Please repair them.

**Comment by Boomflex** [comment]
Same for a lot of the recipes.

Prismarine Shard and Crystals: https://i.imgur.com/0p3ZYS0.png
Fish https://i.imgur.com/tnEY8Zl.png
Wood https://i.imgur.com/WHcqZtx.png
Chicken https://i.imgur.com/NdaTYmG.png
Cow https://i.imgur.com/rvezEaM.png
Rabbit https://i.imgur.com/fjFjDCj.png

**Comment by DerSoftwerker** [comment]
Several colors as well, e.g. yellow and light blue

**Comment by kreezxil** [comment]
confirmed

**Comment by BlakeBr0** [comment]
Version 3.0.4 of cucumber library should fix this.
