### ISSUE TITLE
MCA seed duplication when npc plants it.

### ISSUE THREAD

**Issue by maximogta** [BlakeBr0/MysticalAgriculture#290]
The interaction relates to the npc  from Minecraft Comes Alive.

Expected behaviour:
Make your son use hoe for seed planting.
The seed is consumed.

Actual behaviour:
Make your son use hoe for seed planting.
The seed is nto consumed but planted.
Seed duplication.

**Comment by BlakeBr0** [comment]
I'm going to close this as it would likely be an issue on their end.
