### ISSUE TITLE
1.15.2 No config file in config folder or forge option, what did i do wrong

### ISSUE THREAD

**Issue by deblancs** [BlakeBr0/MysticalAgriculture#293]
i have multiple config files i can access for other mods but i cant seem to get a hold of anything in the mystical mods, just trying to see if i can get seeds above tier 1 and maybe an auto watering can

**Comment by P3rf3ctXZer0** [comment]
Go to the world save.

**Comment by BlakeBr0** [comment]
If you have the mods installed config files should generate automatically on first launch.
