### ISSUE TITLE
[1.15] Crafting recipes broken!!

### ISSUE THREAD

**Issue by Awesomespore** [BlakeBr0/MysticalAgriculture#294]
Heya, so the version is MysticalAgriculture-1.15.2-3.0.1
It would appear as though recipes that rely on being in a certain location on the crafting grid (e.g wood essence crafting recipes) are broken, causing recipe conflicts.
![image](https://user-images.githubusercontent.com/59407684/78464047-caa66d80-7738-11ea-8dab-d7df405feb7c.png)
![image](https://user-images.githubusercontent.com/59407684/78464052-d2fea880-7738-11ea-8e5a-ce5736bf5df0.png)
![image](https://user-images.githubusercontent.com/59407684/78464054-d98d2000-7738-11ea-9738-5ae6864957ce.png)
![image](https://user-images.githubusercontent.com/59407684/78464058-e27df180-7738-11ea-8213-650b7d45865d.png)
![image](https://user-images.githubusercontent.com/59407684/78464061-e90c6900-7738-11ea-867a-3506549f8f49.png)
![image](https://user-images.githubusercontent.com/59407684/78464066-f0337700-7738-11ea-8907-a9b8a1796939.png)

The crafting output defaults to oak logs for the horizontal recipe and dark oak for the vertical recipe. I suspect that there's an issue with the changes in 1.15 that has removed the ability for recipes to rely on their location on the grid, but I know almost nothing about that, it's just my guess...

**Comment by ocram9** [comment]
What version of the cucumber library are you using? 3.0.4 should fix this issue

**Comment by BlakeBr0** [comment]
This issue was fixed with Cucumber Library 3.0.4.

**Comment by Awesomespore** [comment]
Yep, after updating to 3.0.4 the recipes are working as normal! Thank you! :)
