### ISSUE TITLE
Request for some True Science. B/S has failed!

### ISSUE THREAD

**Issue by mastrude** [BlakeBr0/MysticalAgriculture#295]
It is a scientific fact that a woman can’t get a better child by sleeping with four men, right. So can you get a better plant by putting 4 seeds in the outer locations of a cross, with double sticks in the center? I've posted several places and no one has given me an informed answer. Would you, please? If you do, I'll promulgate the answer so the chances will be less you'll be asked again.

**Comment by BlakeBr0** [comment]
That sounds like agricraft, which I dont make.

**Comment by mastrude** [comment]
Quite right. Please excuse me.
