### ISSUE TITLE
Addittion Request: Manual Infusion Altar

### ISSUE THREAD

**Issue by Tyrius1** [BlakeBr0/MysticalAgriculture#298]
Would it be possible to add an alternate way to activate the Infussion Altar? I think it would be neat if there was an option for the player to say, hold right click on it and manually do it. Maybe the player has to stand in a specific location or something to "channel". If this could be done and an event was left hanging it might be possible for other mods to pick up on said event and use it? Personally I would like to see the event used as an active act, that players do to raise their magic skill level. Which is added by Project MMO. 
Version 1.15

**Comment by jayschuster** [comment]
Just put a pressure plate next to it and stand on it whenever you're ready

**Comment by BlakeBr0** [comment]
I would say this is out of the scope of the base mod, and would be better suited for an addon mod.
