### ISSUE TITLE
Feature Request:  Duplication recipe for mod plants, saplings, soils, stones

### ISSUE THREAD

**Issue by MentalMouse** [BlakeBr0/MysticalAgriculture#30]
1.  In lieu of separate recipes for all of Biomes O'Plenty's multitudinous plants, how about a single "duplication" recipe for small plants?  Might use the same or a second recipe for two-high flowers.

Separate recipes for green plants, flowers, fungi, etc. might be stylish, but only if you can identify the categories automatically (by flags or inheritance or something).

2. Similar recipes would likewise serve for new sapling, stone and soil types. ETA: Wood & leaves too!

3. You'd probably want a blacklist for stuff that should not be duplicated (e.g. Thaumcraft's cinderpearls or silverwood saplings).  Those might eventually get separate, more-appropriate recipes, probably via CraftTweaker.

**Comment by BlakeBr0** [comment]
Probably just won't add any recipes for the plants at all.

**Comment by MentalMouse** [comment]
CraftTweaker script for [Biomes O'Plenty dirt, stone, ivy](https://pastebin.com/V2DPdAMP).
CraftTweaker script for [Quark blocks](https://pastebin.com/S221HgsY).

I have not yet attempted BoP's saplings, wood, or other plants except ivy and flowering vines.  
(May 8, 2017).
