### ISSUE TITLE
[1.15.2] Watering Cans

### ISSUE THREAD

**Issue by mmozzo** [BlakeBr0/MysticalAgriculture#302]
Currently our server is using Mystical Agriculture for a little spice to the game. All was fine with the original watering can and the inferium watering can, but once making the third tier watering can whenever you teleport the can empties. To go along with that this can does nothing to the process of the crops. I have sat here with the inferium can and it has produced better speeds and yields than this can. Wondering if anyone else is having this issue.

**Comment by BlakeBr0** [comment]
I'm going to close this on the assumption that it's working in the latest version. If it isn't you can reply here.
