### ISSUE TITLE
MC eternal 1.12.2 Mystical agriculture suddently missing items/blocks

### ISSUE THREAD

**Issue by jhyp3r11** [BlakeBr0/MysticalAgriculture#303]
Started my server up normally today to play, noticed my armor and sword were missing..restarted server and problem still exists. Loading into a single player world I can use and see the blocks/items.  Problem only occurring on server. Below is the console output of whats missing. Anyhelp is appreciated. 

[19:46:05] [Server thread/WARN] [FML]: Forge Mod Loader detected missing registry entries.

There are 24 missing entries in this save.
If you continue the missing entries will get removed.
A world backup will be automatically created in your saves directory.

Missing minecraft:blocks:
    mysticalagriculture:constantan_crop
    mysticalagriculture:wither_skeleton_crop
    mysticalagriculture:creeper_crop
    mysticalagriculture:manyullyn_crop
    mysticalagriculture:emerald_crop
    mysticalagriculture:osmium_crop
Missing minecraft:items:
    mysticalagriculture:wither_skeleton_essence
    mysticalagriculture:constantan_crop
    mysticalagriculture:wither_skeleton_crop
    mysticalagriculture:osmium_essence
    mysticalagriculture:creeper_crop
    mysticalagriculture:creeper_essence
    mysticalagriculture:wither_skeleton_seeds
    mysticalagriculture:emerald_crop
    mysticalagriculture:constantan_essence
    mysticalagriculture:constantan_seeds
    mysticalagriculture:emerald_seeds
    mysticalagriculture:creeper_seeds
    mysticalagriculture:emerald_essence
    mysticalagriculture:manyullyn_crop
    mysticalagriculture:manyullyn_essence
    mysticalagriculture:osmium_seeds
    mysticalagriculture:osmium_crop
    mysticalagriculture:manyullyn_seeds

Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.[19:46:05] [Server thread/WARN] [FML]: Forge Mod Loader detected missing registry entries.

There are 24 missing entries in this save.
If you continue the missing entries will get removed.
A world backup will be automatically created in your saves directory.

Missing minecraft:blocks:
    mysticalagriculture:constantan_crop
    mysticalagriculture:wither_skeleton_crop
    mysticalagriculture:creeper_crop
    mysticalagriculture:manyullyn_crop
    mysticalagriculture:emerald_crop
    mysticalagriculture:osmium_crop
Missing minecraft:items:
    mysticalagriculture:wither_skeleton_essence
    mysticalagriculture:constantan_crop
    mysticalagriculture:wither_skeleton_crop
    mysticalagriculture:osmium_essence
    mysticalagriculture:creeper_crop
    mysticalagriculture:creeper_essence
    mysticalagriculture:wither_skeleton_seeds
    mysticalagriculture:emerald_crop
    mysticalagriculture:constantan_essence
    mysticalagriculture:constantan_seeds
    mysticalagriculture:emerald_seeds
    mysticalagriculture:creeper_seeds
    mysticalagriculture:emerald_essence
    mysticalagriculture:manyullyn_crop
    mysticalagriculture:manyullyn_essence
    mysticalagriculture:osmium_seeds
    mysticalagriculture:osmium_crop
    mysticalagriculture:manyullyn_seeds

Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.

**Comment by BlakeBr0** [comment]
This wouldnt be an issue with the mod. Maybe those crops were disabled by the pack dev?
