### ISSUE TITLE
Soulium dust cant be melted

### ISSUE THREAD

**Issue by kagaikira** [BlakeBr0/MysticalAgriculture#304]
Hello, the soulium dust you can mine in the nether cant melt at all. Is it something i am doing wrong? I use a furnace and coal. It is in 1.15.2 with the newest updates of mystical. Also cucumber is used.

Greetings and tnx

**Comment by BlakeBr0** [comment]
You don't smelt it anymore. Always make sure you check all the possible uses in JEI
