### ISSUE TITLE
[18:17:27] [Client thread/ERROR] [JEI/]: Failed to get tooltip: 1xitem.ma.bronze_essence@0 mysticalagriculture:bronze_essence ?

### ISSUE THREAD

**Issue by Algester** [BlakeBr0/MysticalAgriculture#31]
[fml-client-latest.txt](https://github.com/BlakeBr0/MysticalAgriculture/files/820865/fml-client-latest.txt)
I couldnt upload the log file to pastebin as its too large for free pastebin apparently
well all I know is that when looking at Bronze Essence I'm getting tooltip error, see report

**Comment by BlakeBr0** [comment]
So it's only bronze essence that does that?

**Comment by Algester** [comment]
it looks like it's the only essence I'm missing

**Comment by Algester** [comment]
ok it seems that Mystical Agriculture doesnt detect Mekanism's Bronze as I just recently installed Thermal Expansion and Bronze essence doesnt put out an error...

**Comment by BlakeBr0** [comment]
Alright good to know, I'll make it check for mekanism in the next update
