### ISSUE TITLE
Asynchronous Registy Order Loading Crash 1.15.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [BlakeBr0/MysticalAgriculture#314]
https://gist.github.com/P3rf3ctXZer0/3262bf28137d7d8ea0792aab85ea4171

**Comment by BlakeBr0** [comment]
Is this the only error in the log file?

**Comment by P3rf3ctXZer0** [comment]
Yeah.

**Comment by P3rf3ctXZer0** [comment]
It happend with @Thutmose and his mod Thut Wearables.

**Comment by P3rf3ctXZer0** [comment]
The way forge handles extension mods with asynchronous loading has made dependency mods run before the dependency runs. This cause a false "Registry Error" I have more examples if you would like. I am also sure if you message @Thutmose he could explain how to add the needed fix. 

Fun fact thanks to the nature of the crash it only happens 20% of the time.

**Comment by BlakeBr0** [comment]
The only way I can see this crash happening is if the blocks don't get registered, which usually happens if another error happens prior. Can I get the full log because there should be another error that atleast says where it crashed.

**Comment by BlakeBr0** [comment]
That being said I might have a workaround that could just make this a non-issue.

**Comment by P3rf3ctXZer0** [comment]
As soon as your mod crashes again since I have a lot of mods with dependancies and I added more so now the crash is about 7% of the time.

**Comment by BlakeBr0** [comment]
I think I might have a solution actually, so dont worry about it.

**Comment by Thutmose** [comment]
the forge block/item registration is asynchronous now, so in the case where an addon requires something that has not been made by the main mod yet, then you can have this sort of issue occur if said addon happens to reach that stage first.

**Comment by BlakeBr0** [comment]
That doesn't seem relevant in this case since neither of these mods depend on each others blocks during registration. What it actually looks like is happening is that the RegistryObjects for the blocks sometimes aren't being updated in time for item registration (which they should as far as I know) and therefor throwing that error. I should just have to manually update the references and this shouldn't happen anymore.

The reason I assumed that this had to do with other errors (which my still be the case) is because generally when I have issues like this that's where they stem from.

**Comment by P3rf3ctXZer0** [comment]
I would agree if this was 1.12.2 but seems like 1.15.2 doesn't suffer reg issues the same way (typically)

**Comment by BlakeBr0** [comment]
This error is caused by a class that didn't exist in 1.12 so I'm not sure what you mean. It has nothing to do with dependencies or load order.

**Comment by P3rf3ctXZer0** [comment]
well glad I can help - fyi not a coder.

**Comment by BlakeBr0** [comment]
If my theory is correct then 3.0.6 should not have this issue 🤞

**Comment by BlakeBr0** [comment]
I'm going to assume this is fixed.

**Comment by P3rf3ctXZer0** [comment]
yeah sorry sometimes I forget to close issues.
