### ISSUE TITLE
[1.15.2] MA Book text turned into boxes

### ISSUE THREAD

**Issue by Omni35** [BlakeBr0/MysticalAgriculture#315]
I've got no clue what on earth I did to make this happen, but most of the books text turned into boxes, doesn't matter if I'm on an existing or new world.
Restarting game,  PC, removing and adding back the mod don't change anything.

Version: MysticalAgriculture-1.15.2-3.0.4.jar
Modlist: 
<details>
Minecraft Version: 1.15.2

Forge Version: 1.15.2-forge-31.2.0
MixinBootstrap Version: MixinBootstrap-1.0.3
OptiFine Version: preview_OptiFine_1.15.2_HD_U_G1_pre18.jar

Abnormals Core | Abnormals-Core-1.15.2-v1.0.4.jar
AppleSkin | AppleSkin-mc1.15.2-forge-1.0.13.jar
Aquaculture 2 | Aquaculture-1.15.2-2.0.14.jar
AttributeFix | AttributeFix-1.15.2-7.0.2.jar
AutoRegLib | AutoRegLib-1.5-40.jar
Autumnity | autumnity-1.3.0-1.15.2.jar
Better Bedrock Generator | betterbedrockgenerator-1.15.2-0.0.6.jar
Better Muffling | Better+Muffling-1.15.2-0.5.0-Beta.jar
Better PVP Mod | BetterPvP_20.11.0_Forge_1.15.2.jar
Biomes O' Plenty | BiomesOPlenty-1.15.2-10.0.0.361-universal.jar
Block Highlighter | blockhighlighter-1.15.2-1.2.0.jar
Bloomful | Bloomful-1.15.2-v1.4.0.jar
Blur | Blur-1.1.0-1.jar
Bonsai Trees 2 | BonsaiTrees-2.1.2.6.jar
Bookshelf | Bookshelf-1.15.2-5.5.38.jar
Botania | Botania-r1.15-384.jar
BotanyPots | BotanyPots-1.15.2-2.0.18.jar
Bow Infinity Fix | BowInfinityFix-1.15.2-rv8.jar
Building Gadgets | buildinggadgets-3.3.5.jar
Caelus API | caelus-FORGE-1.15.2-2.0-beta2.jar
Carpet Stairs Mod | carpetstairsmod-1.15.2_v1.4.4.jar
Carrots Lib | carrotslib-mc1.15.2-2.5.jar Carrots Lib
Charm | Charm-1.15.2-1.5.7.jar
ChineseWorkshop | ChineseWorkshop-1.15.2-2.4.4.jar
Clay Conversion | clayconversion-1.15-1.0.jar
Client Tweaks | ClientTweaks_1.15.2-4.1.2.jar
Cloth Config v2 API | config-2-3.0.jar
Compact Storage | compact-storage-forge-4.0.3-1.15.2.jar
Controlling | Controlling-6.1.4.jar
Corail Tombstone | tombstone-4.3.7-1.15.2.jar
Corail Woodcutter | corail_woodcutter-1.1.3-1.15.2.jar
CosmeticArmorReworked | CosmeticArmorReworked-1.15.2-v3a.jar
Crafting Tweaks | CraftingTweaks_1.15.1-11.0.0.jar
CTD Core | CTD-Core-1.15.2-2.0.5b.jar
Cucumber Library | Cucumber-1.15.2-3.0.5.jar
Curios API | curios-FORGE-1.15.2-2.0.2.2.jar
Curious Elytra | curiouselytra-FORGE-1.15.2-2.0.jar
Decorative Blocks | decorative_blocks-6d.jar
Ding | Ding-1.15.2-1.1.0.jar
Disenchanting | Disenchanting-forge_1.15.2-1.3.0.jar
Dismount Entity | dismounte_1.15-1.1.jar
Doggy Talents | DoggyTalents-1.15.2-1.15.2.3.jar Doggy
Double Slabs | DoubleSlabs-1.15-2.3.0.jar
Dragon Mounts: Legacy | dragonmounts-1.0.3.jar
Dramatic Doors | DramaticDoors-1.15.2-1.1.0.jar
Dungeon Crawl | DungeonCrawl-1.15.2-1.6.3.jar
Elevator Mod | elevatorid-1.15.2-1.7.0.jar
EmbellishCraft BoP Addon | embellishcraft-bop-1.15.2-2.0.0.jar
EmbellishCraft | embellishcraft-1.15.2-2.2.0.0.jar
EnchantmentDescriptions | EnchantmentDescriptions-1.15.2-2.0.8.jar
Extended Bone Meal | extbonemeal_1.15-1.0.jar
Extended Lights | extlights-2.0.jar
Familiar Horses | FamiliarHorses-v1.4-1.15.2.jar
FastLeafDecay | FastLeafDecay-v22.jar
Get In The Bucket Mod | getinthebucketmod-1.15.2-2.2.0.jar
Glasscutter | glasscutter-1.0.1-1.15.2.jar
Glassential | glassential-forge-1.15.2-1.1.2.jar
Global XP | globalxp-1.15.2-v1.4.11.jar
Grass Seeds | grassseeds_1.15.2-1.1.jar
GreaterEye | GreaterEye-1.15.2-1.0.10.jar
Guard Villagers | guardvillagers-1.15.2-1.0.6.jar
Hwyla/Waila | Hwyla-forge-1.10.8-B72_1.15.2.jar
InstantLava | InstantLava_1.13.2-1.1.1.jar
JEI Integration | jeiintegration_1.15.2-3.1.0.1.jar
Just Enough Items | jei-1.15.2-6.0.0.4.jar
Just Enough Resources | JustEnoughResources-1.15.2-0.10.1.77.jar
Kelp Fertilizer | kelpfertilizer-1.15-1.0.jar
Kiwi | Kiwi-1.15.2-2.7.1.jar
Lava Clear View | ClearView-1.15.2-1.0.0.jar
Libnonymous | libnonymous-1.15.2-1.1.1.5.jar
Light Overlay Forge | LightOverlay-4.6.jar
Macaw's Doors | mcw-doors-1.0.0-mc1.15.2.jar
Macaw's Windows | mcw-windows-1.0.1-mc1.15.2_1.15.1.jar
Mapper Base | mapperbase-1.15.2-1.1.0.0.jar
Material Master | MaterialMaster-v1.2-1.15.2.jar
Mo' Glowstone | Mo-Glowstone-1.15.1-2.0.4.jar
MoreCrashInfo | MoreCrashInfo-1.0.4.jar
Mouse Tweaks | MouseTweaks-2.13-mc1.15.1.jar
MrCrayfish's Furniture Mod | furniture-7.0.0-pre16-1.15.1.jar
Mystical Agriculture | MysticalAgriculture-1.15.2-3.0.4.jar
No Increasing Repair Cost | NoIncreasingRepairCost-1.15.2-1.0.0.jar
OptiForge | OptiForge-MC1.15.2-0.1.19.jar
Ore Excavation | OreExcavation-1.7.151.jar
Packing Tape | PackingTape-1.15.2-0.9.6.jar
Pane In The Glass | pitg-1.15.2-1.3.0.jar
Passive Endermen | passiveendermen_1.15-1.0.jar
Patchouli | Patchouli-1.15.2-1.2-33.jar
Persistent Bits | PersistentBits-1.15.2-2.0.2.jar
Phosphor | phosphor-forge-mc1.15.2-0.5.2+build.4.jar
Pickle Tweaks | PickleTweaks-1.15.2-4.0.2.jar
Quark | Quark-r2.1-237.jar
RandomPatches | randompatches-1.15.2-1.21.1.2.jar
Rings of Ascension | RingsOfAscension-1.15.2-1.4.jar
Serene Seasons | SereneSeasons-1.15.2-3.0.0.69-universal.jar
Sign Button | SignButton-1.15.2-2.1.0.jar
Simple Storage Network | SimpleStorageNetwork-1.15.2-0.3.2.jar
Sound Filters | SoundFilters-0.13_for_1.15.2.jar
Speedy Ladders | speedyladders-1.15.2-1.jar
Spice of Life: Carrot Edition | solcarrot-1.15.2-1.9.4.jar
Storage Drawers | StorageDrawers-1.15.2-7.0.2.jar
Strange | Strange-1.15.2-1.0.0-beta.3.jar
Swamp Expansion | Swamp-Expansion-1.15.2-v1.7.1.jar
Sword Blocking Combat | SwordBlockingCombat-v1.4-1.15.2.jar
The Endergetic Expansion | The-Endergetic-Expansion-1.15.2-v1.3.1.jar
The Midnight | themidnight-0.5.7-3.jar
Tool Belt | ToolBelt-1.15.2-1.14.1.jar
Trample Stopper | tramplestopper-1.15.2-2.0.0.1-universal.jar
Trash | trash-1.15.2-0.1.4.jar
Upgrade Aquatic | Upgrade-Aquatic-1.15.2-v1.6.1.jar
Valhelsia Structures | valhelsia_structures-15.0.2a.jar
Vanilla Food Pantry | vanillafoodpantry-mc1.15.2-5.5.jar
VanillaTweaks | VanillaTweaks-1.15.2.1.5.24.jar
WAWLA | WAWLA-1.15.2-3.0.2.jar
Xaero's World Map | XaerosWorldMap_1.5.7_Forge_1.15.2.jar
</details>

![2020-05-22_21 22 42](https://user-images.githubusercontent.com/7506611/82711900-fbaa1580-9c86-11ea-9b31-f115829b986e.png)
![2020-05-22_21 23 08](https://user-images.githubusercontent.com/7506611/82711901-fc42ac00-9c86-11ea-92cb-a7f936051dbb.png)
![2020-05-22_21 26 07](https://user-images.githubusercontent.com/7506611/82711902-fcdb4280-9c86-11ea-9d91-517e53e5ffe7.png)

**Comment by BlakeBr0** [comment]
Maybe it has something to do with your texturepack or font? I don't make patchouli so I don't think this is my issue anyways.

**Comment by Omni35** [comment]
Oof, didn't even think abou that, since my rp only changes the font and sky, turns out Botania book also does this.

Sorry and thanks for helping me figure it out, I'll reach out to Patchouli then.
