### ISSUE TITLE
Seed Reprocessor bug

### ISSUE THREAD

**Issue by Loreeeh** [BlakeBr0/MysticalAgriculture#319]
Hi everyone, hope you're all having a good day.
I'm writing this post since I've probably found a bug in the Mystical Agriculture mod [version 1.7.5 for Minecraft 1.12.2] and I don't know if it's my modpack's fault (I made it). The problem occurs when I put a lava bucket into a seed reprocessor as fuel but, after it starts to use the lava, the empty bucket disappears from the GUI. Because of this bug I can't use lava if I want to create an automated farm (I don't want to waste all of my iron just to craft buckets).
I was wondering if anyone else has this bug or knows other methods (if possible using AE2 system to store Inferium seeds/essence).
Thank you for your time.
PS: First post, plz be gentle xd

**Comment by BlakeBr0** [comment]
Since I am no longer supporting the 1.12 version of this mod I'm going to close this.
