### ISSUE TITLE
Agricraft JSON Inputs

### ISSUE THREAD

**Issue by KebnTheFirst** [BlakeBr0/MysticalAgriculture#32]
I know there has been a lot of requests to have MA integrate with AgriCraft and I decided to do the world a favor and make the JSONs for crops myself. This should belong over there, but I believe my issue is that I'm using the wrong pieces of crop information for the JSONs and I don't know where to find them.

Here is a [working JSON for Quartz](http://pastebin.com/CQqKd4UY), and here is [one that isn't working](http://pastebin.com/axYhXKDe). They both seem to be using the proper information to get the crop to plant, but the latter doesn't work at all, and I have absolutely no idea where to look.

**Comment by BlakeBr0** [comment]
Inferium is spelt Inferium not Infernium. That might be your problem :P

**Comment by KebnTheFirst** [comment]
Thanks I completely missed that. I'm running into some other weird issues as I make more JSONs but I have no clue as to what might be causing them. If I can figure it out and it is an MA issue I'll let you know.
