### ISSUE TITLE
seeds not dropping

### ISSUE THREAD

**Issue by geeksquadfry** [BlakeBr0/MysticalAgriculture#321]
I was told to try posting my issue here. I have a world in HR: New Beginnings and I have been playing it since yesterday. and yesterday everything was dropping seeds just fine, but now since I loaded the game today something seems to have changed and the world has broken and seeds from any source will not drop. I have wheat, inferium, nether quartz, and quartz enriched iron all planted and they were all dropping seeds yesterday but now are not dropping seeds. I have tested on another world and seeds will drop fine on another world, but this world will not drop seeds.

**Comment by BlakeBr0** [comment]
I'm going to close this as it seems to be a pack/instance specific issue.
