### ISSUE TITLE
[1.15.2] Recipe complications with CraftTweaker

### ISSUE THREAD

**Issue by TheUntamed** [BlakeBr0/MysticalAgriculture#322]
If I remove the tag from an item e.g. an copper ingot that ingot can still be used to craft the copper seed.
This only happens for Infusion Altar recipes of this mod. All other recipes (of all mods) using the item tag cannot longer use that item (because it doesn't have the tag anymore).

forge-31.2.30
MysticalAgriculture-3.0.8

**Comment by BlakeBr0** [comment]
As I said in the other repo the solution will have to be to re-add the recipes manually. Unfortunately with the way recipes work with crafttweaker now there may be weird inconsistencies like this.
