### ISSUE TITLE
[1.12.2-1.15.2] Unable to harvest seeds

### ISSUE THREAD

**Issue by AceTheGay** [BlakeBr0/MysticalAgriculture#324]
I've been playing on a small server on 1.12.2 and today I noticed I was unable to harvest seeds, I downloaded 1.15.2 to test the issue and see if it was only 1.12.2 or if it was multiple versions. Going into a single player world in 1.15.2 I was again, unable to harvest anything from fully grown seeds. This is across all seeds, not just specific ones.

**Comment by BlakeBr0** [comment]
I'm not really sure what you mean by not being able to harvest seeds.
