### ISSUE TITLE
[1.15.2] Right Clicking crops with mystical fertilizer - Mod Interaction: Pam's Harvestcraft Crops

### ISSUE THREAD

**Issue by TheUntamed** [BlakeBr0/MysticalAgriculture#328]
I'm not sure on which github I should open this ticket, so I will do it on both: https://github.com/MatrexsVigil/phc2crops/issues/16

**Describe the bug**
Right clicking crops (both vanilla and mystical agriculture crops) with mystical fertilizer or fertilized essence doesn't work if pam's right-click harvesting of crops is enabled.
Vanilla bone meal still works.
If right-clicking is disabled the mystical bone meal works again.
If crop right-click harvesting of other mods like Pickle Tweaks or Simple Farming is enabled, the mystical fertilizer works fine.

**To Reproduce**
Plant vanilla seeds and/or mystical seeds from mystical agriculture and right-click it with mystical fertilizer or fertilized essence while pams' harvestcraft crops right-click harvesting is enabled.

**Expected behavior**
The crops should be fertilized or, if its already fully grown, harvested if right-clicked with mystical fertilizer.

**Screenshots / Scripts / Logs**
No logs or meaningful screenshots.

**Versions (please complete the following information):**
 - Minecraft: 1.15.2
 - Forge: 31.2.33
 - Cucumber: 3.0.9
 - Mystical Agriculture: 3.0.9
- Pam's Harvestcraft Crops: 1.0.5

**Comment by BlakeBr0** [comment]
This would be an issue with pams, caused by this line:
https://github.com/MatrexsVigil/phc2crops/blob/c26b542a21d4c5dede59b1a14b80b5c53885ddf4/src/main/java/pam/pamhc2crops/events/harvest/CropHarvest.java#L52

If the player right clicks on a crop with something in their hand the event gets cancelled.

**Comment by andrewsf** [comment]
Until & unless Pam's adds an exception for Mystical Fertilizer (like the one for Bone Meal), edit `config/pamhc2crops.toml` to set:

```
"Enable right-click harvesting for crops" = false
```
