### ISSUE TITLE
[Suggestion] Prosperity Shard seeds

### ISSUE THREAD

**Issue by InjuredWolf** [BlakeBr0/MysticalAgriculture#33]
We can get pretty much every material in the game using Mystical Agriculture, except one of the most important ones: Prosperity Shards. Could we have a seed for it, please?

**Comment by InjuredWolf** [comment]
Perhaps make the Base Crafting Seed plantable?

**Comment by BlakeBr0** [comment]
The point was there would be no seed for it.

**Comment by BlakeBr0** [comment]
Might add different ways to get them though, I feel like that improve the "mechanic" a lot.

**Comment by InjuredWolf** [comment]
Yeah, ore-only materials are somewhat annoying. You can't really have them be renewable without external mods.

**Comment by BlakeBr0** [comment]
I had an idea where essence pickaxes (and maybe other tools/weapons) has a chance to drop them, not sure how well that would work though.

**Comment by Nuinethir** [comment]
Wanted to chime in on this as I am experiencing this...

I am playing a custom modpack with Captive Minecraft IV, and without Prosperity Ore generated, the mod is useless. I have added it to the drop table for the Water Strainer mod (at a 5% drop rate on the best filter to make it fair), but there should be another solution here.

Perhaps a rare chance to drop from monsters (Prosperity Shards, similar to zombies dropping ingots) that would later allow us to craft Prosperity seeds (as a T5 seed recipe). These two options would be **disabled by default** (and enabled via a config change), so those that play pre-generated saves (Captive Minecraft, Skyblock, custom challenge maps, etc.) can still use the mod without relying on another mod to fill the gap.

Thanks for reading! :)
