### ISSUE TITLE
A lot of essences won't craft anything

### ISSUE THREAD

**Issue by math909** [BlakeBr0/MysticalAgriculture#332]
**Describe the bug**
In 1.16.1 with the latest update, a lot of essence won't craft the corresponding ingots, mostly with mekanism ingots. Vanilla ingots are working and Osmium too but other ones like Uranium and bronze won't work.

**To Reproduce**
Open the world
Go to a crafting table with the essences
See that it's impossible to craft anything with these essence (uranium is the one I tried, but I looked at some others)

**Expected behavior**
Crafting makes the X amount of ingots it should

**Versions (please complete the following information):**
 - Minecraft: 1.16.1
 - Forge: 32.0.106
 - Cucumber: 1.16.1-4.0.0
 - Mystical Agriculture: 1.16.1-4.0.1

**Comment by BlakeBr0** [comment]
This should be fixed in Cucumber 4.0.1.

**Comment by mGodinho87** [comment]
I have the same problem with but on 1.18.2 version
