### ISSUE TITLE
Farmland with other crops

### ISSUE THREAD

**Issue by ArturilloD** [BlakeBr0/MysticalAgriculture#335]
I'm not sure if it's a problem or an addition, the point is that vanilla and modified crops, like pam's or other food crops or things like that are not affected by the type of farmland. I mean for the seeds of Mystical Agriculture when they are lands of higher tier they release more elements, however with potatoes it is not the same.

**Comment by BlakeBr0** [comment]
Yes, they are only intended to provide benefits for Mystical Agriculture crops.
