### ISSUE TITLE
Missing Essence Recipes

### ISSUE THREAD

**Issue by Beer1976** [BlakeBr0/MysticalAgriculture#336]
Description:
Unable to craft any custom ore from essence - specifically Immersive Engineering/NetherOre ores (Copper, Steel, Uranium, Aluminum, etc).  Vanilla Iron works.

Replication:
Created a standard world and tested crafting what the last known recipe was for these in 1.15.2 (8 essence in chest recipe form) and no resulting ingots

Expectation:
Essence should provide a resulting amount of ingots

![craftingbug](https://user-images.githubusercontent.com/69606768/90073864-9da63080-dcbf-11ea-9890-533fb7ddcd79.PNG)

**Versions (please complete the following information):**
 - Minecraft: 1.16.1
 - Forge: 32.0.108
 - Cucumber: 4.0.0
 - Mystical Agriculture: 4.0.1

**Comment by BlakeBr0** [comment]
This was fixed in cucumber 4.0.1.

**Comment by xXmilchzombieXx** [comment]
I have the same Problem with the uranium essence from mekanism.

**Comment by xXmilchzombieXx** [comment]
I have just discovered that not a single essence from the default crops has a recipe.
