### ISSUE TITLE
[1.16] Applied Energistics 2 & Refined Storage seeds 

### ISSUE THREAD

**Issue by 016Nojr** [BlakeBr0/MysticalAgriculture#338]
I assume it's probably already on a todo list, but figured I would put it on just in case because it would be really nice to get seeds for AE2 resources (Sky Stone, Certus Quartz & Fluix for AE2 and Quartz Enriched Iron for RS)

Edit, I see the seeds exist in your code, but it doesnt appear in game.

MC: 1.16.1
Forge: 108
MA/Cucumber: 402

**Comment by BlakeBr0** [comment]
Quartz enriched iron should already exist. AE2 crops are coming in the next release (which will come out for 1.16.3 once forge adds the necessary world generation hooks)

**Comment by 016Nojr** [comment]
I see the seeds are in, but the essences cant be crafted into certus quartz or fluix

**Comment by BlakeBr0** [comment]
e99e053609d0482c0c087c17ae180ac31d19d5f5
