### ISSUE TITLE
Ingame guide not showing up in 1.7.5

### ISSUE THREAD

**Issue by Gunner76th** [BlakeBr0/MysticalAgriculture#341]
**Describe the bug**
According to this thread https://github.com/BlakeBr0/MysticalAgriculture/issues/182 there is suppose to be an in game guide now when you have Patchouli installed. However in RAD 1.39 which has Mystical Agriculture and Patchouli installed, there is no guide being generated. I have looked and do not see any config settings that would be preventing this from being generated. 

**To Reproduce**
Using a modpack launcher such as Twitch or GDLauncher, install version 1.39 of this modpack https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons
Start a world, then try to locate the guide for Mystical Agriculture, you will find there isnt one. 

**Expected behavior**
As per this thread https://github.com/BlakeBr0/MysticalAgriculture/issues/182 there should be an in game guide, there is not

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).
![image](https://user-images.githubusercontent.com/5566872/91001932-2b74fc00-e59b-11ea-93bb-dea6d51bc440.png)
![image](https://user-images.githubusercontent.com/5566872/91001940-30d24680-e59b-11ea-8cdd-428e5aa22772.png)
![image](https://user-images.githubusercontent.com/5566872/91001977-4b0c2480-e59b-11ea-9f6a-4d01e449cb4b.png)
![image](https://user-images.githubusercontent.com/5566872/91002000-5cedc780-e59b-11ea-9e00-d9a9d33fa2e3.png)

**Versions (please complete the following information):**
 - Minecraft: 1.12.2
 - Forge: 2854
 - Cucumber: 1.1.3
 - Mystical Agriculture: 1.7.5
 - Patchouli: 1.0-21

**Comment by BlakeBr0** [comment]
The guide is only added in versions 2.x or later.
