### ISSUE TITLE
Mystical Agriculture 1.12.2-v1.7.3 Watering can & Mechanical user

### ISSUE THREAD

**Issue by Sindenky** [BlakeBr0/MysticalAgriculture#342]
This is in regards to mechanical users and watering cans. I found a ton of links online about this being broken, but never anything too helpful, so i did a little testing and want to share my findings to see if it helps at all. 

The fake player config is turned on. 
Mechanical user is set to "use item on block".
If more than 1 mechanical user has a watering can none of them will ever work. 
When only 1 mechanical user has a watering can it will work but only when the player is holding a watering can them self. 
If the player uses a watering can the one in the user will stop working. When the player stops it will work again. 

This is all tested on a multiplayer server hosting "The 1.12.2 Pack". I have yet to test how this will react when multiple players are performing the same actions, or if the behavior is different on single player. 

I hope this somehow helps someone.

**Comment by BlakeBr0** [comment]
I'm going to close this as it's for a long unsupported version. I will note that this should no longer be an issue in recent versions as watering cans now properly handle multiple users watering at once.
