### ISSUE TITLE
[1.15.2] Supremium Sword can't be enchanted

### ISSUE THREAD

**Issue by Snaitf** [BlakeBr0/MysticalAgriculture#343]
**Describe the bug**
Supremium Sword can't be enchanted, either via the enchanting table, or the anvil.

**To Reproduce**
Try to enchant a Supremium Sword

**Expected behavior**
The ability to enchant Supremium Swords

**Screenshots / Scripts / Logs**
n/a

**Versions (please complete the following information):**
 - Minecraft: 1.15.2
 - Forge: 31.2.36
 - Cucumber: 3.0.9
 - Mystical Agriculture: 3.0.10

**Comment by BlakeBr0** [comment]
Supremium gear intentionally cannot be enchanted. You should be able to use books in an anvil, which works from my testing in 1.16.4.
