### ISSUE TITLE
occassionally not getting seeds back

### ISSUE THREAD

**Issue by DoomSquirter** [BlakeBr0/MysticalAgriculture#344]
**Describe the bug**
normal farmland, IF sower and plant gatherer.  moving seeds from output of PG to sower and essences out of system.  I noticed that there were some essences that didn't seem to be increasing so stopped everything and pulled out all the seeds from system and there are some seeds that have gone missing, some entirely.  

could the fact that some of the seeds are different tiers and I'm growing everything on normal farmland be the issue?  does it require a farmland of the tier's type to get a guaranteed 100% seed drop?

**To Reproduce**
see above

**Expected behavior**
I expected there to be at least a 1:1 seed drop with every essence.

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.16.1
 - Forge:32.0.108
 - Cucumber:Cucumber-1.16.1-4.0.2
 - Mystical Agriculture:MysticalAgriculture-1.16.1-4.0.2

**Comment by BlakeBr0** [comment]
Crops will always drop atleast one seed. My guess is that some of the farmland has insufficient lighting so the seeds pop out of the ground in those places and despawn.
