### ISSUE TITLE
Basalt Seed or recipe?

### ISSUE THREAD

**Issue by 016Nojr** [BlakeBr0/MysticalAgriculture#348]
Can we get either a basalt seed, or a way to create basalt with stone essence or something? :)

**Comment by andrewsf** [comment]
In the meantime, are you aware of the vanilla mechanic of basalt formation?

- Make a 3x1 patch of soul soil
- Place blue ice atop the left-most spot
- Pour a lava bucket on the right-most spot

And you're generating infinite basalt instantly without farming or mods.

**Comment by 016Nojr** [comment]
Of course, but when you have a farm setup already, it's easier to add a basalt seed, more compact :D
