### ISSUE TITLE
Netherite seeds in Botany Pots not working

### ISSUE THREAD

**Issue by IamStig** [BlakeBr0/MysticalAgriculture#349]
**Describe the bug**
A clear and concise description of what the bug is. Can't use the Netherite seeds in the Botany pots not sure if it is a problem with MA or with Botany pots

**To Reproduce**
Steps to reproduce the behavior: Place Botany pot, add Farmland, try to plant seed ....fail

**Expected behavior**
A clear and concise description of what you expected to happen.Seeds plant

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).N/A

**Versions (please complete the following information):**
 - Minecraft:1.16.3
 - Forge:34.1
 - Cucumber:4.1.2
 - Mystical Agriculture:4.1.0
 Botany Pots v 5.0.1

**Comment by BlakeBr0** [comment]
I don't make that mod.

**Comment by IamStig** [comment]
Sorry, I did say wasn't sure if it was MA or Botany pots. The reason being I was unable to get Netherite seed growing at all. Not on Supremium in the overworld or in the nether and no indication of any other soil type needed that I could find.

Good news is Botany pots now work with Netherite - since last update - so I don't need to find the "normal" method" 

Thanks for your work
