### ISSUE TITLE
Texture Patchouli

### ISSUE THREAD

**Issue by felipeboff** [BlakeBr0/MysticalAgriculture#350]
Sorry my english, i am brazilian.

Texture Patchouli not working

Screenshots
![image](https://user-images.githubusercontent.com/45862227/94355125-c3ad4780-0057-11eb-877d-e6fd445c60da.png)

 - Minecraft: 1.16.1
 - Forge: 32.0.108
 - Cucumber: 4.0.2
 - Mystical Agriculture: 4.0.2

**Comment by BlakeBr0** [comment]
I don't make that mod.
