### ISSUE TITLE
Watering can growth of trees no fully rendered

### ISSUE THREAD

**Issue by redo6565** [BlakeBr0/MysticalAgriculture#351]
when using the watering can on trees in both Mystical Agriculture and Pickle Tweaks the tree doesnt not fully Render, it will only render 1 or 2 logs the rest is invisible

**Comment by redo6565** [comment]
this is for 1.16.1 and 1.16.3

**Comment by BlakeBr0** [comment]
Update on this: I've looked into it and haven't been able to find a solution yet.
