### ISSUE TITLE
mystical integration with the immersive garden cloche

### ISSUE THREAD

**Issue by felipeboff** [BlakeBr0/MysticalAgriculture#352]
I did a mystical integration with the immersive garden cloche and I would like to make the codes available to add to the mod, where can I do this?

**Comment by A009i8** [comment]
hey did you do that for the 1.15.2 ?

**Comment by felipeboff** [comment]
> @A009i8  hey did you do that for the 1.15.2 ?

I created a data pack for 1.16, but it should work at 1.15

https://www.curseforge.com/minecraft/customization/ie-garden-cloche-integration-mystical-agriculture

**Comment by A009i8** [comment]
> 
> 
> > @A009i8  hey did you do that for the 1.15.2 ?
> 
> I created a data pack for 1.16, but it should work at 1.15
> 
> https://www.curseforge.com/minecraft/customization/ie-garden-cloche-integration-mystical-agriculture

@felipeboff where do i put the zip in ?

**Comment by felipeboff** [comment]
@A009i8 .minecraft/saves/(your world)/datapacks

it’s a regular data pack, so put it in the datapack folder in the world folder

**Comment by A009i8** [comment]
@felipeboff okey i will try it out thanks

**Comment by A009i8** [comment]
@felipeboff can you send me a screen where do i put this in

**Comment by A009i8** [comment]
> 
> 
> > @A009i8  hey did you do that for the 1.15.2 ?
> 
> I created a data pack for 1.16, but it should work at 1.15
> 
> https://www.curseforge.com/minecraft/customization/ie-garden-cloche-integration-mystical-agriculture

not working

**Comment by BlakeBr0** [comment]
I won't be including integration like this in the mod itself as it's a maintenance nightmare. This one in particular is also decently controversial.
