### ISSUE TITLE
Seeds disappear while crafting

### ISSUE THREAD

**Issue by SoNiice** [BlakeBr0/MysticalAgriculture#354]
**Describe the bug**
When I try to craft any seeds they just disappear.

**To Reproduce**
Craft a seed.

**Expected behavior**
Receive a seed?

**Screenshots / Scripts / Logs**
https://files.soniice.tech/2020-10-13/18-54-07.mp4

**Versions (please complete the following information):**
 - Minecraft: 1.16.3
 - Forge: 34.1.18
 - Cucumber: 4.1.2
 - Mystical Agriculture: 4.1.0

Asked the server owner about logs, gonna add 'em if there's anything interesting in there.

**Comment by BlakeBr0** [comment]
This may have been fixed in version 4.1.6. Let me know if the issue persists.

**Comment by BlakeBr0** [comment]
I am going to assume this is fixed.
