### ISSUE TITLE
[1.16.3] No new seed drop when harvest

### ISSUE THREAD

**Issue by moulecake** [BlakeBr0/MysticalAgriculture#356]
**Describe the bug**

In my different field inferium seed, dirt seed, wood, cow, gold... and when I harvest with right clic; empty hand, no new seed drop when harvest.
I loot all essence and sometime fertilized essence but no seed.
All seeds are planted in good tier.

**To Reproduce**
I try deactivate chunk, chunk loader of FTB chunk. I've ask Pam's mod, nothing change. I've look for in config if they is "no seed loot" nothing found.

**Expected behavior**

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).
Mod list : https://pastebin.com/6ne25Z6V

**Versions (please complete the following information):**
 - Minecraft: 1.16.3
 - Forge: forge-1.16.3-34.1.12] Edit : same in 34.1.25
 - Cucumber: Cucumber-1.16.3-4.1.2
 - Mystical Agriculture: MysticalAgriculture-1.16.3-4.1.0

**Comment by Icey455** [comment]
Having the same issue, would also like to see the config option to change the seed drop chance readded.

**Comment by sunnyughs** [comment]
> Having the same issue, would also like to see the config option to change the seed drop chance readded.

Bumping for this and I'm also having the same issue with seeds not duplicating at all.

**Comment by North-West-Wind** [comment]
Are you using Essence Farmlands? According to the code, secondary seeds will only drop when farmland is an instance of IEssenceFarmland or it is "effective".

Found in `ICrop`:
```java
default double getSecondaryChance(Block block) {
    double chance = 0;
    if (!this.getTier().hasSecondarySeedDrop())
        return chance;
    if (block instanceof IEssenceFarmland)
        chance += 0.1;
    if (this.getTier().isEffectiveFarmland(block))
        chance += 0.1;

    return chance;
}
```

This might be intentional, or not yet implemented.

**Comment by BlakeBr0** [comment]
Seeds need to be planted on essence farmland to drop additional seeds.
