### ISSUE TITLE
[1.16.3] seed reprocessor recipe stops working on mouse click

### ISSUE THREAD

**Issue by thecow275** [BlakeBr0/MysticalAgriculture#357]
clicking with inferium essence to output slot of seed reprocessor causes recipe to disappear until singleplayer server reload

**To Reproduce**
1. open seed reprocessor (tertium)
2. put fuel and inferiums seeds in machine
3. take essence out from output slot with half stack of inferium essence and click with the stack on empty output slot recipe stops working until server restart

**Expected behavior**
when taking out a item from output slot of seed reprocessor it should not stop working.

**Screenshots / Scripts / Logs**
[debug.log](https://gist.github.com/thecow275/407b41127ae32d44fa367a3f5addcee6)
[latest.log](https://gist.github.com/thecow275/40beffbdb463512af9e8756b4e88a96c)
[modlist](https://gist.github.com/thecow275/6359bf374c5ab2f11f344b8479f9cbcc)

**Versions (please complete the following information):**
 - Minecraft: 1.16.3
 - Forge: 34.1.22
 - Cucumber: 4.1.2
 - Mystical Agriculture: 4.1.0

**Comment by andrewsf** [comment]
Oh, I've been wracking my brain trying to figure out what causes this so I could report it. I see this a lot. Seed Reprocessor breaks until a restart. Moving the block, Redstone activity, and adjusting its inventory have no effect.

**Comment by BlakeBr0** [comment]
This should be fixed in Cucumber 4.1.3
