### ISSUE TITLE
Version 1.16.1 has only one tinker table slot available with every tier of armor and tools

### ISSUE THREAD

**Issue by Simps0909** [BlakeBr0/MysticalAgriculture#359]
**Describe the bug**
In version 1.16.1 tinkering table has only one slot at tier 1 or tier5 armor and equipment

**To Reproduce**
Steps to reproduce the behavior:Put anytier armor or toosl to tinkering table and you have only one slot open

**Expected behavior**
A clear and concise description of what you expected to happen.To have all slots open in the tinkering tabe on tier 5 stuff

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable
[2020-10-14-2.log.gz](https://github.com/BlakeBr0/MysticalAgriculture/files/5425297/2020-10-14-2.log.gz)
).![2020-10-22_22 27 56](https://user-images.githubusercontent.com/52635673/96921071-b0569600-14b6-11eb-83f6-109d21926d83.png)
![2020-10-22_22 28 06](https://user-images.githubusercontent.com/52635673/96921216-daa85380-14b6-11eb-8a07-7136222e019c.png)

**Versions (please complete the following information):**
 - Minecraft:1.16.1
 - Forge:32.0.108
 - Cucumber:4.0.2
 - Mystical Agriculture:4.0.2

**Comment by BlakeBr0** [comment]
Yes, the equipment in the mod currently can only have one augment installed
