### ISSUE TITLE
Soulium Recipe Issue

### ISSUE THREAD

**Issue by Iareawsome** [BlakeBr0/MysticalAgriculture#36]
With the most recent update (version 1.11.2-144) the soulium recipe now uses prudentium and soulium, rather than prudentium and soul dust, making it impossible to craft. 

Here is a picture in case I wasn't clear: [http://imgur.com/2HhNfY4](url)

Ps, I hope I spelled everything right, and I love your mod!

**Comment by BlakeBr0** [comment]
Thanks for reporting.
