### ISSUE TITLE
can't make it so infusion recipes don't show up

### ISSUE THREAD

**Issue by Warbringer12** [BlakeBr0/MysticalAgriculture#362]
tried making a recipe to cancel out a infusion crafting recipe but didn't work cause I didn't see where said infusion recipe was located at..

also tried removing a seed repocessor recipe also couldn't find it either

**Comment by BlakeBr0** [comment]
The infusion recipes for seeds are generated dynamically, same goes for the seed reprocessor recipes. How are you going about trying to remove them?

**Comment by Warbringer12** [comment]
by using a json to remove the recipes by making the output to be minecraft:air

**Comment by BlakeBr0** [comment]
Can you let me know if 4.1.4 fixes this issue? 

Note that the recipe IDs changed in this update.

**Comment by Warbringer12** [comment]
works in 4.1.4 update can confirm. thanks for doing that 👍

**Comment by Warbringer12** [comment]
it does however break the any mystical customization seeds that are made, that is the only thing I have found wrong. It breaks there infusion recipes

**Comment by Warbringer12** [comment]
nevermind, I found a way to include those seeds into the infusion ;p
