### ISSUE TITLE
How does tincking table work?

### ISSUE THREAD

**Issue by Matteo-04** [BlakeBr0/MysticalAgriculture#364]
I really can't understand how the tinckering table works.

 1- What is each space for?
 2- once I put the weapon or armor in its slot and the upgrade in its slot, how do I get the enchanted item?
 3- are weapons and upgrades interchangeable or are only those created with the same powder compatible?

 Thanks for your help and sorry for the bad English.

**Comment by ghost** [comment]
Hi,

I tested it and I can tell you this: it's pretty simple in fact. Oh, I tested on mc 1.16.3.

You put your armor or tool in the center of tinkering table. All of the armors and tools have **only** one slot (why? I don't know).

After, the top right slot will unlock, in this slot you can put your augment **BUT** augments works with his tier armor.
I explain: flight augment will work on supremium chestplate only 'cause it is a tier 5 augment.
inferium = tier1, prudentium = tier2...

To get the enchanted item you just need to take back your item after place the augment in the slot.

I learned it from the book :)

The only thing I haven't understand yet is how to unlock the other slots. It is not writen in the book.

I hope I helped you

**Comment by BlakeBr0** [comment]
As far as the other slots go they are currently unused.
