### ISSUE TITLE
Garden Cloche interaction with mystical seeds

### ISSUE THREAD

**Issue by A009i8** [BlakeBr0/MysticalAgriculture#365]
hey boys and girls

i need your help i search a mod in 1.16+ where i can use myst seeds in Garden Cloche from immersive.
anyone have a mod ?

**Comment by glahera** [comment]
Hello, I'm playing Allthemod6 and it seems that Garden Cloche is working fine with Mystical Agriculture, I've been able to grow Inferium inside Garden Cloche. The only thing is that you have to use farmland at same tier with the seed itself (I haven't confirmed if using higher tier is possible).

**Comment by A009i8** [comment]
> 
> 
> Hello, I'm playing Allthemod6 and it seems that Garden Cloche is working fine with Mystical Agriculture, I've been able to grow Inferium inside Garden Cloche. The only thing is that you have to use farmland at same tier with the seed itself (I haven't confirmed if using higher tier is possible).

hey i try it in 1.15 and its not working

**Comment by A009i8** [comment]
> 
> 
> Hello, I'm playing Allthemod6 and it seems that Garden Cloche is working fine with Mystical Agriculture, I've been able to grow Inferium inside Garden Cloche. The only thing is that you have to use farmland at same tier with the seed itself (I haven't confirmed if using higher tier is possible).

in 1.16 is not working to so its a side mod and i need the side mod

**Comment by glahera** [comment]
Okay, I've just dug around a bit in Allthemod 6 files, there's this file:
https://github.com/AllTheMods/ATM-6/blob/master/kubejs/server_scripts/cloche.js
It seems to fix the ability of cloche to contain Mystical Agriculture crops. You can try to install KubeJS mod then drop the script file in there.

**Comment by ProjectGSX** [comment]
As glahera mentioned, you need a datapack to enable these two mods to work together.  There is a mod out there called Cloche Call that ads the required support, assuming the modpack you are using does not include it.  MC Eternal already had the support baked in, but Valhesia 3 did not.  Cloche Call is working for me on 1.16.1 with V3.  The tree support is not working for me though, so FYI in case you notice that listed in Cloche Call.

**Comment by A009i8** [comment]
Its working thanks 🖖

glahera <notifications@github.com> schrieb am Di., 3. Nov. 2020, 22:42:

**Comment by BlakeBr0** [comment]
Noting for future reference that this integration was never added by MA itself, and never will be.
