### ISSUE TITLE
Tag support on Mystical Agriculture items

### ISSUE THREAD

**Issue by glahera** [BlakeBr0/MysticalAgriculture#366]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.**
This is related to Mekanism integration since I'd like to automate with its Logistical Sorter. When I want to redirect Seeds to the Plant Sower from Industrial Foregoing and the Essence to storage system, essentially I have to put every single Item Stack filter into the Logistical Sorter.

**Describe the solution you'd like**
I think putting a tag like "mysticalagriculture:seed" and "mysticalagriculture:essence" would make the solution easy and elegant. That way we can just use tag filter from Mekanism to sort items without having a lot of filter just for a farm

**Comment by jayschuster** [comment]
+1 this

**Comment by Rurido** [comment]
up!
