### ISSUE TITLE
[1.16.3] AE2 no silicon item recipe 

### ISSUE THREAD

**Issue by YOYOK9** [BlakeBr0/MysticalAgriculture#368]
**Describe the bug**
Can't craft silicon seeds with AE2 silicon item. As well as silicon essence to silicon item. The press can be crafted but not the actual silicon itself. 

Item: appliedenergistics2:silicon 
vs
press: appliedenergistics2:silicon_press

**To Reproduce**
Install latest Mystical Agriculture and AE2 1.16.3
look up silicon

**Expected behavior**
Able to craft silicon seeds and use the essence to make silicon

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).
Options to make the seeds: https://puu.sh/GKdtd/c0e1080e41.png
Current Silicon recipes (no crafting available): https://puu.sh/GKduK/cd29875ce5.png

**Versions (please complete the following information):**
 - Minecraft: 1.16.3
 - Forge: 34.1.42
 - Cucumber: 1.16.3-4.1.3
 - Mystical Agriculture: 1.16.3-4.1.1

**Comment by BlakeBr0** [comment]
This is fixed in newer releases of AE.
