### ISSUE TITLE
[1.16.3]Pickaxe not required when mining mod ores.

### ISSUE THREAD

**Issue by MoxieGrrl** [BlakeBr0/MysticalAgriculture#369]
When mining Mystical Agriculture ore, a pickaxe is not needed. Tested on version 1.16.3-4.1.3 of Cucumber and 1.16.3-4.1.1 of Mystical Agriculture using Forge 34.1.42. Reproduced with just these mods, just to make sure. I noticed when using The One Probe that while it said that a pickaxe was the right tool to harvest, a fist was all that was actually required.

**Comment by BlakeBr0** [comment]
Fixed in version 4.1.5 of cucumber.
