### ISSUE TITLE
FPS lag with growth crystal

### ISSUE THREAD

**Issue by Tenchu98** [BlakeBr0/MysticalAgriculture#37]
I was wondering if it would be possible to have an option to lower the number of block updates used for plant growth, as in not rendering some of the steps of the plant. When I use a tier 1 growth crystal my fps drop when looking in the direction of my farm.

**Comment by BlakeBr0** [comment]
I do plan on making it more efficient in the future. Unfortunately though, a lot of the issue is the fact that block updates are just super laggy in general, so it they will be laggy pretty much no matter what.

Simply moving the crops somewhere you arent fixes all the fps problems.

**Comment by BlakeBr0** [comment]
Also just noticed you said growth crystal, not growth accelerator. If you meant growth crystal, thats from Tiny Progressions, not my mod.

**Comment by Tenchu98** [comment]
I was just thinking less state changes would limit chunks updates.

**Comment by BlakeBr0** [comment]
The states have to change for the crops to grow.

**Comment by Tenchu98** [comment]
I was referring to the rendering states. I'm not sure if it would lower lag or not though

**Comment by Tenchu98** [comment]
ok, so I think the issue had something to do with a combination of MA, actually additions farmer, and a growth crystal from tiny progressions. When I removed any one of the 3 the lag spike disappeared. I am thinking that maybe the farmer is trying to harvest the plants before they are mature, as if reading one of the states as being mature.
