### ISSUE TITLE
No recipe to craft steel

### ISSUE THREAD

**Issue by b52src** [BlakeBr0/MysticalAgriculture#371]
**Describe the bug**
no recipe to craft steel mod with steel in the pack is IE and I can craft the steel seed but the steel essence has no recipe.
copper and lead recipes work fine.

**To Reproduce**

**Expected behavior**
a recipe for steel with steel essence

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.16.3
 - Forge: 34.1.42
 - Cucumber: 1.16.3 - 4.1.3
 - Mystical Agriculture: 1.16.3 - 4.1.1

**Comment by BlakeBr0** [comment]
Is the steel tag properly mapped in the cucumber-tags.json config?

https://mods.blakebr0.com/docs/cucumber/tags-config

**Comment by BlakeBr0** [comment]
I'm going to close this in favor of https://github.com/BlakeBr0/MysticalAgriculture/issues/375. This issue should theoretically be fixed, though it's been a bit hard to reproduce every scenario where these recipes don't work.
