### ISSUE TITLE
[Suggestion] Decrease minimum dependency version for 1.16.4 builds

### ISSUE THREAD

**Issue by ArcanoxDragon** [BlakeBr0/MysticalAgriculture#373]
According to the Forge developers, Minecraft Forge versions for 1.16.4 are supposed to be fully compatible with 1.16.3 (and mods targeting the 1.16.4 versions should also be compatible with 1.16.3) except in _very_ specific situations. Most mods I have seen updating to 1.16.4 have kept their dependency versions for FML/Forge/MC at `34.1` and `1.16.3` respectively so that players still stuck on 1.16.3 can boot 1.16.4 mods. As far as I can tell, both Cucumber and Mystical Agriculture (latest 1.16.4 versions of both) still seem to run fine on 1.16.3 when I alter the `mods.toml` dependency versions on my local copy. Is there a specific reason why they both require FML/Forge `35.0` and Minecraft `1.16.4` as minimums? If there isn't, could the dependency minimums be relaxed in a future 1.16.4 build so they can be installed into 1.16.3 without modifying the `.jar` file?

**Comment by BlakeBr0** [comment]
Forge for 1.16.4 should load 1.16.3 mods even if the mods.toml says not to, so I don't see how anyone could be stuck on 1.16.3. I'll try to be more lax with minimum required versions in the future..

**Comment by ArcanoxDragon** [comment]
Well, part of the problem is that there are other modders who put `[34.1,35)` in their FML dependency range, so Forge _refuses_ to load those mods on 1.16.4. Of course that's mainly on them, but I run a private server, and the last time we tried to upgrade to 1.16.4, there were _lots_ of mods doing that, but almost none that were specifying a minimum of Forge 35 for 1.16.4
