### ISSUE TITLE
Lots of metal essence recipes doesn't work

### ISSUE THREAD

**Issue by Metaz78** [BlakeBr0/MysticalAgriculture#375]
A lot of recipes doesn't work.
After upgrading ATM6 from 1.2.1 to 1.3.3 a lot of recipes stopped existing.
I have no clue (yet) if the is something I can copy from a newly created server to my upgraded one to fix it.
I tried creating a new SP world but that didn't work either.
Not working that I know:
Steel, Copper, Tin, Uranium, Platinum, Lead, Zinc, Nickel etc

 - Minecraft: 1.16.4
 - Forge: 35.1.4
 - Cucumber: 4.1.5
 - Mystical Agriculture: 4.1.3

**Comment by BlakeBr0** [comment]
Is the cucumber-tags.json file configured to properly map the corresponding tags to their items?

https://mods.blakebr0.com/docs/cucumber/tags-config

**Comment by BlakeBr0** [comment]
Is this still an issue with the latest version?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. From what I can tell, in the latest version these recipes work fine.
