### ISSUE TITLE
Enabling Supremium armor on Galactic Engineers server crashes it

### ISSUE THREAD

**Issue by Neekalos** [BlakeBr0/MysticalAgriculture#378]
I just want to preface this by saying it's on Minecraft version 1.10.2, so I don't expect you guys to change anything.  I just wanted to see if you had any idea how I could fix it.  I recently started a Galactic Engineers server, which is a space-themed modpack.  By default, supremium armor is disabled.  Wanting to enable it, I went into the server config files and set $gear_module_override from false to true.  I then tried to start the server, and it crashes.  I am positive it is because of this change.  Any ideas why this might be?  Could it be that not everyone who's been on the server has it enabled in their personal files, so it causes a crash?  Here's a copy of the crash log:  https://pastebin.com/XNpgtmk1

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue you can reply here.
