### ISSUE TITLE
Please contribute the old 32x textures to faithful32 project

### ISSUE THREAD

**Issue by cpw** [BlakeBr0/MysticalAgriculture#38]
Hi,
I noticed that the new mystical agriculture has lower resolution textures than previously. It looks awful when paired with the faithful 32x texture pack. Can I suggest you contribute your old textures to that pack so it looks good with faithful 32 again?

Thanks!

https://github.com/F32Organization/Faithful32-1.10.2

**Comment by BlakeBr0** [comment]
Yeah I can do that.
Someone else would have to make 32x textures for any new blocks/items I add or any that I didn't make 32x textures for.
