### ISSUE TITLE
Config Files Missing Settings 1.16.4

### ISSUE THREAD

**Issue by dangoodie** [BlakeBr0/MysticalAgriculture#380]
Hi,

I am looking through the config files and it looks like it has been significantly reduced from what it previously was. I am trying to remove flight from the superium armor in my server and it appears that the config files to change that with mystical agriculture are lacking the settings to do so. In fact the config files are quite bare and have very few of the settings that I've seen listed. Maybe this is intentional and there is a way to make the changes but I do not see any documentation to reflect that. How can I remove flight from the superium armor?

**Comment by BlakeBr0** [comment]
You can disable the recipe for the flight augment if you don't want flight.
