### ISSUE TITLE
No recipes to craft ingots from essences for certain materials

### ISSUE THREAD

**Issue by seniorpepper24** [BlakeBr0/MysticalAgriculture#381]
I've tried copper, tin, silver, platinum, lead.. 

I can make the seeds using the infusion altar, I grow them to give essences but there is no recipe to create ingots from essences. In fact, there is no use for the essences at all.

EDIT: I see the multiple posts with the same problem. I'm playing on a modded server that my friend made using ATM6. Is there a way to add a recipe for these? I want to use essences to make ingots.

**Comment by BlakeBr0** [comment]
You saw that multiple people have reported this issue but you didn't look at my replies?

**Comment by huy08071997** [comment]
Your friend can disable this recipe! Ask your friend to enable or add recipe!

**Comment by seniorpepper24** [comment]
> You saw that multiple people have reported this issue but you didn't look at my replies?

I posted the issue before seeing the multiple posts. Your replies didn't help me much either way. How do you add recipes?

**Comment by BlakeBr0** [comment]
Is the cucumber-tags.json file configured to properly map the corresponding tags to their items?

https://mods.blakebr0.com/docs/cucumber/tags-config

**Comment by BlakeBr0** [comment]
I just tested with a fresh server/client using MA, Mekanism, and Silents Mechanisms and the cucumber-tags config seems to have generated properly and the recipes for copper, tin, silver, platinum essence all work properly.

If you could give me the server logs I can take a look.

**Comment by BlakeBr0** [comment]
I'm going to close this in favor of https://github.com/BlakeBr0/MysticalAgriculture/issues/375. If you have any other information please provide it there.
