### ISSUE TITLE
Seeds with tag materials missing Infusion Altar recipes

### ISSUE THREAD

**Issue by kaiju-fxt** [BlakeBr0/MysticalAgriculture#385]
**Describe the bug**
Many of the ore seeds, both vanilla and modded, don't have a proper recipe in the Infusion Altar. They'll only show 4 of each of each base essence, such as Imperium or Supremium, without the actual ingot being shown to complete the recipe in the altar. Even when placing the corresponding ingot directly into the pedestals alongside the dust nothing happens when the altar is powered.

![2021-01-17_11 28 54](https://user-images.githubusercontent.com/77557097/104827932-c908f900-58b7-11eb-9e5a-abf7d82d4b45.png)
![2021-01-17_11 29 05](https://user-images.githubusercontent.com/77557097/104827936-d0c89d80-58b7-11eb-9aa9-80733741eb0f.png)
![2021-01-17_11 29 14](https://user-images.githubusercontent.com/77557097/104827937-d32af780-58b7-11eb-9237-b28a2a2878b8.png)

 - Minecraft: 1.16.4
 - Forge: 35.1.29
 - Cucumber: 1.16.4-4.1.5
 - Mystical Agriculture: 1.16.4-4.1.4

**Comment by FC12000** [comment]
I am also seeing the issue with the recipe missing the component material.
For this case I am trying to infuse a stone seed, but the the stone icons are missing. 
The infusion works when I place the stones in the missing spots on the pedestals though.
Edit: The missing components are only happening on Multiplayer mode. Running my own Forge server. The components show up in Singleplayer mode.

![2021-01-27_15 55 46](https://user-images.githubusercontent.com/6664571/106064054-d34ca380-60be-11eb-9a64-488fdefee376.png)

Minecraft: 1.16.4
Modloader Forge: 35.1.36
Cucumber: 1.16.4-4.1.5
Mystical Agriculture: 1.16.4-4.1.4
Just Enough Items (JEI): 1.16.4-7.6.1.65
