### ISSUE TITLE
copper ingot

### ISSUE THREAD

**Issue by Cy6erDoogHD** [BlakeBr0/MysticalAgriculture#386]
playing on 1.16.4 and it wont allow me to craft copper essence into copper ingot same for tin

**Comment by BlakeBr0** [comment]
Is the cucumber-tags.json file configured to properly map the corresponding tags to their items?

https://mods.blakebr0.com/docs/cucumber/tags-config

**Comment by BlakeBr0** [comment]
I'm going to close this in favor of https://github.com/BlakeBr0/MysticalAgriculture/issues/375. If you have any other information please provide it there.
