### ISSUE TITLE
Recipes diappearing when accelerating the crafting process with Watch Of Flowing Time

### ISSUE THREAD

**Issue by Scha7ten** [BlakeBr0/MysticalAgriculture#388]
When one accelerates the crafting process with a ProjectE Watch Of Flowing Time of any seed, the recipe just disappears never to be seen. Sadly i cannot provide screenshots, as for the Netherite seed I crafted in 1.16.5 I no longer have any recipe via JEI. Please fix this, as this most certainly is a bug.

**Comment by BlakeBr0** [comment]
I tested this and didn't everything worked as expected. Was this on a server?

**Comment by BlakeBr0** [comment]
I'm going to assume this is fixed.
