### ISSUE TITLE
Feature request:  Allow Master Infusion Crystal to work with blocks.

### ISSUE THREAD

**Issue by MentalMouse** [BlakeBr0/MysticalAgriculture#39]
Like the title says -- since it doesn't use durability anyway, why not let it infuse blocks into blocks?

**Comment by BlakeBr0** [comment]
use minetweaker and add the recipes yourself

**Comment by MentalMouse** [comment]
I just tried that.  Exposed _two_ bugs in CraftTweaker. (They only recently updated to 1.11.2.)  Arggh.

**Comment by BlakeBr0** [comment]
I might actually add this suggestion, I'll add it to the todo list.

**Comment by MentalMouse** [comment]
In the meantime, I got the script working:  [Blockwise Infusion with CraftTweaker](https://pastebin.com/2V4ikuhY).
