### ISSUE TITLE
Can't enchant Supremium tools

### ISSUE THREAD

**Issue by ghost** [BlakeBr0/MysticalAgriculture#390]
**Describe the bug**
I can't enchant any of the Supremium tools. All the other tiers work and the Supremium armor also works. JEI also doesn't show any enchants for the Supremium tools while it shows them for all the other tools and armors.

**To Reproduce**
Try to enchant Supremium tools in an Vanilla enchanting table with Vanilla Bookshelves around it.

**Expected behavior**
I should be able to enchant the Supremium tools just like everything else.

**Screenshots / Scripts / Logs**
![Enchanting Supremium](https://user-images.githubusercontent.com/37956499/108626577-1b0de300-7451-11eb-8aec-ae3b0dc69c43.png)

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.0.42
 - Cucumber: 4.1.6
 - Mystical Agriculture: 4.1.5

**Comment by BlakeBr0** [comment]
This is intentional. I will probably change this though.

**Comment by ghost** [comment]
Oh ok, thanks for the reply!

**Comment by timo103** [comment]
Please change this. You can enchant supremium armor just fine and it's weird to prevent enchanting directly when it still allows for enchanting through anvils.

 I went through a mountain of effort to collect enchanted books just to find out that you can't place the supremium sword in a mana enchanter from botania to enchant it up all at once.

**Comment by BlakeBr0** [comment]
The reason currently is that the default behavior in Minecraft is that an item must be damageable to enchantable. I may just change it though since it's a bit unintuitive. That being said, it's also kind of over-powered with disenchanting though, so I may hide it behind a config option.
