### ISSUE TITLE
Essence smokers and essence blast furnances

### ISSUE THREAD

**Issue by AbacusOperator** [BlakeBr0/MysticalAgriculture#391]
**Is your feature request related to a problem? Please describe.**
Furnaces added by this lack smoker and blast furnace counterparts.

**Describe the solution you'd like**

- Add smoker and blast furnace counterpart to each essence furnace.
- Each of them should have two crafting recipes: from corresponding essence furnace by vanilla recipe for smoker/blast furnace and from vanilla smoker/blast furnace using corresponding Mystical Agriculture essence furnace recipe.
- They provide the same trade off as vanilla smoker and blast furnace: essence smoker is twice as fast as corresponding essence furnace, but only can perform same recipes as vanilla smoker, essence blast furnace is twice as fast as corresponding essence furnace, but only can perform same recipes as vanilla blast furnace.

**Comment by BlakeBr0** [comment]
I'm going to close this as I don't think these are necessary. The benefits of these blocks are that they have increased cooking speed which I feel is already covered by the Essence Furnaces. Thanks for the suggestion though!
