### ISSUE TITLE
Ability to disable Augments

### ISSUE THREAD

**Issue by AsheX1** [BlakeBr0/MysticalAgriculture#393]
what can i say a way to disable some augments

edit: think best setting you can do is disable Tier X augments or seeds maybe

like flight....

can't seem to get craft tweaker working to remove it

**Comment by AsheX1** [comment]
got it disabled with crafttweaker but took very long to understand how it works

**Comment by AsheX1** [comment]
feel free to close it wen you see it

**Comment by BlakeBr0** [comment]
I'm going to be making it so that augments can be edited using Mystical Customization.

**Comment by BlakeBr0** [comment]
Augments can now be disabled using Mystical Customization version 2.1.3.
