### ISSUE TITLE
[1.16.5] Rock crystal seeds(astral sorcery) not craftable at infusion altar

### ISSUE THREAD

**Issue by LuciusV** [BlakeBr0/MysticalAgriculture#394]
**Describe the bug**
Cannot craft rock crystal seeds. Maybe because they have internal properties when they dropped in the world and recipe does not expect that?

**To Reproduce**
Place crafting seed on infusion altar, 4 supremium essences and 4 rock crystals on infusion pedestals, activate altar.
Infusion will not start

**Expected behavior**
Crafting of rock crystal seeds

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 16.5
 - Forge: 36.0.39
 - Cucumber: 1.16.4-4.1.6
 - Mystical Agriculture: 1.16.4-4.1.5

**Comment by BlakeBr0** [comment]
I just tested and was able to craft them just fine. Maybe there's some other factor causing it not to work?

**Comment by LuciusV** [comment]
I will test again and report there if it can be reproduced

**Comment by BlakeBr0** [comment]
This issue was likely fixed in version 4.1.6. Let me know if that's not the case.

**Comment by MelanX** [comment]
For me it works perfectly fine with 4.1.7

**Comment by LuciusV** [comment]
It works in 4.1.7, thank you!
