### ISSUE TITLE
[1.16.5] [Mod interaction] [Astral Sorcery]Essence tools do not get bonus from Astral Sorcery  Resplendent prism

### ISSUE THREAD

**Issue by LuciusV** [BlakeBr0/MysticalAgriculture#395]
**Describe the bug**
Wearing Resplendent prism with enchantment level bonus does not provide bonus to Supremium Sword, Axe and Pickaxe (I suppose other Essence tools as well)
**To Reproduce**
Get Supremium sword/pickaxe, enchant with Looting/Sharpness/Fortune, wear  Resplendent prism with bonus to that or all enchantment.
It will not give bonus to Essence tool

**Expected behavior**
Expected enchant applied normally.
Actually it DOES work with Soulium dagger giving it bonuses

**Versions (please complete the following information):**
Minecraft: 16.5
Forge: 36.0.39
Cucumber: 1.16.4-4.1.6
Mystical Agriculture: 1.16.4-4.1.5

**Comment by BlakeBr0** [comment]
Obviously this is a late response, but I looked into it and found that the Resplendent Prism specifically checks if the item is damageable (see [here](https://github.com/HellFirePvP/AstralSorcery/blob/ff2d8d52d3275da401d954c86199ef92ef3779fa/src/main/java/hellfirepvp/astralsorcery/common/enchantment/dynamic/DynamicEnchantmentHelper.java#L178)), so Supremium tools won't be able to gain that items effects.
