### ISSUE TITLE
red stone seed bug

### ISSUE THREAD

**Issue by willis543210** [BlakeBr0/MysticalAgriculture#398]
**Describe the bug**

this does not only seem to be red seeds but all seeds, for some reason the red stone seed just could not be infused so i reinstalled the mod and it seemed to brought it back but long story short, please fix the interaction between hoppers and the alter, when a hopper is connected to the alter and after a seed is created, the hopper spits the next prosperity seed and it destroys the seed that was infused. 

Update***any block that involves transferring causes the seed to not be created please fix

**To Reproduce**
i do the usual set up of Redstone seed.  I place  4 red stone and 4  of the orange essence  and a prosperity seed
**Expected behavior**

i expected it to produce a red stone seed but it the seed just has a shatter effect after the infusion is done.

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft:1.16.5
 - Forge: 1.16.5
 - Cucumber: 1.16.4-4.1.8
 - Mystical Agriculture: 16.4-4.1.5

**Comment by BlakeBr0** [comment]
This may have been fixed in version 4.1.6. Let me know if the issue persists.

**Comment by willis543210** [comment]
Thanks for responding. no longer able to extract seeds from alter with pipe, I was able to earlier today


update: it's a little fishy. it just able to be extracted again with the pipe. Just in case if you did not get a notification for this comment @BlakeBr0

**Comment by BlakeBr0** [comment]
I believe this was fixed.
