### ISSUE TITLE
extra essence seeds

### ISSUE THREAD

**Issue by lucid-void** [BlakeBr0/MysticalAgriculture#399]
I love the mod but having only inferium seeds is not good for farming for essence.

I'd like to have prudentium, tertium, imperium and supremium seeds to be able to get more essence out of farming.

you could build a mob farm to farm for the essence but this adds to lag

this existed in an older version of the mod or an addon
![image](https://user-images.githubusercontent.com/74971817/112276483-08e4b780-8c3e-11eb-8d42-af17582557d0.png)

**Comment by BlakeBr0** [comment]
You can grow the Inferium seeds on better essence farmland to get more essence. Make sure to add Patchouli to your modpack so you can get the ingame guide which has lots of useful information.
