### ISSUE TITLE
Suggestion:  Use Mystical Machine Frame for Accelerator

### ISSUE THREAD

**Issue by MentalMouse** [BlakeBr0/MysticalAgriculture#40]
The Mystical Machine Frame is AFAICT only used for making the Seed Reprocessor, yet its recipe produces 4 of them.  Perhaps the MMF should be worked into the recipe for the Accelerator; it's a modest individual cost, but would bring the Accelerators under the constraint of Prosperity supply.

This speaking as someone who currently has 88 accelerators under a farm stack four layers high.  Once I was growing diamonds and three layers of Tier 3 and 5 inferium, well the last half of those accelerators came in a rush.

**Comment by BlakeBr0** [comment]
Growth accelerators arent a machine though.

**Comment by MentalMouse** [comment]
They're a block that affects their surroundings, with an animated texture yet.  That's machine-like enough for me, and AFAIK the next closest thing (After the Reprocessor) to a machine in the mod.

**Comment by BlakeBr0** [comment]
Well it's not a machine to me. You can always change the recipe with crafttweaker if you want.

**Comment by MentalMouse** [comment]
I did just find the MMF's Seekret Feature.  I did not know you could do that with JEI.  It would be slightly more interesting if you could put in other blocks, but still a bit pointless.
