### ISSUE TITLE
garden cloches

### ISSUE THREAD

**Issue by lucid-void** [BlakeBr0/MysticalAgriculture#400]
It would be nice to be able to use the seeds in a garden cloche just as you can in potany pots and the phytogenic isolator from the thermal series mod.

you could just use the botany pots but the garden cloches can be faster when you have a fertilizer.

![image](https://user-images.githubusercontent.com/74971817/112277832-63324800-8c3f-11eb-88c7-9f951a6314c8.png)
![image](https://user-images.githubusercontent.com/74971817/112277845-69282900-8c3f-11eb-948e-cc7ce8dd4d7e.png)

**Comment by BlakeBr0** [comment]
You'll have to ask the IE devs if they'll add support for it.
