### ISSUE TITLE
Issue With seeds

### ISSUE THREAD

**Issue by pewsay** [BlakeBr0/MysticalAgriculture#401]
my inferium seeds won't grow at all, i have them in good light, i tried accelerators, fertlizers wont work, watering can, nothing. they are stuck on 0 growth and i don't know what to do please help

**Comment by pewsay** [comment]
to clarify this isn't just inferium its any mystical ag seed, fertilizer will actually get them to grow but thats it. i can sit there and water can it for 19 minutes with growth accelerator under it and it wont

**Comment by crocodilovoador** [comment]
i have been suffering from this same issue

**Comment by Lothanas** [comment]
I am having the same issue as well.

**Comment by Lice2** [comment]
I have the same problem. After updating to MysticalAgriculture-1.16.4-4.1.6. Does the watering can no longer work!

**Comment by Jordan231111** [comment]
I have the same problem all my seeds are just at 0 percent.

**Comment by MinecraftianoBr** [comment]
me and the other brazilian boys are suffering from the same issue
