### ISSUE TITLE
Watering can disapears after a while when placed in an auto clicker

### ISSUE THREAD

**Issue by MushuPlatypus** [BlakeBr0/MysticalAgriculture#403]
**Describe the bug**
Watering can disapears after a while when placed in an auto clicker

**To Reproduce**
Place an Imperium watering can in an auto clicker (Cyclic, ClickMachine).
After a while the watering can disappears.

**Expected behavior**
The watering should not disappear

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - ATM 6: To the sky
 - Mystical Agriculture: 1.16.4-2.1.2

**Comment by BlakeBr0** [comment]
Is this still an issue? I don't think I've heard of anyone else having this problem.

**Comment by LeSwede** [comment]
They work fine in the Item User from Cyclic.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
