### ISSUE TITLE
Seeds do not duplicate

### ISSUE THREAD

**Issue by sunnyughs** [BlakeBr0/MysticalAgriculture#404]
**Describe the bug**
When harvested in any way, be it by right click or breaking the Mystical Agriculture crop, will not drop an extra seed.

Vanilla harvested plants duplicate like normal.

**To Reproduce**
Harvest a fully grown crop from Mystical Agriculture any number of times there will not be a seed drop

**Expected behavior**
Progression through the mod by gaining seed drops when harvesting plants.

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.1.2
 - Cucumber: 4.1.9
 - Mystical Agriculture: 4.1.7

**Comment by sunnyughs** [comment]
This isn't a bug it's just completely undocumented that you're required to grow crops on Essence Farmland unless you install Patchouli which isn't even listed as a dependency. You don't have a discord to ask questions in, and this mod is slowly becoming more and more extra as it develops.

**Comment by BlakeBr0** [comment]
👍
