### ISSUE TITLE
Crash loading pack

### ISSUE THREAD

**Issue by ejjo01** [BlakeBr0/MysticalAgriculture#405]
**Describe the bug**
Mod File: MysticalAgriculture-1.16.4-4.1.7.jar
	Failure message: Mystical Agriculture (mysticalagriculture) encountered an error during the sided_setup event phase
		java.lang.NullPointerException: Registry Object not present: mysticalagriculture:infusion_altar

**Versions (please complete the following information):**
 - Minecraft:1.16.5
 - Forge:36.1.3
 - Cucumber:1.16.4-4.1.9
 - Mystical Agriculture:1.16.4-4.1.7

**Comment by BlakeBr0** [comment]
Is this a persistent crash? If so can I see a full crash log?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If it's still an issue with the most recent version you can reply to this issue.

**Comment by HixxyDubz** [comment]
i get the same crash now, i found this place while googling the issue, here is my crash log.

https://pastebin.com/cezbUCAV
