### ISSUE TITLE
Crops dont grow

### ISSUE THREAD

**Issue by HerrBockwurst** [BlakeBr0/MysticalAgriculture#406]
**Describe the bug**
The seeds dont grow on my server. I planted it, tried normal farmland and also tried essence farmland, but still the grow is 0 percent. Also tried the watering can and bonemeal, still nothing is growing All i can find online is that it is taking long to grow, but i was 5 hours ingame, while i was near the chunk, still 0 percent. Is there any special biome required, planted it in forest biome. We play with gamerule mobgriefing false, if this is important...

**Screenshots / Scripts / Logs**
![image](https://user-images.githubusercontent.com/7777672/113506998-2d973400-9548-11eb-9d56-71b0447712b2.png)

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: forge-1.16.5-36.1.2
 - Cucumber: Cucumber-1.16.4-4.1.9
 - Mystical Agriculture: MysticalAgriculture-1.16.4-4.1.6

**Comment by BlakeBr0** [comment]
Update to the latest version.
