### ISSUE TITLE
Rubber Seed has no recipe

### ISSUE THREAD

**Issue by ModernGamingWorld** [BlakeBr0/MysticalAgriculture#407]
**Describe the bug**
According to rubber.json there should be a recipe for rubber and there is not.

**To Reproduce**
Launch my Custom Pack
Search Rubber in Jei and see No recipe, The only recipe I am getting is Botany Pots and Phytogenic Insolator and not any Mystical recipe for it

**Expected behavior**
A fix or way to fix it

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).
https://i.imgur.com/9r9XCdQ.png

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.1.4
 - Cucumber: Cucumber-1.16.4-4.1.9
 - Mystical Agriculture:  MysticalAgriculture-1.16.4-4.1.7

**Comment by flin7101** [comment]
did you resolve this issue as I am having same issue in 1.16.5, I can make the rubber seeds but the Essence can not be used to craft anything
