### ISSUE TITLE
[Suggestion] BetterEnd Seeds

### ISSUE THREAD

**Issue by CraftSpider** [BlakeBr0/MysticalAgriculture#408]
**Is your feature request related to a problem? Please describe.**
When playing with BetterEnd, there's no renewable way to get many of the ingredients, and it would be nice to have MA support.

**Describe the solution you'd like**
It would be nice to have seeds for at least Thallasium, Raw Amber, and Ender Shards. Flavolite, Crystal Shards, and possibly Aeternium I think would also make sense. (Aeternium can be crafted from prior items, but so can say Lumium or Enderium.)

**Describe alternatives you've considered**
N/A I think, as this is a straight addition of mod compat. Not supporting BetterEnd is the current status quo.

**Comment by BlakeBr0** [comment]
It does not appear like this mod is available for newer forge versions.
