### ISSUE TITLE
Horn of the Wild does not operate properly in 1.11.2 version

### ISSUE THREAD

**Issue by AranaiRa** [BlakeBr0/MysticalAgriculture#41]
I have made sure that the value in the config file is set to true.

Unlike the 1.10 version, in the 1.11 version Botania's Horn of the Wild breaks all magical crops without regard to growth stage and does not replant.

**Comment by BlakeBr0** [comment]
Botania wasnt updated to 1.11 when i added that feature, so the code isnt in the 1.11 version. I'm adding it in the next update though

**Comment by BlakeBr0** [comment]
Couldn't actually add this in the most recent update because botania would crash in my dev env. Reopening to remind me to check this out again at another time.

**Comment by BlakeBr0** [comment]
I've decided I'm not going to add this feature to any versions past the 1.10 version. In the next update I release I'm adding Scythes which have the same functionality as this anyways, so the mechanic will still be there to some capacity.
