### ISSUE TITLE
Only one slot in Tinkering Table

### ISSUE THREAD

**Issue by poopkickercmyk** [BlakeBr0/MysticalAgriculture#413]
**Describe the bug**
When i put anything in the Tinkering Talbe only one slot opens

**To Reproduce**
1. Put anything into the Tinkering Table
2. Watch

**Expected behavior**
I expected more slots to unlock the higher tier, my essence armor was

**Screenshots / Scripts / Logs**
![image](https://user-images.githubusercontent.com/82456324/116670719-5cb29100-a9a0-11eb-96b8-8d32fbea538a.png)
![image](https://user-images.githubusercontent.com/82456324/116670771-6d630700-a9a0-11eb-9c22-9c6ad522764f.png)

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 1.16.5 (36.1.13)
 - Cucumber: 1.16.4-4.1.9
 - Mystical Agriculture: 1.16.4-4.1.7

**Comment by RobertLSnead** [comment]
You have one slot unlocked, I have none unlocked.
Unable to use any augments.

**Comment by BlakeBr0** [comment]
There are currently no items in the mod that have more than 1 augment slot.
