### ISSUE TITLE
Rat Tracker

### ISSUE THREAD

**Issue by AblePoison** [BlakeBr0/MysticalAgriculture#415]
My favorite rat, Big Hat Logan, disappeared in Ratlantis after getting stuck in a tree while using the biplane, and I'd think a tracker similar to doggy talents would be effective in solving this issue. It may be the problem with rats respawning after loading a chunk, as I've had my rats die after loading into my home chunk from falling into the ceiling, but I put in the effort to make it so he respawns, but now with the unfortunate problem that he disappeared.

**Comment by BlakeBr0** [comment]
Pretty sure you posted this in the wrong repo.
