### ISSUE TITLE
Supremium armor with flight augment won't fly

### ISSUE THREAD

**Issue by ChynaRose17** [BlakeBr0/MysticalAgriculture#417]
I used the tinkering table, put the flight augment on the supremium chestplate, it says on mouseover it has flight, put on the whole suit, and no flight

Pack: Chyna's Pack - Rainbows and Unicorns-05-12-2021b.zip
Mods:MysticalAgriculture-1.16.4-4.1.7, MysticalAgradditions-1.16.4-4.1.5, MysticalCustomization-1.16.4-2.1.3, Cucumber-1.16.4-4.1.9
Forge: 36.1.16, Game 1.16.5

**Comment by ChynaRose17** [comment]
After testing and removing mods i figured out the create mod was stopping it from working

**Comment by puppet04** [comment]
hi bro, there is any configuration to make them work togheter?
