### ISSUE TITLE
Disabling the Altar

### ISSUE THREAD

**Issue by TakkinFaircrest** [BlakeBr0/MysticalAgriculture#418]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.**
I'd like to be able to disable the altar and allow people to craft their seeds in a normal crafting table. 
I'd also like to be able to adjust the already set recipes for seeds to different items; like instead of various soul jars, it would be their raw materials dropped. For example; sheep would simply be wool. 

**Additional context**
I tried looking for config files on our server box, but was unable to locate anything that seemed to allow me to do this. I tried Mystical Customization, but that seems to make me 'create' new seeds and crops; whereas I just want to modify the ones already being used.

**Comment by BlakeBr0** [comment]
You can use Mystical Customization to edit crops, including their crafting materials. In the server config file (located inside of each save folder) you can enable regular crafting recipes.

**Comment by BlakeBr0** [comment]
The server config I mentioned earlier wasn't working prior to the most recent update. The config option is now in the regular config file. 

Here's the docs for editing crops: https://mods.blakebr0.com/docs/mysticalcustomization/editing-crops
