### ISSUE TITLE
Unable to find recipes?

### ISSUE THREAD

**Issue by liampearson96** [BlakeBr0/MysticalAgriculture#420]
Just would like to know where to find the crafting recipes on 1.16.5, I've followed the docs and cannot find the recipes anywhere.  i've looked in the world folder, kubejs folder, main config folder, and datapack folder. 
Reason for asking is because in JEI the some recipes don't show all the required items, however the recipes still work.

**Versions (please complete the following information):**
 - Minecraft:1.16.5
 - Forge: forge-1.16.5-36.1.4
 - Cucumber: Cucumber-1.16.4-4.1.9
 - Mystical Agriculture: MysticalAgriculture-1.16.4-4.1.7

**Comment by BlakeBr0** [comment]
Which recipes aren't showing properly? Is this in single player or on a server?

**Comment by CTO7** [comment]
I'm getting the same issue, the recipes show up in single player but if I join my server they stop showing up, they stay missing if I go back to single player without restarting the game. I added the mod to Enigmatica 6. The recipes still work on the server if I attempt to make them but nothing in JEI. The missing recipes are pretty much anything made with the infusion altar so mostly seeds.
MC 1.16.5
Forge: 36.1.31
Cucumber: 4.1.10
Mystical Agriculture: 4.2.0

**Comment by BlakeBr0** [comment]
This should be fixed in the latest version.
