### ISSUE TITLE
Add insanium tier tools and armor

### ISSUE THREAD

**Issue by jarquafelmu** [BlakeBr0/MysticalAgriculture#421]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.**
The only problem here is that they do not exist :D

**Describe the solution you'd like**
I would love a 6th tier of armor and weapons. Insanium tier. Potentially these could be completely enchantable like normal tools, something the supermium sword is lacking, it is also lacking the ability to have the lucky or fortune. additionally they could potentially have more than one augment slot

**Describe alternatives you've considered**
nothing really touches the idea of a sixth tier of tools and armor

**Comment by BlakeBr0** [comment]
I have no plans to ever add insanium tools/armor.
