### ISSUE TITLE
Diamond essence farm crashing server

### ISSUE THREAD

**Issue by Zynax1** [BlakeBr0/MysticalAgriculture#423]
Whenever I go near my base my game goes down to 1fps and the server crashes shortly after. All the recent crash reports point towards diamond essence. Here is the most recent crash report: [crash-2021-05-29_20.22.21-server.txt](https://github.com/BlakeBr0/MysticalAgriculture/files/6565302/crash-2021-05-29_20.22.21-server.txt)

**Versions: **
 - Minecraft: 1.12.2
 - Forge: 1.12.2-14.23.5.2854
 - Cucumber: 1.12.2-1.1.3
 - Mystical Agriculture: 1.12.2-1.7.5

**Comment by BlakeBr0** [comment]
Maybe you let too may items spawn into the world.  You'll have to find a way to get rid of them, or restore from a backup.
