### ISSUE TITLE
Will the mod be updated to version 1.17?

### ISSUE THREAD

**Issue by AST3RIXX** [BlakeBr0/MysticalAgriculture#425]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.**
My only “feature” that I want to be added is for the mod to work on 1.17 servers.

**Comment by remplerus** [comment]
uhm, it cant be updated to 1.17 since forge isnt out for 1.17 duh...

**Comment by AST3RIXX** [comment]
> uhm, it cant be updated to 1.17 since forge isnt out for 1.17 duh...

Well, smartass, I meant when it was able to be updated duh…

**Comment by BlakeBr0** [comment]
Just a tip: don't ask modders this question.

**Comment by BlakeBr0** [comment]
I guess for reference: I do plan on updating my mods to 1.17
