### ISSUE TITLE
Various Mod Seed Compat Issues

### ISSUE THREAD

**Issue by justwlocke** [BlakeBr0/MysticalAgriculture#426]
**Describe the bug**
Certain seeds for modded materials won't grow with certain methods.

Specifically, the seeds for Tinker's Construct materials will not grow in Botany Pots, or a Phytogenic Insulator.
The seeds for Big Reactors materials won't grow in a Phytogenic Insulator.

**To Reproduce**
Put any type of farmland in a botany pot, Tinkers seeds wont grow.
Try to put Tinkers seeds in a phytogenic insulator, won't grow.

Try to put Big Reactors seeds in a Phytogenic Insulator, won't grow.

**Expected behavior**
All Seeds grow in the botany pots and/or phytogenic insulator

**Screenshots / Scripts / Logs**
I can confirm these situations with Hepatizon seeds (TC) and Yellorium seeds (Reactors).
However, JEI does not display the respective outputs for the rest of the seeds, so I'll assume the rest don't work either.

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.1.24
 - Cucumber: 1.16.4-4.1.9
 - Mystical Agriculture: 1.16.4-4.1.18
 - [Tinker's Construct](https://www.curseforge.com/minecraft/mc-mods/tinkers-construct): 1.16.5-3.0.4.171
 - - I don't imagine the tinkers update will fix it, but this is one update behind.
 - [Extreme Reactors](https://www.curseforge.com/minecraft/mc-mods/extreme-reactors): 1.16.4-2.0.23
 - [Botany Pots](https://www.curseforge.com/minecraft/mc-mods/botany-pots): 1.16.4-7.0.18
 - [Thermal All-Of-Them](https://www.curseforge.com/minecraft/mc-mods/thermal-foundation): 1.16.4-1.2.0

**Comment by BlakeBr0** [comment]
I don't make those mods, you'll have to ask them to update their integrations.
