### ISSUE TITLE
Mystical agriculture cant plant inferium seeds in crop sticks

### ISSUE THREAD

**Issue by Lordsupermen** [BlakeBr0/MysticalAgriculture#429]
well i cant plant inferium seeds in crop sticks,also i want a step by step because i dont know so much englsih

**Comment by BlakeBr0** [comment]
This mod doesn't have crop sticks. I think you're referring to Agricraft.

**Comment by tyggna** [comment]
the problem is in config/agricraft/json/mod_mysticalagriculture/plants/fire_plant.json  -- it's a duplicate ID
