### ISSUE TITLE
[1.11.2 - 1.5.0] Crash interaction with entities

### ISSUE THREAD

**Issue by VallenFrostweaver** [BlakeBr0/MysticalAgriculture#43]
Not sure if this is MA or Animania so I'm posting it on both githubs.

Crash report:
[https://hastebin.com/enixesemax.sql](https://hastebin.com/enixesemax.sql)

EDIT: I can load up the modpack but upon approaching a nearby cow it crashes. Still experimenting.
EDIT#2: Looks like it's just any entities and not Animania at all as I can reproduce with a zombie. Caused by updating from v1.4.5 to 1.5.0
Cinfirmed on EDIT#2

**Comment by BlakeBr0** [comment]
I'm assuming you have the passive mob inferium drop chance set to 0?

**Comment by VallenFrostweaver** [comment]
Yes. Passive mob drop inferium drop chance is at zero

**Comment by BlakeBr0** [comment]
1.5.0a shoud fix the issue
