### ISSUE TITLE
server crash with 4.2.0

### ISSUE THREAD

**Issue by CKY-** [BlakeBr0/MysticalAgriculture#430]
**Describe the bug**

Crash when opening seed re-processor 

**To Reproduce**

open seed re-processor 

**Expected behavior**

https://gist.github.com/CKY-/aec1d78e4874dcbdd928f733b5af4d46

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.1.32
 - Cucumber: 4.1.10  
 - Mystical Agriculture: 4.2.0

**Comment by BlakeBr0** [comment]
Looks like an addon crash since this mod doesn't have an Insanium Seed Reprocessor.
