### ISSUE TITLE
Certus quartz and fluix seeds recipes not properly displaying in multiplayer

### ISSUE THREAD

**Issue by IchHabeHunger54** [BlakeBr0/MysticalAgriculture#434]
**Describe the bug**
Certus quartz and fluix crops' recipes do not properly display in JEI in multiplayer, but display in singleplayer. Can still be crafted. No clue why. Sky Stone works normally. Mystical Customization is installed, but I didn't change anything regarding AE2.

**To Reproduce**
Start a server. Join with a client that has the same mods. Try to lookup the recipe for certus quartz/fluix seeds.

**Expected behavior**
Displaying just fine.

**Screenshots / Scripts / Logs**
![2021-07-15_21 23 01](https://user-images.githubusercontent.com/52419336/125845602-229486d4-dcbf-4ac1-a598-103e9fdfbac1.png)
![2021-07-15_21 23 24](https://user-images.githubusercontent.com/52419336/125845657-435601c9-e8e9-43e0-8a53-86df08a4a6be.png)
![2021-07-15_21 23 57](https://user-images.githubusercontent.com/52419336/125845715-c684ad5d-bb10-45f5-9aa2-110dbaaa7696.png)

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.1.0
 - Cucumber: 4.1.10
 - Mystical Agriculture: 4.2.0
 - Mystical Customization: 2.1.5
 - Applied Energistics 2: 8.3.1
 - JEI: 7.7.1.110

**Comment by Sunekaer** [comment]
Same issue here with other seeds, seems like the JEI plugin doesn't sync everything to the client.
