### ISSUE TITLE
marble , ruby and sapphire seeds have no recipe

### ISSUE THREAD

**Issue by wackoamd1** [BlakeBr0/MysticalAgriculture#436]
**Describe the bug**
the marble seed  for astral sorcery shows up in jei with the  marble essence  but doesnt have a recipe same thing for the ruby and sapphire.
i even tried to use the altar with the mostly standard recipe ie. 4 marble , 4 prudentium esence and a base seed but no go , the recipe just isnt in the mod it looks like

**To Reproduce**
just install the mod ;-)

**Expected behavior**
getting a seed recipe when clicked on in jei 

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.1.32
 - Cucumber: 4.1.10
 - Mystical Agriculture: 1.16.5-4.2.1

**Comment by BlakeBr0** [comment]
Currently the marble seeds require chisel marble. Each of the 3 mods that have marble essence recipes all use different tags which makes things annoying, so I'll have to add additional seed recipes for the others.

Does your modpack have any ruby or sapphire items? If so do they have the forge:gems/ruby & forge:gems/sapphire tags? I think I only tested with thermal foundation.

**Comment by BlakeBr0** [comment]
I'm going to close this as I believe it's resolved. In the latest version marble seeds can be created using chisel, quark and astral sorcery marble. Ruby/sapphire seeds can be crafted using thermal expansion ruby/sapphire and should work with any items with the tags I mentioned above.
