### ISSUE TITLE
Bad Jei Pattern For recipes

### ISSUE THREAD

**Issue by ghost** [BlakeBr0/MysticalAgriculture#437]
Is this related to JEI? Some recipes for seeds miss materials like silicon (Refined Storage) in 4 squares.
![image](https://user-images.githubusercontent.com/10179239/126998072-492dcec2-c477-4923-b927-38d5fdd7da4b.png)

**Comment by BlakeBr0** [comment]
This is a very annoying issue that I haven't been able to reproduce. (assuming this is on a server)
