### ISSUE TITLE
1.16.5 Growth Accelerators not effecting full column

### ISSUE THREAD

**Issue by ElijahSimonson** [BlakeBr0/MysticalAgriculture#438]
Minecraft Version: 1.16.5
MA Version: 4.2.1

Not sure if this is as intended or a bug (reading about growth accelerators says that it may be).
Crops placed directly above growth accelerators growing at increased rates but crops further up not being effected.
![javaw_DhFX8dirWW](https://user-images.githubusercontent.com/24466927/127761752-7977bf20-e484-4132-9149-13328ed5a27d.png)

**Comment by BlakeBr0** [comment]
correct
