### ISSUE TITLE
Soul Jar with Crafttweaker

### ISSUE THREAD

**Issue by Inverseder** [BlakeBr0/MysticalAgriculture#440]
Hello,
I want to make a custom recipe for seeds with soul jar on crafttweaker. But I don't have the ID of specific soul jar with specific entity. Can you help me please?

**Comment by BlakeBr0** [comment]
You should be able to see the mob soul type ID in the tooltip of the filled soul jar in JEI if you have advanced tooltips enabled (f3 + h).

**Comment by DeadTrapsDevelopment** [comment]
> Hello,
> I want to make a custom recipe for seeds with soul jar on crafttweaker. But I don't have the ID of specific soul jar with specific entity. Can you help me please?

take the soul jars with the souls out of JEI and u get the exact id via /ct hand
Guardian soul as example look like

<item:mysticalagriculture:soul_jar>.withTag({Souls: 10.0 as double, Type: "industrialagriculture:guardian" as string})
