### ISSUE TITLE
Shift Clicking Upgrade into Tinkering Table delates extra

### ISSUE THREAD

**Issue by UnRealDinnerbone** [BlakeBr0/MysticalAgriculture#441]
**Describe the bug**
When shift-clicking a stack of upgrades into the tinkering tables it puts when it deletes the rest

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.2
 - Cucumber: 4.1.10
 - Mystical Agriculture: 4.2.1

**Comment by BlakeBr0** [comment]
When I tested it seemed to delete just 1 extra. I'm assuming that's what you experienced?

**Comment by UnRealDinnerbone** [comment]
yha it was one extra not a stack
