### ISSUE TITLE
All Mystical Agriculture Tinker Seeds incompatible with Botany Pots. 

### ISSUE THREAD

**Issue by Gillios** [BlakeBr0/MysticalAgriculture#442]
Hey, I can craft the Tinker Seeds with the Altar., but I can't put them into an Botany Pot. 
All other Seeds working fine, only the Tinker Seeds.
I play with the newest Version of Mytical Agriculture and Tinker and Botany Pots.

**Comment by BlakeBr0** [comment]
This integration is handled on the Botany Pots side. You'll have to ask them to update if they haven't already.
