### ISSUE TITLE
Astral Sorcery Integration bug

### ISSUE THREAD

**Issue by AlgorithmLX** [BlakeBr0/MysticalAgriculture#445]
**Describe the bug**
Rock Crystal Seeds are not created

**To Reproduce**
Download Mystical Agraculture
Download Cucumber Library
Download Astral Sorcery

**Expected behavior**

**Screenshots / Scripts / Logs**
Video!
https://youtu.be/mjv6eGFsY7w

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.2
 - Cucumber: 4.1.10
 - Mystical Agriculture: 4.2.1 (lasted (may be))

**Comment by BlakeBr0** [comment]
I am able to create them just fine. Is there any other info you can provide?

**Comment by AlgorithmLX** [comment]
> I am able to create them just fine. Is there any other info you can provide?

No, I can't provide anything else. I have all the seeds are created, but the crystal from Astral Sorcery do not want. I had to put ore instead of Rock Crystals.

**Comment by AlgorithmLX** [comment]
Video is all I can provide. Well, okay, I can also provide a modpack.
