### ISSUE TITLE
Bugged Soul Jar

### ISSUE THREAD

**Issue by Zaxmyss** [BlakeBr0/MysticalAgriculture#447]
**Describe the bug**
Any type of filled soul jar and even empty soul jar produce random soul seed when placed at infusion altar in the mod latest version.
I tried rolling back to 4.2.1 and there's no issue.

**To Reproduce**
Install Mystical Agriculture 1.16.5-4.2.2

**Expected behavior**
Each filled soul jar should produce their respective soul seed.

**Screenshots / Scripts / Logs**
-

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.2
 - Cucumber: 4.1.10
 - Mystical Agriculture: 1.16.5-4.2.2

**Comment by Sunekaer** [comment]
@BlakeBr0 Pretty big bug FYI :)

**Comment by benbenlaw** [comment]
https://github.com/benbenlaw/seaopolis/issues/138
