### ISSUE TITLE
When I try to craft cow seeds, or any other mob seeds for the matter, I only get chicken seeds

### ISSUE THREAD

**Issue by Leidenfrost245** [BlakeBr0/MysticalAgriculture#449]
**Describe the bug**
When I try to craft cow seeds, it only gives me chicken seeds.

**To Reproduce**
Steps to reproduce the behavior: 1. Gather cow soul using soul jar
                                                      2. Craft cow seed as usual using infusion altar.

**Expected behavior**
Cow seed to result in end crafting.

**Screenshots / Scripts / Logs**
-

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.20
 - Cucumber: 4.1.10
 - Mystical Agriculture: 4.2.2

**Comment by Elvundil** [comment]
https://github.com/BlakeBr0/MysticalAgriculture/issues/447 

 all .craft with soul jar bug it does not work. it seems that it does not take into account whether the jar is full or not.
