### ISSUE TITLE
Fertilized Essence config suggestion

### ISSUE THREAD

**Issue by NealHicks** [BlakeBr0/MysticalAgriculture#45]
You might want to connect the config settings "B:fertilized_essence=" and "I:fertilized_essence_chance=" so the first overrides the second.  I made the mistake of disabling fertilized essence and neglecting to disable chance to drop from harvesting, and when something that didn't exist tried to drop, it crashed the game.

I don't know if there's a recipe to craft the stuff offhand, so maybe someone wouldn't want it to drop but still have it exist, but the opposite settings will kill a save.  Playing All The Mods 2 for 1.11.2

**Comment by BlakeBr0** [comment]
Fixed in the next update.
