### ISSUE TITLE
Tinker's Bronze Seed unplantable in Botany Pot

### ISSUE THREAD

**Issue by 2ndRecon** [BlakeBr0/MysticalAgriculture#450]
**Problem Statement**

It does not appear that there is any way to plant "Tinker's Bronze Seed" into botany pot. 
The rest of the seeds in Mystical Ag. seem to be working fine. Not sure if this is an issue on the M.A. side, or an issue with Botany Pot. There doesn't seem to be any way to configure / modify this via a config / JSON / SNBT. So without looking at the source I can't really troubleshoot any further.

**Reproduce Issue:**

Place a "Botany Pot" or a "Botany Hopper Pot". Place an appropriate soil (any soil, really) in the pot. (i tried them all)

Attempt to place the "Tinker's Bronze Seed". 

It won't place.
--[Note] - The "bronze" seed from M.A. works just fine. It appears the only substantial difference between them is that items created with the Tinker's have a slightly lower durability.

It works fine in correct soil placed in the world / on the ground, but not in a Botany Pot.

The remainder of the Seeds from the Mod seem to be working fine including the standard M.A. Bronze, as mentioned. 

**Versions**
 - Minecraft: 1.16.5
 - [Botany Pots is 1.16.5-7.1.24)
 - Cucumber: 1.16.5-4.1.10
 - Mystical Agriculture: 1.16.5-4.2.3

**Comment by BlakeBr0** [comment]
You'll have to ask the botany pot devs to add it as the integration is added on their end.

**Comment by 2ndRecon** [comment]
Thanks.. Understood.
