### ISSUE TITLE
soft obsidian dupe of sorts

### ISSUE THREAD

**Issue by frakier** [BlakeBr0/MysticalAgriculture#452]
**Describe the bug**
Soft obsidian can be doubled... sort of a dupe... two obsidian and two of stone give you four obsidian.
This could be the side effect of some mod adding tags but I'm not sure. Seems like it was not intended though.
Guess you could call it some kind of equivalent exchange but it does make some really expensive recipes very cheap.

**To Reproduce**
[andesite for example][soft obsidian]
[soft obsidian][andesite for example]

gives four [soft obsidian]

**Expected behavior**
well, guessing this recipe should not exist

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.2
 - Cucumber: not installed I guess
 - Mystical Agriculture: 0.3.2.16
 
Modpack: Valhelsia 3-3.4.2a

**Comment by BlakeBr0** [comment]
Perhaps this issue was meant for a different repo?

**Comment by frakier** [comment]
Yep my bad.. mystical world... not mystical agriculture. I'm always confusing the names. Sorry for the inconvenience.
