### ISSUE TITLE
Health Boost V augment resets on server leave

### ISSUE THREAD

**Issue by LeSwede** [BlakeBr0/MysticalAgriculture#454]
**Describe the bug**
Health Boost V augment resets on server leave and join

**To Reproduce**
Steps to reproduce the behavior: Just leave and rejoin the sever and the hearts goes away

**Expected behavior**
I expected it to keep my hearts when I leave the server :P

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.8
 - Cucumber: 4.1.10
 - Mystical Agriculture: 4.2.3

**Comment by Twisted-Code** [comment]
@BlakeBr0 You may want to take a look at Darkhax-Minecraft/Max-Health-Fix, which uses a mixin to catch and store the player's health during the deserialization process. Looks like it might be a simpler solution (depending on how you feel about mixins) than yours, and it only has to run when the player is loading in.
Disclaimer: this is the opinion of a fairly inexperienced programmer, and one that rarely writes in Java. YMMV, etc. etc.
