### ISSUE TITLE
Can't create Inferium Seeds with AgriCraft in 1.16.5

### ISSUE THREAD

**Issue by liadon10** [BlakeBr0/MysticalAgriculture#456]
**Describe the bug**
When trying to craft Inferium Seeds, the recipe is apparently looking for wheat seeds with metadata from Minecraft (base), however if running AgriCraft all base game metadata seems to be changed to AgriCraft, which makes crafting Inferium Seeds impossible

**To Reproduce**
-Gather 8 Inferium Essence
-Gather Wheat Seeds
-Place in crafting table in expected orientation

**Expected behavior**
I expected to be able to craft Inferium seeds

**Screenshots / Scripts / Logs**
<img width="357" alt="Inferium Seeds crafting attempt" src="https://user-images.githubusercontent.com/3718841/143789276-423aa206-ee31-4d0b-923f-8d3a8f7361e3.png">

<img width="667" alt="Inferium Seeds Recipe" src="https://user-images.githubusercontent.com/3718841/143789274-a5ce19c7-a205-4db9-9a8b-16de6293f060.png">

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 1.16.5-36.2.19
 - Cucumber: 1.16.5-4.1.12
 - Mystical Agriculture: 1.16.5-4.2.5

**Comment by BlakeBr0** [comment]
Have you reported this to the agricraft devs? I very hightly doubt that this issue would be exclusive to MA, considering what they're doing is adding an entirely different item.

**Comment by BlakeBr0** [comment]
I just tested with the latest AgriCraft for 1.16 installed and breaking grass dropped a vanilla wheat seed, which I could use to craft Inferium Seeds. Planting it changes it to an AgriCraft plant but they are atleast craftable now from what I can tell.
