### ISSUE TITLE
no ultimate furnace

### ISSUE THREAD

**Issue by katashiii204** [BlakeBr0/MysticalAgriculture#457]
**Describe the bug**
I installed mystical agriculture into my already used world and wanted to craft the ultimate furnace I looked for it but didn't find the recipe then I looked into all confic files and it said that the ultimate furnace and essence furnace are allowed then I looked again and still haven't found the recipe 
**To Reproduce**
just installed it and looked for the recipe
tried the recipe after I looked at ftp wiki and it still didnt work

**Expected behavior**
The recipe is there

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft:1.16.5
 - Forge: 36.2.16
 - Cucumber: 4.1.12
 - Mystical Agriculture: 4.2.5

[2021-11-30-4.log.gz](https://github.com/BlakeBr0/MysticalAgriculture/files/7626268/2021-11-30-4.log.gz)

**Comment by BlakeBr0** [comment]
There is no ultimate furnace in newer versions. I plan on adding a replacement at some point, but it won't be for 1.16.

**Comment by BlakeBr0** [comment]
The Awakened Supremium Furnace available in version 6.0.0 is the new equivalent of the Ultimate Furnace.
