### ISSUE TITLE
[Suggestion]: Make compatible with ore processing mods.

### ISSUE THREAD

**Issue by NightOps007** [BlakeBr0/MysticalAgriculture#458]
Instead of giving the resource in a ready to use state from crafting essences, give the raw ore so it can be processed and multiplied by other mods. Alternatively, just add more recipes that give ores instead of the resource. Or make it an option in the config.

**Comment by BlakeBr0** [comment]
I decided to go the route of giving the processed resources for consistency. I would also prefer not to have to balance certain essence recipes around the potential of there being mods installed that give increased outputs.
