### ISSUE TITLE
[1.10.2-1.4.3] Items from MA picked up by Item Collectors frequently result in a stack of zero items, which appear to behave incorrectly

### ISSUE THREAD

**Issue by JaSpr** [BlakeBr0/MysticalAgriculture#46]
I'll frequently see stacks of 0 inferium, which previously I would ignore.  You can click on them (as if to pick them up) and they disappear.  I had previously assumed it was because the inferium was being removed in another way (e.g. by a hopper) and there was just an update bug where there weren't any left, but the stack wasn't removed once it was empty.  

But since I've started automating mob chunk collecting, I've noticed the same thing with mob chunks.  Sometimes there will be 3 of one type of mob chunk, and 0 of another, and 0 of another.  The others which show 0 in their stack had not been there previously, so it wasn't an instance of a stack getting emptied then left behind.  These items were being added to the chest as stacks of 0.  

Additionally a stack of 0 inferium would completely halt piping items out of a chest, as when the exporter (from any other mod) got to the empty inferium stack, it would just stall out, as if it were waiting for the stack to empty, not realizing that the stack shouldn't exist in the first place if it was a zero item stack.)

Throwing an additional inferium out for the collector to pick up *does* result in the zero stack updating to a 1 item stack, however.

![Screenshot](https://cloud.githubusercontent.com/assets/1010443/25034936/e7551a2c-20af-11e7-93b8-54bcb4e74367.png)

Versions:
FTB SkyFactory 3 3.0.8
FML 8.0.99.99
MC 1.10.2
Forge 12.18.3.2254
Mystical Agriculture 1.4.3

**Comment by BlakeBr0** [comment]
1. Most recent version is 1.5.0a
2. Is it only with item collectors, or do other vacuums do the same thing?

**Comment by JaSpr** [comment]
I haven't tried other vacuums. Generally that item collector is my go to vacuum.  

Regarding the version, that is (unfortunately) the current version packaged in SkyFactory 3.

**Comment by BlakeBr0** [comment]
I'll look into this more later. The next update I release probably won't fix it if it isn't fixed already.

**Comment by BlakeBr0** [comment]
Just released 1.5.2 with what might be a fix. Let me know if this still happens or not.

**Comment by BlakeBr0** [comment]
I'm gonna assume this isn't an issue anymore.

**Comment by JaSpr** [comment]
We're running SkyFactory 3, which just updated to 1.5.0, so won't know for (probably) quite a while, whenever they issue a new release.  If you think it's fixed, I'd say it probably is in this case.
