### ISSUE TITLE
[1.18.1] cannot upgrade to the tier 2 inferium seeds

### ISSUE THREAD

**Issue by rincher** [BlakeBr0/MysticalAgriculture#465]
**Describe the bug**
Upgrade the inferium seeds' tier using the prudentium essence

**To Reproduce**
Try to create tier 2 inferium seeds with tier 1 inferium seeds with 8 prudentium essences.

**Expected behavior**
According to FTB wiki (https://ftb.fandom.com/wiki/Inferium_Seeds_(Tier_2)), the old versions of Mystical Agriculture had a seed upgrade.

**Screenshots / Scripts / Logs**

![2021-12-22_04 37 22](https://user-images.githubusercontent.com/37427048/146987969-fe0777e2-8933-4d6a-abe7-99daadf908ac.png)

**Versions (please complete the following information):**
 - Minecraft: 1.18.1
 - Forge: 39.0.5
 - Cucumber: 5.0.1
 - Mystical Agriculture: 5.0.0

**Comment by BlakeBr0** [comment]
Tiered Inferium seeds no longer exist in versions past 1.12. Now you upgrade the farmland to higher tier essence farmland to increase Inferium output. [more info here](https://blakesmods.com/guides/mysticalagriculture/gameplay/getting-started#growing-inferium)

**Comment by rincher** [comment]
Thank you for the update. And Merry Christmas to you.
