### ISSUE TITLE
Applied Energistics 2 Seeds in 1.18 missing

### ISSUE THREAD

**Issue by Megafoan** [BlakeBr0/MysticalAgriculture#468]
**Describe the bug**
When playing with both Applied Energistics 2 and Mystical Agriculture, certain items do not have associated seeds or recipes to craft seeds - specifically, certus quartz and sky stone. Silicon has a seed and recipe for it.

**To reproduce**
Play with both Applied Energistics 2 and Mystical Agriculture in 1.18.

**Expected behavior**
I expected to be able to craft seeds of these items.

**Screenshots / Scripts / Logs**
N/A

**Versions (please complete the following information):**

- Minecraft: 1.18
- Forge: 1.18-38.0.14
- Cucumber: 1.18.1-5.0.1
- Mystical Agriculture: 1.18.1-5.0.0

**Comment by BlakeBr0** [comment]
This should've been fixed in the latest release.

**Comment by Megafoan** [comment]
It has indeed been fixed. Thank you.
