### ISSUE TITLE
Inferium seeds in Foolcraft

### ISSUE THREAD

**Issue by IAmKedde** [BlakeBr0/MysticalAgriculture#47]
I cant seem to find any diffrence between the agriculture (10/10/10) tier 1 seeds and the tier 5. Is there any diffrence at all? or is it only without agriculture?

**Comment by BlakeBr0** [comment]
I don't do any of the support for agricraft, you'll have to talk to whoever does.
The normal seeds give +1 essence per harvest per tier.
