### ISSUE TITLE
[Feature Request] Make Supremium and Insanium gear immune to fire and explosions

### ISSUE THREAD

**Issue by Inonedn** [BlakeBr0/MysticalAgriculture#472]
Making Supremium and Insanium related items immune to lava and explosions will allow you to safely fight the wither without worrying of destroying the item

N/A

**Comment by BlakeBr0** [comment]
There are fire and wither resistance augments.

**Comment by LotP1** [comment]
> There are fire and wither resistance augments.

i'm pretty sure they mean you should make the items entity fire/explosion resistant like netherite armor or nether stars
