### ISSUE TITLE
All current tools/armor can only use one augment. Also the left slots won't be augment slots.

### ISSUE THREAD

**Issue by InfernumYT** [BlakeBr0/MysticalAgriculture#473]
All current tools/armor can only use one augment. Also the left slots won't be augment slots.

_Originally posted by @BlakeBr0 in https://github.com/BlakeBr0/MysticalAgriculture/issues/267#issuecomment-577034432_

when will the update be? (1.18)

**Comment by BlakeBr0** [comment]
Awakened Supremium tools and armor added in version 6.0.0 can have 2 augments added. As far as the slots on the left, they were intended for adding essences to Staffs but I have put those on the backburner to prioritize adding other features instead.
