### ISSUE TITLE
failed to load correctly java.lang.reflect.invocationTargetException: null

### ISSUE THREAD

**Issue by kingwesley2000** [BlakeBr0/MysticalAgriculture#476]
**Describe the bug**
failed to load mystical agriculture

**To Reproduce**
i do not have any idea before it was working fine,,, i made a hardcore world after i played with the same mods on a skyblock for over 2 weeks i load the game twice because for some reason i couldnt craft.. though i could open a chest but not see what would be inside because the menue didnt pop up 

**Expected behavior**
to load correctly as it did before
i tried readding all 3 mystical agraculture mods but it didnt change

**Screenshots / Scripts / Logs**
the message i get is   Failed to load correctly java.lang.reflect.invocationTargetException: null

**Versions (please complete the following information):**
 - Minecraft: 1.18.1
 - Forge: 1.18.1-39.0.9
 - Cucumber: 1.18.1-5.0.1
 - Mystical Agriculture:1.18.1-5.0.1
 - Mystucal additions: 1.18.1-5.0.2

**Comment by BlakeBr0** [comment]
Without any logs there's really nothing I can do about this.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
