### ISSUE TITLE
the seed bags are broken

### ISSUE THREAD

**Issue by krjencik** [BlakeBr0/MysticalAgriculture#478]
**Describe the bug**
see the screenshot

**To Reproduce**
take a seed bag from creative inventory and open it

**Expected behavior**

I dont know, because im new to this mod

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

![2022-01-18_15 51 43](https://user-images.githubusercontent.com/92643141/149960607-43d4a9c3-ceb2-4dd1-9ad4-a65fa1653002.png)

**Versions (please complete the following information):**
 - Minecraft: 1.18.1
 - Forge: 39.0.40
 - Cucumber: 5.0.1
 - Mystical Agriculture: 5.0.1

**Comment by BlakeBr0** [comment]
This mod doesn't add a 'seed bag'.
