### ISSUE TITLE
[1.16.5]some kind of issue when trying to join server due to missing seeds

### ISSUE THREAD

**Issue by BeastMaw** [BlakeBr0/MysticalAgriculture#479]
Unable to join server due to missing seeds(?)

https://imgur.com/a/cFxbVfG
https://imgur.com/SLBQhVa

I turned on vanilla crafting recipies for seeds
https://drive.google.com/file/d/12BfKcpz_M_TfqG-uldAK5-Gjcd0cFDo4/view?usp=sharing
^modlist if there is some kind of conflict I dont know about

 - Minecraft:1.16.5
 - Forge:1.16.5 36.2.23
 - Cucumber:1.16.5-4.1.12
 - Mystical Agriculture:1.16.5-4.2.3

**Comment by BlakeBr0** [comment]
It seems to be looking for polar bear/fox seeds, which this mod doesn't add. Maybe another mod adds those?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
