### ISSUE TITLE
[1.16.5] Crafting recipes not shown

### ISSUE THREAD

**Issue by MurricaMan** [BlakeBr0/MysticalAgriculture#480]
**Describe the bug**
When I connected to my brother's LAN server, I could not see recipes that used a crafting table or anything that acted like one, such as an auto-crafting device. We were able to narrow down the cause to Mystical Agriculture. However when I tested a pack with JEI, Mystical Agriculture, and Cucumber Library alone, crafting table recipes were visible. As such I'm not sure which of the other mods is causing issues when ran together with Mystical Agriculture.

**To Reproduce**
1. Install the mods listed here: [https://pastebin.com/zkB8XpSB](url)
2. Launch Minecraft
3. Join a LAN world (or dedicated server, I would assume)

**Expected behavior**
Crafting table recipes are visible as they should be in JEI

**Screenshots / Scripts / Logs**
[2022-01-19-1.log.gz](https://github.com/BlakeBr0/MysticalAgriculture/files/7921243/2022-01-19-1.log.gz)

**Versions:**
 - Minecraft: 1.16.5
 - Forge: 36.2.22
 - Cucumber: 4.1.12
 - Mystical Agriculture: 4.2.6

**Comment by BlakeBr0** [comment]
Is this still an issue? I believe there was a forge issue involving something similar to this, but I'm not 100% sure if it was fixed.

**Comment by MurricaMan** [comment]
I honestly completely forgot about this post here, but I assume were I to recreate that custom pack and run it that it would have this issue. I don’t see anyone else here saying they have this problem, and I haven’t seen anything like it since, so as far as I’m concerned, the bug is irrelevant at this point.
