### ISSUE TITLE
Can't remove recipes from seeds added to MA

### ISSUE THREAD

**Issue by Elrol** [BlakeBr0/MysticalAgriculture#483]
**Describe the bug**
My mod adds seeds and MA creates the recipes for those seeds. When I try to use KubeJS to remove the recipes, it is unable to. 

**To Reproduce**
Install my mod
Install KubeJS
Create script to remove recipe for a seed from my mod.

**Expected behavior**
For the recipes to be able to be removed.

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.18.1
 - Forge: 39.0.59
 - Cucumber: 5.0.3
 - Mystical Agriculture: 5.0.2

**Comment by Elrol** [comment]
I am not sure if this issue is specifically on the MA side of things or if it is on the KubeJS side, but I know KubeJS is able to remove the recipes for MA seeds, but not the ones that my mod makes with MA.

**Comment by BlakeBr0** [comment]
The auto-generated recipes get added dynamically which may happen after kubejs runs. I generate the recipe json files for the base mod crops, which would get loaded at the right time. I would recommend adding the recipes manually.

Example jsons:
https://github.com/BlakeBr0/MysticalAgriculture/tree/1.18/src/generated/resources/data/mysticalagriculture/recipes/seed

If you're going to add them manually you should also disable the dynamic recipes in your plugin:
https://github.com/BlakeBr0/MysticalAgriculture/blob/3ceacb522a23545d479a74c435ae8c3d0c56c4b4/src/main/java/com/blakebr0/mysticalagriculture/lib/ModCorePlugin.java#L17

**Comment by Elrol** [comment]
Perfect, that helps out a lot. 
I don't have an issue with making the recipes myself, I just couldn't figure out how I would prevent the auto recipe generation. 

Thanks for this  👍
