### ISSUE TITLE
Glass Farmland

### ISSUE THREAD

**Issue by BenGoldberg1** [BlakeBr0/MysticalAgriculture#484]
It's not uncommon to build a farm vertically, with many layers of farmland.  Because blocks of farmland are opaque, I cannot see most of the (cool looking) mystical plants.

I would like it if using an inferium or better hoe on a block of glass or stained glass turns it into glass farmland or stained glass farmland.

This glass or stained glass farmland could be upgraded by applying (inferium, prudentium, etc) essence to it.

**Comment by BlakeBr0** [comment]
I don't think it really makes sense to grow plants on glass.

**Comment by BlakeBr0** [comment]
I'm going to close this as I consider it out of the scope of this mod. I think it would be interesting as a standalone mod though.
