### ISSUE TITLE
Mystical Agriculture crashes the client and does not let the player back on the server again

### ISSUE THREAD

**Issue by HenrikoMagnifico** [BlakeBr0/MysticalAgriculture#486]
**Describe the bug**
A player who was playing on my server suddenly had their game crash whilst mining, and is now unable to join the server again. It says that the mod Mystical Agriculture "failed to load".

**To Reproduce**
Run Mystical Agriculture on a server, play for a period of time until the game crashes.

**Expected behavior**
The game to not crash or have this issue.

**Screenshots / Scripts / Logs**
[crash-2022-02-05_23.17.31-fml.txt](https://github.com/BlakeBr0/MysticalAgriculture/files/8009042/crash-2022-02-05_23.17.31-fml.txt)

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.23
 - Cucumber: 4.1.9 
 - Mystical Agriculture: 4.1.7

**Comment by BlakeBr0** [comment]
Does this occur with the latest 1.16 version? That seems to be a pretty old version.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
