### ISSUE TITLE
[1.16.5] compileJava FAILED

### ISSUE THREAD

**Issue by Sgale952** [BlakeBr0/MysticalAgriculture#487]
**Describe the bug**
When compiling a mod using gradle, the error `FAILURE: Build failed with an exception` appears.

**To Reproduce**
1) download the source code
2) Enter the command in the `gradlew build` console

**Expected behavior**
I expected the mod to compile successfully and I would get a .jar file

**Screenshots / Scripts / Logs**
[log.txt](https://github.com/BlakeBr0/MysticalAgriculture/files/8009938/log.txt)
_I took the message from the console to a separate file_

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.26
 - Java: jdk 11.0.10
 - Cucumber: 4.1.12
 - Mystical Agriculture: 4.2.6

**Comment by BlakeBr0** [comment]
There are some dependencies that you need to provide manually in a /libs folder

**Comment by Sgale952** [comment]
Oh, thank you. I understand what you mean
