### ISSUE TITLE
Crash when I join the world.

### ISSUE THREAD

**Issue by DrSigma4164** [BlakeBr0/MysticalAgriculture#488]
**Describe the bug**
Crash when I join the world.

**To Reproduce**
1) Join to world
2) See eror

**Screenshots / Scripts / Logs**
[crash-2022-02-06_21.00.42-server.txt](https://github.com/BlakeBr0/MysticalAgriculture/files/8010995/crash-2022-02-06_21.00.42-server.txt)

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.21
 - Cucumber: 4.1.12
 - Mystical Agriculture: 4.2.6

**Comment by BlakeBr0** [comment]
That crashlog mentions tardis mod. Don't see mystical agriculture in there

**Comment by DrSigma4164** [comment]
Sorry. I was wrong. Thanks for correcting me
