### ISSUE TITLE
Dupe with Seed Reproccessor

### ISSUE THREAD

**Issue by Aiidoneus** [BlakeBr0/MysticalAgriculture#49]
I will try to explain this the best way I can. It is a pretty easy dupe. I don't see any issues or patches for this so I am going to assume this hasn't been reported or fix.
Using:
forge-1.10.2-12.18.3.2281-universal
mysticalagriculture[1.10.2]-1.4.3
Skyfactory 3 Version 3.0.8

Reproducing:
Get a seed reprocessor and grab any stackable item. Place the stackable items in your first slot on the hotbar, then shift click it while in the seed reprocessor. will double the item.

http://imgur.com/ccemJp2.png
http://imgur.com/2EU1zjH.png
http://imgur.com/fHRcKFx.png

Let me know if you need further information.
-Aiden

**Comment by BlakeBr0** [comment]
Man that was annoying to fix, even though it was just a couple values being 1 higher than they should be.

Thanks for the report, next update should fix it.

**Comment by Aiidoneus** [comment]
Thank you! Keep up the good work. =)
