### ISSUE TITLE
Right Click Harvesting

### ISSUE THREAD

**Issue by JustinB77** [BlakeBr0/MysticalAgriculture#493]
Heya,

Not sure if I missed a memo or anything, but I'm playing on 1.18.1 and I am unable to right click harvest plants, I have to break them. is this an intentional thing? If it is, no big deal, I think I just missed it somewhere.

**Comment by BlakeBr0** [comment]
You would need to add a mod like Pickle Tweaks to get right click harvesting. Mystical Agriculture does not come with that feature.
