### ISSUE TITLE
[Question] 1.18.1 Growth Accelerator

### ISSUE THREAD

**Issue by Cicopath** [BlakeBr0/MysticalAgriculture#495]
Hello. I have a question regarding the growth accelerators for 1.18.1 Mystical Agriculture.

I understand that the growth accelerators must be put under fertilized blocks to have the plants grow. However, I am unsure if there is a range to how many blocks one accelerator can affect, and or if there is a maximum amount of accelerators one can place under a block.

For example, an Inferium Growth Accelerator has a range of, "12 blocks." Does this mean it will affect blocks/plants in a 21x21 rectangular area? If so, does it have a specified height for how many blocks it can affect above the accelerator? For example, will a growth accelerator affect a block that is three blocks above it if the blocks in between is air? What about how many accelerators can be placed under a block? If more accelerators are added, will plants be affected faster?

Thank you.

**Comment by BlakeBr0** [comment]
The range is 12 blocks under the farmland, where it will periodically tick the crop above it to grow. There's more info in this guide:

https://blakesmods.com/guides/mysticalagriculture/gameplay/speeding-up-crop-growth#growth-accelerators

I would also recommend installing the Patchouli mod for an ingame guide book.
