### ISSUE TITLE
[Suggestion] Drop Essences When Breaking Farmland Blocks

### ISSUE THREAD

**Issue by Cicopath** [BlakeBr0/MysticalAgriculture#496]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.**
Using supremium essence to craft things is a hassle, but once you finally get the item you want using supremium, it's a great feeling... until you accidentally mine your supremium farmland and it becomes dirt again. Hours of work into reaching supremium-tier, all for it to be destroyed with the breaking of one block. With a stack of supremium farmland, that is equivalent to a stack of supremium essence, and all of that could be destroyed by breaking the farmland blocks without using Silk Touch. This is frustrating. Nobody wants to go through that trouble again.

**Describe the solution you'd like**
I would suggest for any block that is created with any essences to drop the essence they were crafted with. For example, supremium farmland uses is crafted with one supremium essence. When you break the supremium farmland, it drops the supremium essence if the tool did not have Silk Touch

**Describe alternatives you've considered**
It could be possible to drop half of the essence. For example, instead of dropping one supremium essence, breaking a supremium farmland block would drop two imperium essence. At least you get some of your work back.

**Additional context**
N/A

**Comment by BlakeBr0** [comment]
There's a 25% chance that the farmland will drop the essence when broken

**Comment by Cicopath** [comment]
Ah, alright. Thanks for the clarification.
