### ISSUE TITLE
Growth Accelerators broken

### ISSUE THREAD

**Issue by Styx-B** [BlakeBr0/MysticalAgriculture#497]
**Describe the bug**
It seems as if the growth accelerators are not functioning properly and by properly I mean at all.

**To Reproduce**
I have currently 12 inferium, then 12 prudentium, then 12 tertium growth accelerators under a supremium farm plot. 

**Expected behavior**
An obvious increase in the growth of the planted crop (tested with inferium and netherite seeds). As far as i can tell there is no difference when. That or having 60% of the maximum growth accelerators is not sufficient for a noticeable change in growth, if that is the case I would ask what then is the point and/or suggest the accelerators be buffed

**Screenshots / Scripts / Logs**

**Versions (please complete the following information):**
 - Minecraft: 1.18.1
 - Forge: newest
 - Cucumber: newest
 - Mystical Agriculture: newest
![mysticagri bug shot](https://user-images.githubusercontent.com/29577113/154390675-1f0e0b96-a77e-46e6-ba5b-217faf17658f.PNG)

**Comment by BlakeBr0** [comment]
Are all the regular conditions for crops to grow being met? Ex. light level

**Comment by recon88** [comment]
I've encountered the same issue but went to check the config files where I found:

```
	#The amount of time in seconds between each Growth Accelerator growth tick.
	#Range: > 1
	growthAcceleratorCooldown = 10
```

Which is the default value.
I turned it down to 5 which made a big difference.

**Comment by Styx-B** [comment]
@BlakeBr0 So I should have mentioned that this was in all the mods 7. I'm not sure if it was some typo or intentional or however it was implemented into the mod pack, but in my config file it was 50 seconds between each growth accelerator tick.
