### ISSUE TITLE
[Question]1.17.x Support?

### ISSUE THREAD

**Issue by MaybeYouShould-GetTheHeckouttaHere** [BlakeBr0/MysticalAgriculture#498]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**
That Makes This Post Pointless

**Is your feature request related to a problem? Please describe.**
Not Really

**Describe the solution you'd like**
A 1.17.1 Version For Mystical Agriculture.

**Additional context**
So I Have Been Trying To Make A Modpack For The Latest Version Of Minecraft That I Can Use And Found 1.17.1 To Be A Viable Option, The Problem Is That Most Of The Modpack Was Gonna Revolve Around A Combination Of Mystical Agriculture, Mystical Customization And Create To Automate Most Items From The Modpack. Maybe There Is An Alternate Version Of This Mod?

**Comment by BlakeBr0** [comment]
I will not be releasing a version for 1.17.
