### ISSUE TITLE
Flight Augment

### ISSUE THREAD

**Issue by gawamaster** [BlakeBr0/MysticalAgriculture#499]
Flight Augment in Another Quality Modpack 3 (Forge) doesn't craft.  It shows up in the JEI but doesn't show recipe. It isn't disabled because if I go into Creative and grab one and put it on my chest it works perfectly.  I tried crafting like I have done in previous packs with 4 Nether Stars, 4 Supremium Essence, and 1 Unattuned Augment but it won't craft.  I checked the different config files on the server as well as the config section in the mods on the client side and nothing for flight mentioned.

**Comment by BlakeBr0** [comment]
This would be a change done by the modpack author. They probably removed the recipe using a datapack or a crafttweaker/kubejs script.
