### ISSUE TITLE
Certain seeds do not work in Botany Pots

### ISSUE THREAD

**Issue by DBerke** [BlakeBr0/MysticalAgriculture#500]
**Describe the bug**
Apatite seeds, marble seeds, ruby seeds, sapphire seeds, fluorite seeds (and nitro crystal seeds from Mystical Aggraditions) are not plantable in Botany Pots.

**To Reproduce**
Try to plant the listed seeds in a Botany Pot, or hit U on them in JEI and see that they don't have a Botany Pots tab.

**Expected behavior**
The seeds would be plantable, like all the other Mystical Aggriculture seeds. It's possible this is intended behavior, but it doesn't seem to be a balancing issue, as there are much more valuable seeds that are plantable (like diamond and emerald seeds). I tried checking configs to see if they were disabled on purpose (for either MA or BP), but couldn't find anything related to enabling or disabling specific seeds. I also couldn't see a pattern for the specified seeds that don't work with the pots, which makes me think this is unintended behavior. (It's also possible the issue could be on Botany Pots' side.)

**Screenshots / Scripts / Logs**
Don't think these are necessary, but I can provide them if required.

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.19
 - Cucumber: 4.1.12
 - Mystical Agriculture: 4.2.6

This is in the FTB Endeavor mod pack.

**Comment by BlakeBr0** [comment]
You'll have to ask the botany pot devs to add it as the integration is added on their end.

**Comment by DBerke** [comment]
Thanks! Wasn't sure which side it was on. I'll do that.
