### ISSUE TITLE
Steel Recipe not working

### ISSUE THREAD

**Issue by LittleLyla** [BlakeBr0/MysticalAgriculture#501]
**Describe the bug**
With the listed versions, I am able to get steel essence, but cannot craft steel from the essence.

**To Reproduce**
Install immersive engineering and mystical agriculture versions.

**Expected behavior**
You should be able to craft steel ingots.

**Screenshots / Scripts / Logs**
https://prnt.sc/Qv7BrPq-qfZw

**Versions (please complete the following information):**
 - Minecraft: 1.18.1
 - Forge: 39.1.0
 - Cucumber: 5.0.3
 - Mystical Agriculture: 5.0.3
 - Immersive Engineering: 1.18.1-7.1.0-145

**Comment by BlakeBr0** [comment]
Is this still an issue you're experiencing?

**Comment by alexbown** [comment]
@BlakeBr0 Can't speak for OP, but I'm getting this issue too, it looks like recipes are missing from all metals from Thermal and Mekanism (possibly others, any that include steel in my pack) in game - recipes for mods such as Tinkers are working.
I'm playing on this modpack v3.1.0 on MC 1.18.2: https://www.curseforge.com/minecraft/modpacks/random-flim-flam

Relevant mods:
MysticalAgradditions-1.18.2-5.1.2
MysticalAgriculture-1.18.2-5.1.2
Mekanism-1.18.2-10.2.5.465
ImmersiveEngineering-1.18.2-8.2.2-154
thermal_integration-1.18.2-9.0.0.9

**Comment by alexbown** [comment]
Fixed by deleting cucumber-tags.json and letting it regenerate as mentioned in https://github.com/BlakeBr0/MysticalAgriculture/issues/520

**Comment by BlakeBr0** [comment]
This type of problem should automatically resolve itself in 1.19.2 and 1.19.3 with Cucumber versions 6.0.4 and 6.1.1.
