### ISSUE TITLE
i want to add the block(anyblock) can grow tier1-6 in botany pot how? or not have this feature

### ISSUE THREAD

**Issue by zen-zen-zen** [BlakeBr0/MysticalAgriculture#504]
i have added this into crafttweaker for botanypots
val dirt = crops.create("__", <item:mysticalagriculture:dirt_seeds>, <blockstate:minecraft:grass_block>, 1200, "magic_farmland");
dirt.addDrop(<item:mysticalagriculture:dirt_essence>, 0.75);
dirt.addDrop(<item:mysticalagriculture:dirt_seeds>, 0.05);
dirt.addDrop(<item:mysticalagriculture:fertilized_essence>, 0.01);

and i have added dirt that have same id(magic_farmland)
but I cant use it

**Comment by BlakeBr0** [comment]
As I stated in the other issue, this would be a question for the botany pots devs.
