### ISSUE TITLE
Crashes server but not client

### ISSUE THREAD

**Issue by H4ckerxx44** [BlakeBr0/MysticalAgriculture#505]
**Describe the bug**
I seem not to be able to install this mod on my "Better Minecraft v5 [FORGE]" server. The server crashes but the client runs fine.

**Steps to reproduce**:
1. Install the Better Minecraft v5 [FORGE] Modpack
2. Add MysticalAgriculture and Cucumber
3. Try to start the server

**Screenshots / Scripts / Logs**
"Relevant" stuff?: [Here.](https://hastebin.skyra.pw/irexututaw.log)
Whole debug.log: [Here.](https://paste.nextcord.dev/?id=164979940247496)

**Versions (please complete the following information):**
 - Minecraft: 1.18.2
 - Forge: 40.0.44
 - Cucumber: 5.1.0
 - Mystical Agriculture: 5.1.0

**Comment by BlakeBr0** [comment]
Is this still an issue you're experiencing?

**Comment by H4ckerxx44** [comment]
Probably not, I close this issue and whenever this is the case, I will reopen it.
Thanks for reminding me here.
