### ISSUE TITLE
Soul Extractor and Seed Reproccessor crashing client

### ISSUE THREAD

**Issue by BWITTZ** [BlakeBr0/MysticalAgriculture#506]
**Describe the bug**
crashed game when used

**To Reproduce**
shift clicked feathers into soul extractor game crashed
shift clicked inferium seeds into inferium seed reproccessor game crashed

**Expected behavior**

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).
https://crashy.net/jchHbFlEfdSpklu38rNS

**Versions (please complete the following information):**
 - Minecraft: 1.18.2
 - Forge: 40
 - Cucumber:
 - Mystical Agriculture:

**Comment by BlakeBr0** [comment]
You didn't put any version numbers. Are you using both the latest versions of Cucumber and Mystical Agriculture?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
