### ISSUE TITLE
[1.16.5] Seeds from Mystical Agriculture won't grow in a Garden Cloche

### ISSUE THREAD

**Issue by Quintiliu5** [BlakeBr0/MysticalAgriculture#507]
Is there a way to fix a problem, where you can't grow Mystical Agriculture Seeds in a Garden Cloche?

**Comment by AlgorithmLX** [comment]
This is not a bug, manually add craft or use a mod(I won’t say the name, because I don’t remember)

**Comment by BlakeBr0** [comment]
https://github.com/BlakeBr0/MysticalAgriculture/issues/365 this issue has more information.
