### ISSUE TITLE
Fluorite Seed (Mekanism) not working in Garden Cloche (Immersive Engineering)

### ISSUE THREAD

**Issue by Skelliekellie** [BlakeBr0/MysticalAgriculture#513]
Description and Reproduction
Minecraft 1.18.2 with actual modversions and actual Forge. Using Mekanism, Immersive Engineering, Mystical Agriculture. Fluorite is an ore from Mekanism, it is possible to craft the seed but there is no "link" to the garden cloche (immersive engineering) and when I put the seed in the garden cloche nothing happen.

**Comment by AlgorithmLX** [comment]
This is not a bug, manually add craft or use a mod(I won’t say the name, because I don’t remember)

**Comment by Pecant-Pie** [comment]
I made a script file to use with Crafttweaker to add all of the seeds to cloches for a personal pack I made, here's the code: https://pastebin.com/ePfFxPcu

**Comment by AlgorithmLX** [comment]
> I made a script file to use with Crafttweaker to add all of the seeds to cloches for a personal pack I made, here's the code: https://pastebin.com/ePfFxPcu

I did the same with Crafttweaker. For seeds, I even wrote a separate mod. So that Cruxed seeds are not so simple.
