### ISSUE TITLE
Mod Compatibility (MA & Botania)

### ISSUE THREAD

**Issue by Cicopath** [BlakeBr0/MysticalAgriculture#514]
**Describe the bug**
I'm not certain this is a bug, but it is a _partial_ incompatibility between Mystical Agriculture and Botania with the Enchanting Apparatus. (The Enchanting Apparatus enchants applicable items placed on the Enchanting Apparatus block. To enchant the item, you throw the respective Enchantment Books on the ground within the obsidian circle.) You can enchant Mystical Agriculture swords with Enchantment Books in the Anvil, so enchanting such swords with the Enchanting Apparatus should work as well. I'm aware that Mystical Agriculture swords cannot receive certain enchantments, but I'm sure that by using this method of enchanting, any inapplicable enchantments wouldn't be added anyway.

I've only tried this with the Supremium Sword, and I am assuming lower-tier swords are also inapplicable. Mystical Agriculture tools and armor may also be inapplicable.

Also, I'm unsure if this is on purpose, or if this is outside your purview and rather part of the developer(s) of Botania's purview.

**To Reproduce**
1. Have both Mystical Agriculture and Botania installed
2. Receive an un-enchanted Supremium Sword
3. Construct the Mana Enchanter
4. Right-click the functional Enchanting Apparatus with the Supremium Sword

**Expected behavior**
When you right-click the Enchanting Apparatus, the Enchanting Apparatus should accept the Supremium Sword, ready to be enchanted.

**Versions (please complete the following information):**
 - Minecraft: 1.18.2
 - Forge: 40.1.31
 - Cucumber: 5.1.1
 - Mystical Agriculture: 5.1.0

**Comment by BlakeBr0** [comment]
Supremium tools are not enchantable by default. You have to enable that in the config.
