### ISSUE TITLE
Validate automatic in and out put

### ISSUE THREAD

**Issue by efinder2** [BlakeBr0/MysticalAgriculture#517]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.**
 Problem is the in- and  output isn't validated. It is possible to put the Jar in the other slot. I tried to semi automate the soul binder. The empty jars are inserted in the wrong slot first (the slot used for Items). Also empty jars are extracted before they are ready.

**Describe the solution you'd like**
In my opinion would it be best, if the Inputfaces could be configured (see Mekanism factories, ThermalSeries...) with auto push. This may be a lot of effort but vary easy to use. 

As alternative the binder may checks the transferred Items:
 * soul jar can only be inserted in the corresponding slot
 * only items with recipe may be inserted in the other slot
 * if a jar is partially filled only items wich suits may be added
 * soul jar can only be extracted if it is filled

**Comment by BlakeBr0** [comment]
I'm going to close this issue in favor of #503. I'll mention the changes I'm making in there.
