### ISSUE TITLE
Inferium plants aren't dropping seeds

### ISSUE THREAD

**Issue by Endmateria** [BlakeBr0/MysticalAgriculture#52]
K, I spent hours trying to troubleshoot this before bugging you.  Apparently none of the inferium plants are dropping seeds during harvest.  Strangely enough, they don't drop when playing on a server, but they do drop when playing in single player mode.  I tested this thoroughly using fresh worlds with only Mystical Agriculture 1.5.2, Mystical Agradditions 1.0.2, and JEI 4.3.3.269 installed.  Forge 2285  MC version 1.11.2  It doesn't affect the other MA crops, just the 5 tiers of inferium.

**Comment by Endmateria** [comment]
Also, do you know what this issue is about?  Here is a log from one of my other server startups.  For some reason, I'm getting a chisel/mystical agriculture error in my log during server startup.  It doesn't crash the server, but it does seem like a legitimate conflict of sorts.  I'm using the latest versions of both MA and Chisel, so I don't know...  https://gist.github.com/Endmateria/453f5c91894a80a0fbc6e2d1eb95b100#file-latest-log

**Comment by BlakeBr0** [comment]
Version 1.5.2b, which I just submitted, should fix these issues,

**Comment by Endmateria** [comment]
Thanks!
