### ISSUE TITLE
Missing Recipes

### ISSUE THREAD

**Issue by Glitched-Fox-Studios** [BlakeBr0/MysticalAgriculture#520]
**Describe the bug**
A lot of jar recipes are not being loaded

**To Reproduce**
Install Direwolf20 1.18 v 1.5.1 modpack
Add Agriculture/Agriditions
See multiple missing recipes

**Expected behavior**
All recipes should work without issue

**Screenshots / Scripts / Logs**
https://pastebin.com/b8Cer38n

**Versions (please complete the following information):**
 - Minecraft: 1.18.2
 - Forge: 40.1.47
 - Cucumber: 5.1.1
 - Mystical Agriculture: 5.1.0

Tested this with nothing but JEI, Cucumber, Mystical Agriculture, & Mystical Agriditions and ran into the same problem. None of the recipes listed in the pastebin error log will work.

**Comment by BlakeBr0** [comment]
Is this still an issue you're experiencing?

**Comment by alexbown** [comment]
@BlakeBr0 Can't speak for OP, but I'm getting this issue too, it looks like recipes are missing from all metals from Thermal and Mekanism (possibly others, any that include steel in my pack) in game - recipes for mods such as Tinkers are working.
I'm playing on this modpack v3.1.0 on MC 1.18.2: https://www.curseforge.com/minecraft/modpacks/random-flim-flam

Relevant mods:
MysticalAgradditions-1.18.2-5.1.2
MysticalAgriculture-1.18.2-5.1.2
Mekanism-1.18.2-10.2.5.465
ImmersiveEngineering-1.18.2-8.2.2-154
thermal_integration-1.18.2-9.0.0.9

**Comment by BlakeBr0** [comment]
@alexbown can you try removing the `cucumber-tags.json` file in the config folder and restarting the pack?

**Comment by alexbown** [comment]
Thanks, that has resolved the issue for me!
I wasn't aware of that file before, comparing a local world and a test server, one had `null` which didn't work, and one had `mekanism:steel_ingot`, which also seemed to not work, but after regenerating it has `thermal:steel_ingot` tag which is working correctly (other materials are also working correctly now too).

**Comment by BlakeBr0** [comment]
This type of problem should automatically resolve itself in 1.19.2 and 1.19.3 with Cucumber versions 6.0.4 and 6.1.1.
