### ISSUE TITLE
galacticraft has a ishue with MA

### ISSUE THREAD

**Issue by OverlordAvali** [BlakeBr0/MysticalAgriculture#522]
**Describe the bug**
When an attempt is made to connect with a server with glacticraft it fails to connect latest.log modlist and error meg is included in the post. 

**To Reproduce**
Steps to reproduce the behavior: Simply try to connect with Galaticraft installed.

**Expected behavior**

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).
![javaw_wD5mTnVQ6A](https://user-
![polymc_Nuw2BzEa1I](https://user-images.githubusercontent.com/83912658/180631121-e5ed4819-4fdd-445a-81be-d07a3a147617.png)
images.githubusercontent.com/83912658/180631117-09805ab3-2401-4322-ab48-f3a022b249c1.png)

**Versions (please complete the following information):**
 - Minecraft:1.12.2
 - Forge:14.23.5.2860
 - Cucumber:1.1.3
 - Mystical Agriculture:1.7.3
[latest.log](https://github.com/BlakeBr0/MysticalAgriculture/files/9175066/latest.log)

**Comment by BlakeBr0** [comment]
From that error it looks like a nickel ingot item from the GalaxySpace mod is being added to the ore dictionary but isn't actually being registered in the game. It happens to be the first nickel ingot in the ore dictionary and thus is causing this crash.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
