### ISSUE TITLE
Inferium not properly growing with Agricraft

### ISSUE THREAD

**Issue by IVebs** [BlakeBr0/MysticalAgriculture#523]
**Describe the bug**
I fully grow inferium seeds in crop sticks then place double crop sticks adjacent. The seed catches but is does not produce an inferium seed, it honestly looks just like grass. When broken it only drops the crop sticks left behind. I have watered this "seed" for 20 minutes and nothing. I have tried to edit JSON file from previous bugs on 1.12 but all it did was put a question mark in my inventory and make the seeds useless.

**Expected behavior**
Inferium seed should mutate to the crop stick adjacent. Fully grow. Then be able to break crow stick and grab new seed.

**Screenshots / Scripts / Logs**
![image](https://user-images.githubusercontent.com/110319760/182009603-a1c7ed0f-d29d-4c69-852f-08b592d6c809.png)

**Versions (please complete the following information):**
 - Minecraft: 1.18.2
 - Forge: 40.1.68
 - Cucumber: 1.18.2-5.1.2
 - Mystical Agriculture: 1.18.2-5.1.1

**Comment by BlakeBr0** [comment]
The agricraft integration is handled on the agricraft side, though I think what you're experiencing is the weeds mechanic. I don't really remember what to do about that since I always played with that disabled back in the day.
