### ISSUE TITLE
Saltpeter essence

### ISSUE THREAD

**Issue by Mitchell5200** [BlakeBr0/MysticalAgriculture#524]
**Describe the bug**
Saltpeter essence can create IE nitrate dust and thermal niter dust in the same shaped recipe (pictured below)

**To Reproduce**
Press "U" on saltpeter essence 

**Expected behavior**
Not what's pictured below, expected what's coded in
https://github.com/BlakeBr0/MysticalAgriculture/blob/1.18/src/main/resources/data/mysticalagriculture/recipes/essence/common/saltpeter.json
https://github.com/BlakeBr0/MysticalAgriculture/blob/1.18/src/main/resources/data/mysticalagriculture/recipes/essence/common/niter.json

**Screenshots / Scripts / Logs**
![2022-08-05_00 35 38](https://user-images.githubusercontent.com/45913837/183036495-da0fb750-1306-41ba-9581-0515d953fdc2.png)

**Versions (please complete the following information):**
 - Minecraft: 1.18.2
 - Forge: 40.1.68
 - Cucumber: 1.18.2-5.1.2
 - Mystical Agriculture: 1.18.2-5.1.1
- Modpack ATM 7 v0.4.24 (present in earlier)

Potential solution (from my limited experience), change one of the recipes to a vertical shaped craft

**Comment by BlakeBr0** [comment]
This issue should be fixed in Cucumber 6.0.1. I'm not sure if I'll be releasing another version for 1.18 so I'm going to consider this resolved.
