### ISSUE TITLE
[1.18.2] Allow Bonemeal Fertilizer via config

### ISSUE THREAD

**Issue by MerosXX** [BlakeBr0/MysticalAgriculture#525]
I am playing the 1.18.2 version, and I am not a fan of the way the resource generation ramps up. It just takes too long to generate even minor amounts of resources in the beginning (hours of time for a single crop to grow without external support).

I would love to be able to fertilize the MA crops with bonemeal. This would enable a manual growth boost in the beginning if necessary, or more automation options in combination with other mods (i.e. cyclic sprinkler). I would suggest to add a configurable option in the config that allows or disallows the use of bonemeal on crops. By default, this should be turned off, to not break most mostpacks' balancing.

Alternative:
A config option to increase base grow speed of crops (might need to come along with a nerf / config to growth accelerator tick rates), or removing the diamond requirement from the early stages of accelerators.

**Comment by IsaiahMM** [comment]
Idk if you're aware you can create a type of bonemeal you can grow the crops with. 

There are two ways to do this:

1 diamond, 4 bonemeal, & 4 inferium essence (this recipe makes 5 of the bonemeal)

Or

1 diamond, 4 bonemeal, 4 fertilizer essence. (This recipe makes 10 of the bonemeal)

While I agree that crops do take some time to grow when you're just starting out, I believe this should happen as when you start to increase growth and get more seeds it ramps up rather quickly. 

Two more ways you can increase growing speed is by utilizing the growth accelerates that will increase growth rates by a pseudorandom tick rate. This option is still relatively cheap and helps a lot early game. 

A second, more obvious option is to plant more of the essence seed you are attempting to grow. Using either the altar to create new seeds or using the mods included bonemeal to get more seeds faster.

**Comment by BlakeBr0** [comment]
The intended ways to increase crop growth are watering cans, growth accelerators and Fertilized Essence/Mystical Fertilizer. You can craft Mystical Fertilizer using Bonemeal. Being able to use regular Bonemeal to grow the crops would be way too powerful especially with Skeleton seeds in the mod.
