### ISSUE TITLE
[1.19.2] Registry Object not present: mysticalagriculture:infusion_crystal

### ISSUE THREAD

**Issue by grothedev** [BlakeBr0/MysticalAgriculture#526]
**Describe the bug**
game crashes on start because forge modloader requires registered objects to be non-null, however registration of InfusionCrystalItem is returning null. perhaps the constructor of BaseReusableItem() is failing? 

**To Reproduce**
Steps to reproduce the behavior: launch minecraft from the launcher

**Expected behavior**
the game launches

**Screenshots / Scripts / Logs**
[Crash Log](https://hastebin.com/raw/ecejorowen)

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.1.1
 - Cucumber: 1.19.1-6.0.0
 - Mystical Agriculture: 1.19.1-6.0.0

**Comment by BlakeBr0** [comment]
Do you have the full log? Most of the time errors like this come up after something else had gone wrong first

**Comment by grothedev** [comment]
huh, well it appears to be working now, and i don't remember what i changed. weird. i'll respond with anymore info i find out.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
