### ISSUE TITLE
Can’t craft infusion alter or pedestals 

### ISSUE THREAD

**Issue by arron1052** [BlakeBr0/MysticalAgriculture#527]
Using the stone, gold, and red carpet as other players have repeatedly used to make these and it doesn’t come up in the crafting table. All of the other essence and infusion stuff work up till now.

**Comment by BlakeBr0** [comment]
The recipes have changed in recent versions. I would recommend using Just Enough Items to view the recipes in-game.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
