### ISSUE TITLE
There seems to be no Charm for the Supremium Bow.  

### ISSUE THREAD

**Issue by MentalMouse** [BlakeBr0/MysticalAgriculture#53]
The problem of course, is that the Supremium Bow is already a serious killer, especially if properly enchanted  Extra damage would be besides the point....  Some ideas:  Speedy Flight (extra range, straighter trajectory), Homing (targets enemy that would be a "near miss"), Piercing (can pass through first mob to strike another behind it).

**Comment by BlakeBr0** [comment]
I've got some charms planned already, thanks for the extra ideas.
