### ISSUE TITLE
Essense recipes not showing for any essence crafting

### ISSUE THREAD

**Issue by Zelioth** [BlakeBr0/MysticalAgriculture#533]
I created and published a modpack and server called "Friends United". the modpack has been going pretty well but recently i discovered that none of the essence from the Mystical Ag plants have a complete recipe. I thought it was a mod "Almost unified" maybe messing with the recipes but after testing different mods being active and changing some configs i can not get anything to show up for the mystical ag. essence recipes. This issue affects most essence recipes but common ones would be the uranium, sapphire, ruby, essence recipes. the REI shows the crafting grid but no output. and when attempting to craft there is also no output.

Minecraft Version 1.19.2
Forge Version 43.1.2
Latest version of Mystical ag and cucumber core.

**Comment by BlakeBr0** [comment]
Not even the ones for vanilla items? If it's just certain ones like copper, tin etc, try updating or deleting the cucmber-tags.json file.

**Comment by Zelioth** [comment]
Howdy, so I fixed the issue by changing values in Cucumber config. But it wasn't easy. it refused to use mekanisms uranium even when setting it. I had to disable everymod to generate a cucumber config that would just auto place mekanisms as the main ingot. Almost Unified is another mod that takes all ingots and picks the best mod and places it and it was breaking it to but after removing it, it didn't fix it so had to do some troubleshooting but it was figured out

**Comment by BlakeBr0** [comment]
I'm going to close this as I think it seems like you've resolved this issue. For future reference, there should be a config option in the `cucumber-common.toml` called `modTagPriorities` which should help with picking which mods the `cucumber-tags.json` file should pull from.
