### ISSUE TITLE
Awakening Altar ghost renderer doesn't match JEI layout

### ISSUE THREAD

**Issue by TheColdGod1** [BlakeBr0/MysticalAgriculture#534]
Literally cant awaken supremium the recipe is flipped making it impossible (See screenshot for more)

Download jei and try ;-;

I wanted to awaken some supremium-

![2022-08-30_01 26 02](https://user-images.githubusercontent.com/112132925/187356755-83cd3964-44a0-4290-b1e7-266bfc06cbbd.png)
![2022-08-30_01 29 00](https://user-images.githubusercontent.com/112132925/187356910-5e5a8449-b603-4bae-b69d-82a6399086e6.png)

**Versions (please complete the following information):**
 -1.19.2
 - 43.1.3
 - 6.0.0
 - 6.0.0

**Comment by TheColdGod1** [comment]
I broke the two not in so you could see the placement is how it wants.

**Comment by BlakeBr0** [comment]
It should still work if you place the pedestals and vessels in either order. I'll change the ghost renderer to match the JEI layout in the next release.
