### ISSUE TITLE
[1.19.2] awakening not working

### ISSUE THREAD

**Issue by Jorue23** [BlakeBr0/MysticalAgriculture#536]
**Describe the bug**
When putting in the essences, dust and supremium block into the awakening ritual it just doesn't work.
I've looked around a bit and saw this issue https://github.com/BlakeBr0/MysticalAgriculture/issues/534 but either order doesn't work.

**To Reproduce**
1. Place down the altar, vessels and pedestals
2. put in essences, dust and supremium block
3. activate it by using lever/button or whatever
4. Doesn't work

**Expected behavior**
The ritual starts and forms awakened supremium essence.

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.1.3
 - Cucumber: Cucumber-1.19.1-6.0.0
 - Mystical Agriculture: MysticalAgriculture-1.19.1-6.0.0
 - Mod Pack: ATM 8 v 0.0.1

**Comment by BlakeBr0** [comment]
I wasn't able to test in that modpack specifically but I was able to craft an awakened supremium block just fine. I'm guessing maybe your vessels may not have all the essence required. Are you using the awakening altar/pedestals?

**Comment by Jorue23** [comment]
It was caused by a wrong recipe shown in jei
