### ISSUE TITLE
Cant craft harvester

### ISSUE THREAD

**Issue by TheRTGGaming** [BlakeBr0/MysticalAgriculture#537]
**Describe the bug**
The harvaster block is missing recipe

**To Reproduce**
Steps to reproduce the behavior: try and craft harvaster in survival

**Expected behavior**

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.1.16
 - Cucumber: 6.0.1
 - Mystical Agriculture: 6.0.1
![2022-09-09_13 26 43](https://user-images.githubusercontent.com/48783483/189439007-6596965a-80f3-4aa2-b8ee-1d2c2a6e1b14.png)
![2022-09-09_13 36 08](https://user-images.githubusercontent.com/48783483/189439010-0ad6b25f-75cc-4920-a70a-506951587e99.png)

**Comment by BlakeBr0** [comment]
Are those scythes from mystical agriculture or pickle tweaks?

**Comment by BlakeBr0** [comment]
Is this still an issue in the latest version?

**Comment by TheRTGGaming** [comment]
I will inform you after i look more into the bug.

**Comment by TheRTGGaming** [comment]
I looked at the recipes and yes. the Scythes that i made where from pickle tweaks. they have the same crafting recipes. maybe when pickle tweaks is installed you can also let the Scythes from pickle tweaks be used?

**Comment by BlakeBr0** [comment]
You should be able to use either in version 6.0.2

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
