### ISSUE TITLE
Break a tinkering table with armor on it will crash the game

### ISSUE THREAD

**Issue by amoeba1125** [BlakeBr0/MysticalAgriculture#538]
**Describe the bug**
When break a tinkering table which holds any armor will instantly crash the game.

**To Reproduce**
Place a tinkering table.
Open the tinkering table's GUI
Put an armor in the slot.
Close the GUI.
Break the tinkering table, and the game will crash.

**Expected behavior**
Drop the tinkering table and the armor on it.

**Screenshots / Scripts / Logs**
https://drive.google.com/file/d/1daNkdgDY9TuWTXflGW8wBJdSNuY1XpeO/view?usp=sharing

**Versions (please complete the following information):**
- Minecraft: 1.18.2
- Forge: 40.1.54
- Cucumber: 5.1.1
- Mystical Agriculture: 5.1.0

**Comment by BlakeBr0** [comment]
This was fixed in the latest 1.19 version. I'll make sure to get that fix in the final 1.18 bugfix release.

**Comment by BlakeBr0** [comment]
Fixed in 5.1.2
