### ISSUE TITLE
1.11.2-1.5.2c Supreme Armor bug/feature

### ISSUE THREAD

**Issue by TwitchtvCarbs** [BlakeBr0/MysticalAgriculture#54]
I'm not sure if it intended but the supreme armor absorbs all damage from any mob attack or really any incoming damage (Even lava) The player takes no damage though the armor takes a tiny amount of damage.

Is this intended or is it still supposed to deal a little damage to the player still like normal armor?

**Comment by BlakeBr0** [comment]
I mean, generally speaking, high tier armor should negate almost all damage. I just tested and mobs can hit me and I do take damage eventually when sitting in lava.
