### ISSUE TITLE
Harvester disabling by redstone

### ISSUE THREAD

**Issue by a-sakharov** [BlakeBr0/MysticalAgriculture#542]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.**
Harvester is an awesome machine, that generating tons of crops, but in some moment it becomes too many of them. And I can't see any way to stop it other than break it.

**Describe the solution you'd like**
I want a way to pause harvester with redstone signal. It will not only helps me to avoid chests overflow, but also allow to use it in automation circuits.

**Describe alternatives you've considered**
Breaking harvester or moving harvester with pistons can stop it from producing crops.

**Comment by BlakeBr0** [comment]
I'm not sure if providing a redstone signal is the most intuitive way to have the machine stop, considering powering something with redstone usually turns it on.

I think what I'll do is add an on/off switch to the GUI or something else if I can think of it.

**Comment by a-sakharov** [comment]
Immersive engineering machines, some IC2 machines and even vanilla hopper are disabled with redstone signal. Anyway, I'll be glad with any solution.
