### ISSUE TITLE
Infusion Crystal and Master Infusion Crystal stack support v1.12.2

### ISSUE THREAD

**Issue by Chromayx** [BlakeBr0/MysticalAgriculture#543]
Infusion Crystal and Master Infusion Crystal are missing a stack support,
if you select something to craft with I Crystal or MI Crystal with Shift in Crafting recipes to craft a whole stacke but i does'nt
adding 64 items to crafting table, it stays with 1 items each slot

**Comment by BlakeBr0** [comment]
Duplicate of https://github.com/BlakeBr0/MysticalAgriculture/issues/372
