### ISSUE TITLE
Awakening Altar not processing recipes 

### ISSUE THREAD

**Issue by IsaiahMM** [BlakeBr0/MysticalAgriculture#544]
**Describe the bug**
Set up the Awakening Altar in order to make the Awakened Supremium Block. Once it had been set up with the proper recipe, I attempted the start it with a redstone signal; it won't process the recipe, I'm not sure if the altar isn't seeing the redstone signal, i tried to deliver a redstone signal to it from multiple faces utilizing multiple redstone methods.

it could also not be reading the recipe correctly from the config files, or there is something in conflict with the coding.
ATM8 is a very new modpack so I could see that being the case. 

**To Reproduce**
All you have to do is attempt to execute the recipe for the Awakened Supremium Block. it won't let me past that point.

**Expected behavior**
Recipe was expected to execute and create the proper block upon completion.

**Screenshots / Scripts / Logs**
https://imgur.com/a/x8TgyiX

Link to imgur screenshots of Awakening Altar set up; in the screenshots each of the essence vessels contain 10 of the essence as the recipe calls for. I also attempted the recipe with them completely full of the essence as well.

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 1.19.2-43.1.27
 - Cucumber: 1.19.2-6.0.1
 - Mystical Agriculture: 1.19.2-6.0.2
 - Mystical Agradditions: 1.19.1-6.0.0

**Comment by BlakeBr0** [comment]
Should be cognizant dust on all 4 pedestals

**Comment by IsaiahMM** [comment]
> Should be cognizant dust on all 4 pedestals

Understood, I'll give that a try tomorrow. 

If that's the case, the the recipe is incorrect in the JEI. The JEI recipe showcases it the way I'm using it in the screenshots. 

Overall a good experience in all other faucets of this mod, thank you for the speedy reply.

**Comment by KevinGMK** [comment]
> Debe haber polvo consciente en los 4 pedestales.

How do you mean dust? it doesn't bother me either

**Comment by IsaiahMM** [comment]
> > Debe haber polvo consciente en los 4 pedestales.
> 
> 
> 
> How do you mean dust? it doesn't bother me either

The JEI in ATM 8 has the recipe incorrect for the awakened supremium block as well as all of the awakened tools. They have an air shard and earth shard shown on two of the pedestals, when in fact it should be cognizant dust on all four of the normal pedestals which you get from killing withers and the dragon with an essence weapon enchanted with mystical enlightenment 1-5.
