### ISSUE TITLE
Awakening table not working on All the Mods 8.

### ISSUE THREAD

**Issue by epic9863** [BlakeBr0/MysticalAgriculture#546]
So for me I can't get the awakening table to work on this private server and I have followed all of the steps and it seems to not work properly. I have tried giving it a proper redstone signal but it doesn't seem to be working correctly.  I am trying to make the awakened supremium block and no matter what I do it doesn't seem to work but it also seems like it kinda does work as well as the preview comes up and it shows that I am going to make awakened supremium. I feel like it is a bug.

**Comment by IsaiahMM** [comment]
This "problem" was recently solved, look at the closed tickets. It's probably still the top one. The recipe in the JEI is incorrect. It's four cognizant dust and not the air/earth shard it has on the JEI recipe.

**Comment by epic9863** [comment]
Is this the same for the other awakened supremium items?

**Comment by IsaiahMM** [comment]
Indeed, they all use four cognizant dust

**Comment by DeluxeO** [comment]
What about the awakened supremium furnace?, i tried codnizant dust on all 4, it recognizes the recipe on the alter when using the one stated in JEI but does not craft

**Comment by IsaiahMM** [comment]
Hi> What about the awakened supremium furnace?, i tried codnizant dust on all 4, it recognizes the recipe on the alter when using the one stated in JEI but does not craft 

I believe the awakened tier tools and equipment have 2 awakened ingots as well as 2 awakened gemstones (I believe that's what they're called) 

They should be place parallel from each other so the awakened ingots will be on one half of the alters and the gemstones on the other half they won't be alternated.

**Comment by BlakeBr0** [comment]
I believe this was fixed in the latest release.
