### ISSUE TITLE
Mystical Ag Causing issues with other mods, and Requesting Cucumber Lib version

### ISSUE THREAD

**Issue by Zelioth** [BlakeBr0/MysticalAgriculture#547]
I currently have a public mod pack "Friends United" This pack is featuring some of the most popular mods including Mystical ag. I am testing the updates that were posted and when installed they do not allow the pack to even launch. I pulled the mods into a test pack where it was only the mystical ag mods and it refused to launch do it cucumber lib version being incorrect. 

The third log i am not sure if it says why but I know when downgrading the version of mystical ag the pack will launch fine. when updating it it refuses to open 

**To Reproduce**
Steps to reproduce the behavior: Install all Mystial Ag latest versions. No cucumber core version 6.0.2

**Expected behavior**
To launch correctly

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.1.27 - 43.1.33
 - Cucumber: 6.0.1
 - Mystical Agriculture: 6.0.3

The logs I I will post will be the individual pack forge versions 43.1.27 and 43.1.33 and then the friends united pack with the mods installed. 
[crash-2022-10-04_15.31.12-fml.txt](https://github.com/BlakeBr0/MysticalAgriculture/files/9710493/crash-2022-10-04_15.31.12-fml.txt)
[crash-2022-10-04_15.36.53-fml.txt](https://github.com/BlakeBr0/MysticalAgriculture/files/9710494/crash-2022-10-04_15.36.53-fml.txt)
[latest.log](https://github.com/BlakeBr0/MysticalAgriculture/files/9710504/latest.log)

**Comment by BlakeBr0** [comment]
Submitted new cucumber version to curse.
