### ISSUE TITLE
Improve contributing dev environment setup

### ISSUE THREAD

**Issue by nskobelevs** [BlakeBr0/MysticalAgriculture#549]
I was trying to setup a dev environment for Mystical Agriculture (not as a dependency but this repo itself) and ended up hitting a few issues on my way that could be solved.

1. The gradle wrapper is broken. `distributionUrl` in `gradle/wrapper/gradle-wrapper.properties` is `https\://services.gradle.org/distributions-snapshots/gradle-7.2-20210702220150+0000-bin.zip` which doesn't exist.

I ended up changing to grade 7.3
`https\://services.gradle.org/distributions/gradle-7.3-bin.zip`

2.`Project with path <path> could not be found in root project <project>`

Seems it wants a _local_ Cucumber project instead of downloading it as a dependency. (Understandably makes development easier on your end)
So I had to setup a root project that includes both MysticalAgriculture and Cucumber.

While I did solve these, it took a few hours figuring out what the issues were and searching due to not being overly used to gradle.

It would be helpful to those who want to contribute to fix the gradle link and perhaps setup a new GitHub repo with submodules to make the dev environment in one place?

**Comment by BlakeBr0** [comment]
I fixed those gradle distribution links and made it so the dependencies fall back to builds on my maven if there isn't a local project setup. I'll work on making a contribution guide at some point to flesh this all out better at some point.

**Comment by nskobelevs** [comment]
Cheers, that al least should make it easier to setup the repo
