### ISSUE TITLE
Compatibility with Pixelmon

### ISSUE THREAD

**Issue by Nillecram** [BlakeBr0/MysticalAgriculture#55]
v1.4.2 broked compatibility with Pixelmon

public static boolean ALUMINUM = OreDictionary.getOres("ingotAluminum").size() > 0 || OreDictionary.getOres("ingotAluminium").size() > 0 || THERMAL || IE || TECHREBORN || SUBSTRATUM || BASEMETALS;
	
Does not return true.

http://pixelmonmod.com/wiki/index.php?title=Aluminum_Ingot

Perhaps because the ingotAluminium that should be ingotAluminum.

Thanks in advance for the correction.
Keep the good work.
PS: I love your mod :1st_place_medal:

**Comment by BlakeBr0** [comment]
That boolean checks for both spellings. The oredict checks would only really do anything if the mod were to load before Mystical Agriculture, so I'll have to add Pixelmon to the checks manually.

**Comment by BlakeBr0** [comment]
https://github.com/BlakeBr0/MysticalAgriculture/commit/5bc41737dedf23e881d01ab936a0cf744713a852
