### ISSUE TITLE
Add support for the Assembly Line Machines Mod

### ISSUE THREAD

**Issue by XiaoKe89** [BlakeBr0/MysticalAgriculture#554]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.** No

**Describe the solution you'd like**
Support for the Assembly Line Machines mod, adding it's ores as growable seeds

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by BlakeBr0** [comment]
I don't think I'm going to be adding first-party support for this. It's always possible to create an addon or use Mystical Customization to add crops for any materials. Thanks for the suggestion!
