### ISSUE TITLE
[1.19.2] Option to turn off Armor Set Bonus

### ISSUE THREAD

**Issue by HalcyonSeas73** [BlakeBr0/MysticalAgriculture#556]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.**
The Growth 3 set bonus on the Awakened Supremium Armor is nice, but it would be nice if there was a config option to turn off set bonuses (I assume there might be more added for other armor sets at a later time?).

**Describe the solution you'd like**
An option in config to turn off set bonuses.

**Describe alternatives you've considered**
Not wearing the armor??

**Comment by BlakeBr0** [comment]
Awakened Supremium is the only armor set that will have an implicit set bonus. I can add a config option to disable it.
