### ISSUE TITLE
excessive growth animations 

### ISSUE THREAD

**Issue by zookeper** [BlakeBr0/MysticalAgriculture#557]
Too many animations, there's no need to have that much, you get to a certain point when the growth rate is so high that even if you dig a block, its glitching the animations through the ground 1000 blocks out you can see your farm???

Build a large farm, 3x3 chunks. use lilypads and water can, use on farm.

also Go out 100 blocks and dig looking toward your farm you will see black glitched affects from the farm's animations.

To have Suttle animations when using growth acceleration mechanics.

No logs, this is an ongoing problem

**Versions (please complete the following information):**
 - Minecraft: 1.19
 - Forge: i dont know
 - Cucumber: i dont know 
 - Mystical Agriculture: MysticalAgriculture-1.19.2-6.0.5.jar
 - ATM 8

**Comment by zookeper** [comment]
I may have misused the word animations, to better correct the issue I believe it's the particle effects.

**Comment by BlakeBr0** [comment]
I'll re-evaluate the particle effects for this.
