### ISSUE TITLE
Apatite Seeds

### ISSUE THREAD

**Issue by harryijim** [BlakeBr0/MysticalAgriculture#559]
No crafting use for apatite essence in the latest version of Mystical Agriculture (1.19.2-6.0.5) in AllTheMods8 Pack MC Vers 1.19.2. Possibly Craft into Thermal Expansion Apatite as no Forestry in pack.

**Comment by BlakeBr0** [comment]
Sorry for the late reply. I just checked the latest version of the modpack (1.0.10) and it seems that the recipe is now working.
