### ISSUE TITLE
Using other Essences types in the Awakening Alter

### ISSUE THREAD

**Issue by YOYOK9** [BlakeBr0/MysticalAgriculture#560]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.**
Currently it seems only the 4 elemental essences can be used in the awakening alter, Would be neat for pack devs to be able to infuse other items or blocks with some of the other essence types available. Could come up with some pretty neat hybrid style items or blocks. 

**Describe the solution you'd like**
Allowing other essences to be used in a datapack. 

**Describe alternatives you've considered**
Possibly using the infusing alter, or adjusting the amount of elemental essences to match higher craft requirements.
(Use another mod) :(

**Additional context**
Something I was thinking of doing for my pack was to make the AE2 meteor blocks craftable by infusing an already tough block with obsidian essence. Creating that "even tougher" block. 

I have tested with other essence, unless I am missing something(didn't see anything on the wiki)

**Comment by benbenlaw** [comment]
would love to see this as well

**Comment by BlakeBr0** [comment]
Unfortunately this would require a rework to how the Awakening Altar works. I'm going to keep this open however because I do think it would be a good addition, just not sure when I can get to it.

**Comment by benbenlaw** [comment]
no poblem huge fan of your work :)

**Comment by BlakeBr0** [comment]
As of version 7.0.0 you can use any items as essences. You'll need to use a resource pack to color the contained essence texture for any items that aren't the 4 elemental essences.

Docs: https://blakesmods.com/docs/mysticalagriculture/awakening-recipes
