### ISSUE TITLE
No End Prosperity Ore

### ISSUE THREAD

**Issue by wizcj3** [BlakeBr0/MysticalAgriculture#562]
Playing on a 1.19.2 server. There is no prosperity ore generating in the end. Tore apart a whole island and found nothing.
I checked the settings and see that its set to spawn in the world but nothing exclusively for the end if that's required.
Playing with version 6.0.3

**Comment by BlakeBr0** [comment]
Do you have Mystical Agradditions installed?  Nether/End Prosperity Ore is added by it.

**Comment by wizcj3** [comment]
I did not, that fixed it. Thank you.
