### ISSUE TITLE
Pickaxe with AOE Augment creates Invisible Blocks [1.19.2]

### ISSUE THREAD

**Issue by Crystallyne** [BlakeBr0/MysticalAgriculture#564]
I have a Supremium Pickaxe with the Mining AOE I augment on it. If there is a block in its radius that it normally ignores (IE wood or dirt) then it sometimes causes that block to become invisible. The only fix I have found so far is to exit out to the main menu and reload. (I have had issues getting F3+T to work, it usually crashes my game, but that's another issue.)

So far this hasn't been a major issue. I can usually see the blocks in time to avoid them with my pickaxe.

However, I have just ventured into the Nether, and I'm digging a tunnel down to "sea level." I discovered while doing so that it is also doing this with lava sources! First time this happened, I couldn't for the life of me figure out why I was getting lava flow, with no visible lava source! It wasn't until I reloaded my game that I realized it had been turned invisible.

This doesn't happen every time it encounters a block it normally ignores. It happens frequently enough, however, to be a real pain at times.

I'm playing on version 1.19.2 with a customized modpack.

PS: I've seen others using a pre written form to put in their bug reports, but I couldn't find a copy of the form. If this is required, and someone can point out where to find it, I'll edit this post to fit the form. Otherwise, if any other information is needed, I'll do my best to provide it.

Edit Jan 21: I wanted to come back and add that the same thing happens if I put the Mining AOE I augment on a shovel. It has a high chance of turning stone blocks invisible. On the other hand, I have discovered if I can target a block adjacent to it with the appropriate tool, with the AOE I augment on it, then it will break the target block AND any adjacent invisible blocks. But that's not always an option, and I don't always catch when a block's been turned invisible, until I reload my game.

**Comment by BlakeBr0** [comment]
I can make it create a single ghost block when the incorrect block type is the top leftmost block in the AOE. Is this the same behavior you're experiencing?

![image](https://user-images.githubusercontent.com/12994882/216435130-046adaab-830f-4084-9446-aad5a2db779d.png)

**Comment by BlakeBr0** [comment]
This should be fixed with the latest release of Cucumber. If you're still having this issue after updating you can let me know.

**Comment by Crystallyne** [comment]
Now that you mention it, it usually was the upper left corner every time! It's been long enough since I used it that I don't recall if any other blocks were affected. But I'm glad to hear it's been fixed, thank you!!
