### ISSUE TITLE
Crafting Seeds missing - MysticalAgriculture-1.18.2-5.1.1 and 5.1.2

### ISSUE THREAD

**Issue by Junkdog8** [BlakeBr0/MysticalAgriculture#568]
I have searched and tried everything I could, but it is not possible to craft seeds of a higher level than level 1; and the recipe is not in jei nor the guide book... there is nothing on the website talking about this being a change that I could find...

**Comment by BlakeBr0** [comment]
Resource seeds are now crafting using Prosperity Seed Base, and mob seeds are now crafted using Soulium Seed Base

**Comment by Junkdog8** [comment]
> Resource seeds are now crafting using Prosperity Seed Base, and mob seeds are now crafted using Soulium Seed Base

![image](https://user-images.githubusercontent.com/122975939/215494071-3e45ec99-57f7-40ea-8219-b5eaf13ebb4b.png)

"I have searched and tried everything I could, but it is not possible to craft seeds of a higher level than level 1"

**Comment by BlakeBr0** [comment]
I'm not really sure where the confusion would be since you have JEI installed.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
