### ISSUE TITLE
Cascading worldgen lag

### ISSUE THREAD

**Issue by Endmateria** [BlakeBr0/MysticalAgriculture#57]
Hey man, I noticed that I was getting "cascading worldgen lag" warnings from your mod in my server log during pre-generation of the nether...  (scroll to the end of the log where I start the pre-gen) https://gist.githubusercontent.com/Endmateria/de932c2dc7976622e67a57c2a33f2f78/raw/415aeeeea85a4c307ec759912f591e1b4189ccf5/fml-server-latest.log

MC 1.11.2
Forge 2294
Mystical Agriculture 1.5.2c (all worldgen configs set to default except "end ore generation" which is set to false)

Strangely, I was not getting those warnings during overworld pre-gen.  In case you're not aware, I guess Forge just introduced this detection/log system for runaway worldgen back in 1.11.2 2258 and now a lot of mods are getting hit with this warning.  Quark currently has an issue open regarding it, and a bunch of other mod authors jumped in there to discuss the best methods of fixing it in detail... definitely worth a read. https://github.com/Vazkii/Quark/issues/412

P.S. I've only tested this with the pre-generator.  Going to bed now, but tomorrow I'll test it in-game just to make sure it's not the pre-generator that's causing the issue and I'll report back.

**Comment by BlakeBr0** [comment]
The issue is soulstone generation. I bet if you turn that off there should be no issues. I'll look into it.

**Comment by Endmateria** [comment]
Well I left the generator running all night and got a crash.... don't know how helpful this crash report is (considering the amount of mods that could be influencing it), but your mod did get two hits on the report.  https://gist.github.com/Endmateria/873b27de1508e65f04df8b2e42cd586d#file-crash-2017-05-08_09-50-33-server-txt

**Comment by BlakeBr0** [comment]
I lowered the size of soulstone veins and stopped getting this issue. If you want to try settings the vein size to 40 in the config and seeing if the problem persists you may.

**Comment by Endmateria** [comment]
K, I'll give it a shot when I'm done pre-generating the overworld.

**Comment by Endmateria** [comment]
P.S. you can close this if you're pretty sure you got it, as I may not get to the nether pregen tonight.  If I run into it again, I'll report it here.
