### ISSUE TITLE
Cannot directly enchant a Supremium Sword to get Mystical Enlightenment.

### ISSUE THREAD

**Issue by SephirothWS** [BlakeBr0/MysticalAgriculture#572]
**Describe the bug**
Cannot directly enchant a Supremium Sword in an enchantment table for Mystical Enlightenment. Looking up **Cognizant Dust** says I need to kill **The Wither or Ender Dragon** with an _ESSENCE WEAPON **enchanted** with Mystical Enlightenment_ to obtain.

**To Reproduce**
1) Craft Supremium Sword
2) Set up Enchantment Table
3) Insert Supremium Sword into Enchantment Table
4) ???
5) Profit (Or rather, lack of profit)

**Expected behavior**
Sticking the Supremium Sword into the Enchantment Table should allow me to select a randomized enchantment like any other tool/weapon.

**Screenshots / Scripts / Logs**
![image](https://user-images.githubusercontent.com/9165737/215135580-c545bd2e-bee4-491b-a709-8654889f6980.png)
![image](https://user-images.githubusercontent.com/9165737/215136049-01636e5b-ab41-4270-bb9c-76b76fb471bf.png)

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.2.3
 - Cucumber: 6.0.3
 - Mystical Agriculture: 6.0.5

**Comment by BlakeBr0** [comment]
By default you can't enchant Supremium tools in an enchanting table. You'd have to use a book or enable the config option.

**Comment by SephirothWS** [comment]
So you're telling me it is intended to need to use books to get around being unenchantable?  This doesn't make a lick of sense. Why create an enchantment that cannot be applied because the targeted item for the enchantment is set to being unenchantable?

**Comment by SephirothWS** [comment]
I forgot to add, most people generally play modpacks, where the configuration is set by the modpack author. And even then, some of those people like myself, are playing online on a server, where one doesn't have control over the config option. I guess you could say I am requesting the config option to go the way of the Dodo and no longer exist, and the item to be always enchatable, thus fixing the inability to acquire the enchantment without needing to roll against the entire enchantment pool via books.

**Comment by BlakeBr0** [comment]
I guess at this point it would make sense to make Supremium tools enchantable by default. It's been a point of confusion for a while and I guess keeping the vanilla behavior of unbreakable tools not being enchantable doesn't really matter as much as I felt it did originally.

**Comment by BlakeBr0** [comment]
Version 6.0.6 changes the config option to be enabled by default.
