### ISSUE TITLE
ATM7 sky 1.18.2 server crash bcs of MysticalAgriculture

### ISSUE THREAD

**Issue by Nick3222** [BlakeBr0/MysticalAgriculture#573]
server keeps crashing

 - Minecraft:1.18.2
 - Forge:40.1.86
 - Cucumber:Cucumber-1.18.2-5.1.3
 - Mystical Agriculture:MysticalAgriculture-1.18.2-5.1.2
[latest.log](https://github.com/BlakeBr0/MysticalAgriculture/files/10527208/latest.log)

**Comment by BlakeBr0** [comment]
I'm not really seeing anything that would suggest that the game had crashed in that log. Neither of those errors mentioning MA should have crashed the game.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
