### ISSUE TITLE
[1.19.3]Exetremely terrible bug in soul extractor that it could MULTIPLY everything you want

### ISSUE THREAD

**Issue by ColdTearsYY** [BlakeBr0/MysticalAgriculture#574]
**Describe the bug**
You can use this bug to produce anything you need.

**To Reproduce**
See this video I did. Google drive. Use coal for an example. You can put anything you want.
https://drive.google.com/file/d/1-LOQKSv76jwkFEZbu5HXtOo29HBqOr6B/view?usp=share_link

**Expected behavior**
Work normally.

**Screenshots / Scripts / Logs**
See the video

**Versions (please complete the following information):**
 - Minecraft: 1.19.3
 - Forge: 44.1.5
 - Cucumber:1.19.3-6.1.0
 - Mystical Agriculture: 1.19.3-6.1.1

**Comment by BlakeBr0** [comment]
Looks like it's just coal (unless I'm mistaken). Seems to be setting the slot to the fuel item instead of the slot item
