### ISSUE TITLE
awakened supremium essence has no recipe in 1.19.X

### ISSUE THREAD

**Issue by VenoPhage** [BlakeBr0/MysticalAgriculture#578]
**Describe the bug**
awakened supremium essence has no recipe in 1.19.X

**To Reproduce**
launch any 1.19.X version of this mod with a mod like JEI check for the recipe for awakened supremium essence and nothing will show

**Expected behavior**
A recipe of any sort really

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.2.3
 - Cucumber: Cucumber-1.19.2-6.0.3.jar
 - Mystical Agriculture: MysticalAgriculture-1.19.2-6.0.5.jar

**Comment by BlakeBr0** [comment]
The recipes seem to show up just fine for me. Perhaps it's a modpack issue?

**Comment by VenoPhage** [comment]
[latest.log](https://github.com/BlakeBr0/MysticalAgriculture/files/10564749/latest.log)
where heres my logs if that helps, atm ive just solved the problem using kubejs.

**Comment by BlakeBr0** [comment]
This recipe isn't showing up for you? And you aren't playing a modpack with modified recipes?

![image](https://user-images.githubusercontent.com/12994882/216235267-9cd604dc-b973-412e-8b7c-539479786a11.png)

**Comment by VenoPhage** [comment]
Alright.. well now i feel dumb i assumed the awakened essence recipe was like the previous tiers, using the infusion crystal.. however i did still come across an issue with thermal series essence to ingot recipes not working

**Comment by BlakeBr0** [comment]
That recipe issue might be an invalid cucumber-tags.json entry. I just released a new version of Cucumber (6.0.4) that should in theory automatically fix it.

**Comment by VenoPhage** [comment]
Yea latest cucumber version fixed it 👌
