### ISSUE TITLE
I can't enchant my pickaxe in the enchanting table. I can enchant everything else like armour

### ISSUE THREAD

**Issue by EmberHydra** [BlakeBr0/MysticalAgriculture#580]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft:
 - Forge:
 - Cucumber:
 - Mystical Agriculture:

**Comment by BlakeBr0** [comment]
Make sure the enchantableSupremiumTools config option is enabled

**Comment by EmberHydra** [comment]
Hi sorry for the late reply. How do I change that configuration?
Can you guide me like Option> something>where the configuration is located?

**Comment by BlakeBr0** [comment]
In your instance it'll be in the config folder. It's one of the options in the mysticalagriculture-common.toml file
