### ISSUE TITLE
harvester acting strange, voiding stuff or not harvesting at all

### ISSUE THREAD

**Issue by mindforger** [BlakeBr0/MysticalAgriculture#583]
**Describe the bug**
in single player a test setup for measuring optimal growth acceleration showe dstrange behaviour

looking at the screenshot, the north facing harvester does harvest nothing at all (although after 30 minutes running now it harvested one single essence JUST now as i wrote the issue)

and the other do harvest one single resource ony and void the rest if not pulled out immediately with a hopper

**To Reproduce**
see linked screenshot

**Expected behavior**
harvesting all resources planted not only one voiding the rest ... or harvesting anything at all in the north facing case

**Screenshots / Scripts / Logs**

https://puush.mgc4you.de/9ZVbn

**Versions (please complete the following information):**
 
    Minecraft: 1.19.3
    Forge: 44.1.16
    Cucumber: 6.1.1
    Mystical Agriculture: 6.1.2

**Comment by DutchDaddyDoes** [comment]
Can confirm, this still happens, just tested on latest current version (see below).

The harvester harvests the items, but **_only holds items in the first slot of its inventory_**, the rest is lost to the void.


```
Minecraft: 1.19.4
Forge: 45.0.43
Cucumber: 6.2.0
Mystical Agriculture: 6.2.0
```

**Comment by DutchDaddyDoes** [comment]
> Can confirm, this still happens, just tested on latest current version (see below).
> 
> The harvester harvests the items, but **_only holds items in the first slot of its inventory_**, the rest is lost to the void.
> 
> ```
> Minecraft: 1.19.4
> Forge: 45.0.43
> Cucumber: 6.2.0
> Mystical Agriculture: 6.2.0
> ```

I'd like to make an addendum, after a bit more testing:
It only holds one *type* of item, if enough of the same item are harvested it will fill more than one slot.

**Comment by BlakeBr0** [comment]
I'll have a fix out for the item deletion in the next release.

As for the second harvester not harvesting anything, that would be because harvesters currently scan the area in the same order/pattern regardless of their direction. I'm going to look into improving that as well.
