### ISSUE TITLE
Shift-Clicking into a Seed Processor crashes the client

### ISSUE THREAD

**Issue by BeckPhillips** [BlakeBr0/MysticalAgriculture#584]
**Describe the bug**
(I have not seen this firsthand. I run a server and have had 2 members report this to me.)
If you attempt to Shift-Click an item into a Seed Processor, it will crash your client.

**To reproduce**
Shift-click an item into a Seed Processor

**Expected Behavior**
Item should be moved from current slot to whatever slot holds it, like other inventories in the game.

**Versions (please complete the following information):**

```Minecraft: 1.19.2
Forge: 43.2.0
Cucumber: 6.0.6
Mystical Agriculture: 6.0.7

**Comment by BlakeBr0** [comment]
This issue was fixed in version 6.0.8
