### ISSUE TITLE
Forge Tagging

### ISSUE THREAD

**Issue by XxInvictus** [BlakeBr0/MysticalAgriculture#585]
I was specifically looking for 1.16.5 and thought I would raise it anyway as tagging is a very minor request.

**Is your feature request related to a problem? Please describe.**
Updating Project MMO for 1.16.5 and in the process converting the XP values for Smelting to reference Forge Tags instead of individual items to ensure consistent XP values across different mods providing similar items.

**Describe the solution you'd like**
Forge tags to be implemented for Mystical Agriculture 

**Describe alternatives you've considered**
We could use individual items for values but this is a very poor solution considering forge tagging is one of the most basic standards of all mods these days and it leaves the door open for inconsistencies to come up between mods.

**Additional context**
N/A

**Comment by BlakeBr0** [comment]
I believe I added the relevant items to tags at some point. I'm going to close this as the 1.16 has been EOL for quite some time now.
