### ISSUE TITLE
“Gear Module” option not present

### ISSUE THREAD

**Issue by CoffeeLakeIntel** [BlakeBr0/MysticalAgriculture#587]
I am currently running the latest version of the minecraft 1.18.2 Mystical Agriculture mod. As me and my buddies progressed, I in particularly noticed the bonuses received from the tiered armor sets were not actually there. Upon checking the server config, there was nothing related to armor in the config file. I was wondering if i could get some direction on where to go in order to fix this issue.

We are currently on Forge on a dedicated server

**Comment by BlakeBr0** [comment]
The old set bonuses are now need to be added via Augments in a Tinkering Table.
