### ISSUE TITLE
Add support for Ex-Nihilo Crooks

### ISSUE THREAD

**Issue by Jack-McKalling** [BlakeBr0/MysticalAgriculture#588]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my crook breaks, after use on a couple of trees.

**Describe the solution you'd like**
If you could craft essence tiered crooks, being an upgrade of one of the existing materials, similar to shears, you could get the tool to higher durabilities and unbreakable at supremium.

**Describe alternatives you've considered**
If you enchant a crook with unbreaking, it still breaks eventually. If you enchant it with mending, you have to throw it into an xp farm to repair it every now and then.

**Additional context**
The crook is a very simple item, similar to the shears or even the hoe. There are many other tools from other mods that would go really well with essence tiered variants as well (but I'll keep it specific in this report). Maybe this would need a new compat mod e.g. Mystical Utilities/Tools/Integration

**Comment by BlakeBr0** [comment]
Thanks for the suggestion! 

I think this is out of scope for the base mod and would make more sense as an addon mod.
