### ISSUE TITLE
Mystical Ag Went Belly Up

### ISSUE THREAD

**Issue by dreamwvr792** [BlakeBr0/MysticalAgriculture#589]
Currently playing Minecraft 1.18.2 with the MA mod. Which I love. But ran into a really weird issue yesterday.  I was placing an enchantment on a bow at my anvil. The anvil broke and when it did, my tinkering table (which was back to back with my anvil) "broke" as well.  That's really the only way I can describe what happened to it.  Not only did the tinkering table break, but my enchanting apparatus did as well. I ran outside to check on my crops and could not believe what i saw.  I have absolutely no idea what happened or how to fix it.  Screenshots are attached.  Any help would be appreciated.
![2023-03-16_23 18 34](https://user-images.githubusercontent.com/128186395/226028397-171c6718-780b-4451-9561-e3fbb3c2c979.png)
![2023-03-16_23 19 19](https://user-images.githubusercontent.com/128186395/226028402-a2b7962a-3e22-4c6a-bcac-ece52386c7ef.png)
![2023-03-16_23 19 28](https://user-images.githubusercontent.com/128186395/226028406-5b06f0f2-aaed-4d2e-8a12-48f34f1d35a1.png)
![2023-03-16_23 19 35](https://user-images.githubusercontent.com/128186395/226028408-2f48f375-9f71-46ca-b210-038418a3cf8d.png)

**Comment by BlakeBr0** [comment]
Stuff like this can happen if your world gets corrupted

**Comment by dreamwvr792** [comment]
this may sound like a dumb question, but how does a world get corrupted and how does one fix a corrupted world?

**Comment by SimonLyke** [comment]
various reasons how worlds can get corrupted, best look on google how minecraft worlds can become corrupted. as for fixing a corrupted world, you cant fix a corrupted world. but if the corruption only lies with mystical agriculture, or certain areas you can probably work around in game by deleting said areas or corrupted blocks and replacing them. or rolling back to previous backup
