### ISSUE TITLE
Suggestion: Biotite seeds for Quark

### ISSUE THREAD

**Issue by MentalMouse** [BlakeBr0/MysticalAgriculture#59]
This would naturally be a Tier 5 seed; the stuff appears in the End, usually after the dragon's death.

**Comment by BlakeBr0** [comment]
From what I can tell it's almost completely useless. It could probably be a tier 3/4 seed max, unless theres something im missing.

**Comment by MentalMouse** [comment]
I was thinking "post dragon", but I'll admit it's not very interesting.  Given you need a sample for the seed anyway, I could see a lower tier.
