### ISSUE TITLE
Mining Augment AOE Break not calling proper methods. Interaction with mekanism bug.

### ISSUE THREAD

**Issue by SimonLyke** [BlakeBr0/MysticalAgriculture#590]
Essentially having an AOE mining augment on a mystical agriculture pickaxe causes machines or storage containers from certain mods to have their contents deleted when breaking them, even with shift break to only break one block when you have the augment on the  pickaxe. 
Found the bug when breaking chemical tanks from mekanism that had oxygen inside, when broken they turn into empty chemical tanks.
Removing the mining AOE augment causes this to stop and breaking the chemical tank functions as normal as it retains its contents.

As described above, break machines or storage containers that have contents whilst using an AOE augment on mystical agriculture pickaxe

This occured on All The Mods 8, version 1.0.13 of the modpack.

I raised the issue to Mekanism devs first, who were adamant that the issue was not with how mekanism handles their blocks inventories. and was potentially an issue with AOE Augment not calling all the methods it should.

P.S love the mod, easily one of my favourites, please continue to work on it in your own time of course.
one thing to note also, from someone who loves balanced mods and tycoon things,  I found 12 inferium growth accelerators to be rather too OP, from growing a creeper seed in 4 hoursish to growing it in sometimes less than 20s.  i feel like it should be nerfed a little, or reducing the number of growth accelerators per recipe to one. or altering the max possible under a plot and changing how many can be obtained at such a cheap cost before having to go up the tiers. 
However this could just be my opinion so you are entitled to ignore this bit if you decide you are happy with it. 

Cheers

**Comment by DctrPepper** [comment]
I had the same issue and noticed it was with a lot of, if not all, blocks carrying NBT tags like backpacks, shulker boxes and cardboard boxes (although those are from Mekanism as well). When these blocks are mined the tags simply seem to be cleared, or rather not remembered.

Experienced on: ATM8-1.0.18 using MysticalAgriculture-1.19.2-6.0.8
