### ISSUE TITLE
No Immersive Engineering Essences craft the items 

### ISSUE THREAD

**Issue by FocusedVex** [BlakeBr0/MysticalAgriculture#591]
**Describe the bug**
Currently none of the immersive engineering essences craft any of the respective items. I have read the previous issues and deleted the cucumber tag json. However this hasn't resolved the issue on this occasion.

This issue appears to be affecting all Immersive Engineering Metals/Items, but does not extend to other mods such as Tinker Construct or Twilight Forest.

**Expected behavior**
Essences to craft their respective items.

**Versions (please complete the following information):**
 - Minecraft: 1.18.2
 - Forge: 40.2.0
 - Cucumber: 5.1.3
 - Mystical Agriculture: 5.1.4
 - Immersive Engineering: 8.4.0-161

**Comment by BlakeBr0** [comment]
I did a quick test and everything seemed to work for me. Do you have another mod installed with the same ingots? Does HOP Graphite essence have a use? Does the `cucumber-tags.json` file have any references to `immersiveengineering`?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
