### ISSUE TITLE
I cannot create tier 2 inferium seeds.

### ISSUE THREAD

**Issue by CadleWhitney** [BlakeBr0/MysticalAgriculture#592]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft:
 - Forge:
 - Cucumber:
 - Mystical Agriculture:

**Comment by CadleWhitney** [comment]
I put the mod onto my 1.19.2 world, and while creating the farm, i realized that, at least the version i downloaded on curseforge by BlakeBr0, this version does not have any tiers of the inferium seeds.

**Comment by DutchDaddyDoes** [comment]
Tiers of inferium seeds? I don't believe the mod is supposed to have tiers of inferium seeds? Unless you're referring to different seeds alltogether?

**Comment by BlakeBr0** [comment]
The different tiers of Inferium seeds were replaced with Essence Farmland. Growing Inferium crops on higher tier essence farmlands will drop more essence.
