### ISSUE TITLE
Mystical Agriculture Crashes server on startup

### ISSUE THREAD

**Issue by ZVLIAN** [BlakeBr0/MysticalAgriculture#596]
`MysticalAgriculture integration cancelled: unable to find a class: com.blakebr0.mysticalagriculture.api.crop.ICrop`

**Comment by BlakeBr0** [comment]
That error is coming from another mod. I also don't think that causes the game to crash.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
