### ISSUE TITLE
Usage of the Acceleration Wand

### ISSUE THREAD

**Issue by SikiciBebek** [BlakeBr0/MysticalAgriculture#599]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.**
Its kinda sad the Acceleration Wand isnt working anymore on the seeds. 

**Describe the solution you'd like**
U could add a config which allows u to use them or dont use them.

**Describe alternatives you've considered**
-

**Additional context**
-

I couldnt find anything on github about the Acceleration Wand, so i tought it would be helpful to write and "issue"

Cya soon ^^

**Comment by BlakeBr0** [comment]
I did a quick test and it doesn't seem to speed up vanilla wheat crops either. It might just not work on crops anymore.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
