### ISSUE TITLE
Feature Request - 1.10.2 Additional Support!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [BlakeBr0/MysticalAgriculture#6]
-Simple Ores - They now completely support TConstruct 
https://minecraft.curseforge.com/projects/simplecore-api
https://minecraft.curseforge.com/projects/simpleores
https://minecraft.curseforge.com/projects/simple-tcon/files/2347870
https://minecraft.curseforge.com/projects/fusion
https://minecraft.curseforge.com/projects/netherrocks

-Silent Gems - They have Crystals and Special ore types
https://minecraft.curseforge.com/projects/silents-gems?gameCategorySlug=mc-mods&projectID=220311

-Pokecube
https://minecraft.curseforge.com/projects/pokecube-revival?gameCategorySlug=mc-mods&projectID=224362
So I can farm pokeballs. Reason being is no currency mod is currently working. (At least not in the way I need.)

**Comment by BlakeBr0** [comment]
I'll look into them, no promises though.
