### ISSUE TITLE
AgriCraft Bug Issue

### ISSUE THREAD

**Issue by StanTheMann** [BlakeBr0/MysticalAgriculture#60]
Hi, I cant seem to get AgriCraft and MysticalAgriculture to work properly together. I was first having an issue with all of the crops randomly spawning inside of cropsticks. After I changed all of the Mystical Ag crops spawn chance to 0 in the json, I went back into the game. However regular crop mutations with Agricraft is not working with vanilla plants. I've only tried it with wheat seeds. If I could get help on this issue that would be much appreciated.

**Comment by BlakeBr0** [comment]
I don't make agricraft so I cant help you, sorry.
