### ISSUE TITLE
how to make it so that when you click on the right mouse button, all essences are collected, and not just the basic one?

### ISSUE THREAD

**Issue by mathewsmelentev** [BlakeBr0/MysticalAgriculture#603]
how to make it so that when you click on the right mouse button, all essences are collected, and not just the basic one, since it was done in ftb. version 1.12.2

**Comment by BlakeBr0** [comment]
Honestly not entirely sure what you mean. If you're talking about right click harvesting that's added by other mods usually. MA comes with Scythes which do AOE farming as well

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
