### ISSUE TITLE
Duplicate Essence from Gold/Creeper seeds.

### ISSUE THREAD

**Issue by Bufficorn** [BlakeBr0/MysticalAgriculture#606]
Farming Gold and Creeper seeds inside botany pots produces 2 versions of the essence, one with and one without NBT data.

**To Reproduce**
Plant Gold Seed and Creeper Seed in Botany Pots.

**Expected behavior**
Seeds produce only 1 essence type without the added NBT data to match the other seeds outputs.

**Screenshots / Scripts / Logs**
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/138082872/99b23c97-7dc7-40b4-a876-3c15b7f6e03f)
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/138082872/f1fe471f-732a-4ccb-8dd2-da1a4862719f)
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/138082872/ed1b1856-592c-4397-931c-6a25df20303a)
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/138082872/c7d7678d-2b40-40cb-85ad-0856b367ec7b)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.0.34
 - Cucumber: Cucumber-1.20.1-7.0.0
 - Mystical Agriculture: MysticalAgriculture-1.20.1-7.0.0.jar

**Comment by Bufficorn** [comment]
I checked all the seeds from the base mod and Aggriditions and these are the only 2 with the NBT data issue.
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/138082872/08351312-0e98-49fe-8360-f314685fd60d)

**Comment by BlakeBr0** [comment]
Does this happen when you harvest them normally? If it's only happens with botany pots then it would be an issue on their end.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
