### ISSUE TITLE
the game crashes when I equip boots or leggings with "step assist augment" 

### ISSUE THREAD

**Issue by Pinowings** [BlakeBr0/MysticalAgriculture#607]
**Describe the bug**
when I equip boots or leggings with "step assist augment" the game crashes and i can't go back in my world .

**To Reproduce**
Put "step assist augment" on boots or leggings with the Tinkering table and equip it

**Expected behavior**
I expected the boots to help me climb the blocks.

**Screenshots / Scripts / Logs**
[crash-2023-07-08_22.43.28-server.txt](https://github.com/BlakeBr0/MysticalAgriculture/files/11992398/crash-2023-07-08_22.43.28-server.txt).

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.0.35
 - Cucumber: 7.0.0
 - Mystical Agriculture: 7.0.0

**Comment by BlakeBr0** [comment]
This was fixed in version 7.0.1.
