### ISSUE TITLE
[Suggestion] Mob Chunk Drops from Essence Swords

### ISSUE THREAD

**Issue by piepie62** [BlakeBr0/MysticalAgriculture#61]
Hello, I have been playing with this mod for a while and I was thinking that it would make sense if the essence swords (at least the higher tiers, maybe Superium and above?) made mob chunks drop. Maybe they could have a lower chance than the soulium daggers? Just a thought that I had that might make it easier later on in the mod if you want some mob chunks you don't have. If not, what are your objections? Just for curiosity's sake, this last question.

**Comment by BlakeBr0** [comment]
The point of the soulium dagger (and the soulium material) was it would be the only way to get the chunks, and I think it will stay that way.

If you ever need certain chunks you can always craft them.

**Comment by piepie62** [comment]
Okay, I understand. Just was wondering. Somewhat related, could there be a way to downgrade generic chunks?

**Comment by BlakeBr0** [comment]
I'll write it down, not sure if I want that to be a thing or not.
