### ISSUE TITLE
recipe for an item with custom crops

### ISSUE THREAD

**Issue by RexXx2000** [BlakeBr0/MysticalAgriculture#610]
for the newest Minecraft version 1.20.1 i have created a crop for prosperity shards with Mystical Customization.
The essence and seed are in the game
![Item](https://github.com/BlakeBr0/MysticalAgriculture/assets/140098724/5940d980-4b93-417c-8cbd-de831714d214)
the seed is craftable with the altar 
but i dont know what should i do to craft the prosperity shards with this essence
![craft](https://github.com/BlakeBr0/MysticalAgriculture/assets/140098724/8b16b5f2-d30d-41aa-b598-17a2c8fc222d)

**Comment by BlakeBr0** [comment]
Yeah. You have to add your own essence recipes using something like a datapack, CraftTweaker, etc.
