### ISSUE TITLE
Ender IO seeds missing

### ISSUE THREAD

**Issue by dobemon** [BlakeBr0/MysticalAgriculture#612]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.**
I couldn't find seeds for the 1.20.1 Ender IO resources.

**Describe the solution you'd like**
Add Ender IO seeds back.

**Describe alternatives you've considered**
The curseforge page for Mystical Agriculture claims that it has Ender IO seeds. Exception 1.20.1 for Ender IO integration.

**Additional context**
I'd also suggest it to have an Enderman head recipe.

**Comment by BlakeBr0** [comment]
They're going to be added in the next release.

**Comment by BlakeBr0** [comment]
Added in version 7.0.2.
