### ISSUE TITLE
Graphite Essence not working

### ISSUE THREAD

**Issue by michaelortnerit** [BlakeBr0/MysticalAgriculture#615]
**Describe the bug**
In EMI there is a recipe but it doesn't work.

**To Reproduce**
put graphite essence in crafting table, no output is coming

**Expected behavior**
graphite bars like in EMI to see

**Screenshots / Scripts / Logs**
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/135371107/2a4576b3-c11d-4ea8-a28a-1e38f7c84b4a)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.1.3
 - Cucumber: 7.0.0
 - Mystical Agriculture: 7.0.1

**Comment by BlakeBr0** [comment]
After a quick test it seems to work for me. Are you playing on a server?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
