### ISSUE TITLE
Seed Reprocessor Consumes Bucket

### ISSUE THREAD

**Issue by Caltinor** [BlakeBr0/MysticalAgriculture#616]
**Describe the bug**
When using a lava bucket as fuel in a seed reprocessor, the bucket is consumed.

**To Reproduce**
1. place seed reprocessor and open the gui
2. place a lava bucket into the fuel slot
3. observe the bucket disappear

**Expected behavior**
the lava bucket replaced with an empty bucket.

**Screenshots / Scripts / Logs**
N/A

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.2.7
 - Cucumber: 1.19.2-6.0.7
 - Mystical Agriculture: 1.19.2-6.0.11

**Comment by Aceplante** [comment]
still happens on latest 1.16.5 version
