### ISSUE TITLE
Confing file missing for 1.19.2

### ISSUE THREAD

**Issue by Vaffinx** [BlakeBr0/MysticalAgriculture#618]
So, I realized that the tier 2-5 armor doesn't do anything in the game, I tried to check the config, but I didn't see any. I also attempted to copy and paste the config from Google, but it still doesn't work (playing with my friend on Essential) (also checked on single player).

**Comment by BlakeBr0** [comment]
The armor set bonuses were changed in later versions to be upgrades. If you want flight/step assist etc they need to be added as Augments using a TInkering Table.
