### ISSUE TITLE
Awakened Suprenium Chestplate can't be placed in the Smithing Table

### ISSUE THREAD

**Issue by TiphaineLAURENT** [BlakeBr0/MysticalAgriculture#619]
**Describe the bug**
Awakened Suprenium Chestplate can't be placed in the Smithing Table

**To Reproduce**
Craft an Awakened Suprenium Chestplate and try to put it in the Smithing Table

**Expected behavior**
We should be able to put the Awakened Suprenium Chestplate in the second slot of the Smithing Table

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.1.3
 - Cucumber: 1.20.1-7.0.0
 - Mystical Agriculture: 1.20.1-7.0.2

**Comment by BlakeBr0** [comment]
Why do you want to put it in a Smithing Table? I'm not 100% sure what the reason would be.

**Comment by TiphaineLAURENT** [comment]
It is useful for other mods like Utilix gilding upgrade

**Comment by BlakeBr0** [comment]
I've never used that mod but I'm not sure if adding that kind of integration is something I would have to do on my end. I think they would have to add recipes for them, or maybe you can yourself with a datapack. Again, I'm not 100% sure how that mod works so I may be wrong.

Thanks for the suggestion though.
