### ISSUE TITLE
[Suggestion] Adding Niter and Sulfur crops

### ISSUE THREAD

**Issue by Bobynoby** [BlakeBr0/MysticalAgriculture#62]
Hi, I was wondering if you could add Niter and Sulfur from Thermal Expansion as a crop if possible (And maybe Railcraft Saltpeter which is pretty much Niter) , Maybe as a tier 3 or tier 4 crop? Specifically Niter, As I find it very difficult to collect without having to pulverize a lot of materials to get any decent amount.

Thanks! and continue with this amazing mod :)

**Comment by BlakeBr0** [comment]
Added in the next update. https://github.com/BlakeBr0/MysticalAgriculture/commit/c1317cbd9ad1e5eb755ac19914eed0d71c6cd952
