### ISSUE TITLE
Blaze seed flower texture missing

### ISSUE THREAD

**Issue by Raresheky2227** [BlakeBr0/MysticalAgriculture#620]
**Describe the bug**
The yellowy top of the blaze seed when planted is missing

**To Reproduce**
Fully grow the blaze seed

**Expected behavior**
Yellow-orange flower

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).
![2023-08-09_13 10 54](https://github.com/BlakeBr0/MysticalAgriculture/assets/94103541/0f9d57aa-f104-4455-a614-2271ad3c8b63)

**Versions (please complete the following information):**
 - Minecraft:1.18.2
 - Forge:40.2.10
 - Cucumber:1.18.2-5.1.4
 - Mystical Agriculture:1.18.2-5.1.5

**Comment by BlakeBr0** [comment]
Does this issue occur when the crop is planted normally?  (eg. not using agricraft)

**Comment by BlakeBr0** [comment]
After testing without Agricraft installed the crop does render properly. So this is an Agricraft issue.
