### ISSUE TITLE
Missing tiered Seed Reprocessors

### ISSUE THREAD

**Issue by Maxi90909** [BlakeBr0/MysticalAgriculture#621]
**Describe the bug**

I don't have seed reprocessors of above the normal type exept the one from the mystical adaptations addon.

**To Reproduce**

I don't know how to reproduce it.

**Expected behavior**

I should have the tiered seed reprocessors (Inferium and up)

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

![Screenshot (104)](https://github.com/BlakeBr0/MysticalAgriculture/assets/76815835/7c1ba712-1e65-4aa1-b69e-68ab609b1ed0)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.1.43
 - Cucumber: Cucumber-1.20.1-7.0.0.jar
 - Mystical Agriculture: MysticalAgriculture-1.20.1-7.0.2.jar

**Comment by BlakeBr0** [comment]
The Seed Reprocessor was changed to use Upgrades like the Harvester and Soul Extractor do.
