### ISSUE TITLE
Inferion Flower will produce infinite resources with enchanted hoe (Harvester 1)

### ISSUE THREAD

**Issue by arturandre** [BlakeBr0/MysticalAgriculture#622]
**Describe the bug**
Inferion Flower will produce infinite resources with enchanted hoe (Harvester 1)

**To Reproduce**
Right click with a stone hoe enchanted with Harvester 1 over a full grown inferion flower.

**Expected behavior**
Either nothing (as with an unenchanted hoe) or the flower should break giving more resources than usual (due to the enchantement).

**Screenshots / Scripts / Logs**
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/1486993/5a5bd15d-1ae8-43d2-8d85-005e2b9e62b2)

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.34 
 - Cucumber: ?
 - Mystical Agriculture: 1.16.5-4.2.6

**Comment by BlakeBr0** [comment]
This sounds like it would be an issue with whichever mod adds that enchantment.

**Comment by arturandre** [comment]
I see. It is an enchantment from [Wonderful Enchantments](https://majruszs-enchantments.fandom.com/wiki/Majrusz%27s_Enchantments_Wiki). I would rather say it is more of a incompatibility, but indeed, it doesn't look like a bug from MA.

Thanks for the response, I'll close the issue.
