### ISSUE TITLE
Mining AOE IV isn't working as expected

### ISSUE THREAD

**Issue by DruBrandon** [BlakeBr0/MysticalAgriculture#628]
**Describe the bug**
Supremium Pickaxe with 9x9 mining AOE doesnt mine a 9x9 chunk

**To Reproduce**
Attempt to mine with it

**Expected behavior**
A 9x9 chunk to be mined out

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Curse Forge: 0.231.1.12152
 - Cucumber Library: 1.20.1-7.0.0
 - Mystical Agriculture: 1.20.1-7.0.2

**Comment by BlakeBr0** [comment]
It seems to work fine for me. Can you give any other details?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
