### ISSUE TITLE
Infusion Crystal is missing Crafting recipe and is uncraftable in Forge 7.0.3

### ISSUE THREAD

**Issue by Huntessluna** [BlakeBr0/MysticalAgriculture#629]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft:
 - Forge:
 - Cucumber:
 - Mystical Agriculture:

**Comment by Huntessluna** [comment]
I have been trying to make an infusion crystal in Forge version 7.0.3 there is no crafting recipe for the first level crystal and it is uncraftable in survival.

**Comment by BlakeBr0** [comment]
This recipe isn't working?
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/12994882/a61987e2-3248-4d80-937a-1b889d59ffab)

Is there a recipe for it in JEI? Maybe there's something up with the modpack your playing?

**Comment by LlubNek** [comment]
probably has the [Mystical Agriculture Tiered Crystals](https://www.curseforge.com/projects/299045) mod.  It disables the default crystal

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
