### ISSUE TITLE
Water Essence and Concrete Powder to Concrete

### ISSUE THREAD

**Issue by raflowers** [BlakeBr0/MysticalAgriculture#631]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.**
Not related to a problem, just a recipe addition suggestion

**Describe the solution you'd like**
It would be nice to be able to put Water Essence and Concrete Powder together in a normal crafting grid to create Concrete.

**Describe alternatives you've considered**
Other mods offer concrete automation but, as far as I know, none via just a regular crafting table recipe. This idea feels in line with being able to craft a water bucket from essence and an empty bucket.

**Additional context**

**Comment by BlakeBr0** [comment]
I like this idea.
