### ISSUE TITLE
Slower growth on infused farmland

### ISSUE THREAD

**Issue by Nuclear-Crow** [BlakeBr0/MysticalAgriculture#634]
**Describe the bug**
Plants grow much slower on infused farmland. Around 8 times slower, to be specific.

**To Reproduce**
Build a farm with regular farmland; build a farm with infused farmland (I tried both inferium and supremium farmlands). No growth accelerators. Wait until the soil is all hydrated. Plant a mystical crop (I tried air, ice and diamond plants, with same result).
On infused soil the growth rate ends up being around 0.00027 growth stages per plant per second.
On regular soil the growth rate ends up being around 0.0019 (7 times more) growth stages per plant per second.

**Expected behavior**
I would expect plant growth speed to be the same on infused soil as on regular soil, or maybe even faster on infused soil.

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: Fabric 0.14.22 i think
 - Cucumber: 1.0.6
 - Mystical Agriculture: 2.0.5
 - Modpack: All Of Fabric 6; version 1.10.1

**Comment by BlakeBr0** [comment]
You seem to mention Fabric multiple times but this mod is only available for Forge. If someone made a Fabric port you'll probably want to report this to them. 

As far as this version is concerned they should work the same assuming there are no external factors (such as changes by another mod).

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
