### ISSUE TITLE
Add a way to turn off step assist

### ISSUE THREAD

**Issue by MooMcMooman** [BlakeBr0/MysticalAgriculture#635]
**Is your feature request related to a problem? Please describe.**
If you look at the mod "StepItUp", when you crouch, the step assist stops
**Describe the solution you'd like**
When crouching, step assist stops
**Describe alternatives you've considered**
A keybind to turn it off
**Additional context**

**Comment by BlakeBr0** [comment]
I think this change makes sense. I've noticed that I can't sneak to prevent falling off a 1 block high drop as well, which didn't feel right.
