### ISSUE TITLE
how to find out ticks

### ISSUE THREAD

**Issue by excalation** [BlakeBr0/MysticalAgriculture#636]
where can I find information. how long do seeds grow in ticks? is it possible to get this information? I want to complicate my passage and increase the seed growth time, but I can't find anywhere information on how to do it

**Comment by BlakeBr0** [comment]
Resource Crops grow using the exact same logic as vanilla Wheat crops. This wiki article has an in-depth breakdown of how it all works: https://minecraft.fandom.com/wiki/Tutorials/Crop_farming#Growth_rate
