### ISSUE TITLE
[Suggestion] Make Soulium a little more common

### ISSUE THREAD

**Issue by Catomax262** [BlakeBr0/MysticalAgriculture#637]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.**
I'm angry how a single Soulium ore is as rare as Ancient Debris.

**Describe the solution you'd like**
Make it a little more common.

**Describe alternatives you've considered**
None.

**Additional context**
N/A

**Comment by BlakeBr0** [comment]
They're definitely much more common than that. Soulstone veins spawn pretty commonly in Netherrack-based biomes. Maybe the spawn rate of the ore has been decreased in whichever modpack you're playing?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.

As a quick note/clarification: by default approximately 5% of every Soulstone vein spawned will be Soulium Ore. This rate can be changed in the config.
