### ISSUE TITLE
(Suggestion) Please add a Prosperity Shard Seed and a Soulium Seed + Essences.

### ISSUE THREAD

**Issue by KyraelFenris777** [BlakeBr0/MysticalAgriculture#638]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.**
I find it annoying that basic ressources for MA still need to be mined even at mid/endgame.

**Describe the solution you'd like**
It would be more logical to have a seed to farm them just like everything else. 
Even if it's in higher tiers of MA.
Having the possibility to craft a Prosperity Shard Seed and a Soulium Seed would reduce the need for exploration and keep the focus on farming.

**Additional context**
At the moment I added custom recipes and crops to make this possible.
Each seeds are setup like diamond seeds T5, but requires 4 blocks instead of just 4 items.

**Comment by BlakeBr0** [comment]
Prosperity Shards aren't going to be getting a crop as that was a key design decision when adding them. I haven't ever considered adding a crop for Soulium though, so I'll have to think about that.

**Comment by BlakeBr0** [comment]
I have added Soulium seeds in release 7.0.7. As I said before I'm not going to add Prosperity Shard seeds (at least to the base mod.) Thanks for the suggestion!
