### ISSUE TITLE
Disabling Secondary Seed Outputs Doesn't Work [1.20.1]

### ISSUE THREAD

**Issue by Carolly** [BlakeBr0/MysticalAgriculture#641]
**Describe the bug**
When the config file shows:

#Should crops have a chance of dropping a second seed when harvested?
	secondarySeedDrops = false
	
	secondary seed drops are still occurring on every harvest
	
**To Reproduce**
Set secondarySeedDrops to false and harvest a Mystical Agriculture crop

**Expected behavior**

A second seed does not drop

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

![2023-10-26_01 38 32](https://github.com/BlakeBr0/MysticalAgriculture/assets/18418280/3bec0714-b4b0-4bb3-8833-c0cac186c4c7)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.1.3
 - Cucumber: 1.20.1-7.0.3
 - Mystical Agriculture: 1.20.1-7.0.4

**Comment by BlakeBr0** [comment]
I just tested and disabling that config definitely seems to work. I only get one seed back every harvest. Are you using a mod to harvest them?

**Comment by Carolly** [comment]
So this is when harvesting by right-clicking; I do get one seed back,
however, the plant does not go away, it goes back to the lowest maturity
stage. Thus, it's effective seed duplication on every harvest. Last night I
turned a single Certus Quartz seed into several hundred just by right-click
harvesting.

I'm not certain if that's a feature of MA or one of the other mods - I'm
running the MineColonies Dimensional Adventure pack, version 1.9.5.

**Comment by Inverse84** [comment]
I am having the opposite issue, I have the config set to true and my seeds are on the correct essence farmland but I can't get any more seeds to drop. I am on the latest version of both cucumber and mystical agriculture and there aren't any conflicting mods as the extra seeds still wouldn't drop when all I had were cucumber and mystical agriculture.

**Comment by Olfi01** [comment]
@Inverse84 For me, too, on 1.20.1 no additional seeds seem to be dropping, even though I have planted all my seeds on corresponding levels of essence farmland

**Comment by Olfi01** [comment]
Having debugged the code a bit, I noticed that there seems to be a rounding issue for the LootContextParams origin vector, causing negative x, y or z coordinates to be off by 1. This means, the mod is actually checking adjacent farmlands instead of the ones directly below. I will provide a PR with a fix in a little bit.

**Comment by BlakeBr0** [comment]
@Carolly are you still experiencing your issue with the latest MA release?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
