### ISSUE TITLE
mining augmetn not crafting

### ISSUE THREAD

**Issue by LostAstronaut175** [BlakeBr0/MysticalAgriculture#642]
when placing the items to create the minning augment in the pedestals the augment don't xraft

just placing the 4 iron pickaxe and 4 prudentium 
**Expected behavior**
would expect to see the augment getting crafted after placing the items in the pedestals and giving it a red stone signal

**Versions (please complete the following information):**
 - Minecraft: 1.18.2
 - Forge: 40.2.10
 - Cucumber: 1.18.2  5.1.4
 - Mystical Agriculture: 1.18.2   5.1.5

**Comment by BlakeBr0** [comment]
Are you sure the recipe is correct? Are any of the pickaxes broken or named or enchanted or something else?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
