### ISSUE TITLE
Compatibility for Common Sense mod

### ISSUE THREAD

**Issue by TheRTGGaming** [BlakeBr0/MysticalAgriculture#643]
**Describe the bug**
Hello, I am a fellow MCreator mod maker. My mod [common sense](https://legacy.curseforge.com/minecraft/mc-mods/the-common-sense-mod) has added a few items/ores to minecraft that should be compatible with your mod (Steel, Amber, Niter, and Sulfur) and a new ore called "Ancient Ore" I was wondering if you can add my mod into the Compatibility list?

 - Minecraft: 1.20.1
 - Forge: 47.1.47

**Comment by BlakeBr0** [comment]
The items that correspond with [these](https://github.com/BlakeBr0/MysticalAgriculture/tree/1.20/src/main/resources/data/mysticalagriculture/recipes/essence/common) essence recipes should work if your items have the proper tags and are set to be used in the `cucumber-tags.json` file.

I don't take suggestions for new crops to add to the base mod. If you would like to add compatibility yourself you can look at how [Mystical Agradditions](https://github.com/BlakeBr0/MysticalAgradditions/blob/1.20/src/main/java/com/blakebr0/mysticalagradditions/lib/ModCorePlugin.java) adds it's crops.
