### ISSUE TITLE
Essence Bows/Crossbows deal the same amount of damage as their normal counterparts.

### ISSUE THREAD

**Issue by Saucers2233** [BlakeBr0/MysticalAgriculture#645]
**Describe the bug**
The title is pretty self explanatory, that essence bows/crossbows don't deal extra damage. It seems that the draw speed is shorter.

**Expected behavior**
The expected behavior is that they should deal more damage than their normal counterparts.

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.2.14
 - Cucumber: 6.0.10
 - Mystical Agriculture: 6.0.12

**Comment by Saucers2233** [comment]
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/132640044/52b66464-8362-44a5-9a49-d031af134f01)
Test on pigs with 500 HP (A. Supremium - Awakened Supremium)
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/132640044/55e6c834-a244-4568-9d12-3eae586ecf70)
The A. Supremium Crossbow performed worse than the vanilla variant by 2 HP, and the bow performed better than the vanilla one by 2 HP

**Comment by Saucers2233** [comment]
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/132640044/6e84d1d8-c0f0-4461-b908-de46ff4b8c58)
The experiment was done again, and the crossbow was better, and the bows are equal.
The result will be approximated, as another test was done with the crossbows, and they changed again.

**Comment by BlakeBr0** [comment]
So the amount of damage a bow does is decided by the arrow being shot, not the bow itself. The benefit of essence bows was meant to be the quicker draw speed.

I may look into making the bows add additional power but I'm not 100% sure if I will.
