### ISSUE TITLE
No Second Seed drop even when true in config

### ISSUE THREAD

**Issue by Catoumy** [BlakeBr0/MysticalAgriculture#646]
**Describe the bug**
I never got a second seed from any resource crop, even tho the config has been set to true.
i tested this with certus quartz, coal and lead seeds. however, i did get a second seed from inferium crop.
Both on a server with the same modpack, aswell as on a singleplayer world with the same modpack

**To Reproduce**
create a quick farmland next to water, convert the farmland to inferium farmland. Place a seed (not inferium), keep using inferium watering can until fully grown. break the crop and replace. repeat that 10x

**Expected behavior**
As the wiki says that on inferium farmland every crop has a 10% chance to drop a second seed, i expected that i would get at least 1 seed when harvesting 10x

**Screenshots / Scripts / Logs**
![2023-10-30_12 56 42](https://github.com/BlakeBr0/MysticalAgriculture/assets/118620387/341de8c6-f3ae-4588-8444-5d3b1088bd5a)
![Screenshot 2023-10-29 225745](https://github.com/BlakeBr0/MysticalAgriculture/assets/118620387/246c8fdd-436e-4133-955f-24a8b8a4a935)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.0
 - Cucumber: 7.0.3
 - Mystical Agriculture: 7.0.4
 - ModPack: https://paste.ee/p/6kjwe#vJQhglH4xJifSX0eREch1B0pYsPEx6Fq

**Comment by Inverse84** [comment]
I have been experiencing the same issue
