### ISSUE TITLE
[Feature Request] Watering Can Animation or Sound Effect

### ISSUE THREAD

**Issue by Darkosto** [BlakeBr0/MysticalAgriculture#648]
Hey Blake,

Would you willing to investigate adding an animation to the watering cans in the mod? I trying to use your watering cans with a retexture for modpack theme consistency and it would be very helpful if there was more visual feedback that the watering can is functioning. If not, would you be willing to add a sound effect while it's being used? 

Thanks so much for all of your hard work!
Darkosto

MC: 1.20.1
Mystical Agriculture: 7.0.6
PickleTweaks: 8.0.0

**Comment by BlakeBr0** [comment]
Added in release 7.0.7. Thanks for the suggestion streamerman!

As a note I couldn't get the usage animation to work with auto-watering but it works fine when holding right click like normal.
