### ISSUE TITLE
Can't craft Seed Reprocessor

### ISSUE THREAD

**Issue by hiimk3v** [BlakeBr0/MysticalAgriculture#649]
**Describe the bug**
Seed reprocessor cannot be crafted, more specifically it is the hoes that are not accepted for some reason as viewed by REI.

**To Reproduce**
Try to craft a seed reprocessor as normal.

**Expected behavior**
A seed reprocessor to be crafted.

**Screenshots / Scripts / Logs**
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/75728910/a8a812ab-d23c-4d2c-9cdf-8b2d49c2d59c)
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/75728910/b960f185-0835-4906-a5f6-7f45ea049142)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Fabric: 0.14.24
 - Cucumber: 2.0.1
 - Mystical Agriculture: 3.0.2

**Comment by BlakeBr0** [comment]
This mod is for forge.
