### ISSUE TITLE
Step Assist is not working

### ISSUE THREAD

**Issue by Gamertagls** [BlakeBr0/MysticalAgriculture#650]
**Describe the bug**
I am playing ATM8, and I have step assist augment installed in tier 4 boots but when I walk up to 1 high blocks I do not automatically step over them like expected. Is there a toggle option I am not aware of? I had thought that they worked when I first put them on the boots but then stopped working.

**To Reproduce**

Create tier 4 boots
add step assist
walk into 1 tall blocks

**Expected behavior**
I expected to be able to disabled auto jump because I could now walk up 1 high blocks as if they were stairs.

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.2.14
 - Cucumber: 6.0.10
 - Mystical Agriculture: 6.0.12

**Comment by BlakeBr0** [comment]
Fixed in 6.0.13
