### ISSUE TITLE
[1.20.1] game crashes at launch

### ISSUE THREAD

**Issue by Bass2style** [BlakeBr0/MysticalAgriculture#651]
**Describe the bug**
game is crashing when "latest" versions of the mod is used. (see versions)

**To Reproduce**
Steps to reproduce the behavior: launch the game. xD

**Expected behavior**
A clear and concise description of what you expected to happen. : launching successfuly.

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).
latest.log : https://gist.github.com/Bass2style/274eb14216879e81c56ac6c81b78344f
"fml" crash report : https://gist.github.com/Bass2style/13c6fe4dc2dff4569988bb46f0ec04da
"client" crash report : https://gist.github.com/Bass2style/07e0963ebc187ad5940a5d6480c7c48c

**Versions (please complete the following information):** (i added some related mods versions too)
 - Minecraft : 1.20.1
 - Forge : 
 - Cucumber : 7.0.5
 - Mystical Agriculture : 7.0.7
 - Myst aggraditions : 7.0.2
 - adaptations : 1.0.0
 - customisation : 5.0.0
 - Singleplayer or Multiplayer : single player
 
 edit : fallbacking to MA 7.0.6 and Cucumber 7.0.4 fixes the issue, so its one of the two mods, or a compat issue somewhere with the changes made in those versions.

**Comment by BlakeBr0** [comment]
Looks like an error in Mystical Adaptations

**Comment by Bass2style** [comment]
hi,

i confirm it seems related to Adaptations, i updated both Mystical Agriculture and Cucumber, then disabled Adaptations, and it's loading now.

i'm going to report this to Focamacho.

have a nice day.

**Comment by MokahTGS** [comment]
I do not have Mystical Adaptations and have this crash: https://pastebin.com/6evKw4BX

**Comment by BlakeBr0** [comment]
This appears to have been fixed.
