### ISSUE TITLE
SoundInstance for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by Sultia** [BlakeBr0/MysticalAgriculture#652]
**Describe the bug**
After new mystical AG update throwing similar errors related to client only mods for mystical ag. Best guess is the water can sound.

**To Reproduce**
Run mystical ag with all the mods on latest forge in the log

**Expected behavior**
the server launching

**Screenshots / Scripts / Logs**
Server log: 
[latest.log](https://github.com/BlakeBr0/MysticalAgriculture/files/13478365/latest.log)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.8
 - Cucumber: 7.0.5
 - Mystical Agriculture: 7.0.7
 - Singleplayer or Multiplayer: Multiplayer

**Comment by BlakeBr0** [comment]
Damn, I thought I tested on the server...

**Comment by BlakeBr0** [comment]
Fixed in version 7.0.6 of Cucumber.
