### ISSUE TITLE
1.20.1 - 7.0.7  Watering can no longer works in Modular Router

### ISSUE THREAD

**Issue by Maxter-Max** [BlakeBr0/MysticalAgriculture#653]
**Describe the bug**
Modular Routers set to right click with a watering can no longer works
My setup worked exactly as expected after I downgraded Mystical Agriculture to 7.0.6  (Playing on ATM9 0.2.25)

**To Reproduce**
Setup a Modular Router from the Modular Routers Mod
I used a Filled Supremium Watering Can
Ensure that fakePlayerWatering = true in the Mystical Agriculture config

**Expected behavior**
The crops to grow as if the watering can was getting used on them.

**Screenshots / Scripts / Logs**
This youtube video is using a similar setup: https://www.youtube.com/watch?v=6LzwgKSHxGU

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.14
 - Cucumber: 7.0.6
 - Mystical Agriculture: 7.0.7
 - Singleplayer or Multiplayer: Multiplayer

**Comment by BlakeBr0** [comment]
I changed how the watering cans work internally to make their growth speeds consistent between regular and auto-watering. This change made it so spamming right-click no longer has any effect. I didn't really think about how this would apply to auto-clicker blocks.

I'll look into re-adding the old activation methods for fake players specifically. If there's no side effects for regular use then it should be fine.

**Comment by BlakeBr0** [comment]
This should be fixed with Cucumber version 7.0.7
