### ISSUE TITLE
server config error

### ISSUE THREAD

**Issue by Lofkrad** [BlakeBr0/MysticalAgriculture#655]
**description of the problem**
I encountered a problem that when changing the "mysticalagriculture.cfg" file, 

1)"mob chunk" are not disabled, when the parameter = false

2)The durability of the "Core Remover" does not change the number of uses, with a value of 1 (by default 4)

all other config parameters work...

**to repeat**
no idea

**request**
so that the configs work fully, a hint on how to fix it

**Screenshots**
![Без имени](https://github.com/BlakeBr0/MysticalAgriculture/assets/139816328/38f98878-9fe1-4bff-b59c-00ab0b28a8d5)
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/139816328/f0d85fca-fab5-466a-b7c5-36bb5720f5f1)

 - Minecraft:1.12.2
 - forge: 1.12.2 - 14.23.5.2860
 - Mystical Agriculture 1.7.5
 - Singleplayer or Multiplayer: Multiplayer

**Comment by BlakeBr0** [comment]
So the first option is just to disable the recipes for the Mob Chunks, meaning you could only get them by killing the corresponding mob with a Soulium Dagger.

I just tested and changing the durability of the Core Remover to 1 was reflected after restarting the game. I'm not sure why that wouldn't have worked for you in this case.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
