### ISSUE TITLE
Cobalt and Osmium seeds not available

### ISSUE THREAD

**Issue by neinome** [BlakeBr0/MysticalAgriculture#657]
**Describe the bug**
Despite having cobalt and osmium (both registered with forge:ingots/*), neither are available in game (neither in JEI or creative menu).  Other resources, such as Platinum, Iridium, and Zinc are available as seeds.

Attempting to create the seeds manually with Mystical Customization also yields no effect.

**To Reproduce**
Not sure.
Mods used are:
ChemLib (which is providing the resources) 1.20.1-2.0.18
Mystical Agriculture 1.20.1-7.0.7
Mystical Agradditions 1.20.1-7.0.2
Mystical Adaptations 1.20.1-1.0.1
Mystical Customization 1.20.1-5.0.0
Cucumber 1.20.1-7.0.6

**Expected behavior**
With a resource registered in forge:ingots/<ingot>, the seed should be available.

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.4
 - Cucumber: 7.0.6
 - Mystical Agriculture: 7.0.7
 - Singleplayer or Multiplayer: Single Player
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/7586178/52582f42-154a-402a-b2a5-b11199a3a707)
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/7586178/c42b2be4-0bbe-45c3-b7d2-c05c072936c4)
[latest.log](https://github.com/BlakeBr0/MysticalAgriculture/files/13775220/latest.log)

**Comment by neinome** [comment]
Added pictures of creative menu to show seeds not present.
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/7586178/ab2b4cd7-20c4-46fb-a62f-54a49f30050b)
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/7586178/1b71a3f9-f25e-40d4-b448-96294afbb12d)

**Comment by BlakeBr0** [comment]
So Cobalt seeds need Tinkers' Construct and Osmium seeds need Mekanism to be enabled by default. Since you're using Mystical Customization you can add entries to the `configure-crops.json` file to enable them, see [docs](https://blakesmods.com/docs/mysticalcustomization/editing-crops#enabled).

Setting `enabled` to `true` should work.

**Comment by neinome** [comment]
I did not read that being the case when i looked at the code for the materials. It appeared to check for the applicable material to determine whether or not the seed should exist.  It seems odd that those two would adopt that behaviour when normally Thermal and Tech Reborn materials do not considering that they all use the same conditions in their code...

Enabling the materials in configure-crops.json did indeed work, thank you.
