### ISSUE TITLE
Server configs for 7.0.7 not working on servers

### ISSUE THREAD

**Issue by jlsafof** [BlakeBr0/MysticalAgriculture#658]
**Describe the bug**
Configs not applying in server but work on single player

**To Reproduce**
Edit
	#Should fake players be able to use watering cans?
	fakePlayerWatering = true

**Expected behavior**
Watering can to work in something like the modular router

**Screenshots / Scripts / Logs**
ATM9, trying to reallow watering cans to work in machines

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.16
 - Cucumber: 7.0.6
 - Mystical Agriculture: 7.0.7
 - Singleplayer or Multiplayer: Multiplayer

**Comment by BlakeBr0** [comment]
This should've been fixed with the latest release of Cucumber.

**Comment by chocomint02** [comment]
Just as an addendum, I am running into the same issue using Cucumber 7.0.7. Mystical Agriculture has been updated to 7.0.8 in the latest server build of ATM9 (0.2.36).

**Comment by BlakeBr0** [comment]
I just tested on a server (ATM9 0.2.51, fakePlayerWatering set to true) with the following Activator Module config and it appears to work. Does this work for you guys?

![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/12994882/95a7cf88-c9b6-4879-88bf-8d9afe9b0af1)

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
