### ISSUE TITLE
Soul glass recipe not working 

### ISSUE THREAD

**Issue by MeguminChan69** [BlakeBr0/MysticalAgriculture#659]
**Describe the bug**
JEI shows the recipe for soul glass (which is 4 soul dust), when the items are put in it doesnt make the soul glass. Saw other recipes online but none work. Can't make the glass in survival.

**Expected behavior**
The craft making the glass when the right items are put on.

**Versions (please complete the following information):**
 - Minecraft: 1.20.1 
 - Fabric: 0.15.3 
 - Cucumber: 1.20.1-2.0.1 
 - Mystical Agriculture: 1.20.1-3.0.2 
 - Singleplayer or Multiplayer: Singleplayer

**Comment by RezkinlovesDragons** [comment]
How did you fix it? I’m having the same issue
