### ISSUE TITLE
Flight don't work 1.20.1

### ISSUE THREAD

**Issue by Lucasbigbox** [BlakeBr0/MysticalAgriculture#660]
**Describe the bug**
Flight don't work

**To Reproduce**
Just put flight augments

**Expected behavior**
Just flight with the chestplate

**Screenshots / Scripts / Logs**
I just press espace : [https://youtu.be/1HNzcBuxJOw
All mods in this modpack :
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/79045971/2a4bc742-969a-4c4e-8c3d-bc7f623c7fc5)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.19
 - Cucumber:7.0.6
 - Mystical Agriculture: 7.0.8
 - Singleplayer and Multiplayer

**Comment by Lucasbigbox** [comment]
[](https://youtu.be/1HNzcBuxJOw)

**Comment by BlakeBr0** [comment]
Does this issue occur with just Mystical Agriculture installed? Maybe try incrementally removing mods until it starts working? Then you could see which mod is conflicting.

**Comment by EllensFish** [comment]
Same issue, but i fixed it by removing the inventory pets mod.  Try removing inventory pets and testing it.

**Comment by puppet04** [comment]
> Same issue, but i fixed it by removing the inventory pets mod.  Try removing inventory pets and testing it.

this is happening in the 1.18.2, how can i solve this and keep the inventory pets mod, any idea?

**Comment by BlakeBr0** [comment]
I just tested with the latest Inventory Pets installed and it seems to work fine. If this is still an issue you can reply here.
