### ISSUE TITLE
Missing items

### ISSUE THREAD

**Issue by Gudu0** [BlakeBr0/MysticalAgriculture#662]
**Describe the bug**
I wanted to make a farm design I found on youtube, but I'm missing the scythes and the sickles.

**To Reproduce**
Steps to reproduce the behavior: I don't know

**Expected behavior**
I expected to look up scythe in JEI and then craft one, but found that it didn't exist

**Screenshots / Scripts / Logs**
![No scythe](https://github.com/BlakeBr0/MysticalAgriculture/assets/125727026/68275e7d-f81a-4727-bbd1-477c8976da9c)

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.34
 - Cucumber: Cucumber-1.16.5-4.1.12.jar
 - Mystical Agriculture: MysticalAgriiculture-1.16.5-4.2.6.jar
 - Singleplayer or Multiplayer: Singleplayer

**Comment by Gudu0** [comment]
I've tried restarting my world and game.

**Comment by Gudu0** [comment]
I just noticed I also don't have awakened supremium anything or the items to make that

**Comment by BlakeBr0** [comment]
Both Awakened Supremium and Scythes were added in version 6.x for 1.19. I'm guessing you saw these features on the wiki? I should probably work on mentioning the versions features were added to avoid confusion.

**Comment by Gudu0** [comment]
Yes, please do that.
