### ISSUE TITLE
MysticalAgriculture API on maven

### ISSUE THREAD

**Issue by stellanera98** [BlakeBr0/MysticalAgriculture#664]
Hi, I saw that the API jar is on maven, but only 1.20.1-7.0.0 which isnt the same version as the latest mod jar which is 1.20.1-7.0.8
Because there seemingly only is one random version I am unsure if it is there on purpose so I dont know if I can rely on it.

Would it be possible to provide API jars on maven going forward?

**Comment by BlakeBr0** [comment]
There's an API jar for each available at the standard maven address, ex https://maven.blakesmods.com/#/releases/com/blakebr0/mysticalagriculture/MysticalAgriculture/1.20.1-7.0.8
