### ISSUE TITLE
Specific Modded Essences not crafting (Custom Modpack)

### ISSUE THREAD

**Issue by KCtops6** [BlakeBr0/MysticalAgriculture#667]
**Describe the bug**
The recipes for some modded items seem to be broken.  Note this is a custom modpack.  An example is apatite below.
**To Reproduce**
Simply launch the game and open uses in JEI for a particular essence (see screenshot)
**Expected behavior**
For this example, apatite essence should be expected to craft into apatite.

**Screenshots / Scripts / Logs**
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/29132307/f40d06c8-d83b-4464-8044-0cdf08b9af54)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.0
 - Cucumber: Cucumber-1.20.1-7.0.7.jar
 - Mystical Agriculture: MysticalAgriculture-1.20.1-7.0.8.jar
 - Singleplayer or Multiplayer: singleplayer

**Comment by BlakeBr0** [comment]
What is `forge:gems/apatite` set to in the `cucumber-tags.json` file?

**Comment by KCtops6** [comment]
Found the error, it was set to NULL by default.  Problem fixed.
