### ISSUE TITLE
Supremium Armor with Flight Augment won't let me fly

### ISSUE THREAD

**Issue by derpyinpain** [BlakeBr0/MysticalAgriculture#670]
After getting a full set of supremium armor, I put only the flight augment on my chestplate (the rest of the armor is blank (i don't know if that alters anything)) and im unable to fly. all i do is have a slightly higher jump when i double tap spacebar.

 - Minecraft: 1.20.1
 - Forge: 47.2.0
 - Mystical Agriculture: 1.20.1-7.0.8
 - Singleplayer or Multiplayer: Multiplayer

**Comment by EllensFish** [comment]
Iv noticed the same issue, however i found out that it was because i had the mod Inventory Pets. Disabling the inventory pets mod fixed the issue.

**Comment by BlakeBr0** [comment]
I'm going to close this in favor of #660
