### ISSUE TITLE
Server Down

### ISSUE THREAD

**Issue by zaciam** [BlakeBr0/MysticalAgriculture#673]
When I open the URL https://maven.blakesmods.com/releases/com/blakebr0/mysticalagriculture/MysticalAgriculture/1.20.1-7.0.7/MysticalAgriculture-1.20.1-7.0.7.jar it says 404 Resource not found.

**Comment by BlakeBr0** [comment]
Should be fixed now.

**Comment by zaciam** [comment]
Thank you very much!
