### ISSUE TITLE
Cucumber does not load during mod development with Forge Mdk

### ISSUE THREAD

**Issue by zaciam** [BlakeBr0/MysticalAgriculture#675]
**Describe the bug**
I want to develop a new Minecraft mod that depends on the Cucumber mod. However, when I add the mods to my dependencies, Minecraft crashes.

**To Reproduce**
1. Download and extract Forge Mdk.
2. Add https://maven.blakesmods.com as a Maven repository.
3. Add the dependencies:
   ```
   implementation fg.deobf("com.blakebr0.cucumber:Cucumber:${minecraft_version}-7.0.6")
   implementation fg.deobf("com.blakebr0.mysticalagriculture:MysticalAgriculture:${minecraft_version}-7.0.7")
   ```
4. Run the Minecraft client by executing the `runClient` Gradle command.

**Expected behavior**
The game should start without errors.

**Screenshots / Scripts / Logs**
![image](https://github.com/BlakeBr0/MysticalAgriculture/assets/5081153/3c76496a-52e4-4272-9b97-9283501e0631)
[crash-2024-02-19_18.31.01-fml.txt](https://github.com/BlakeBr0/MysticalAgriculture/files/14335421/crash-2024-02-19_18.31.01-fml.txt)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.0
 - Cucumber: 7.0.6
 - Mystical Agriculture: 7.0.7
 - Singleplayer or Multiplayer: Singleplayer

**Comment by BlakeBr0** [comment]
You have to add the following to your gradle `plugins` block if you want to use `runClient` from the command line:

```
    id 'org.spongepowered.mixin' version '0.7.+'
```

The recommended approach is to use the IDE run configs which can be generated with ex. `genIntellijRuns` which work without needing that plugin installed. Though the Mixin plugin may still be needed when depending on Cucumber as a local project.

**Comment by zaciam** [comment]
Thank you very much!

**Comment by zaciam** [comment]
Today I found out that the problem was that I had a JDK 8 used by accident for gradle.
