### ISSUE TITLE
Upgrading Furnaces with Machine Upgrades 1.20.1

### ISSUE THREAD

**Issue by minecraftindad** [BlakeBr0/MysticalAgriculture#677]
It seems all the Machine Upgrades have not been implemented in 1.20.1 or  we did something wrong.

**To Reproduce**
Steps to reproduce the behavior: Tried to right-click inferium upgrade to vanilla furnace

**Expected behavior**
Expected with right click for it to replace the Vanilla Furnace with Inferium Furnace as described in the wiki.

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.20
 - Cucumber: Cucumber-1.20.1-7.0.7.jar
 - Mystical Agriculture: MysticalAgriculture-1.20.1-7.0.10.jar
 - Singleplayer or Multiplayer: Both

**Comment by minecraftindad** [comment]
I realized this was only for certain machines and misinterpreted how it worked.

**Comment by BlakeBr0** [comment]
In 1.21 I plan on making it so that the Furnaces are upgradable in the same way as the other machines.
