### ISSUE TITLE
Client Crash when Using Supreium Bow

### ISSUE THREAD

**Issue by Lost-Ninja** [BlakeBr0/MysticalAgriculture#68]
Trying to use a supremium bow, 1st crash just after crafting (no arrow in inventory), 2 & 3 in The End while attempting to kill the dragon (1st time) (end newly loaded). Playing on a locally hosted SMP server.

Minecraft 1.11.2
Forge 13.20.0.2315
Mystical Agriculture 1.5.6 (I have agradditions too @ 1.0.2)
[crash-2017-06-20_16.39.01-client.txt](https://github.com/BlakeBr0/MysticalAgriculture/files/1089057/crash-2017-06-20_16.39.01-client.txt)
[crash-2017-06-20_18.02.03-client.txt](https://github.com/BlakeBr0/MysticalAgriculture/files/1089058/crash-2017-06-20_18.02.03-client.txt)
[crash-2017-06-20_18.07.26-client.txt](https://github.com/BlakeBr0/MysticalAgriculture/files/1089059/crash-2017-06-20_18.07.26-client.txt)

**Comment by Lost-Ninja** [comment]
Just rewatched the footage of the three crashes (I'm in the process of recording a YouTube series), and I notice that in all three occasions I didn't have an arrow in the inventory.

**Comment by BlakeBr0** [comment]
Yea, I might know what the issue is. It's probably because I forgot to change the ItemStack stuff in the bow to the new 1.11 format. Weirdly enough though, I don't think I ever had this issue.

**Comment by BlakeBr0** [comment]
I also just noticed you have optifine installed so that could also be the issue.

**Comment by BlakeBr0** [comment]
If version 1.5.7 doesnt fix it, it might be something else.
