### ISSUE TITLE
Machine upgrades issue

### ISSUE THREAD

**Issue by GenericX2Eric** [BlakeBr0/MysticalAgriculture#682]
![2024-04-17_02 56 47](https://github.com/BlakeBr0/MysticalAgriculture/assets/152666554/99ef737e-7c3f-496e-9cb8-158977f2e508)
**Describe the bug**
![2024-04-17_02 56 56](https://github.com/BlakeBr0/MysticalAgriculture/assets/152666554/54ea14b0-42a2-4127-90f0-6ea2aee11253)
Possibly a bug with machine upgrades, They dont seem to work in increasing the speed or process of the blocks in front, without the upgrade it works normally but takes a bit, when i add the upgrades it just doesnt harvest anything anymore, i know it gets +1 area but my understanding on that would mean it would still do the 3x3 and then +1 to that area, i have sufficient power and the plants are at full harvest, i waited about 5 minutes without it doing anything, with the upgrade it looks like it just stops working.

**To Reproduce**
Steps to reproduce the behavior: put any upgrade into the machine

**Expected behavior**
• expected to speed up harvest of plants

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: v10 (im playing all the forge 10 modpack with a few added mods)
 - Cucumber: idk what cucumber is (if its a pre-requisite then yes i have it with the 1.20.1  version)
 - Mystical Agriculture: 1.20.1
 - Singleplayer or Multiplayer: Iv had the issue on both single and multiplayer

**Comment by BlakeBr0** [comment]
I did a quick test and it seems to work fine. You didn't put the proper mod version (it should be like 7.x.x for 1.20.1) so I'm not sure if you're on the latest version. Is this still an issue you're experiencing?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
