### ISSUE TITLE
Mystical Agriculture seeds

### ISSUE THREAD

**Issue by Aoimina** [BlakeBr0/MysticalAgriculture#683]
I have no idea how ATM9 did it, but i can't seem to find a way to remove the seed drop from mystical agriculture, i tried using kubejs,lootJS none seem to affect the seed drops what to so ever, is this a bug?, is it cucumber fault?, and if both are no, how can i remove the seed drop from mystical agriculture crops leaving only the essence drop

**Comment by BlakeBr0** [comment]
Are you referring to the secondary seed drop? If so you can disable those globally in the config, or per crop/crop tier using Mystical Customization ([docs](https://blakesmods.com/docs/mysticalcustomization/editing-crops)). If you mean that the crop should drop 0 seeds when broken then I don't think that's possible currently.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
