### ISSUE TITLE
Pulling Water Essence out of Crafting Table

### ISSUE THREAD

**Issue by thepriz** [BlakeBr0/MysticalAgriculture#684]
**Describe the bug**
When picking up water essence out of the crating table causes Minecraft to crash.

**To Reproduce**
Put the full stacks of dirt essence and water essence into the crafting table in the clay recipe. Did a shift-click to craft as much clay as would fit in my inventory? then was swapping clay for the leftover water essence (didn't get to dirt) which led to a crash.

**Expected behavior**
It should be able to swap the clay and water essence without Minecraft crashing.

**Screenshots / Scripts / Logs**
Link to crash log: [Mystical Agriculture Crash Log](https://pastebin.com/xVeSTwQ8)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.20
 - Cucumber: 1.20.1-7.0.8
 - Mystical Agriculture: 1.20.1-7.0.11
 - Singleplayer or Multiplayer: Singleplayer

**Comment by BlakeBr0** [comment]
From that log it looks like an issue with Corail Pillar. Polymorph and Fast Workbench are also mentioned but probably aren't the root cause.
