### ISSUE TITLE
Suggestion for disabling features

### ISSUE THREAD

**Issue by Swifty744** [BlakeBr0/MysticalAgriculture#685]
Why not allow the player to be able to disable certain crops i.e. if you don't want the player to be able to grow iron, diamonds, netherite, etc allow the modpack maker to be able to disable it without needing extra mods to do that job.

**Comment by BlakeBr0** [comment]
This functionality is handled by Mystical Customization. What's the issue with adding another mod?

**Comment by Swifty744** [comment]
What other mods are there that can disable certain crops? It's nice to have things work out the box

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by BlakeBr0** [comment]
That's fair. I don't think I'm going to be merging this functionality into the base mod though. Thanks for the suggestion.

**Comment by Swifty744** [comment]
So what's the mod called so I can check it out?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by BlakeBr0** [comment]
It's called Mystical Customization https://www.curseforge.com/minecraft/mc-mods/mystical-customization

**Comment by Swifty744** [comment]
Brilliant thank you

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
