### ISSUE TITLE
Enchanter slots buggy + Accidental Dupe Glitch?

### ISSUE THREAD

**Issue by Ferynix** [BlakeBr0/MysticalAgriculture#687]
**Describe the bug**
For some reason, the enchanter slots are always glitchy. When putting more then 64 items in each slot, the items will pop in and out of view... sometimes just showing as empty slots.

Sometimes when you add more items to other slots, theyll also glitch out and jump around between slots.

Furthermore... I seemed to have accidentally duped on a server using the enchanter. I tried to put 3 stacks of leather in to make a Protection IV book... When I pulled the book out, I clicked the slots just in case there was remnants leftover.. and the empty slot I clicked proceeded to create 8 stacks of leather out of thin air... These items were not ghost objects either. They remained after dropping and even relogging into the server. It genuinely duplicated the items. No clue what the catalyst for it was.

**To Reproduce**

No real way to recreate any of it in particular... Its just general behavior with the enchanter anytime I use it. The time it duplicated items is beyond me. The server certainly wasnt lagging (nor was I), so I have no idea what couldve caused it... Though I have a feeling the buggy / desycned slots contributed to it happening, if I had to guess.

**Expected behavior**

Items should not be glitching out and jumping in and out of existance and flipping between slots every single time I use the enchanter. Something is very wrong. The slot flipping is harder to capture, but the disappearing items happens 100% of the time I use the enchanter... See the video below.

**Video of the glitched slots:**
https://github.com/BlakeBr0/MysticalAgriculture/assets/44554976/df8126fa-75cd-44c5-bc77-2fe280255698

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.0
 - Cucumber: 7.0.8
 - Mystical Agriculture: 7.0.11
 - Singleplayer or Multiplayer: Multiplayer

**Comment by BlakeBr0** [comment]
So this is an unfortunate side effect that I didn't realize when making the enchanter (and I think the spawner) slots take in > 64 items. The screens are buggy but from what I can tell the actual inventories still work properly. From the bit of testing I did I wasn't able to cause a dupe.

I think slots were changed in 1.21 which may solve this, but I'm not really sure if I can reasonably fix this in 1.20 with my current implementation.

**Comment by Ferynix** [comment]
> So this is an unfortunate side effect that I didn't realize when making the enchanter (and I think the spawner) slots take in > 64 items. The screens are buggy but from what I can tell the actual inventories still work properly. From the bit of testing I did I wasn't able to cause a dupe.
> 
> 
> 
> I think slots were changed in 1.21 which may solve this, but I'm not really sure if I can reasonably fix this in 1.20 with my current implementation.

No worries. I'm pretty sure it was a rare bug, as it only happened once and I wasn't able to replicate it. (I used the enchanter a lot), so it's probably not a huge concern for the moment

**Comment by BlakeBr0** [comment]
This should no longer be the case in the 1.21 version.
