### ISSUE TITLE
not respawning with extra hearts

### ISSUE THREAD

**Issue by voltingshock** [BlakeBr0/MysticalAgriculture#689]
**Describe the bug**
After dying while wearing awakened supremium armor with absorption 5 and health boost 5, I respawn with my default heart amount (24) as opposed to the normal 44 I had with the augments, and with 24 absorption (the expected amount). Taking off the armor and putting it back on fixes it, but if I don't I don't get the health boost, even when taking damage / dying. 

**To Reproduce**
Awakened supremium with tier 5 absorption and health boost augments. No other augments, it didn't change when I swapped which piece of the armor had the augment. 

**Expected behavior**

I expected to keep the health boost when I respawn.

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).
There is nothing in the console when this is happening, just death messages as normal.

The modlist is absurdly long. I can post it, but its over 400 mods
**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.32
 - Cucumber: 7.0.8
 - Mystical Agriculture: 7.0.11
 - Singleplayer or Multiplayer: mp

**Comment by BlakeBr0** [comment]
You're using keep inventory correct?
