### ISSUE TITLE
EXP Capsule not working

### ISSUE THREAD

**Issue by nerostudios** [BlakeBr0/MysticalAgriculture#691]
Exp capsules do not receive or give EXP to players when right clicking or shift right clicking

Try to take exp out of the capsule

**Expected behavior**
"Experience can be manually added from the players experience to the Capsule by right-clicking it. Experience can also be taken from the Capsule and added to the players experience by shift-right-clicking it." - https://blakesmods.com/wiki/mysticalagriculture/items/experience-capsule

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.1.47
 - Cucumber: 1.19.2-6.0.3
 - Singleplayer or Multiplayer: Multiplayer

**Comment by BlakeBr0** [comment]
That functionality was added in the 1.20 version. I'll have to make that more clear in the docs.

**Comment by BlakeBr0** [comment]
Updated the wiki article with the version number.
