### ISSUE TITLE
Compat for Alchemistry Water

### ISSUE THREAD

**Issue by TheBedrockMaster** [BlakeBr0/MysticalAgriculture#692]
Add a recipe for Water from Alchemistry crafted with Water Essence. I think this would be a nice QoL feature, plus it makes sense.

**Comment by BlakeBr0** [comment]
Thanks for the suggestion. Unfortunately,, I think I'm pretty much set for built in mod integrations. I have to draw the line somewhere otherwise long term maintenance will get more difficult as I would have to keep up with any potential changes to more mods.
