### ISSUE TITLE
Game crashes when trying to load singleplayer world

### ISSUE THREAD

**Issue by nefariouslegion** [BlakeBr0/MysticalAgriculture#694]
**Describe the bug**
When trying to load my All The Mods 9 world save I get a crash to desktop. Looking at the crash log it seems it's being caused by my MA Flight Augment. However it was working fine up until today when the crashes started.

I did load a backup and it seemed to work. So for now I've removed my flight augment. But still hoping you can help me figure out what caused the issue so I can get my creative flight back

**To Reproduce**
No idea.

**Expected behavior**
I expected my world to load without crashing.

**Screenshots / Scripts / Logs**
Log can be found here https://mclo.gs/lF8zJS2

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.20
 - Cucumber: 7.0.8
 - Mystical Agriculture: 7.0.11
 - Singleplayer or Multiplayer: Singleplayer

**Comment by BlakeBr0** [comment]
Is this a repeatable issue? I'm not entirely sure how this could happen in the base mod. Did you add some kind of addon?

**Comment by nefariouslegion** [comment]
It kept happening until I loaded a backup. Then I removed the flight augment and haven’t had the issue since. This is on All The Mods 9. The ATM team looked at my logs and told me the flight augment was causing the issue
________________________________

**Comment by BlakeBr0** [comment]
Yeah. I'm not sure how that error could happen unless something is causing player ticking to be multi-threaded in some way? It's very odd considering nothing has really changed with the flight augment in a long time and no one else has reported having this crash.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
