### ISSUE TITLE
Scythes interact with crops wrong while in claimed chunks with specific settings.

### ISSUE THREAD

**Issue by VoidTest** [BlakeBr0/MysticalAgriculture#695]
**Describe the bug**
Any scythe while in a claimed chunk and with the "Block Edit Mode" set to private will freak out and any plant it tries to harvest will not break and just summon the resource. I imagine it would happen to any player who doesn't isn't on the team. in BaseScytheItem#useOn they call level.setBlockAndUpdate(aoePos, crop.getStateForAge(0)); to reset the crop without checking if the block should be updateable but forge is already in "block snapshot" mode, and afterwards will restore the block snapshot because the player didn't really have permission to update the block

**To Reproduce**
Claim a chunk with ftb chunks and set "Block Edit Mode" to private and "Allow All Fake Players" to true then place down a block at the level of the crop and a modular router on top. Have an activator module facing down inside the router and any scythe inside it too. This should allow for the bug to be replicated.

**Expected behavior**
With "Block Edit Mode" set to private the scythe should not be able to farm any crop in the claimed chunk.

**Screenshots / Scripts / Logs**
![2024-07-22_22 20 09](https://github.com/user-attachments/assets/815b638e-2c12-4c9b-93b2-3c2c356e1602)
![2024-07-22_22 20 05](https://github.com/user-attachments/assets/7216035c-5cf2-4c55-94cd-4d6d91616812)
![2024-07-22_22 20 00](https://github.com/user-attachments/assets/ae099174-a786-4fd4-bdf8-769c77b3d4ee)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.3.0
 - Cucumber: 7.0.9
 - Mystical Agriculture: 7.0.11
 - Singleplayer or Multiplayer: Singleplayer

**Comment by BlakeBr0** [comment]
This should be fixed in Cucumber 7.0.11
