### ISSUE TITLE
HarvesterTileEntity is missing a mapping

### ISSUE THREAD

**Issue by Waterspark63** [BlakeBr0/MysticalAgriculture#697]
**Describe the bug**
I'm still trying to figure this out a bit on my end, as this is on a server, and I haven't been able to get a time aligned with the player which I think is crashing the server. All I'm aware of at this moment, is the server will crash with the message:
'class com.blakebr0.mysticalagriculture.tileentity.HarvesterTileEntity is missing a mapping! This is a bug!'

**To Reproduce**
Undetermined at the moment, will update when I get more information soon.

**Expected behavior**
For the HarvesterTileEntity to have the mapping it's missing.

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).
[latest (2).log](https://github.com/user-attachments/files/16401953/latest.2.log)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.30
 - Cucumber: 7.0.9
 - Mystical Agriculture: 7.0.11
 - Singleplayer or Multiplayer: Multiplayer 
 - This is a large modpack: Moonlit's Lunar Colonies

**Comment by BlakeBr0** [comment]
I'm not really sure how this could happen. That error happens when a block entity type isn't registered for a block anymore, which should never be the case. Maybe there's a mod that's doing something problematic?

**Comment by Waterspark63** [comment]
Is there anything I can do/send to help try to figure this out? For the moment I'm just having players remove that block, as I'm unsure how to even reproduce this issue.

**Comment by BlakeBr0** [comment]
Not sure sorry. I can't think of a reason this would be caused by anything on my end.

**Comment by Waterspark63** [comment]
Closing the issue for now until I'm able to figure out how this is being caused.
