### ISSUE TITLE
Add Tags to Ores

### ISSUE THREAD

**Issue by TheBedrockMaster** [BlakeBr0/MysticalAgriculture#698]
**Describe the solution you'd like**
Add these item tags to ores

Prosperity Ore: forge:ores_in_ground/stone
Deepslate Prosperity Ore: forge:ores_in_ground/deepslate
Inferium Ore: forge:ores_in_ground/stone
Deepslate Prosperity Ore: forge:ores_in_ground/deepslate

**Comment by BlakeBr0** [comment]
Added in 6.0.15 for 1.19, 7.0.13 for 1.20. Will be added to 1.21 in the next release.
