### ISSUE TITLE
Game Crashing When Loading World

### ISSUE THREAD

**Issue by JackPants2** [BlakeBr0/MysticalAgriculture#699]
**Describe the bug**
Game Crashes when loading world

**To Reproduce**
Loading a world, likely caused by a mod conflict.

**Expected behavior**
I expected the game to launch normally, however it did not :(((((
**Screenshots / Scripts / Logs**
[crash-2024-08-10_17.40.12-server.txt](https://github.com/user-attachments/files/16571234/crash-2024-08-10_17.40.12-server.txt)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge:47.3.0
 - Cucumber:7.0.1.1
 - Mystical Agriculture: 7.0.0 - 7.0.12
 - Singleplayer or Multiplayer: Singleplayer

**Comment by BlakeBr0** [comment]
The crash log mentions mods `zetaimplforge` and `create_dd`. I don't see any mention of MA.

**Comment by Papaturts** [comment]
Same here, when I enable Mystical Agriculture
would loads fine without it, but once added it crashes with virtually the same crash log

edit: did some quick research, found on zetas tracker, seems it is create dreams and desires causing the issue
