### ISSUE TITLE
Mending enchant doesn't work on the Soulium Dagger

### ISSUE THREAD

**Issue by Rseding91** [BlakeBr0/MysticalAgriculture#7]
I enchanted the sword with the mending book and when killing things it never mends.

Is that intentional? If so, is it intentional that I was able to enchant it even though it does nothing?

**Comment by BlakeBr0** [comment]
Which Minecraft version are you on?

**Comment by BlakeBr0** [comment]
Mending is working just fine for me

**Comment by Rseding91** [comment]
1.10.2 using mysticalagriculture[1.10.2]-1.3.8a

**Comment by BlakeBr0** [comment]
Seems to work fine for me.

**Comment by Rseding91** [comment]
I figured out what it was: The "Ring O' Experience" from the mod "Experience Rings" bypasses the normal XP pickup and causes mending to not work.

So, nothing wrong with your mod :) sorry for the trouble.

**Comment by BlakeBr0** [comment]
Glad you figured it out :)
