### ISSUE TITLE
Crops missing `minecraft:crops` tag

### ISSUE THREAD

**Issue by diefesson** [BlakeBr0/MysticalAgriculture#700]
**Describe the bug**
Tinker's Construct Scythe is not working with Mystical Agriculture crops in 1.19.2

**To Reproduce**
Right click Mystical Agriculture crops with a Tinker's Construct scythe

**Expected behavior**
Scythe should should harvest and replant crops

**Screenshots / Scripts / Logs**
Not applicable

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.4.2
 - Cucumber: 6.0.10
 - Mystical Agriculture: 6.0.14
 - Singleplayer or Multiplayer: single-player

**Additional Information**
It worked fine in 1.18.2
May be related to changes introduced in #569

**Comment by diefesson** [comment]
@KnightMiner, did Scythe crop check behavior change?

**Comment by diefesson** [comment]
# 1.19.2 Tags

![2024-08-12_11 08 30](https://github.com/user-attachments/assets/8523752b-0cf8-4604-baaa-cfdb91398ce2)

# 1.18.2 Tags

![2024-08-12_14 16 20](https://github.com/user-attachments/assets/c65fef29-4431-47cb-b1cd-18051372a164)

Seems like changes introduced in #569 are not present in the 1.19.2 release

**Comment by diefesson** [comment]
Using KubeJS to add the tags fixed the problem

``` js
ServerEvents.tags('item', event => {
    event.add('forge:seeds', '#mysticalagriculture:seeds')
})

ServerEvents.tags('block', event => {
    event.add('minecraft:crops', '#mysticalagriculture:crops')
})
```

**Comment by BlakeBr0** [comment]
I guess I forgot to add that tag in later versions.

**Comment by BlakeBr0** [comment]
Added in 6.0.15 for 1.19, 7.0.13 for 1.20 and 8.0.0 for 1.21
