### ISSUE TITLE
Neoforge 1.21.1 Crash

### ISSUE THREAD

**Issue by aAndrew3030** [BlakeBr0/MysticalAgriculture#702]
The game crashes when I make a seed and try to remove it from the alter. It seems like it may be crashing while rendering the tooltip (I am using Jade)

 
[crash-2024-08-19_20.07.42-client.txt](https://github.com/user-attachments/files/16667082/crash-2024-08-19_20.07.42-client.txt)

**Comment by whatthedrunk** [comment]
Yeah, I get the same crash testing for ATM10. I also had to grab cucumber on modrinth because it was not showing up on Curseforge. Also, when you mine the ores the drop like they are silk touched.

**Comment by BlakeBr0** [comment]
![image](https://github.com/user-attachments/assets/6e7e83ee-2e47-4171-86c8-ed602043b527)
