### ISSUE TITLE
[1.11.2] Iridium Ore Typo

### ISSUE THREAD

**Issue by nicuch** [BlakeBr0/MysticalAgriculture#71]
Iridium Ore Seed are called Uranium Ore Seed (and a second Uranium 235 Seed exist)

**Comment by BlakeBr0** [comment]
What do you mean "a second uranium 235 seed exist" ?

**Comment by nicuch** [comment]
So is 'Uranium 356 Seed' wich is actualty Uranium Seed that makes Uranium and 'Uranium Seed' wich is Iridium Seed that makes Iridium.
