### ISSUE TITLE
Enchanter table not working

### ISSUE THREAD

**Issue by Jeurdan** [BlakeBr0/MysticalAgriculture#710]
![Screenshot 2024-08-27 054452](https://github.com/user-attachments/assets/b941a7a7-e2fa-49b1-89fe-fb427a316a74)

**To Reproduce**
Steps to reproduce the behavior: Just in general

**Expected behavior**
Getting the enchanted item

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.21.1
 - Forge: Neoforge latest
 - Cucumber: 1.21.1 8.02
 - Mystical Agriculture: Latest as of now
 - Singleplayer or Multiplayer: Multi

**Comment by Jeurdan** [comment]
Tested it with just the mod and cucumber, still doesn't enchant.

**Comment by Jeurdan** [comment]
Logging in and out for a long time (i don't know if this augment is permanent) also, causes the augment strength 3 to disappear from my suprmium sword.

**Comment by Adrriii** [comment]
This doesn't look fixed, I've tried 8.0.4, 8.0.5 and the latest 8.0.6 and can't get anything using the Enchanter
