### ISSUE TITLE
Enchanter doesnt work in MC 1.21.1

### ISSUE THREAD

**Issue by Saereth** [BlakeBr0/MysticalAgriculture#714]
<img width="474" alt="image" src="https://github.com/user-attachments/assets/4c28520b-6d01-4202-8fab-fa9e8ebbc229">
<img width="387" alt="image" src="https://github.com/user-attachments/assets/ae76ad90-4b8e-49b5-bf8a-4e75f5e497ba">

**Versions (please complete the following information):**
 - Minecraft: 1.21.1
 - NeoForge: 21.1.31
 - Cucumber: Cucumber-1.21.1-8.0.3
 - Mystical Agriculture: MysticalAgriculture-1.21.1-8.0.4
 - Singleplayer or Multiplayer: Both

**Comment by HNGamingUK** [comment]
Can confirm I am getting the same above on All The Mods 10 v0.40.

**Comment by TheMightyMcGrew** [comment]
the same issue is present in 1,20.1 as well

**Comment by BlakeBr0** [comment]
#710
