### ISSUE TITLE
Supremium Chestplate losing augment Functionality/Entirely Removing augments from chestplate

### ISSUE THREAD

**Issue by 7Kav** [BlakeBr0/MysticalAgriculture#715]
**Describe the bug**
Supremium Chestplate removing augment functionality and sometimes entirely wiping augments from existance
**To Reproduce**
1: Use chestplate for awhile
2: Relog and chestplate augment will disappear (not very consistant)

**Expected behavior**
Augments to not disappear from chestplate and remove functionality

**Screenshots / Scripts / Logs**
https://streamable.com/zzbdny
This video shows the disappearing augments. I cannot get a video of the chestplate augment being wiped due to it being a very random and unlikely scenario 

**Versions (please complete the following information):**
 - Minecraft: 1.21.1
 - Forge: NeoForge Version: 21.1.37
 - Cucumber: 8.0.3
 - Mystical Agriculture: 8.0.4
 - Singleplayer or Multiplayer: Multiplayer Server (hosted on a linux machine)

**Comment by 7Kav** [comment]
To add an extra comment. this was on the modpack ATM 10 and the video was recorded when the modpack version was 10.0.39. I managed to have the bug repeat on versions 10.0.41 also

**Comment by BlakeBr0** [comment]
#711
