### ISSUE TITLE
Creative only new NBT bug

### ISSUE THREAD

**Issue by EneroPrime** [BlakeBr0/MysticalAgriculture#716]
**Describe the bug**

Not sure.

**To Reproduce**

When I copy NBT of a tiered, hopper botany pot with a seed and a farmland in it and then I place it the things that come out of it doesn't stack up with the other ones.

**Expected behavior**

Same NBT ig

**Screenshots / Scripts / Logs**

![image](https://github.com/user-attachments/assets/d75871e1-4740-4d2a-9f68-820339f660dd)

**Versions**
Minecraft 1.20.1
ATM9 newet version

**Comment by BlakeBr0** [comment]
These items don't have any NBT by default so I would assume another mod is adding something.
