### ISSUE TITLE
neutronium from avaritia

### ISSUE THREAD

**Issue by Guymito** [BlakeBr0/MysticalAgriculture#717]
there is a missing crafting where you can make neutronium seed and get the essence but you can not make the neutronium bar, in case of question the neutronium is from avaritia

**Comment by BlakeBr0** [comment]
A 3x3 of Neutronium essence should make nuggets, does it not?

**Comment by Guymito** [comment]
just tryed that and don't worked, i think maybe its the version i'm using the 1.20.1, thanks for the response anyway, i just make a bunch of neutroniu colector whit hoppers sendig to a chest, thanks for all

**Comment by BlakeBr0** [comment]
There appears to be multiple forks of Avaritia for 1.20. Which one are you using?

**Comment by BlakeBr0** [comment]
Latest Agradditions release fixes this issue.
