### ISSUE TITLE
farmland craft with hoe bug

### ISSUE THREAD

**Issue by Harrix31** [BlakeBr0/MysticalAgriculture#719]
when you craft farmland with a hoe you can only craft one and the hoe breaks no matter the material

normal result:
1 Supremium hoe + 64 dirt + 64 Inferium Essence = 1 Supremium hoe + 64 inferium farmland

craft:
![Capture d'écran 2024-09-03 211446](https://github.com/user-attachments/assets/7805ccee-a561-4de1-ac74-003a35a5b842)

result without bug (test 1.19.4):
![Capture d'écran 2024-09-03 211644](https://github.com/user-attachments/assets/6f6afceb-3c7d-442b-bc40-f37e73a53a85)

with bug:
![Capture d'écran 2024-09-03 211600](https://github.com/user-attachments/assets/5a2171a6-7909-45e2-8c42-3a9a58b70bf9)

 - Minecraft: 1.21
 - NeoForge: 21.0.167
 - Cucumber: 1.21.1-8.0.1
 - Mystical Agriculture: 1.21.1-8.0.4
 - Singleplayer or Multiplayer: Singleplayer

**Comment by DragonScope** [comment]
Currently having this issue as well. Few days ago perfectly fine now it’s bugged again and it sucks.
