### ISSUE TITLE
[Suggestion] Dispensers plant seeds

### ISSUE THREAD

**Issue by nicuch** [BlakeBr0/MysticalAgriculture#72]
Dispensers can plant seeds, carrots and potatoes, what about mystical seeds too?

**Comment by Knito58** [comment]
The Quark mod already has this feature for vanilla seeds. Maybe they are willing to extend this for MA when asked so?

**Comment by BlakeBr0** [comment]
Don't know if I'll add this, considering dispensers planting seeds isn't a vanilla mechanic, so it'll be a bit inconsistent.

**Comment by Knito58** [comment]
If you would do this, you could also implement a farming device. This means: Automation. Which probably is **not** the topic of this mod. As I said, there are other mods which cover the gap. In example Actually Additions has a farming block which is fun to make and very reliable. It plants and harversts MA crops - nothing left over on the wish list.
