### ISSUE TITLE
Steel Seeds Recipe Missing in ATM 10 Modpack 1.21.1

### ISSUE THREAD

**Issue by TheEnderHacker** [BlakeBr0/MysticalAgriculture#720]
**Describe the bug**
In the ATM 10 modpack (version 1.21.1), there is an issue where steel seeds cannot be crafted through normal means. Although steel essence can be obtained, there is no recipe to convert steel essence into steel, and the steel seeds can only be obtained through Creative mode. Other seeds appear to function correctly.

**To Reproduce**

1. Attempt to craft steel seeds using the appropriate materials at the Infusion Altar.
2. Check EMI to see if the recipe for steel seeds is listed.
3. Attempt to craft the seeds at the Infusion Altar and observe that it does not work.

**Expected behavior**
There should be a recipe for crafting steel seeds available, allowing them to be crafted at the Infusion Altar without the need to use Creative mode.

**Versions:**

- Modpack Version: 1.21.1 (All the Mods 10-0.44)
- Neoforge Version: 21.1.34
- Mystical Agriculture: 1.21.1-8.0.4
- Singleplayer or Multiplayer: Multiplayer

**Comment by BlakeBr0** [comment]
Does the pack have a value  set for `c:ingots/steel`?

**Comment by BlakeBr0** [comment]
I just tested on 10-0.47 and there was recipe for Steel Ingot from alltheores. Is this the case for you as well?

**Comment by TheEnderHacker** [comment]
Steel ingots do exist, but I'm only talking about the steel seeds and essences, which can't be crafted in ATM10

**Comment by TheEnderHacker** [comment]
But it could also be that ATM10 removed them, which I would find strange.

**Comment by DaddyLongspoon** [comment]
the seeds and essence are still most definitely in the pack.  I made the steel seeds early on, had to make steel ingot from some obscure mod I've not played with before, and the essence was crafting to that same steel back then too.  Then there was some more work dictionarying all the metal and gem types again and that steel was removed, it was at that time that atm team broke the steel seed (and a couple others too, uranium for one) so you can't make it anymore..  I still have steel seed and the essence still grows and it now crafts to alltheores:steel_ingot.   This bug is in atm10 implementation and not in MA.

**Comment by BlakeBr0** [comment]
I just tested again and yeah it seems like the seeds aren't craftable. I'm guessing it has to do with the `mysticalagriculture:crop_has_material` checks in the seed recipes and their modifications causing the tags to be empty when the recipes are registered. Has this been reported to them yet?

**Comment by TheEnderHacker** [comment]
I haven't reported it yet, but I'll look into submitting it if no one else has done so already.

**Comment by PonyWarrior** [comment]
will this be fixed? I have the same issue

**Comment by BlakeBr0** [comment]
Just tested in ATM 10 0.60 and the recipe appears to be working.

**Comment by TheBedrockMaster** [comment]
> Just tested in ATM 10 0.60 and the recipe appears to be working.

Note: Some seed recipes in ATM10 are still using the wrong version of materials (EnderIO Silicon instead of AE, etc), so they can't be made in survival.
