### ISSUE TITLE
Seed Reprocessor does not output from bottom

### ISSUE THREAD

**Issue by StyLexR6** [BlakeBr0/MysticalAgriculture#721]
The seed reprocessor happily accepts seeds from the top, but can't extract from any side, including the bottom.
This includes using Pipez, Mekanism, and Hopper. Specifically ATM 10 0.45 if that helps. 

Steps to reproduce the behavior: Put seeds in the reprocessor, it processes, then can't output.

It should output with one of the pipes or hopper.

Pipez
![image](https://github.com/user-attachments/assets/a24fc2ab-4592-4833-9828-5ee8e7198c35)
Mekanism
![image](https://github.com/user-attachments/assets/b8b24aac-e630-4ed6-ba1c-4a3afb935920)
Minecraft
![image](https://github.com/user-attachments/assets/cba4b051-aef2-4405-a5a4-a8ddc5923235)

 - Minecraft: 1.21
 - NeoForge: 21.1.37
 - Cucumber: 8.0.3
 - Mystical Agriculture: 8.0.4
 - Singleplayer or Multiplayer: Multiplayer
 
 Fake players are enabled and permitted in the plot, no issues with any other storage movements or mods.

**Comment by BlakeBr0** [comment]
Should be fixed with Cucumber 8.0.4
