### ISSUE TITLE
Chisel compat not working with latest version

### ISSUE THREAD

**Issue by pietro-lopes** [BlakeBr0/MysticalAgriculture#722]
**Describe the bug**
Recipe is erroring.

**To Reproduce**
Install latest <https://www.curseforge.com/minecraft/mc-mods/chisel-reborn>

Those recipes have invalid items:
<https://github.com/BlakeBr0/MysticalAgriculture/tree/1.21/src/main/resources/data/mysticalagriculture/recipe/essence/chisel>

**Expected behavior**

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.21.1
 - Forge: 21.1.42 (Neo)
 - Cucumber: 8.0.4
 - Mystical Agriculture: 8.0.5
 - Singleplayer or Multiplayer: Both

**Comment by BlakeBr0** [comment]
Doesn't seem like they add any of the blocks for those recipes anymore. I guess I'll just remove them.
