### ISSUE TITLE
Infinite Infusion Crystal

### ISSUE THREAD

**Issue by Caltinor** [BlakeBr0/MysticalAgriculture#724]
**Describe the bug**
When crafting higher tier essence with the basic Infusion Crystal, the crystal will continue to work even after all durability is consumed.

**To Reproduce**
1. Create a new world with only NeoForge, MA, and cucumber
2. give yourself a crafting table, 64 inferium essence, and `/give @s mysticalagriculture:infusion_crystal[minecraft:damage=998]`
3. craft one prudentium essence to see the durability decrease to zero
4. craft as many more predentium essence as you want and see the bug.

**Expected behavior**
the infusion crystal either breaks or stops working once all durability is consumed

**Screenshots / Scripts / Logs**
zero durability crystal (before)
![MA-zeroDur](https://github.com/user-attachments/assets/9c819a24-7d92-464a-8124-097ad28da613)
zero durability crystal (after crafting one more time)
![MA-zeroDur+1](https://github.com/user-attachments/assets/37e36cee-a013-45c5-9545-67691201f5b7)

**Versions (please complete the following information):**
 - Minecraft: 1.21
 - NeoForge: 21.1.49
 - Cucumber: 8.04
 - Mystical Agriculture: 8.05
 - Singleplayer or Multiplayer: Singleplayer

**Comment by BlakeBr0** [comment]
Fixed in Cucumber 8.0.5
