### ISSUE TITLE
[Question] Limiting the harvesting area of a Harvester

### ISSUE THREAD

**Issue by HrPlanlos** [BlakeBr0/MysticalAgriculture#729]
Hi, I wanted to ask if there is a way to limit the harvesting range of a Harvester.

Background is that I would like to grow and harvest seeds as fast as possible without having to consider the range of the Machine Upgrades. I am a fan of only harvesting one type of seed per Harvester and field without having to build the field huge for maximum speed or building the fields far from each other.

**Comment by BlakeBr0** [comment]
There is not a way to do that. I don't think I'll be adding this since the Harvester is meant to be a bit more rudimentary than some from other mods.
