### ISSUE TITLE
No seed from inferium crop

### ISSUE THREAD

**Issue by Knito58** [BlakeBr0/MysticalAgriculture#73]
MC 1.12
Forge 14.21.1.2395
MA 1.6.0

When the Actually Additions Farmblock harvests the inferium crop, it is simply destroyed. Ok, it gives an essence. But never a seed. When I harvest it by hand the same thing happens.
So the crop is useless at that point, as it costs a lot of essences but gives only one back on harvest time and then it is lost.

In the config I could not find the entry concerning the percentage of seed drops.

**Comment by Knito58** [comment]
MA 1.6.1

Yay! It works! Bug squished.
Thank you.

**Comment by BlakeBr0** [comment]
Sweet 👍
