### ISSUE TITLE
No cognizant dust dropped when killing the wither

### ISSUE THREAD

**Issue by M4RC0Sx** [BlakeBr0/MysticalAgriculture#730]
**Describe the bug**
I am killing the Wither with a Supremium Sword enchanted with mystical enlightement 5. When the wither dies, it only drops nether star.

**To Reproduce**
Same as description.

**Expected behavior**
The wither should drop some cognizant dust.

**Screenshots / Scripts / Logs**
Not applicable.

**Versions (please complete the following information):**
 - Minecraft: 1.21.1
 - Forge: Neoforge  21.1.54
 - Cucumber: 1.21.1-8.0.5
 - Mystical Agriculture: 1.21.1-8.0.6
 - Singleplayer or Multiplayer: Multiplayer

**Comment by BlakeBr0** [comment]
I'm guessing you're playing ATM 10? They had the Wither dropping dust disabled but it seems to be enabled in the latest version 0.60.

**Comment by TheBedrockMaster** [comment]
Yeah, it's a config. It was turned back on in ATM10 recently.
