### ISSUE TITLE
Cannot manually store xp inside the Experience Capsule past current level anymore

### ISSUE THREAD

**Issue by Adrriii** [BlakeBr0/MysticalAgriculture#731]
**Describe the bug**
When right-clicking, the tank fills up with the remaining experience of the current level. When right-clicking again, instead of going down a level and using the xp, nothing happens.

I remember previously completely draining my xp levels to fill another capsule earlier, so the bug might need special conditions to happen.

Restarting the game does not fix it.

Note: Gaining XP still correctly fills the container.

**To Reproduce**
Have any level above 1, and try to fill the capsule by draining entire levels.
This may need a prerequisite, since this previously worked on my save. These are the (maybe) relevant steps I did between when it worked, and when I noticed it didn't work anymore : 
- Crafting an experience seed using the altar
- Unlocking experience seeds related quest rewards
- Crafting/Consuming experience droplets 

**Expected behavior**
The capsule should fill by consuming the levels, not only the remains of the current XP level.

**Screenshots / Scripts / Logs**
Video: https://adri-web.dev/mp4/2024-09-21%2023-42-47.mp4

**Versions (please complete the following information):**
 - Minecraft: 1.21.1
 - Forge: neoforge 21.1.47
 - Cucumber: 
 - Mystical Agriculture: 1.21.1-8.0.4
 - Singleplayer or Multiplayer: Singleplayer

And notably:
- ATM 10 0.52
- Mystical Aggraditions 1.21.1-8.0.0
- Mystical Customization 1.21.1-6.0.0

**Comment by Adrriii** [comment]
Similarily, for the opposite action, sometimes it's stuck just below the next level : 
https://adri-web.dev/mp4/2024-09-22%2011-12-23.mp4

**Comment by Bocch** [comment]
Sorry I have the same problem and conditions, but I didn't get how to solve it, could someone help me?

**Comment by jerryjjr** [comment]
Yes, this bug is still present in 1.21.1-8.0.10

**Comment by BlakeBr0** [comment]
I've made some additional changes in 8.0.12 for this. Let me know if it's fixed.

**Comment by ChooseJake** [comment]
Issue is still present for me however oddly enough only when at level 69(nice). Works fine on level 70 and onwards as well as levels 68 and below. Seriously, only on 69. Valentine's day was a week ago... is the mod trying to tell us something?
