### ISSUE TITLE
Can't craft some seeds when using both Mystical Agriculture and Ender IO

### ISSUE THREAD

**Issue by CRUSADER-jp** [BlakeBr0/MysticalAgriculture#739]
**Describe the bug**
When play Minecraft with install both Mystical Agriculture and Ender IO, I can't craft some seeds.
As far as I confirmed, below seeds recipe were disabled.
- Iron Seeds
- Gold Seeds
- Diamond Seeds
- Tin Seeds
- Lead Seeds
Probably other some ores Seeds recipe will affected by this issue.

**To Reproduce**
1. Add below mods
- Mystical Agriculture
- Cucumber Library
- Ender IO(6.2.0-beta)
- Just Enough Items (JEI)(for confirm recipe)
2. launch Minecraft and create new world
3. Check craft recipe using JEI
4. Some other Seeds(Stone Seeds, Ice Seeds) craft recipe can confirm, but Iron Seeds and some other Seeds recipe can't confirm.
5. Also, these Seeds can't craft when try to craft.

**Expected behavior**
Can craft these Seeds.

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.3.10
 - Cucumber: Cucumber-1.20.1-7.0.12
 - Mystical Agriculture: MysticalAgriculture-1.20.1-7.0.14
 - Singleplayer or Multiplayer: Singleplayer

**Comment by muggleorwizard** [comment]
Can confirm as well for MA 1.20.1-7.0.14. List of seeds that have missing recipes:
- Apatite
- Saltpeter
- Aluminum
- Sulfur
- Silicon
- Iron
- Nether Quartz
- Glowstone
- Redstone
- Tin
- Bronze
- Silver
- Lead
- Graphite
- Certus Quartz
- Gold
- Lapis
- Steel
- Nickel
- Constantan
- Electrum
- Invar
- Uranium
- Ruby
- Sapphire
- Signalum
- Lumium
- Osmium
- HOP Graphite
- Fluorite
- Refined Glowstone
- Refined Obsidian
- Compressed Iron
- Fluix
- Diamond
- Emerald
- Enderium
- Draconium
- Yellorium
- Cyanite

**Comment by Rover656** [comment]
It looks like this is a problem on EnderIO's end - I am working on finding out why. Thanks folks.

**Comment by Rover656** [comment]
This issue has been fixed in Ender IO 6.2.1-beta and can be closed. Thanks.

**Comment by CRUSADER-jp** [comment]
@Rover656 I confirmed that we can craft iron and some material's seeds after update EnderIO 6.2.1. Thank you!
