### ISSUE TITLE
1.21.1 Seed reprocessor sidedness is wron

### ISSUE THREAD

**Issue by Saereth** [BlakeBr0/MysticalAgriculture#740]
**Describe the bug**
The seed reprocessor accepts any items from any slot

**To Reproduce**
Hopper coal into the top, side or back of the reprocessor, it will go into the seed slot. 

**Expected behavior**
The seed slot should only accept seeds and the fuel slot only valid fuels and/or be sided like a vanilla furnace

**Versions (please complete the following information):**
 - Minecraft:1.21.1
 - NeoForge: 21.1.66
 - Cucumber:Cucumber-1.21.1-8.0.6.jar
 - Mystical Agriculture:MysticalAgriculture-1.21.1-8.0.7.jar
 - Singleplayer or Multiplayer:Both

**Comment by BlakeBr0** [comment]
Closing in favor of #750
