### ISSUE TITLE
I don’t appreciate the color orange

### ISSUE THREAD

**Issue by Eirekate** [BlakeBr0/MysticalAgriculture#741]
Dear Mr Blake, 

After hours of grinding farming, mining and withers, I was able to awaken the armor that I worked for on for 4 real life days. Only to find out that’s when you actually put in on it’s not even RGB or sometimes orange sometimes red. It’s just orange. 

Now, to say I was disappointed was an understatement but the armor has so much perks I’m stuck looking like a pumpkin. I could’ve lived with that. 

Then I downloaded your new dependency and got so psyched to see PURPLE essence… just to find out you can’t even make tools out of that sh*t. I’ll forgive you I’ll forgive you it makes sense. 

However, my request now is that if you aren’t going to change the awakened to a better color, atleast make the armor dyeable, because I just really despise orange.

Also, sorry if that’s your favorite color man and I really love this mod pack!

Thanks for reading, 
Sincerely, 
-E

**Comment by TheBedrockMaster** [comment]
Issue: I don't like orange

Also what modpack are you talking about?

**Comment by BlakeBr0** [comment]
You or someone else can always make a texture pack.
