### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by gjmhmm8** [BlakeBr0/MysticalAgriculture#743]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft:
 - Forge:
 - Cucumber:
 - Mystical Agriculture:
 - Singleplayer or Multiplayer:
[crash-2024-10-17_07.30.26-client.txt](https://github.com/user-attachments/files/17404088/crash-2024-10-17_07.30.26-client.txt)

**Comment by gjmhmm8** [comment]
ATM9

**Comment by BlakeBr0** [comment]
Is this happening consistently?

**Comment by gjmhmm8** [comment]
Putting on the breastplate and installing the corresponding upgrade has a chance to cause a crash.

**Comment by BlakeBr0** [comment]
Which augment specifically? Flight?

**Comment by gjmhmm8** [comment]
Absorption or Health Boost

**Comment by gjmhmm8** [comment]
at com.blakebr0.mysticalagriculture.augment.HealthBoostAugment.onPlayerTick(HealthBoostAugment.java:54) ~[MysticalAgriculture-1.20.1-7.0.12.jar%23873!/:7.0.12] {re:classloading}

**Comment by BlakeBr0** [comment]
Version 7.0.15 should contain a fix for this. Let me know if the problem still occurs with it.
