### ISSUE TITLE
Wierd Seed Duplication BUG

### ISSUE THREAD

**Issue by TheAssassin96** [BlakeBr0/MysticalAgriculture#744]
**Describe the bug**
You can place infinite amount of seeds with one seed

**To Reproduce**
harvest a Seed , and place it infinitly

**Expected behavior**
you can place only ones

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 1.19.2.43.4
 - Cucumber: 6.011

 - Mystical Agriculture: 6.015
 - Singleplayer or Multiplayer: single player 
 
 Video showing the glitch
https://github.com/user-attachments/assets/606232fe-c4ed-4cc0-bdc8-ac4ab2e95129

**Comment by BlakeBr0** [comment]
I feel like this could be caused by another mod. Can you reproduce this with just MA?

**Comment by TheAssassin96** [comment]
no i dont think so

**Comment by TheAssassin96** [comment]
so i think its a mod incompatibility
