### ISSUE TITLE
transparent ores

### ISSUE THREAD

**Issue by VaporeonScripts** [BlakeBr0/MysticalAgriculture#749]
![image](https://github.com/user-attachments/assets/9462e5bb-2980-4466-9553-94aab2e12efa)
https://mclo.gs/7Fxtaxm
**Versions (please complete the following information):**
 - Minecraft: 1.21.1
 - Forge: neoforge .77
 - Cucumber: latest
 - Mystical Agriculture: latest
 - Singleplayer or Multiplayer: both

**Comment by BlakeBr0** [comment]
Does this happen with just MA installed? Could be an issue with another mod you have added.

**Comment by VaporeonScripts** [comment]
Resource pack error replacing stone texture,not caused by this mod
