### ISSUE TITLE
No End Prosperity Ore

### ISSUE THREAD

**Issue by EmosewaGamer** [BlakeBr0/MysticalAgriculture#75]
I'm not sure after which version it was, but at some point End Prosperity Ore stopped spawning. It doesn't spawn neither in version 1.11.2, nor version 1.12. It probably hasn't been noticed as I'm sure that only in pack the only way to obtain Prosperity Shards is trough the End Ore. And in the config it is set to spawn.

**Comment by BlakeBr0** [comment]
Just submitted hotixes for all versions that should fix this.

**Comment by BlakeBr0** [comment]
It was actually generating just fine, except for the fact it was generating inferium ore instead. ;v
