### ISSUE TITLE
Seed Reprocessor cannot be automated 

### ISSUE THREAD

**Issue by Draskh** [BlakeBr0/MysticalAgriculture#750]
**Describe the bug**
Seed Reprocessor has no locked Inventory slots making it get jammed with fuel.
Usually, machines like vanilla furnace have a behaviour that makes their slots bound to a specific side when automated. 
The Seed Reprocessor, however, accepts fuel from all sides making it impossible to automate. 
As soon as seeds for reprocessing run out, fuel blocks the machine's input. 

**To Reproduce**
1. place a Seed Reprocessor
2. place a hopper on top, place a hopper on the side.
3. fill the top hopper with 32 seeds
4. fill the side hopper with 64 coal

**Expected behavior**
Usually, machines have a vanilla mechanism like a furnace or their slots are locked to their respective items

**Screenshots / Scripts / Logs**
![2024-11-17_18 59 26](https://github.com/user-attachments/assets/7d3b81e6-0f5e-464c-aa01-6c5d574ef016)

**Versions (please complete the following information):**
 - Minecraft :1.21.1
 - Forge: Neoforge 21.1.73
 - Cucumber: 8.0.7
 - Mystical Agriculture: 8.0.7
 - Singleplayer or Multiplayer: both

**Comment by BlakeBr0** [comment]
Fixed in version 8.0.8 of Cucumber.
