### ISSUE TITLE
Recipe Conflict with Rabbit Essence

### ISSUE THREAD

**Issue by alfredggttv** [BlakeBr0/MysticalAgriculture#754]
**Describe the bug**
Rabbit Essence recipes are all the same for each product.

**To Reproduce**
1. Make Rabbit Essence.
2. Try to make Rabbit Hide, Foot, or Raw Rabbit.
3. Recipes Conflict

**Expected behavior**
Separate Recipes for each

**Screenshots / Scripts / Logs**
![image](https://github.com/user-attachments/assets/ac6b046d-f3f2-44d3-a927-19fa1d439b33)

**Versions (please complete the following information):**
 - Minecraft: 1.21.1
 - NeoForge: 21.1.80
 - Cucumber: 1.21.1-8.0.8
 - Mystical Agriculture: 1.21.1-8.0.9
 - Singleplayer or Multiplayer: Both

**Comment by BlakeBr0** [comment]
It never ends
