### ISSUE TITLE
Furnace expose input slot as output, input mixed with fuel slot

### ISSUE THREAD

**Issue by Kenshij** [BlakeBr0/MysticalAgriculture#755]
The new furnace expose its input slot as output slot, so a connected pipe pulls the uncooked input out. And pushing into furnace fills first input and then fuel slot.
The furnace should not let a pipe pull from other slots the output. It should have the same pull/push mechanic like vanilla furnace. Top=input, bottom=output, side=fuel. NOT all sides=all slots. 

**Versions (please complete the following information):**
 - Modpack: Opolis Inc 
 - Minecraft: 1.21.1
 - Forge: Neoforge 21.1.61
 - Cucumber: 1.21.1-8.0.6
 - Mystical Agriculture: 1.21.1-8.0.7
 - Singleplayer or Multiplayer: SMP

**Comment by BlakeBr0** [comment]
This should've been fixed with Cucumber 8.0.8.
