### ISSUE TITLE
crafting bug for updated crazy craft

### ISSUE THREAD

**Issue by CosmicEntertain** [BlakeBr0/MysticalAgriculture#759]
**Describe the bug**
Crafting bug where "thermal series ruby" turns into "chaos awakens ruby" after crafting with essence but thermal series ruby isn't shown in the JEI config as item or ore where in your inventory its on the right side, but i only have the ruby from chaos awakens.
**To Reproduce**
Try to craft seeds for ruby
**Expected behavior**
Wanted to get the ruby seeds but it doesn't even show the ruby from thermal series is in here. but the one of chaos awakens is here but I can't craft with it.
**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).
![Screenshot 2024-12-16 233726](https://github.com/user-attachments/assets/26d6685f-288e-4a49-8f05-087510b53c6a)
![Screenshot 2024-12-16 233736](https://github.com/user-attachments/assets/8af96e68-c614-4e30-8840-e81039ce2cd9)
![image](https://github.com/user-attachments/assets/ac115ffc-7c05-4074-b830-7831f7576c31)
**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.3.35
 - Cucumber: image below
 - Mystical Agriculture: image below
![image](https://github.com/user-attachments/assets/95abd0cd-29e6-4624-80d5-c5989d9a38f7)
![image](https://github.com/user-attachments/assets/85e06396-988c-4ded-828d-4cd0542a9e6b)
 - Singleplayer or Multiplayer: Both
 - modpack is 
![image](https://github.com/user-attachments/assets/447c2f62-0dff-4581-ae8f-2248fd8d758b)
 - only added essential to play multiplayer

**Comment by CosmicEntertain** [comment]
also no ore generation
![image](https://github.com/user-attachments/assets/873d6d22-37f9-4c16-a897-c79a559265e6)
compared to ore gen for the other one
![image](https://github.com/user-attachments/assets/4ebc10a6-7478-4ed4-b396-078b54e2e70b)

**Comment by CosmicEntertain** [comment]
only way around it is both of above orechid and maybe lazer drill :|

**Comment by BlakeBr0** [comment]
You'll have to report this to the modpack developers as it's a configuration issue.
