### ISSUE TITLE
[Suggestion] Blocks

### ISSUE THREAD

**Issue by CrazyLewis** [BlakeBr0/MysticalAgriculture#78]
Hello

I want to suggestion when you put superium blocks into a crafting table instead of getting the superium essence maybe have a pattern recipe for intermedium blocks kind of like how the dye essence is setup for crafting, this would be a great recipe for when I need to craft the furnace or any other items it is used in for other mods like tinkers Tool Forge.

Many thanks

-Lewis

**Comment by BlakeBr0** [comment]
Probably not, you can always use things like auto-crafting tables to speed up crafting. Or you can add your own recipes using CraftTweaker.
