### ISSUE TITLE
[Suggestion/Request] Recipe book

### ISSUE THREAD

**Issue by TheSnowyChickens** [BlakeBr0/MysticalAgriculture#79]
Hello
is it possible , that you add the vanilla recipe book integration ?
It is the best and easiest way to craft a lot of essence into e.g. Diamonds or other ,without JEI mod. :)

I hope you can implement it.

Thx

**Comment by BlakeBr0** [comment]
This is going to be a work in progress while I slowly convert recipes to the new system. I'm gonna try to made sure to convert some recipes to json each update, so they should eventually all work.

I might not be able to get recipes for things like diamond essence to work as I have to register those recipes a bit later than normal recipes.

**Comment by TheSnowyChickens** [comment]
That sounds good , thanks. :)

**Comment by BlakeBr0** [comment]
I have come to the conclusion after all these years that json is the bane of my existence, and therefor I won't be converting any more recipes in the 1.12 version.

All recipes that can be json will be in 1.13 though.
