### ISSUE TITLE
Infinite use on regular Infusion Crystal when used in RS

### ISSUE THREAD

**Issue by gefailter71** [BlakeBr0/MysticalAgriculture#80]
MC version: 1.12
MysticalAgriculture version: 1.6.1a
RefinedStorage version: 1.5.13

When the Infusion crystal is used in the RS crafting grid with 0 durabilities it won't break but will be usable again after taking it out and putting it back into the crafting grid. Not sure if that is because we changed the durability on the server to 250 or not.

**Comment by BlakeBr0** [comment]
I've never been able to reproduce this. Are the configs on the client and server the same?
