### ISSUE TITLE
[1.12] Can't extract essence from seed reprocessor

### ISSUE THREAD

**Issue by kwpugh** [BlakeBr0/MysticalAgriculture#81]
Forge: 2420
Mod: mysticalagriculture[1.12]-1.6.1a.jar

I tried used ducts with servos from Thermal Expansion and none of the sides of the seed reprocessor will extract processed essence.

I can feed seeds into the top of the reprocessor using TE ducts.

**Comment by BlakeBr0** [comment]
Hoppers should work. I need to get around to redoing that thing soon, it's so poorly coded.

**Comment by TheBrain0110** [comment]
Just thought I'd mention I can't get anything to extract from the seed reprocessor in the 1.10 versions either. I can get Thermal Dynamics ducts to pipe in to the top, but not any other side, And servos can't extract anything. Extra Utils 2 pipes don't connect at all. EnderIO machines can "push" into the top as well, but not pull essence out.

Hoppers seem to be the only thing that works, and I never would've thought of it if you hadn't mentioned it. Definitely a bit buggy :p

**Comment by BlakeBr0** [comment]
Finally got around to fixing this, so the next release for 1.12 should work with everything. 👍
