### ISSUE TITLE
Watering Can + Growth Accelerator

### ISSUE THREAD

**Issue by bramvankooten** [BlakeBr0/MysticalAgriculture#82]
I came across an issue where using a watering can on a crop that was also being accelerated by a growth accelerator was not being affected by the watering can. As you might understand this slows the growth of that specific crop quite a lot.

**Comment by BlakeBr0** [comment]
Is this a consistent issue across multiple minecraft versions?

**Comment by bramvankooten** [comment]
I first encountered the problem while playing the mod pack All The Mods 3 on 1.12. I have done some more testing and the issue remains while playing on both 1.12 and 1.11.2 with only Mystical Agriculture installed.

**Comment by DrShtroumphi** [comment]
This also happens with fertilized dirt or soil from other mods. It just doesn't grow.

**Comment by StrikerPro007** [comment]
I noticed this at version 1.10.2, but i don´t know if it happens because of my created modpack or because it really happens without other, i will try this day, when i will be free

**Comment by BlakeBr0** [comment]
I'll be releasing versions for 1.10/1.11 with this fixed tomorrow. A 1.12 version with a fix will be a bit later.
