### ISSUE TITLE
Seed Reprocessor Tiers

### ISSUE THREAD

**Issue by Mohron** [BlakeBr0/MysticalAgriculture#83]
Would you consider adding seed reprocessors for each Mystic ag tier? The current one is way too slow to keep up with massive farms and requires you to either make a large number of reprocessors or build up a backlog of seeds.

Thank you for your consideration.

**Comment by BlakeBr0** [comment]
I have some ideas for the seed reprocessor that should make it more viable, hopefully I can get around to implementing them soon.

**Comment by NIZEYIMAN** [comment]
Nice
