### ISSUE TITLE
1.11.2 supremium armor 'feature'

### ISSUE THREAD

**Issue by croftyraider** [BlakeBr0/MysticalAgriculture#84]
I finally got around to making a full set of supremium armor today, only to discover that it has a builin step assist that I can't disable.

Any way that you could add a config option for that? Vanilla already has an option to enable/disable the feature, and it would be nice if you matched that too.

Thanks!

**Comment by BlakeBr0** [comment]
Vanilla has auto-jump, which is a different mechanic. And yes, it is a "feature", as step assist has been considered a feature in modded minecraft for years.

That being said, I may add a config of some sort, but it won't be a high priority. As well it also depends on if I do ever decide to release an update for older than 1.12 versions of the mod.

**Comment by croftyraider** [comment]
Fair enough, but might I suggest that the assumption that if you make that armor you want that feature be moved to a config option instead of just assuming :)

I happen to strongly dislike that feature because all my years of minecraft habits break down (been playing since Alpha).
