### ISSUE TITLE
question: no findings of prosperitiy ore and /or inferium ore in overworld in MC 1.12

### ISSUE THREAD

**Issue by DietmarKrause** [BlakeBr0/MysticalAgriculture#86]
perhaps i am missing an info. I used to find lots of prosperity and inferium ore in MC 1.10. Now i play the mod (in all the mods 3) but dont find any of the specific ores in the overworld even in new chuncs or the Aroma mining dimension. Has something changed since 1.10?

**Comment by BlakeBr0** [comment]
They disabled overworld oregen for mystical agriculture in that pack. Go to the nether to rarely find some because lowered the spawn rate in the nether by 75%.

**Comment by DietmarKrause** [comment]
https://github.com/AllTheMods/ATM-3/issues/81
