### ISSUE TITLE
Crash with forge 1.10.2-12.18.3.2422

### ISSUE THREAD

**Issue by runescapejon** [BlakeBr0/MysticalAgriculture#89]
hello, one of my players was doing something and he had crash the server i thought it was an sponge issue with this mod but i was wrong i did more testing i loaded up the area that he was at and run it in singleplayer without having sponge and i managed to crash here is the crash report 
https://pastebin.com/GmQmp0Nt - im on 1.10.2 mod version 1.5.8
am unsure how to reproduce the problem because that player is offline but if he comes online i will post back how to reproduce it but if you know how to fix this sort of thing can you please thanks

EDIT: it turns out that the player was just loading up the chunk and it just crash he did nothing but just walking around

**Comment by runescapejon** [comment]
it seem has to do something with this 
https://github.com/BlakeBr0/MysticalAgriculture/blob/1.10/src/main/java/com/blakebr0/mysticalagriculture/blocks/crop/BlockMysticalCrop.java#L47

**Comment by BlakeBr0** [comment]
Can't reproduce. Have you tried making it reoccur in a different world?

**Comment by runescapejon** [comment]
yea i just walk around and it happen randomly  but i removed that line and it help to prevent the crash

**Comment by BlakeBr0** [comment]
Might be something wrong with your forge/minecraft installation, maybe try a different forge version.

**Comment by runescapejon** [comment]
Yeap your right about the forge versions it seem you compile forge with `1.10.2-12.18.3.2185` and i was using the very latest one a `1.10.2 - 12.18.3.2422`
