### ISSUE TITLE
Dispensing Mystical Fertilizer/Essence

### ISSUE THREAD

**Issue by DrShtroumphi** [BlakeBr0/MysticalAgriculture#90]
It might be a bug since we can dispense normal bonemeal with dispensers, but even if it isn't, it would be much easier to make some automatic farms using dispensers if this feature was in the mod. It could be configurable. Maybe also enable dispensers to plant seeds, or even make a completely new block that automatically plants seeds in a specific radius, like in MinefactoryReloaded. Thank you for your help :)
~Dr_Shtroumphi

**Comment by BlakeBr0** [comment]
I'll look into the fertilizer stuff. Don't plan on adding the ability to automatically plant seeds, because as you said, mfr (for example) adds that functionality.

**Comment by DrShtroumphi** [comment]
The only problem is that that mod isn't for 1.12, but really it doesn't matter. As long as there's automatic fertilizer, I'm good :)

**Comment by IamAlathe** [comment]
Actually Additions is on 1.12 and has a farmer block that plays well with Mystical Agriculture plants. :)
