### ISSUE TITLE
Ability to restrict Seed growth to certain biomes

### ISSUE THREAD

**Issue by KAfable** [BlakeBr0/MysticalAgriculture#91]
Would it be possible to have a config option or a way to restrict seeds or plant growth depending on the biome? I really want to include Mystical Agriculture in my pack as near endgame content where the player is forced to grow the plants only in a space biome (rather than letting them go to space/asteroid belt, give xyz item, and then grow the farm in the actual overworld).

**Comment by Vyraal1** [comment]
Or instead of biome, by dimension would also work perfectly fine, but by biome would also allow for greater control to limit certain metals growing only in desert biomes, others in extreme hills, and so forth.

**Comment by BlakeBr0** [comment]
I can look into adding this. Don't think it would be that high on my priority list, and I'd most likely only add it to the 1.12 version.

**Comment by BlakeBr0** [comment]
Once I release the next update of Mystical Customization this will finally be possible.
