### ISSUE TITLE
Not getting any mob chunk from zombies with soulium dagger

### ISSUE THREAD

**Issue by Ubucraft** [BlakeBr0/MysticalAgriculture#94]
Hi, I'm playing Minecraft 1.10.2 with Forge 1.2.18.3.2185 and Mystical Agriculture 1.5.2.
I have crafted the soulium dagger and started slashing some mobs with it: zombies, skeletons, spiders, creepers... but never getting a single one mob chunk.
I can get some slime chunks from slimes.
I did the same at a larger scale in Creative Mobs, spawning massive numbers of mobs: same result.

Is this a bug ?

**Comment by BlakeBr0** [comment]
Probably because you're using a version of the mod 6 versions behind the latest. 
That version had that bug and a hotfix was released shortly after. Is there a reason you're using such an old version?

**Comment by Ubucraft** [comment]
Well... I thought I had the latest version 😯 
I will update soon!
