### ISSUE TITLE
[Suggestion] Maven for devs

### ISSUE THREAD

**Issue by BrainStone** [BlakeBr0/MysticalAgriculture#95]
It would be super cool if you could start uploading jars to a maven so they can be used from gradle. If possible please upload all three (normal, deobf, sources).

If you need help or a maven to uplaod to, I can help with both!

**Comment by BlakeBr0** [comment]
why

**Comment by BrainStone** [comment]
Makes it a lot easier to develop addons for Mystical Agriculture,

**Comment by BlakeBr0** [comment]
I never designed the mod for addons, and I don't really plan on it either

I cant think of any reason to make an addon, besides adding more crops, which can be accomplished without even depending on mystical agriculture

**Comment by BrainStone** [comment]
Well that would be interesting. How would I add crops to Mystical Agriculture without depending on it?

And yes I'm mostly talking about adding crops. Maybe adding charms. (I haven't looked into it but I would have an idea for adding a charm)

**Comment by BlakeBr0** [comment]
Add a wheat crop with a new texture and new drops, and you've added a new crop
Adding charms would require lots of reflection and could/would mess with the mod if I ever added new charms

**Comment by BrainStone** [comment]
I mean I specifically want a MysticalAgriculture crop. That works like all the other with essences etc.
Which I'm almost done with btw.

I'll see regarding the charm though. I think I'll priotize upgrading to 1.12 over this.

Also even though there is no API or you haven't designed anything to be extended it works without issues.

**Comment by BlakeBr0** [comment]
Honestly ive never really seen a need for it since you can just use the jar as a library.

**Comment by BrainStone** [comment]
There is no real need, it's just a conviniece.

**Comment by BlakeBr0** [comment]
I feel like a bit of an asshole for going off on a tangent when I really could've just said no thanks. Sorry about that.

**Comment by BrainStone** [comment]
Don't worry. It was a nice little chat.
