### ISSUE TITLE
Add Just Enough Resources compat

### ISSUE THREAD

**Issue by BrainStone** [BlakeBr0/MysticalAgriculture#96]
Compatibility for [Just Enough Resources](https://minecraft.curseforge.com/projects/just-enough-resources-jer) would be awesome as you could see specify which essences get dropped by which crop, and the chances for everything. Also the oregen could be shown which is also neat.

**Comment by mendel3** [comment]
Is this being worked on/going to be worked on for 1.13?

**Comment by BlakeBr0** [comment]
I will not be doing this as I don't think the value outweighs the maintenance overhead.
